### PR TITLE
Fix UDS Dockerfile Build Path

### PR DESCRIPTION
**Pull request by colin-higgins**
Path was incorrect after moving to a new folder

@DataDog/apm-dotnet

### CODE REVIEW

**Review by andrewlock — APPROVED** [review]
I had totally missed that you'd snuck that _tools_ folder back in again 😛

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #2394 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4) will **not change** line coverage
:heavy_check_mark: Merging #2394 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4) will **not change** branch coverage
:heavy_check_mark: Merging #2394 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4) will **not change** complexity


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4) | #2394       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `10431` / `14873` | `10419` / `14873` |          |
| Lines %   | `70%`      | `70%`      |  `0%` :heavy_check_mark:  |
| Branches  | `5342` / `7780` | `5331` / `7780` |          |
| Branches %| `69%`      | `69%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `8927`      | `8927`        |  `0`  :heavy_check_mark:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/$dd-trace-dotnet/_build/results?buildId=89086&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/89086/artifacts?artifactName=Code%20Coverage%20Report_89086&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2394](https://dev.azure.com/datadoghq/$dd-trace-dotnet/_build/results?buildId=89116&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/89116/artifacts?artifactName=Code%20Coverage%20Report_89116&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4) | #2394       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `70%`      | `70%`       |  `0%` :heavy_check_mark:  |
| Branches %| `69%`      | `69%`       |  `0%` :heavy_check_mark:  |
| Complexity| `8927`      | `8927`       |  `0` :heavy_check_mark:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteIntegrationBis](https://github.com/DataDog/dd-trace-dotnet/tree/a682e0826f2a77f2e1c6e1c1a42975fc0aec63a8/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Couchbase/IIOServiceExecuteIntegrationBis.cs) | `-100%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.MsTestV2.TestMethodRunnerExecuteIntegration](https://github.com/DataDog/dd-trace-dotnet/tree/a682e0826f2a77f2e1c6e1c1a42975fc0aec63a8/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Testing/MsTestV2/TestMethodRunnerExecuteIntegration.cs) | `-33%` :no_entry: | `-19%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.NUnit.NUnitCompositeWorkItemSkipChildrenIntegration](https://github.com/DataDog/dd-trace-dotnet/tree/a682e0826f2a77f2e1c6e1c1a42975fc0aec63a8/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Testing/NUnit/NUnitCompositeWorkItemSkipChildrenIntegration.cs) | `-8%` :no_entry: | `-8%` :no_entry:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/$dd-trace-dotnet/_build/results?buildId=89086&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/89086/artifacts?artifactName=Code%20Coverage%20Report_89086&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2394](https://dev.azure.com/datadoghq/$dd-trace-dotnet/_build/results?buildId=89116&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/89116/artifacts?artifactName=Code%20Coverage%20Report_89116&api-version=6.0&%24format=zip)

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #2394 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4): 
* 1 benchmarks are **faster**, with geometric mean 1.141
* 1 benchmarks are **slower**, with geometric mean 1.192
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`WriteAndFlushEnrichedTraces`|net472|834μs|3.67μs|13.8μs|0| 0|0|3.16&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|681μs|3.65μs|19.7μs|0| 0|0|2.57&nbsp;KB|
|#2394|`WriteAndFlushEnrichedTraces`|net472|896μs|3.26μs|12.6μs|0| 0|0|3.16&nbsp;KB|
|#2394|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|655μs|2.4μs|9.28μs|0| 0|0|2.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Unknown :shrug: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`SendRequest`|netcoreapp3.1|298μs|1.57μs|8.03μs|0.15| 0|0|19.67&nbsp;KB|
|#2394|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#2394|`SendRequest`|netcoreapp3.1|305μs|1.35μs|5.05μs|0.151| 0|0|19.67&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`ExecuteNonQuery`|net472|1.57μs|2.98ns|10.3ns|0.0927| 0.000806|0|586&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`ExecuteNonQuery`|netcoreapp3.1|1.41μs|4.79ns|18.5ns|0.00845| 0|0|624&nbsp;B|
|#2394|`ExecuteNonQuery`|net472|1.58μs|7.25ns|29ns|0.0929| 0.000781|0|586&nbsp;B|
|#2394|`ExecuteNonQuery`|netcoreapp3.1|1.43μs|5.15ns|19.3ns|0.0084| 0|0|624&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`CallElasticsearch`|net472|2.31μs|7.11ns|27.6ns|0.124| 0|0|794&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`CallElasticsearch`|netcoreapp3.1|1.62μs|6.26ns|24.2ns|0.011| 0|0|784&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`CallElasticsearchAsync`|net472|2.46μs|8.12ns|31.5ns|0.145| 0|0|931&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`CallElasticsearchAsync`|netcoreapp3.1|1.71μs|4.59ns|17.8ns|0.0125| 0|0|904&nbsp;B|
|#2394|`CallElasticsearch`|net472|2.31μs|7.46ns|28.9ns|0.124| 0|0|794&nbsp;B|
|#2394|`CallElasticsearch`|netcoreapp3.1|1.64μs|6.73ns|26.1ns|0.0106| 0|0|784&nbsp;B|
|#2394|`CallElasticsearchAsync`|net472|2.49μs|11.3ns|43.8ns|0.145| 0|0|931&nbsp;B|
|#2394|`CallElasticsearchAsync`|netcoreapp3.1|1.72μs|8.94ns|43.8ns|0.0125| 0|0|904&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Faster :tada: Same allocations :heavy_check_mark:



#### Faster :tada: in #2394

|  Benchmark         | base/diff | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.GraphQLBenchmark.ExecuteAsync&#8209;net472 | 1.141 | 3,174.10 | 2,781.07 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`ExecuteAsync`|net472|3.18μs|14.2ns|55.1ns|0.164| 0|0|1.05&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`ExecuteAsync`|netcoreapp3.1|1.96μs|9.9ns|47.5ns|0.0141| 0|0|1.02&nbsp;KB|
|#2394|`ExecuteAsync`|net472|2.79μs|14.3ns|67.2ns|0.165| 0|0|1.05&nbsp;KB|
|#2394|`ExecuteAsync`|netcoreapp3.1|1.84μs|3.83ns|14.3ns|0.0142| 0|0|1.02&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`SendAsync`|net472|6.22μs|18.8ns|67.9ns|0.351| 0|0|2.26&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`SendAsync`|netcoreapp3.1|4.47μs|24.9ns|161ns|0.0302| 0|0|2.16&nbsp;KB|
|#2394|`SendAsync`|net472|6.2μs|23.4ns|93.8ns|0.353| 0|0|2.26&nbsp;KB|
|#2394|`SendAsync`|netcoreapp3.1|4.67μs|20.3ns|78.5ns|0.0302| 0|0|2.16&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #2394

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.ILoggerBenchmark.EnrichedLog&#8209;net472 | 1.192 | 3,313.87 | 3,949.21 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`EnrichedLog`|net472|3.43μs|26ns|252ns|0.226| 0|0|1.44&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`EnrichedLog`|netcoreapp3.1|3.12μs|13.2ns|49.3ns|0.021| 0|0|1.52&nbsp;KB|
|#2394|`EnrichedLog`|net472|3.93μs|22.3ns|168ns|0.225| 0|0|1.44&nbsp;KB|
|#2394|`EnrichedLog`|netcoreapp3.1|3.49μs|46.4ns|462ns|0.0207| 0|0|1.52&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`EnrichedLog`|net472|289μs|1.09μs|4.23μs|0.426| 0.142|0|4.31&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`EnrichedLog`|netcoreapp3.1|238μs|1.04μs|4.04μs|0| 0|0|4.19&nbsp;KB|
|#2394|`EnrichedLog`|net472|286μs|762ns|2.95μs|0.42| 0.14|0|4.31&nbsp;KB|
|#2394|`EnrichedLog`|netcoreapp3.1|228μs|719ns|2.69μs|0| 0|0|4.19&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`EnrichedLog`|net472|7.94μs|20.6ns|77.1ns|0.504| 0|0|3.21&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`EnrichedLog`|netcoreapp3.1|6.34μs|21.5ns|83.3ns|0.0494| 0|0|3.58&nbsp;KB|
|#2394|`EnrichedLog`|net472|8.02μs|38.8ns|165ns|0.504| 0|0|3.21&nbsp;KB|
|#2394|`EnrichedLog`|netcoreapp3.1|6.54μs|35.5ns|207ns|0.0495| 0|0|3.58&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`SendReceive`|net472|2.08μs|8.14ns|31.5ns|0.157| 0|0|1&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`SendReceive`|netcoreapp3.1|1.91μs|5.63ns|20.3ns|0.014| 0|0|1&nbsp;KB|
|#2394|`SendReceive`|net472|2.36μs|13.4ns|93.6ns|0.157| 0|0|1&nbsp;KB|
|#2394|`SendReceive`|netcoreapp3.1|1.92μs|6.16ns|23ns|0.0133| 0|0|1&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`EnrichedLog`|net472|5.95μs|23.1ns|83.2ns|0.288| 0|0|1.85&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`EnrichedLog`|netcoreapp3.1|5.06μs|22.6ns|87.7ns|0.02| 0|0|1.47&nbsp;KB|
|#2394|`EnrichedLog`|net472|6.01μs|26.9ns|104ns|0.289| 0|0|1.85&nbsp;KB|
|#2394|`EnrichedLog`|netcoreapp3.1|5.14μs|22.2ns|85.9ns|0.0202| 0|0|1.47&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`StartFinishSpan`|net472|951ns|5.46ns|39.7ns|0.0707| 0|0|449&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`StartFinishSpan`|netcoreapp3.1|863ns|2.38ns|8.89ns|0.0061| 0|0|448&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`StartFinishScope`|net472|1.1μs|5.76ns|27.6ns|0.0829| 0|0|530&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/596b91264a4845459734c4631fec9dec91d5bba4)|`StartFinishScope`|netcoreapp3.1|1.04μs|5.09ns|21.6ns|0.00771| 0|0|568&nbsp;B|
|#2394|`StartFinishSpan`|net472|910ns|2.36ns|8.83ns|0.0703| 0|0|449&nbsp;B|
|#2394|`StartFinishSpan`|netcoreapp3.1|861ns|2.92ns|11.3ns|0.00602| 0|0|448&nbsp;B|
|#2394|`StartFinishScope`|net472|1.11μs|5.56ns|31.9ns|0.0833| 0|0|530&nbsp;B|
|#2394|`StartFinishScope`|netcoreapp3.1|1.05μs|5.54ns|36.8ns|0.00791| 0|0|568&nbsp;B|
</details>

**Comment by colin-higgins** [comment]
Closing this in favor of the changes in the net5.0 target PR https://github.com/DataDog/dd-trace-dotnet/pull/2399

**Pull request closed without merging**
