### PR TITLE
[Build] Fix S3 upload

### PR DESCRIPTION
**Pull request by pierotibou**
## Summary of changes
Add the region in the command line to fix the upload with newer version of the CLI

## Reason for change
It wasn't working. Workaround found [here](https://github.com/aws/aws-cli/issues/5234#issuecomment-635459464)

## Implementation details
I've tried to set the region through aws configure and it didn't work, had to put it in the command line.
I've left the `--debug` option as it doesn't hurt and could be useful in the future.

## Test coverage
Tested on my branch and worked.

### CODE REVIEW

**Review by andrewlock — APPROVED** [review]
🙇 :salute:

**Review by anna-git — APPROVED** [review]

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #2932 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`WriteAndFlushEnrichedTraces`|net472|711μs|394ns|1.47μs|0.357| 0|0|3.16&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|464μs|962ns|3.6μs|0| 0|0|2.57&nbsp;KB|
|#2932|`WriteAndFlushEnrichedTraces`|net472|717μs|677ns|2.53μs|0.353| 0|0|3.16&nbsp;KB|
|#2932|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|482μs|432ns|1.67μs|0| 0|0|2.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`AllCycleSimpleBody`|net472|1.78μs|2.34ns|9.05ns|0.235| 0|0|1.48&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`AllCycleSimpleBody`|netcoreapp3.1|1.91μs|2.24ns|8.37ns|0.0188| 0|0|1.36&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`AllCycleMoreComplexBody`|net472|17.9μs|16.8ns|65ns|1.39| 0.0179|0|8.74&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`AllCycleMoreComplexBody`|netcoreapp3.1|14.8μs|40.1ns|155ns|0.103| 0|0|7.84&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`BodyExtractorSimpleBody`|net472|272ns|0.25ns|0.969ns|0.0573| 0|0|361&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`BodyExtractorSimpleBody`|netcoreapp3.1|230ns|0.229ns|0.888ns|0.00371| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`BodyExtractorMoreComplexBody`|net472|16μs|9.22ns|33.2ns|1.21| 0.016|0|7.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`BodyExtractorMoreComplexBody`|netcoreapp3.1|12.4μs|12.9ns|49.9ns|0.0866| 0|0|6.75&nbsp;KB|
|#2932|`AllCycleSimpleBody`|net472|1.85μs|1.62ns|6.27ns|0.236| 0|0|1.48&nbsp;KB|
|#2932|`AllCycleSimpleBody`|netcoreapp3.1|1.91μs|3.33ns|12.5ns|0.0182| 0|0|1.36&nbsp;KB|
|#2932|`AllCycleMoreComplexBody`|net472|18μs|22.7ns|87.8ns|1.39| 0.018|0|8.74&nbsp;KB|
|#2932|`AllCycleMoreComplexBody`|netcoreapp3.1|14.4μs|22.5ns|87.1ns|0.101| 0|0|7.84&nbsp;KB|
|#2932|`BodyExtractorSimpleBody`|net472|273ns|0.343ns|1.33ns|0.0574| 0|0|361&nbsp;B|
|#2932|`BodyExtractorSimpleBody`|netcoreapp3.1|231ns|0.214ns|0.827ns|0.00374| 0|0|272&nbsp;B|
|#2932|`BodyExtractorMoreComplexBody`|net472|15.9μs|18ns|67.4ns|1.21| 0.0159|0|7.62&nbsp;KB|
|#2932|`BodyExtractorMoreComplexBody`|netcoreapp3.1|12.4μs|17.3ns|67ns|0.0926| 0|0|6.75&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Unknown :shrug: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`SendRequest`|netcoreapp3.1|174μs|197ns|681ns|0.173| 0|0|19.86&nbsp;KB|
|#2932|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#2932|`SendRequest`|netcoreapp3.1|174μs|115ns|447ns|0.174| 0|0|19.86&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`ExecuteNonQuery`|net472|1.48μs|0.824ns|3.19ns|0.114| 0.000748|0|722&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`ExecuteNonQuery`|netcoreapp3.1|1.27μs|0.34ns|1.18ns|0.00967| 0|0|752&nbsp;B|
|#2932|`ExecuteNonQuery`|net472|1.53μs|0.772ns|2.99ns|0.114| 0.000771|0|722&nbsp;B|
|#2932|`ExecuteNonQuery`|netcoreapp3.1|1.29μs|0.437ns|1.69ns|0.0103| 0|0|752&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`CallElasticsearch`|net472|2.16μs|0.991ns|3.84ns|0.147| 0|0|931&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`CallElasticsearch`|netcoreapp3.1|1.36μs|0.446ns|1.73ns|0.0122| 0|0|912&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`CallElasticsearchAsync`|net472|2.19μs|0.765ns|2.96ns|0.169| 0|0|1.07&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`CallElasticsearchAsync`|netcoreapp3.1|1.43μs|1.09ns|4.21ns|0.0137| 0|0|1.03&nbsp;KB|
|#2932|`CallElasticsearch`|net472|2.16μs|1.08ns|4.18ns|0.147| 0|0|931&nbsp;B|
|#2932|`CallElasticsearch`|netcoreapp3.1|1.35μs|0.571ns|2.14ns|0.012| 0|0|912&nbsp;B|
|#2932|`CallElasticsearchAsync`|net472|2.23μs|0.561ns|2.1ns|0.169| 0|0|1.07&nbsp;KB|
|#2932|`CallElasticsearchAsync`|netcoreapp3.1|1.46μs|4.29ns|16.6ns|0.0138| 0|0|1.03&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`ExecuteAsync`|net472|2.26μs|5.74ns|20.7ns|0.189| 0|0|1.19&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`ExecuteAsync`|netcoreapp3.1|1.49μs|4.49ns|17.4ns|0.0156| 0|0|1.15&nbsp;KB|
|#2932|`ExecuteAsync`|net472|2.3μs|3.58ns|13.9ns|0.188| 0|0|1.19&nbsp;KB|
|#2932|`ExecuteAsync`|netcoreapp3.1|1.48μs|1.97ns|6.82ns|0.0161| 0|0|1.15&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`SendAsync`|net472|4.85μs|7.83ns|29.3ns|0.381| 0|0|2.41&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`SendAsync`|netcoreapp3.1|3.41μs|7.45ns|28.8ns|0.032| 0|0|2.33&nbsp;KB|
|#2932|`SendAsync`|net472|4.95μs|11ns|42.8ns|0.382| 0|0|2.41&nbsp;KB|
|#2932|`SendAsync`|netcoreapp3.1|3.35μs|6.35ns|24.6ns|0.0318| 0|0|2.33&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`EnrichedLog`|net472|2.7μs|1.79ns|6.92ns|0.25| 0|0|1.58&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`EnrichedLog`|netcoreapp3.1|2.23μs|1.43ns|5.33ns|0.0222| 0|0|1.65&nbsp;KB|
|#2932|`EnrichedLog`|net472|2.8μs|1.79ns|6.94ns|0.25| 0|0|1.58&nbsp;KB|
|#2932|`EnrichedLog`|netcoreapp3.1|2.38μs|0.704ns|2.54ns|0.0226| 0|0|1.65&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`EnrichedLog`|net472|146μs|119ns|459ns|0.66| 0.22|0|4.42&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`EnrichedLog`|netcoreapp3.1|111μs|202ns|781ns|0.055| 0|0|4.3&nbsp;KB|
|#2932|`EnrichedLog`|net472|148μs|217ns|839ns|0.667| 0.222|0|4.42&nbsp;KB|
|#2932|`EnrichedLog`|netcoreapp3.1|111μs|189ns|733ns|0.0557| 0|0|4.3&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`EnrichedLog`|net472|5.12μs|9.27ns|34.7ns|0.531| 0.00254|0|3.35&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`EnrichedLog`|netcoreapp3.1|4.15μs|13.4ns|51.7ns|0.0509| 0|0|3.72&nbsp;KB|
|#2932|`EnrichedLog`|net472|5.33μs|11.8ns|45.8ns|0.531| 0.0026|0|3.35&nbsp;KB|
|#2932|`EnrichedLog`|netcoreapp3.1|4.2μs|5.05ns|19.6ns|0.05| 0|0|3.72&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`SendReceive`|net472|2.02μs|1.72ns|6.66ns|0.181| 0|0|1.14&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`SendReceive`|netcoreapp3.1|1.6μs|0.587ns|2.2ns|0.0152| 0|0|1.13&nbsp;KB|
|#2932|`SendReceive`|net472|1.98μs|1.27ns|4.92ns|0.18| 0|0|1.14&nbsp;KB|
|#2932|`SendReceive`|netcoreapp3.1|1.55μs|1.15ns|4.46ns|0.0147| 0|0|1.13&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`EnrichedLog`|net472|4.69μs|1.58ns|6.13ns|0.316| 0|0|2&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`EnrichedLog`|netcoreapp3.1|4.04μs|2.22ns|8.61ns|0.0203| 0|0|1.61&nbsp;KB|
|#2932|`EnrichedLog`|net472|4.54μs|1.58ns|5.92ns|0.316| 0|0|2&nbsp;KB|
|#2932|`EnrichedLog`|netcoreapp3.1|4.05μs|2.22ns|8.59ns|0.0222| 0|0|1.61&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`StartFinishSpan`|net472|802ns|1.12ns|4.35ns|0.093| 0|0|586&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`StartFinishSpan`|netcoreapp3.1|696ns|0.277ns|1.07ns|0.00769| 0|0|576&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`StartFinishScope`|net472|1.1μs|0.314ns|1.18ns|0.106| 0|0|666&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`StartFinishScope`|netcoreapp3.1|814ns|0.283ns|1.06ns|0.00945| 0|0|696&nbsp;B|
|#2932|`StartFinishSpan`|net472|866ns|0.255ns|0.987ns|0.0928| 0|0|586&nbsp;B|
|#2932|`StartFinishSpan`|netcoreapp3.1|715ns|0.195ns|0.729ns|0.00784| 0|0|576&nbsp;B|
|#2932|`StartFinishScope`|net472|1.09μs|0.626ns|2.42ns|0.105| 0|0|666&nbsp;B|
|#2932|`StartFinishScope`|netcoreapp3.1|844ns|0.288ns|1.08ns|0.00955| 0|0|696&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`RunOnMethodBegin`|net472|1.27μs|0.209ns|0.753ns|0.105| 0|0|666&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187)|`RunOnMethodBegin`|netcoreapp3.1|943ns|1ns|3.88ns|0.0094| 0|0|696&nbsp;B|
|#2932|`RunOnMethodBegin`|net472|1.24μs|0.568ns|2.2ns|0.106| 0|0|666&nbsp;B|
|#2932|`RunOnMethodBegin`|netcoreapp3.1|1μs|0.398ns|1.54ns|0.00945| 0|0|696&nbsp;B|
</details>

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #2932 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187) will **not change** line coverage
:heavy_check_mark: Merging #2932 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187) will **not change** branch coverage
:heavy_check_mark: Merging #2932 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187) will **not change** complexity


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187) | #2932       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `15067` / `20461` | `15079` / `20461` |          |
| Lines %   | `74%`      | `74%`      |  `0%` :heavy_check_mark:  |
| Branches  | `9144` / `12948` | `9154` / `12948` |          |
| Branches %| `71%`      | `71%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `13819`      | `13819`        |  `0`  :heavy_check_mark:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=103552&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/103552/artifacts?artifactName=Code%20Coverage%20Report_103552&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2932](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=103560&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/103560/artifacts?artifactName=Code%20Coverage%20Report_103560&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/7c6086fbf27e06c1920ce046cea5ac4936359187) | #2932       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `74%`      | `74%`       |  `0%` :heavy_check_mark:  |
| Branches %| `71%`      | `71%`       |  `0%` :heavy_check_mark:  |
| Complexity| `13819`      | `13819`       |  `0` :heavy_check_mark:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Ci.CIVisibility](https://github.com/DataDog/dd-trace-dotnet/tree/b6df386f305eaca3860506b6499b9b95cdbb0fc8/tracer/src/Datadog.Trace/Ci/CIVisibility.cs) | `7%` :heavy_check_mark: | `7%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Telemetry.Transports.JsonTelemetryTransport](https://github.com/DataDog/dd-trace-dotnet/tree/b6df386f305eaca3860506b6499b9b95cdbb0fc8/tracer/src/Datadog.Trace/Telemetry/Transports/JsonTelemetryTransport.cs) | `8%` :heavy_check_mark: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Ci.Processors.OriginTagTraceProcessor](https://github.com/DataDog/dd-trace-dotnet/tree/b6df386f305eaca3860506b6499b9b95cdbb0fc8/tracer/src/Datadog.Trace/Ci/Processors/OriginTagTraceProcessor.cs) | `9%` :heavy_check_mark: | `17%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Agent.Transports.HttpStreamRequestFactory](https://github.com/DataDog/dd-trace-dotnet/tree/b6df386f305eaca3860506b6499b9b95cdbb0fc8/tracer/src/Datadog.Trace/Agent/Transports/HttpStreamRequestFactory.cs) | `12%` :heavy_check_mark: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=103552&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/103552/artifacts?artifactName=Code%20Coverage%20Report_103552&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2932](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=103560&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/103560/artifacts?artifactName=Code%20Coverage%20Report_103560&api-version=6.0&%24format=zip)

**Review by zacharycmontoya — APPROVED** [review]
Thank you!

**Pull request merged**
