### PR TITLE
Add locks around Statsd.Add and inside of Statsd.Send call

### PR DESCRIPTION
**Pull request by bobuva**
Attempts to fix a race condition in `Statsd` where the `Commands` collection is not thread-safe.

This PR applies the locks in two places:
1. Where the .NET Tracer calls `IStatsd.Add` in `StatsdExtensions`.
2. In the vendor-ed code for `Statsd`, the no-parameter overload of `Statsd.Send`.

The reason for modifying the vendor-ed code instead of the calls to `IStatsd.Send` is that `IStatsd.Send` is called in several places in the tracer (listed below), and because, sometime over the next couple of months, the `dogstatsd-csharp-client` is going to make the use of the `Statsd` class obsolete. Since we are using a vendor-ed version, we should be able to migrate from `Statsd` to what the new technique will be (I don't have all the details yet) sometime after `dogstatsd-csharp-client` is updated.

I have not been able to reproduce the race condition, which showed up as an exception for at least one of our customers. The exception is:

```
2020-03-17 16:45:36.399 +00:00 [ERR] An unhandled error occurred during the flushing task
	System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
	   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
	   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
	   at System.Collections.Generic.List`1.ToArray()
	   at Datadog.Trace.Vendors.StatsdClient.Statsd.Send()
	   at Datadog.Trace.Agent.AgentWriter.<FlushTracesAsync>d__11.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
	   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
```
I will continue to try to reproduce this and add such a repro case to our suite of tests.

I've run some load against the .NET tracer locally to see if there was any difference in performance due to these locks and my results are not conclusive. In one set of tests, there was a drop of < 1% in throughput and in average latency. In another set of tests, there was an increase in throughput (1.5%) and a slight drop in average latency (-1.6%). We should keep an eye on the performance when this change hits the reliability environment.

@DataDog/apm-dotnet

### CODE REVIEW

**Comment by colin-higgins** [comment]
Would it simplify and be better for performance if we changed `List<string> Commands` to `ConcurrentBag<string> Commands`? Then we wouldn't need to manage the locking.
I think the only other thing that would need to change it an index based access optimization of `Commands[0]` to `Commands.Single()` within the `Send` method.

**Comment by bobuva** [comment]
> Would it simplify and be better for performance if we changed `List<string> Commands` to `ConcurrentBag<string> Commands`? Then we wouldn't need to manage the locking.
> I think the only other thing that would need to change is an index based access optimization of `Commands[0]` to `Commands.Single()` within the `Send` method.

Very interesting suggestion -- I had looked for a concurrent list but it doesn't exist, but the `ConcurrentBag` would do the trick. I'll check it out. Thanks!

**Comment by lucaspimentel** [comment]
These are 2 separate locks, so one thread can still modify the collection using `Add()` while another one is reading it using `Send()`. Unless we go with a concurrent collection like @colin-higgins suggested, consider locking on `statsd.Commands` instead to avoid writing and reading at the same time.

**Comment by bobuva** [comment]
> These are 2 separate locks, so one thread can still modify the collection using `Add()` while another one is reading it using `Send()`. Unless we go with a concurrent collection like @colin-higgins suggested, consider locking on `statsd.Commands` instead to avoid writing and reading at the same time.

Yeah, I have implemented the `ConcurrentBag` and am testing it`

**Pull request merged**
