### PR TITLE
Disable memory dumps in CI

### PR DESCRIPTION
**Pull request by kevingosse**
As much as I'd like to keep them, we've seen them actually hiding a segfault during shutdown.

### CODE REVIEW

**Review by andrewlock — CHANGES_REQUESTED** [review]
May as well remove the `DotNetSettingsExtensions.EnableMemoryDumps` extension method, and the `MiniDumpType` enum too

**Comment by kevingosse** [comment]
> May as well remove the `DotNetSettingsExtensions.EnableMemoryDumps` extension method, and the `MiniDumpType` enum too

I thought it could be useful if we decide to reenable them at some point, but I don't mind removing it

**Comment by andrewlock** [comment]
> > May as well remove the `DotNetSettingsExtensions.EnableMemoryDumps` extension method, and the `MiniDumpType` enum too
> 
> I thought it could be useful if we decide to reenable them at some point, but I don't mind removing it

Yeah fair enough, feel free to leave it. Or delete the enum if we are getting rid of it 😛

**Review by andrewlock — APPROVED** [review]

**Review by zacharycmontoya — APPROVED** [review]

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #1822 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/a2561d2153cb020c651a1c87595be50b1ddfe2a1) will **not change** line coverage
:heavy_check_mark: Merging #1822 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/a2561d2153cb020c651a1c87595be50b1ddfe2a1) will **not change** branch coverage
:no_entry: Merging #1822 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/a2561d2153cb020c651a1c87595be50b1ddfe2a1) will will **increase** complexity by `6`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/a2561d2153cb020c651a1c87595be50b1ddfe2a1) | #1822       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `9431` / `15040` | `9443` / `15052` |          |
| Lines %   | `63%`      | `63%`      |  `0%` :heavy_check_mark:  |
| Branches  | `4158` / `6522` | `4167` / `6528` |          |
| Branches %| `64%`      | `64%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `7684`      | `7690`        |  `6`  :no_entry:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=76128&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/76128/artifacts?artifactName=Code%20Coverage%20Report_76128&api-version=6.0&%24format=zip)  
* [HTML report for this PR #1822](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=76187&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/76187/artifacts?artifactName=Code%20Coverage%20Report_76187&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/a2561d2153cb020c651a1c87595be50b1ddfe2a1) | #1822       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `63%`      | `63%`       |  `0%` :heavy_check_mark:  |
| Branches %| `64%`      | `64%`       |  `0%` :heavy_check_mark:  |
| Complexity| `7684`      | `7690`       |  `6` :no_entry:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.ClrProfiler.CallTarget.Handlers.Continuations.TaskContinuationGenerator`4](https://github.com/DataDog/dd-trace-dotnet/tree/146a60f4c5854f3d026d133886d42af646bfa650/tracer/src/Datadog.Trace/ClrProfiler/CallTarget/Handlers/Continuations/TaskContinuationGenerator`1.cs) | `-5%` :no_entry: | `-9%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Logging.LogRateLimiter](https://github.com/DataDog/dd-trace-dotnet/tree/146a60f4c5854f3d026d133886d42af646bfa650/tracer/src/Datadog.Trace/Logging/LogRateLimiter.cs) | `0%` :heavy_check_mark: | `17%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Elasticsearch.V7.Transport_Request_Integration](https://github.com/DataDog/dd-trace-dotnet/tree/146a60f4c5854f3d026d133886d42af646bfa650/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Logging/Elasticsearch/V7/Transport_Request_Integration.cs) | `0%` :heavy_check_mark: | `30%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Elasticsearch.V7.Transport_RequestAsync_Integration](https://github.com/DataDog/dd-trace-dotnet/tree/146a60f4c5854f3d026d133886d42af646bfa650/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Logging/Elasticsearch/V7/Transport_RequestAsync_Integration.cs) | `0%` :heavy_check_mark: | `30%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.GraphQL.ValidateAsync4Integration](https://github.com/DataDog/dd-trace-dotnet/tree/146a60f4c5854f3d026d133886d42af646bfa650/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Logging/GraphQL/ValidateAsync4Integration.cs) | `18%` :heavy_check_mark: | `67%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.GraphQL.ValidateAsyncIntegration](https://github.com/DataDog/dd-trace-dotnet/tree/146a60f4c5854f3d026d133886d42af646bfa650/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Logging/GraphQL/ValidateAsyncIntegration.cs) | `18%` :heavy_check_mark: | `67%` :heavy_check_mark:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=76128&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/76128/artifacts?artifactName=Code%20Coverage%20Report_76128&api-version=6.0&%24format=zip)  
* [HTML report for this PR #1822](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=76187&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/76187/artifacts?artifactName=Code%20Coverage%20Report_76187&api-version=6.0&%24format=zip)

**Pull request merged**
