### PR TITLE
Run Remote Configuration system tests

### PR DESCRIPTION
**Pull request by shurivich**
## Summary of changes
Run remote configuration system tests during CI

### CODE REVIEW

**Comment by shurivich** [comment]
Depends on https://github.com/DataDog/system-tests/pull/487

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #3212 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`WriteAndFlushEnrichedTraces`|net472|714μs|643ns|2.4μs|0.357| 0|0|3.18&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|461μs|609ns|2.28μs|0| 0|0|2.58&nbsp;KB|
|#3212|`WriteAndFlushEnrichedTraces`|net472|713μs|932ns|3.61μs|0.357| 0|0|3.18&nbsp;KB|
|#3212|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|469μs|418ns|1.62μs|0| 0|0|2.58&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`AllCycleSimpleBody`|net472|186ns|0.168ns|0.652ns|0.0675| 0|0|425&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`AllCycleSimpleBody`|netcoreapp3.1|234ns|0.3ns|1.16ns|0.00591| 0|0|424&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`AllCycleMoreComplexBody`|net472|186ns|0.181ns|0.701ns|0.0637| 0|0|401&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`AllCycleMoreComplexBody`|netcoreapp3.1|233ns|0.252ns|0.975ns|0.0055| 0|0|400&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`BodyExtractorSimpleBody`|net472|266ns|0.611ns|2.37ns|0.0573| 0|0|361&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`BodyExtractorSimpleBody`|netcoreapp3.1|224ns|0.252ns|0.976ns|0.00371| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`BodyExtractorMoreComplexBody`|net472|14.4μs|10ns|38.8ns|1.21| 0.0216|0|7.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`BodyExtractorMoreComplexBody`|netcoreapp3.1|12μs|15.4ns|59.6ns|0.0911| 0|0|6.75&nbsp;KB|
|#3212|`AllCycleSimpleBody`|net472|187ns|0.211ns|0.816ns|0.0676| 0|0|425&nbsp;B|
|#3212|`AllCycleSimpleBody`|netcoreapp3.1|237ns|0.252ns|0.976ns|0.00583| 0|0|424&nbsp;B|
|#3212|`AllCycleMoreComplexBody`|net472|182ns|0.203ns|0.759ns|0.0637| 0|0|401&nbsp;B|
|#3212|`AllCycleMoreComplexBody`|netcoreapp3.1|236ns|0.284ns|1.1ns|0.00543| 0|0|400&nbsp;B|
|#3212|`BodyExtractorSimpleBody`|net472|269ns|0.502ns|1.94ns|0.0573| 0|0|361&nbsp;B|
|#3212|`BodyExtractorSimpleBody`|netcoreapp3.1|236ns|0.166ns|0.642ns|0.00367| 0|0|272&nbsp;B|
|#3212|`BodyExtractorMoreComplexBody`|net472|14.8μs|5.61ns|20.2ns|1.2| 0.0148|0|7.62&nbsp;KB|
|#3212|`BodyExtractorMoreComplexBody`|netcoreapp3.1|12.3μs|18.9ns|70.6ns|0.092| 0|0|6.75&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`SendRequest`|netcoreapp3.1|182μs|344ns|1.33μs|0.181| 0|0|20.57&nbsp;KB|
|#3212|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#3212|`SendRequest`|netcoreapp3.1|181μs|203ns|761ns|0.27| 0|0|20.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`ExecuteNonQuery`|net472|1.76μs|2.75ns|10.7ns|0.15| 0.000883|0|947&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`ExecuteNonQuery`|netcoreapp3.1|1.4μs|1.56ns|6.04ns|0.0127| 0.000706|0|936&nbsp;B|
|#3212|`ExecuteNonQuery`|net472|1.84μs|1.82ns|6.82ns|0.15| 0.000922|0|947&nbsp;B|
|#3212|`ExecuteNonQuery`|netcoreapp3.1|1.44μs|0.826ns|3.09ns|0.0122| 0|0|936&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`CallElasticsearch`|net472|2.6μs|1.88ns|7.29ns|0.184| 0|0|1.16&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`CallElasticsearch`|netcoreapp3.1|1.49μs|1.14ns|4.42ns|0.0149| 0|0|1.1&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`CallElasticsearchAsync`|net472|2.76μs|1.56ns|5.63ns|0.204| 0|0|1.29&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`CallElasticsearchAsync`|netcoreapp3.1|1.62μs|0.554ns|2ns|0.0162| 0|0|1.22&nbsp;KB|
|#3212|`CallElasticsearch`|net472|2.65μs|2.01ns|7.77ns|0.183| 0|0|1.16&nbsp;KB|
|#3212|`CallElasticsearch`|netcoreapp3.1|1.56μs|2.52ns|9.42ns|0.0149| 0|0|1.1&nbsp;KB|
|#3212|`CallElasticsearchAsync`|net472|2.8μs|2.32ns|8.68ns|0.205| 0|0|1.29&nbsp;KB|
|#3212|`CallElasticsearchAsync`|netcoreapp3.1|1.58μs|0.428ns|1.48ns|0.0167| 0|0|1.22&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`ExecuteAsync`|net472|2.81μs|5.38ns|20.1ns|0.225| 0|0|1.42&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`ExecuteAsync`|netcoreapp3.1|1.68μs|2.18ns|8.17ns|0.0185| 0|0|1.34&nbsp;KB|
|#3212|`ExecuteAsync`|net472|2.83μs|7.74ns|30ns|0.225| 0.00139|0|1.42&nbsp;KB|
|#3212|`ExecuteAsync`|netcoreapp3.1|1.68μs|4.06ns|15.7ns|0.0185| 0|0|1.34&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`SendAsync`|net472|5.65μs|17ns|65.8ns|0.44| 0|0|2.77&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`SendAsync`|netcoreapp3.1|3.59μs|5.86ns|22.7ns|0.036| 0|0|2.6&nbsp;KB|
|#3212|`SendAsync`|net472|5.62μs|10.4ns|37.6ns|0.438| 0.00281|0|2.77&nbsp;KB|
|#3212|`SendAsync`|netcoreapp3.1|3.49μs|8.44ns|31.6ns|0.0352| 0|0|2.6&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`EnrichedLog`|net472|3.07μs|1.69ns|6.32ns|0.287| 0|0|1.81&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`EnrichedLog`|netcoreapp3.1|2.51μs|0.875ns|3.15ns|0.0251| 0|0|1.85&nbsp;KB|
|#3212|`EnrichedLog`|net472|3.28μs|4.07ns|15.2ns|0.287| 0|0|1.81&nbsp;KB|
|#3212|`EnrichedLog`|netcoreapp3.1|2.51μs|2.02ns|7.55ns|0.0253| 0|0|1.85&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`EnrichedLog`|net472|152μs|201ns|779ns|0.687| 0.229|0|4.66&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`EnrichedLog`|netcoreapp3.1|115μs|126ns|455ns|0.0576| 0|0|4.49&nbsp;KB|
|#3212|`EnrichedLog`|net472|153μs|185ns|691ns|0.69| 0.23|0|4.65&nbsp;KB|
|#3212|`EnrichedLog`|netcoreapp3.1|118μs|111ns|431ns|0.0586| 0|0|4.49&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`EnrichedLog`|net472|5.59μs|10.2ns|39.4ns|0.569| 0.00279|0|3.59&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`EnrichedLog`|netcoreapp3.1|4.45μs|10.8ns|41.6ns|0.0528| 0.0022|0|3.91&nbsp;KB|
|#3212|`EnrichedLog`|net472|5.58μs|9.82ns|36.7ns|0.569| 0.00279|0|3.59&nbsp;KB|
|#3212|`EnrichedLog`|netcoreapp3.1|4.32μs|8.74ns|33.9ns|0.0541| 0|0|3.91&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`SendReceive`|net472|2.29μs|1.14ns|4.42ns|0.218| 0|0|1.37&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`SendReceive`|netcoreapp3.1|1.85μs|0.765ns|2.96ns|0.0184| 0|0|1.32&nbsp;KB|
|#3212|`SendReceive`|net472|2.46μs|3.26ns|12.6ns|0.218| 0|0|1.37&nbsp;KB|
|#3212|`SendReceive`|netcoreapp3.1|1.87μs|1.07ns|3.99ns|0.0178| 0|0|1.32&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`EnrichedLog`|net472|5.2μs|4.54ns|17.6ns|0.354| 0|0|2.23&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`EnrichedLog`|netcoreapp3.1|4.46μs|1.55ns|5.58ns|0.0246| 0|0|1.8&nbsp;KB|
|#3212|`EnrichedLog`|net472|4.96μs|2.44ns|9.46ns|0.352| 0|0|2.23&nbsp;KB|
|#3212|`EnrichedLog`|netcoreapp3.1|4.34μs|1.82ns|6.79ns|0.0237| 0|0|1.8&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`StartFinishSpan`|net472|1.13μs|0.617ns|2.39ns|0.129| 0|0|810&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`StartFinishSpan`|netcoreapp3.1|969ns|0.382ns|1.43ns|0.0102| 0|0|760&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`StartFinishScope`|net472|1.34μs|0.569ns|2.2ns|0.141| 0|0|891&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`StartFinishScope`|netcoreapp3.1|1.13μs|0.515ns|1.99ns|0.0119| 0|0|880&nbsp;B|
|#3212|`StartFinishSpan`|net472|1.22μs|0.752ns|2.91ns|0.128| 0|0|810&nbsp;B|
|#3212|`StartFinishSpan`|netcoreapp3.1|914ns|0.403ns|1.56ns|0.0101| 0|0|760&nbsp;B|
|#3212|`StartFinishScope`|net472|1.35μs|0.806ns|3.12ns|0.141| 0|0|891&nbsp;B|
|#3212|`StartFinishScope`|netcoreapp3.1|1.06μs|0.612ns|2.29ns|0.0123| 0|0|880&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`RunOnMethodBegin`|net472|1.54μs|0.992ns|3.84ns|0.141| 0|0|891&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42)|`RunOnMethodBegin`|netcoreapp3.1|1.14μs|0.403ns|1.45ns|0.012| 0|0|880&nbsp;B|
|#3212|`RunOnMethodBegin`|net472|1.51μs|0.621ns|2.41ns|0.141| 0|0|891&nbsp;B|
|#3212|`RunOnMethodBegin`|netcoreapp3.1|1.22μs|0.39ns|1.46ns|0.0116| 0|0|880&nbsp;B|
</details>

**Review by andrewlock — APPROVED** [review]
Thanks for doing this 🙂

**Review by OmerRaviv — APPROVED** [review]
LGTM, thanks!

**Review by robertpi — APPROVED** [review]

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #3212 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42) will **not change** line coverage
:heavy_check_mark: Merging #3212 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42) will **not change** branch coverage
:heavy_check_mark: Merging #3212 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42) will **not change** complexity


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42) | #3212       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `17971` / `24517` | `17987` / `24517` |          |
| Lines %   | `73%`      | `73%`      |  `0%` :heavy_check_mark:  |
| Branches  | `10585` / `15050` | `10597` / `15050` |          |
| Branches %| `70%`      | `70%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `16261`      | `16261`        |  `0`  :heavy_check_mark:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=111938&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/111938/artifacts?artifactName=Code%20Coverage%20Report_111938&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3212](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=111996&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/111996/artifacts?artifactName=Code%20Coverage%20Report_111996&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/65c6c4e95b8092d1e4608d482f5e91a8044eaf42) | #3212       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `73%`      | `73%`       |  `0%` :heavy_check_mark:  |
| Branches %| `70%`      | `70%`       |  `0%` :heavy_check_mark:  |
| Complexity| `16261`      | `16261`       |  `0` :heavy_check_mark:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Ci.CIVisibility](https://github.com/DataDog/dd-trace-dotnet/tree/f4d8a90430ecd1ec2fbf64163fb37ba5bd5ad6ab/tracer/src/Datadog.Trace/Ci/CIVisibility.cs) | `5%` :heavy_check_mark: | `6%` :heavy_check_mark:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=111938&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/111938/artifacts?artifactName=Code%20Coverage%20Report_111938&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3212](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=111996&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/111996/artifacts?artifactName=Code%20Coverage%20Report_111996&api-version=6.0&%24format=zip)

**Pull request merged**
