### PR TITLE
Run MSI smoke tests against x86 runtime with the x64 installer

### PR DESCRIPTION
**Pull request by andrewlock**
## Summary of changes

Runs the MSI smoke tests when using the x86 runtime with the x64 MSI installer

## Reason for change

This a scenario we need to support, but we don't currently have any tests for it

## Implementation details

Add an additional entry to the platform test matrix

- x86 installer, x86 runtime
- x64 installer, x64 runtime, 
- x64 installer, x86 runtime `<- New`

## Test coverage

I've manually triggered the smoke tests [here](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=107277&view=results)

## Other details
Prerequisite for the work in #3060

### CODE REVIEW

**Review by zacharycmontoya — APPROVED** [review]
LGTM and we should see the new x64-platform/32-bit-app test case pass

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #3065 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305): 
* 1 benchmarks are **slower**, with geometric mean 1.116
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`WriteAndFlushEnrichedTraces`|net472|722μs|472ns|1.77μs|0.357| 0|0|3.18&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|482μs|204ns|789ns|0| 0|0|2.58&nbsp;KB|
|#3065|`WriteAndFlushEnrichedTraces`|net472|726μs|542ns|2.03μs|0.359| 0|0|3.18&nbsp;KB|
|#3065|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|465μs|395ns|1.53μs|0| 0|0|2.58&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`AllCycleSimpleBody`|net472|1.67μs|1.64ns|6.36ns|0.237| 0|0|1.49&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`AllCycleSimpleBody`|netcoreapp3.1|1.8μs|2.16ns|8.37ns|0.0187| 0|0|1.37&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`AllCycleMoreComplexBody`|net472|17.3μs|11.4ns|42.5ns|1.39| 0.025|0|8.75&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`AllCycleMoreComplexBody`|netcoreapp3.1|14.4μs|47.3ns|183ns|0.106| 0|0|7.85&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`BodyExtractorSimpleBody`|net472|259ns|0.536ns|2.08ns|0.0573| 0|0|361&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`BodyExtractorSimpleBody`|netcoreapp3.1|225ns|0.234ns|0.874ns|0.00361| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`BodyExtractorMoreComplexBody`|net472|15.5μs|9.1ns|35.2ns|1.2| 0.0154|0|7.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`BodyExtractorMoreComplexBody`|netcoreapp3.1|11.9μs|16.9ns|65.6ns|0.0892| 0|0|6.75&nbsp;KB|
|#3065|`AllCycleSimpleBody`|net472|1.79μs|3.24ns|12.5ns|0.237| 0|0|1.49&nbsp;KB|
|#3065|`AllCycleSimpleBody`|netcoreapp3.1|1.81μs|1.63ns|6.31ns|0.018| 0|0|1.37&nbsp;KB|
|#3065|`AllCycleMoreComplexBody`|net472|16.8μs|5.36ns|20.1ns|1.39| 0.0251|0|8.75&nbsp;KB|
|#3065|`AllCycleMoreComplexBody`|netcoreapp3.1|13.8μs|14.9ns|57.8ns|0.103| 0|0|7.85&nbsp;KB|
|#3065|`BodyExtractorSimpleBody`|net472|256ns|0.169ns|0.631ns|0.0573| 0|0|361&nbsp;B|
|#3065|`BodyExtractorSimpleBody`|netcoreapp3.1|221ns|0.202ns|0.757ns|0.00365| 0|0|272&nbsp;B|
|#3065|`BodyExtractorMoreComplexBody`|net472|15μs|11ns|42.7ns|1.21| 0.0149|0|7.62&nbsp;KB|
|#3065|`BodyExtractorMoreComplexBody`|netcoreapp3.1|12.3μs|14.4ns|55.8ns|0.087| 0|0|6.75&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Unknown :shrug: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`SendRequest`|netcoreapp3.1|180μs|285ns|1.03μs|0.268| 0|0|20.33&nbsp;KB|
|#3065|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#3065|`SendRequest`|netcoreapp3.1|178μs|106ns|412ns|0.178| 0|0|20.33&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`ExecuteNonQuery`|net472|1.56μs|0.907ns|3.51ns|0.126| 0.000782|0|794&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`ExecuteNonQuery`|netcoreapp3.1|1.21μs|1.72ns|6.67ns|0.0112| 0|0|824&nbsp;B|
|#3065|`ExecuteNonQuery`|net472|1.53μs|0.572ns|2.14ns|0.126| 0.000766|0|794&nbsp;B|
|#3065|`ExecuteNonQuery`|netcoreapp3.1|1.18μs|0.329ns|1.27ns|0.0112| 0|0|824&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`CallElasticsearch`|net472|2.2μs|0.993ns|3.85ns|0.159| 0|0|1&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`CallElasticsearch`|netcoreapp3.1|1.4μs|1.58ns|5.9ns|0.0131| 0|0|984&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`CallElasticsearchAsync`|net472|2.29μs|0.554ns|2.14ns|0.18| 0|0|1.14&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`CallElasticsearchAsync`|netcoreapp3.1|1.5μs|1.53ns|5.92ns|0.0143| 0|0|1.1&nbsp;KB|
|#3065|`CallElasticsearch`|net472|2.22μs|0.633ns|2.45ns|0.158| 0|0|1&nbsp;KB|
|#3065|`CallElasticsearch`|netcoreapp3.1|1.3μs|0.685ns|2.65ns|0.0131| 0|0|984&nbsp;B|
|#3065|`CallElasticsearchAsync`|net472|2.32μs|0.468ns|1.81ns|0.18| 0|0|1.14&nbsp;KB|
|#3065|`CallElasticsearchAsync`|netcoreapp3.1|1.43μs|0.529ns|1.91ns|0.0151| 0|0|1.1&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`ExecuteAsync`|net472|2.28μs|4.83ns|18.7ns|0.2| 0|0|1.26&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`ExecuteAsync`|netcoreapp3.1|1.52μs|2.24ns|8.39ns|0.0168| 0|0|1.22&nbsp;KB|
|#3065|`ExecuteAsync`|net472|2.45μs|3.03ns|11.7ns|0.2| 0|0|1.26&nbsp;KB|
|#3065|`ExecuteAsync`|netcoreapp3.1|1.61μs|2.21ns|8.56ns|0.0168| 0|0|1.22&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`SendAsync`|net472|4.89μs|10.6ns|40.9ns|0.392| 0|0|2.48&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`SendAsync`|netcoreapp3.1|3.19μs|6.85ns|26.5ns|0.0324| 0|0|2.36&nbsp;KB|
|#3065|`SendAsync`|net472|4.93μs|6.75ns|25.3ns|0.393| 0|0|2.48&nbsp;KB|
|#3065|`SendAsync`|netcoreapp3.1|3.24μs|4.45ns|16.7ns|0.0326| 0|0|2.36&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`EnrichedLog`|net472|2.91μs|1.18ns|4.42ns|0.263| 0|0|1.66&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`EnrichedLog`|netcoreapp3.1|2.36μs|0.712ns|2.76ns|0.0236| 0|0|1.73&nbsp;KB|
|#3065|`EnrichedLog`|net472|2.79μs|0.981ns|3.67ns|0.263| 0|0|1.66&nbsp;KB|
|#3065|`EnrichedLog`|netcoreapp3.1|2.29μs|0.577ns|2.16ns|0.0229| 0|0|1.73&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`EnrichedLog`|net472|146μs|104ns|374ns|0.656| 0.219|0|4.5&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`EnrichedLog`|netcoreapp3.1|113μs|97.4ns|365ns|0.0564| 0|0|4.38&nbsp;KB|
|#3065|`EnrichedLog`|net472|147μs|93.5ns|350ns|0.667| 0.222|0|4.5&nbsp;KB|
|#3065|`EnrichedLog`|netcoreapp3.1|112μs|267ns|1.03μs|0.0547| 0|0|4.38&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`EnrichedLog`|net472|5.27μs|12.5ns|48.5ns|0.544| 0.00266|0|3.43&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`EnrichedLog`|netcoreapp3.1|4.32μs|8.49ns|32.9ns|0.0523| 0|0|3.8&nbsp;KB|
|#3065|`EnrichedLog`|net472|5.36μs|6.44ns|25ns|0.546| 0.00266|0|3.43&nbsp;KB|
|#3065|`EnrichedLog`|netcoreapp3.1|4.22μs|3.59ns|13.9ns|0.0529| 0|0|3.8&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`SendReceive`|net472|2.05μs|0.8ns|2.99ns|0.194| 0|0|1.22&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`SendReceive`|netcoreapp3.1|1.67μs|0.629ns|2.35ns|0.016| 0|0|1.21&nbsp;KB|
|#3065|`SendReceive`|net472|1.99μs|0.371ns|1.34ns|0.194| 0|0|1.22&nbsp;KB|
|#3065|`SendReceive`|netcoreapp3.1|1.8μs|0.667ns|2.49ns|0.0163| 0|0|1.21&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`EnrichedLog`|net472|4.59μs|1.71ns|6.39ns|0.33| 0|0|2.08&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`EnrichedLog`|netcoreapp3.1|4.07μs|1.06ns|4.1ns|0.0222| 0|0|1.69&nbsp;KB|
|#3065|`EnrichedLog`|net472|4.76μs|2.52ns|9.78ns|0.328| 0|0|2.08&nbsp;KB|
|#3065|`EnrichedLog`|netcoreapp3.1|4.15μs|1.18ns|4.59ns|0.023| 0|0|1.69&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #3065

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.SpanBenchmark.StartFinishScope&#8209;netcoreapp3.1 | 1.116 | 858.63 | 957.86 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`StartFinishSpan`|net472|902ns|0.179ns|0.668ns|0.104| 0|0|658&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`StartFinishSpan`|netcoreapp3.1|781ns|0.717ns|2.59ns|0.00887| 0|0|648&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`StartFinishScope`|net472|1.04μs|0.28ns|1.08ns|0.117| 0|0|738&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`StartFinishScope`|netcoreapp3.1|859ns|0.234ns|0.877ns|0.0104| 0|0|768&nbsp;B|
|#3065|`StartFinishSpan`|net472|865ns|0.334ns|1.2ns|0.105| 0|0|658&nbsp;B|
|#3065|`StartFinishSpan`|netcoreapp3.1|745ns|0.251ns|0.973ns|0.00891| 0|0|648&nbsp;B|
|#3065|`StartFinishScope`|net472|1.06μs|0.269ns|1.01ns|0.117| 0|0|738&nbsp;B|
|#3065|`StartFinishScope`|netcoreapp3.1|957ns|0.275ns|1.03ns|0.01| 0|0|768&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`RunOnMethodBegin`|net472|1.22μs|0.224ns|0.777ns|0.117| 0|0|738&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305)|`RunOnMethodBegin`|netcoreapp3.1|1.03μs|0.558ns|2.01ns|0.0103| 0|0|768&nbsp;B|
|#3065|`RunOnMethodBegin`|net472|1.21μs|0.683ns|2.55ns|0.117| 0|0|738&nbsp;B|
|#3065|`RunOnMethodBegin`|netcoreapp3.1|1μs|0.365ns|1.26ns|0.0101| 0|0|768&nbsp;B|
</details>

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #3065 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305) will **not change** line coverage
:heavy_check_mark: Merging #3065 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305) will **not change** branch coverage
:heavy_check_mark: Merging #3065 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305) will **not change** complexity


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305) | #3065       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `16770` / `22876` | `16802` / `22876` |          |
| Lines %   | `73%`      | `73%`      |  `0%` :heavy_check_mark:  |
| Branches  | `9992` / `14196` | `10014` / `14196` |          |
| Branches %| `70%`      | `71%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `15264`      | `15264`        |  `0`  :heavy_check_mark:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=107221&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/107221/artifacts?artifactName=Code%20Coverage%20Report_107221&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3065](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=107280&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/107280/artifacts?artifactName=Code%20Coverage%20Report_107280&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/c8722d2f6362db5765f50a5c8094510461122305) | #3065       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `73%`      | `73%`       |  `0%` :heavy_check_mark:  |
| Branches %| `70%`      | `71%`       |  `0%` :heavy_check_mark:  |
| Complexity| `15264`      | `15264`       |  `0` :heavy_check_mark:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Ci.CIVisibility](https://github.com/DataDog/dd-trace-dotnet/tree/6d2790b08a08f8d78a6247891eb333a024ccf123/tracer/src/Datadog.Trace/Ci/CIVisibility.cs) | `7%` :heavy_check_mark: | `7%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Propagators.SpanContextPropagator](https://github.com/DataDog/dd-trace-dotnet/tree/6d2790b08a08f8d78a6247891eb333a024ccf123/tracer/src/Datadog.Trace/Propagators/SpanContextPropagator.cs) | `8%` :heavy_check_mark: | `6%` :heavy_check_mark:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=107221&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/107221/artifacts?artifactName=Code%20Coverage%20Report_107221&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3065](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=107280&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/107280/artifacts?artifactName=Code%20Coverage%20Report_107280&api-version=6.0&%24format=zip)

**Comment by zacharycmontoya** [comment]
> I've manually triggered the smoke tests [here](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=107277&view=results)

LGTM :shipit:

**Pull request merged**
