### PR TITLE
Add fast lookup for `SpanId` and `LocalRootSpanId`.

### PR DESCRIPTION
**Pull request by macrogreg**
In https://github.com/DataDog/dd-trace-dotnet/pull/1839 we are adding the `LocalRootSpanId` property to `Span` for use by Code Hotspots. Notably, Code Hotspots accesses `SpanId` and `LocalRootSpanId` very frequently. This PR stores those values in local fields to avoid repeated dereferencing. 

Putting it in draft mode for now as it is not clear at this point whether this change would really improve performance.

### CODE REVIEW

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #1831 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/ed0e465a7ca7fc7cec7f7523997c533104961742) will **not change** line coverage
:heavy_check_mark: Merging #1831 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/ed0e465a7ca7fc7cec7f7523997c533104961742) will **not change** branch coverage
:no_entry: Merging #1831 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/ed0e465a7ca7fc7cec7f7523997c533104961742) will will **increase** complexity by `5`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/ed0e465a7ca7fc7cec7f7523997c533104961742) | #1831       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `9445` / `15052` | `9440` / `15054` |          |
| Lines %   | `63%`      | `63%`      |  `0%` :heavy_check_mark:  |
| Branches  | `4168` / `6528` | `4168` / `6534` |          |
| Branches %| `64%`      | `64%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `7690`      | `7695`        |  `5`  :no_entry:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=76570&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/76570/artifacts?artifactName=Code%20Coverage%20Report_76570&api-version=6.0&%24format=zip)  
* [HTML report for this PR #1831](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=76606&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/76606/artifacts?artifactName=Code%20Coverage%20Report_76606&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/ed0e465a7ca7fc7cec7f7523997c533104961742) | #1831       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `63%`      | `63%`       |  `0%` :heavy_check_mark:  |
| Branches %| `64%`      | `64%`       |  `0%` :heavy_check_mark:  |
| Complexity| `7690`      | `7695`       |  `5` :no_entry:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.HttpOverStreams.HttpHeaders](https://github.com/DataDog/dd-trace-dotnet/tree/7ea4d513bc390d2ed2a24268b4cb16c75317494c/tracer/src/Datadog.Trace/HttpOverStreams/HttpHeaders.cs) | `4%` :heavy_check_mark: | `12%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Agent.Transports.HttpStreamResponse](https://github.com/DataDog/dd-trace-dotnet/tree/7ea4d513bc390d2ed2a24268b4cb16c75317494c/tracer/src/Datadog.Trace/Agent/Transports/HttpStreamResponse.cs) | `10%` :heavy_check_mark: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=76570&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/76570/artifacts?artifactName=Code%20Coverage%20Report_76570&api-version=6.0&%24format=zip)  
* [HTML report for this PR #1831](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=76606&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/76606/artifacts?artifactName=Code%20Coverage%20Report_76606&api-version=6.0&%24format=zip)

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #1831 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/ed0e465a7ca7fc7cec7f7523997c533104961742) will **not change** line coverage
:heavy_check_mark: Merging #1831 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/ed0e465a7ca7fc7cec7f7523997c533104961742) will **not change** branch coverage
:no_entry: Merging #1831 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/ed0e465a7ca7fc7cec7f7523997c533104961742) will will **increase** complexity by `5`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/ed0e465a7ca7fc7cec7f7523997c533104961742) | #1831       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `9445` / `15052` | `9445` / `15054` |          |
| Lines %   | `63%`      | `63%`      |  `0%` :heavy_check_mark:  |
| Branches  | `4168` / `6528` | `4176` / `6534` |          |
| Branches %| `64%`      | `64%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `7690`      | `7695`        |  `5`  :no_entry:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=76570&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/76570/artifacts?artifactName=Code%20Coverage%20Report_76570&api-version=6.0&%24format=zip)  
* [HTML report for this PR #1831](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=76613&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/76613/artifacts?artifactName=Code%20Coverage%20Report_76613&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/ed0e465a7ca7fc7cec7f7523997c533104961742) | #1831       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `63%`      | `63%`       |  `0%` :heavy_check_mark:  |
| Branches %| `64%`      | `64%`       |  `0%` :heavy_check_mark:  |
| Complexity| `7690`      | `7695`       |  `5` :no_entry:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.RuntimeMetrics.RuntimeMetricsWriter](https://github.com/DataDog/dd-trace-dotnet/tree/fdfdb0f049400d7d44ea0c30fd1193b7345f9ad3/tracer/src/Datadog.Trace/RuntimeMetrics/RuntimeMetricsWriter.cs) | `0%` :heavy_check_mark: | `-8%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.Helpers.AsyncHelper](https://github.com/DataDog/dd-trace-dotnet/tree/fdfdb0f049400d7d44ea0c30fd1193b7345f9ad3/tracer/src/Datadog.Trace/ClrProfiler/Helpers/AsyncHelper.cs) | `0%` :heavy_check_mark: | `8%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.HttpOverStreams.HttpHeaders](https://github.com/DataDog/dd-trace-dotnet/tree/fdfdb0f049400d7d44ea0c30fd1193b7345f9ad3/tracer/src/Datadog.Trace/HttpOverStreams/HttpHeaders.cs) | `4%` :heavy_check_mark: | `12%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Agent.Transports.HttpStreamResponse](https://github.com/DataDog/dd-trace-dotnet/tree/fdfdb0f049400d7d44ea0c30fd1193b7345f9ad3/tracer/src/Datadog.Trace/Agent/Transports/HttpStreamResponse.cs) | `10%` :heavy_check_mark: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=76570&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/76570/artifacts?artifactName=Code%20Coverage%20Report_76570&api-version=6.0&%24format=zip)  
* [HTML report for this PR #1831](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=76613&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/76613/artifacts?artifactName=Code%20Coverage%20Report_76613&api-version=6.0&%24format=zip)

**Comment by kevingosse** [comment]
I'm not 100% convinced that this results in a net gain, since it's going to make the Span bigger and therefore increase heap allocations in every workflow. Do you have evidence that the benefits of not having to read `Context.TraceContext?.RootSpan.SpanId` are worth making Span bigger?

Rather than guessing, I'd rather put this PR and have code hotspots use `Context.TraceContext?.RootSpan.SpanId`, then we can make the change to measure the difference.

**Comment by macrogreg** [comment]
> [. . .] I'd rather put this PR and have code hotspots use `Context.TraceContext?.RootSpan.SpanId`, then we can make the change to measure the difference.

Hey @kevingosse, this works for me.

For that approach, would you prefer to still add the `LocalRootSpanId` property, just implement it like you suggest, or not add the property at all? In case of not minding it, I would err on the side of adding the property, so that potential future changes are well encapsulated.

**Comment by kevingosse** [comment]
> For that approach, would you prefer to still add the `LocalRootSpanId` property, just implement it like you suggest, or not add the property at all? In case of not minding it, I would err on the side of adding the property, so that potential future changes are well encapsulated.

I really don't mind about the property, I was just worried about the performance impact. If it's not backed by a field then I have no objection 👍

**Comment by macrogreg** [comment]
> But then I'd rather name it `RootSpanId` than `LocalRootSpanId`. I'm not sure what local implies in this context, is there a "non-local" root span somewhere?

I have turned this PR into Draft and created https://github.com/DataDog/dd-trace-dotnet/pull/1839 instead following up on your suggestion to avoid private fields. I created that before I saw your comment on the naming. For the benefit of other reviewers, I will respond there.

**Comment by zacharycmontoya** [comment]
@gleocadie @chrisnas is this draft still needed?

**Comment by gleocadie** [comment]
> @gleocadie @chrisnas is this draft still needed?

**Pull request closed without merging**
