### PR TITLE
Skip loader injection on profiler managed loader

### PR DESCRIPTION
**Pull request by tonyredondo**
This PR fix a crash in WCF applications when using the Tracer and Profiler together by skipping the tracer loader injection in the profiler loader.

@DataDog/apm-dotnet

### CODE REVIEW

**Review by gleocadie — APPROVED** [review]
LGTM

**Review by pierotibou — APPROVED** [review]

**Comment by gleocadie** [comment]
This has been fixed in https://github.com/DataDog/dd-trace-dotnet/pull/2194

**Comment by tonyredondo** [comment]
> This has been fixed in #2194

Where? https://github.com/DataDog/dd-trace-dotnet/blob/release/1.x/tracer/src/Datadog.Trace.ClrProfiler.Native/dd_profiler_constants.h#L74-L80

**Review by zacharycmontoya — APPROVED** [review]

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:no_entry: Merging #2195 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/69527f7c9d20f0c28a04c9b997deecb063685b3c) will will **decrease** line coverage by `6%`
:warning: Merging #2195 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/69527f7c9d20f0c28a04c9b997deecb063685b3c) will will **decrease** branch coverage by `2%`
:no_entry: Merging #2195 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/69527f7c9d20f0c28a04c9b997deecb063685b3c) will will **increase** complexity by `643`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/69527f7c9d20f0c28a04c9b997deecb063685b3c) | #2195       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `9240` / `12704` | `10366` / `15516` |          |
| Lines %   | `73%`      | `67%`      |  `-6%` :no_entry:  |
| Branches  | `4210` / `6206` | `4531` / `6846` |          |
| Branches %| `68%`      | `66%`      |  `-2%` :warning:  |
| Complexity|   `7386`      | `8029`        |  `643`  :no_entry:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=84374&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/84374/artifacts?artifactName=Code%20Coverage%20Report_84374&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2195](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=84387&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/84387/artifacts?artifactName=Code%20Coverage%20Report_84387&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :no_entry:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/69527f7c9d20f0c28a04c9b997deecb063685b3c) | #2195       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `73%`      | `67%`       |  `-6%` :no_entry:  |
| Branches %| `68%`      | `66%`       |  `-2%` :warning:  |
| Complexity| `7386`      | `8029`       |  `643` :no_entry:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Log4Net.AppenderAttachedImplIntegration](https://github.com/DataDog/dd-trace-dotnet/tree/d8ffb0835746a9a3fcc2e315c2fd4a140c08b4ab/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Logging/Log4Net/AppenderAttachedImplIntegration.cs) | `-100%` :no_entry: | `-81%` :no_entry:   | `-2` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Logging.ILogger.LoggerIntegrationCommon](https://github.com/DataDog/dd-trace-dotnet/tree/d8ffb0835746a9a3fcc2e315c2fd4a140c08b4ab/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Logging/ILogger/LoggerIntegrationCommon.cs) | `-43%` :no_entry: | `-50%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.WebRequest.HttpWebRequest_EndGetResponse_Integration](https://github.com/DataDog/dd-trace-dotnet/tree/d8ffb0835746a9a3fcc2e315c2fd4a140c08b4ab/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Http/WebRequest/HttpWebRequest_EndGetResponse_Integration.cs) | `-28%` :no_entry: | `-23%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Logging.ILogger.DatadogLoggingScope](https://github.com/DataDog/dd-trace-dotnet/tree/d8ffb0835746a9a3fcc2e315c2fd4a140c08b4ab/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Logging/ILogger/DatadogLoggingScope.cs) | `-27%` :no_entry: | `-18%` :no_entry:   | `-8` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Http.WebRequest.HttpWebRequest_BeginGetRequestStream_Integration](https://github.com/DataDog/dd-trace-dotnet/tree/d8ffb0835746a9a3fcc2e315c2fd4a140c08b4ab/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Http/WebRequest/HttpWebRequest_BeginGetRequestStream_Integration.cs) | `-14%` :no_entry: | `-20%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.CallTarget.Handlers.BeginMethodHandler`4](https://github.com/DataDog/dd-trace-dotnet/tree/d8ffb0835746a9a3fcc2e315c2fd4a140c08b4ab/tracer/src/Datadog.Trace/ClrProfiler/CallTarget/Handlers/BeginMethodHandler`2.cs) | `-12%` :no_entry: | `0%` :heavy_check_mark:   | `-4` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.AdoNet.AdoNetConstants](https://github.com/DataDog/dd-trace-dotnet/tree/d8ffb0835746a9a3fcc2e315c2fd4a140c08b4ab/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/AdoNet/AdoNetConstants.cs) | `-10%` :no_entry: | `0%` :heavy_check_mark:   | `-1` :heavy_check_mark: |
| [Datadog.Trace.DuckTyping.DuckTypeExtensions](https://github.com/DataDog/dd-trace-dotnet/tree/d8ffb0835746a9a3fcc2e315c2fd4a140c08b4ab/tracer/src/Datadog.Trace/DuckTyping/DuckTypeExtensions.cs) | `-9%` :no_entry: | `-15%` :no_entry:   | `22` :no_entry: |
| [Datadog.Trace.ClrProfiler.CallTarget.Handlers.BeginMethodHandler`10](https://github.com/DataDog/dd-trace-dotnet/tree/d8ffb0835746a9a3fcc2e315c2fd4a140c08b4ab/tracer/src/Datadog.Trace/ClrProfiler/CallTarget/Handlers/BeginMethodHandler`8.cs) | `-9%` :no_entry: | `20%` :heavy_check_mark:   | `-16` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.NUnit.NUnitCompositeWorkItemSkipChildrenIntegration](https://github.com/DataDog/dd-trace-dotnet/tree/d8ffb0835746a9a3fcc2e315c2fd4a140c08b4ab/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Testing/NUnit/NUnitCompositeWorkItemSkipChildrenIntegration.cs) | `-8%` :no_entry: | `-8%` :no_entry:   | `0` :heavy_check_mark: |
| ...And 31 more  | | | |


The following classes were added in #2195:

| File    | Line coverage | Branch coverage | Complexity |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.AsyncLocalCompat\`1](https://github.com/DataDog/dd-trace-dotnet/pull/2195/files) | `100%` | `100%` | `8` |
| [Datadog.Trace.Ci.CITracer](https://github.com/DataDog/dd-trace-dotnet/pull/2195/files) | `100%` | `100%` | `1` |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.AwsConstants](https://github.com/DataDog/dd-trace-dotnet/pull/2195/files) | `0%` | `100%` | `1` |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Elasticsearch.V5.ElasticsearchV5Constants](https://github.com/DataDog/dd-trace-dotnet/pull/2195/files) | `100%` | `100%` | `1` |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Elasticsearch.V6.ElasticsearchV6Constants](https://github.com/DataDog/dd-trace-dotnet/pull/2195/files) | `100%` | `100%` | `1` |
| ...And 68 more  | | | |


65 classes were removed from Datadog.Trace in #2195


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=84374&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/84374/artifacts?artifactName=Code%20Coverage%20Report_84374&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2195](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=84387&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/84387/artifacts?artifactName=Code%20Coverage%20Report_84387&api-version=6.0&%24format=zip)

**Pull request merged**
