### PR TITLE
[Tracer] Kafka - Create or not create, that is the question.

### PR DESCRIPTION
**Pull request by pierotibou**
## Summary of changes
Partially changed the way we handle `DD_TRACE_KAFKA_CREATE_CONSUMER_SCOPE_ENABLED` in the kafka integration for disucssion.

## Reason for change
The description of this config key states: 

> Configuration key to enable or disable the creation of a span context on exiting a successful Kafka Consumer.Consume() call

whereas we were actually always creating a scope, but depending on the flag we were closing it instantly or on the next message consumption.

### CODE REVIEW

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #2871 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`WriteAndFlushEnrichedTraces`|net472|721μs|437ns|1.69μs|0| 0|0|3.16&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|470μs|165ns|573ns|0| 0|0|2.57&nbsp;KB|
|#2871|`WriteAndFlushEnrichedTraces`|net472|733μs|505ns|1.89μs|0| 0|0|3.16&nbsp;KB|
|#2871|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|459μs|109ns|394ns|0| 0|0|2.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`AllCycleSimpleBody`|net472|1.79μs|0.696ns|2.7ns|0.234| 0|0|1.48&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`AllCycleSimpleBody`|netcoreapp3.1|1.85μs|0.596ns|2.07ns|0.0184| 0|0|1.36&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`AllCycleMoreComplexBody`|net472|18.2μs|9.6ns|37.2ns|1.37| 0.0181|0|8.74&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`AllCycleMoreComplexBody`|netcoreapp3.1|14.7μs|5.49ns|19ns|0.103| 0|0|7.84&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`BodyExtractorSimpleBody`|net472|280ns|0.393ns|1.52ns|0.0571| 0|0|361&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`BodyExtractorSimpleBody`|netcoreapp3.1|237ns|0.181ns|0.701ns|0.00369| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`BodyExtractorMoreComplexBody`|net472|15.7μs|7.03ns|26.3ns|1.19| 0.0157|0|7.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`BodyExtractorMoreComplexBody`|netcoreapp3.1|13μs|6.86ns|25.7ns|0.0902| 0|0|6.75&nbsp;KB|
|#2871|`AllCycleSimpleBody`|net472|1.82μs|0.827ns|3.2ns|0.234| 0|0|1.48&nbsp;KB|
|#2871|`AllCycleSimpleBody`|netcoreapp3.1|1.89μs|1.52ns|5.67ns|0.0181| 0|0|1.36&nbsp;KB|
|#2871|`AllCycleMoreComplexBody`|net472|18.1μs|6.54ns|24.5ns|1.37| 0.0181|0|8.74&nbsp;KB|
|#2871|`AllCycleMoreComplexBody`|netcoreapp3.1|14.9μs|3.87ns|14.5ns|0.104| 0|0|7.84&nbsp;KB|
|#2871|`BodyExtractorSimpleBody`|net472|274ns|0.165ns|0.638ns|0.0571| 0|0|361&nbsp;B|
|#2871|`BodyExtractorSimpleBody`|netcoreapp3.1|239ns|0.167ns|0.647ns|0.00373| 0|0|272&nbsp;B|
|#2871|`BodyExtractorMoreComplexBody`|net472|16.2μs|5.44ns|20.4ns|1.2| 0.0162|0|7.62&nbsp;KB|
|#2871|`BodyExtractorMoreComplexBody`|netcoreapp3.1|13μs|6.41ns|24ns|0.0909| 0|0|6.75&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`SendRequest`|netcoreapp3.1|172μs|97.3ns|377ns|0.258| 0|0|19.74&nbsp;KB|
|#2871|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#2871|`SendRequest`|netcoreapp3.1|174μs|169ns|653ns|0.174| 0|0|19.74&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`ExecuteNonQuery`|net472|1.37μs|0.869ns|3.36ns|0.0938| 0.000685|0|594&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`ExecuteNonQuery`|netcoreapp3.1|1.12μs|0.508ns|1.97ns|0.00833| 0|0|632&nbsp;B|
|#2871|`ExecuteNonQuery`|net472|1.41μs|0.812ns|3.14ns|0.0937| 0.000715|0|594&nbsp;B|
|#2871|`ExecuteNonQuery`|netcoreapp3.1|1.07μs|0.507ns|1.96ns|0.00854| 0|0|632&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`CallElasticsearch`|net472|2.02μs|0.829ns|3.21ns|0.126| 0|0|802&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`CallElasticsearch`|netcoreapp3.1|1.31μs|0.849ns|3.29ns|0.0105| 0|0|792&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`CallElasticsearchAsync`|net472|2.21μs|0.548ns|1.98ns|0.147| 0|0|939&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`CallElasticsearchAsync`|netcoreapp3.1|1.32μs|0.459ns|1.78ns|0.012| 0|0|912&nbsp;B|
|#2871|`CallElasticsearch`|net472|2.01μs|1.14ns|4.41ns|0.126| 0|0|802&nbsp;B|
|#2871|`CallElasticsearch`|netcoreapp3.1|1.22μs|0.917ns|3.55ns|0.0111| 0|0|792&nbsp;B|
|#2871|`CallElasticsearchAsync`|net472|2.23μs|0.674ns|2.61ns|0.147| 0|0|939&nbsp;B|
|#2871|`CallElasticsearchAsync`|netcoreapp3.1|1.3μs|0.381ns|1.48ns|0.0121| 0|0|912&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`ExecuteAsync`|net472|2.13μs|3.28ns|12.7ns|0.166| 0|0|1.06&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`ExecuteAsync`|netcoreapp3.1|1.39μs|3.69ns|14.3ns|0.0137| 0|0|1.03&nbsp;KB|
|#2871|`ExecuteAsync`|net472|2.22μs|1.17ns|4.54ns|0.166| 0|0|1.06&nbsp;KB|
|#2871|`ExecuteAsync`|netcoreapp3.1|1.44μs|1.16ns|4.49ns|0.0144| 0|0|1.03&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`SendAsync`|net472|4.68μs|10.1ns|38.9ns|0.356| 0|0|2.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`SendAsync`|netcoreapp3.1|3.35μs|6ns|23.2ns|0.03| 0|0|2.21&nbsp;KB|
|#2871|`SendAsync`|net472|4.85μs|6.25ns|24.2ns|0.357| 0|0|2.28&nbsp;KB|
|#2871|`SendAsync`|netcoreapp3.1|3.26μs|3.39ns|12.7ns|0.0307| 0|0|2.21&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`EnrichedLog`|net472|2.79μs|1.11ns|4.3ns|0.228| 0|0|1.45&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`EnrichedLog`|netcoreapp3.1|2.19μs|0.791ns|2.96ns|0.0207| 0|0|1.53&nbsp;KB|
|#2871|`EnrichedLog`|net472|2.7μs|1.82ns|7.03ns|0.228| 0|0|1.45&nbsp;KB|
|#2871|`EnrichedLog`|netcoreapp3.1|2.13μs|0.8ns|2.99ns|0.0203| 0|0|1.53&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`EnrichedLog`|net472|149μs|141ns|546ns|0.519| 0.148|0|4.29&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`EnrichedLog`|netcoreapp3.1|112μs|83.1ns|311ns|0.0552| 0|0|4.18&nbsp;KB|
|#2871|`EnrichedLog`|net472|148μs|108ns|418ns|0.519| 0.148|0|4.29&nbsp;KB|
|#2871|`EnrichedLog`|netcoreapp3.1|112μs|190ns|735ns|0.0556| 0|0|4.18&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`EnrichedLog`|net472|5.29μs|7.97ns|30.9ns|0.507| 0.00255|0|3.23&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`EnrichedLog`|netcoreapp3.1|4.09μs|5.38ns|20.8ns|0.0486| 0|0|3.6&nbsp;KB|
|#2871|`EnrichedLog`|net472|5.27μs|6.43ns|24.9ns|0.508| 0.00263|0|3.23&nbsp;KB|
|#2871|`EnrichedLog`|netcoreapp3.1|4.04μs|1.95ns|7.02ns|0.0485| 0|0|3.6&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`SendReceive`|net472|1.84μs|0.658ns|2.46ns|0.159| 0|0|1.01&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`SendReceive`|netcoreapp3.1|1.44μs|0.4ns|1.55ns|0.0136| 0|0|1.01&nbsp;KB|
|#2871|`SendReceive`|net472|1.89μs|0.746ns|2.89ns|0.158| 0|0|1.01&nbsp;KB|
|#2871|`SendReceive`|netcoreapp3.1|1.51μs|1.01ns|3.79ns|0.0136| 0|0|1.01&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`EnrichedLog`|net472|4.54μs|1.49ns|5.58ns|0.292| 0|0|1.87&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`EnrichedLog`|netcoreapp3.1|3.93μs|1.55ns|5.79ns|0.0198| 0|0|1.49&nbsp;KB|
|#2871|`EnrichedLog`|net472|4.54μs|0.996ns|3.86ns|0.292| 0|0|1.87&nbsp;KB|
|#2871|`EnrichedLog`|netcoreapp3.1|3.87μs|2.56ns|9.58ns|0.0195| 0|0|1.49&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`StartFinishSpan`|net472|725ns|0.38ns|1.42ns|0.0719| 0|0|457&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`StartFinishSpan`|netcoreapp3.1|643ns|0.281ns|1.09ns|0.00632| 0|0|456&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`StartFinishScope`|net472|1.02μs|0.614ns|2.38ns|0.0842| 0|0|538&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`StartFinishScope`|netcoreapp3.1|790ns|2.06ns|7.97ns|0.00761| 0|0|576&nbsp;B|
|#2871|`StartFinishSpan`|net472|787ns|0.732ns|2.83ns|0.0719| 0|0|457&nbsp;B|
|#2871|`StartFinishSpan`|netcoreapp3.1|628ns|0.358ns|1.34ns|0.00632| 0|0|456&nbsp;B|
|#2871|`StartFinishScope`|net472|968ns|1.16ns|4.47ns|0.0845| 0|0|538&nbsp;B|
|#2871|`StartFinishScope`|netcoreapp3.1|779ns|0.606ns|2.27ns|0.0078| 0|0|576&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`RunOnMethodBegin`|net472|1.11μs|1.16ns|4.5ns|0.0844| 0|0|538&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`RunOnMethodBegin`|netcoreapp3.1|920ns|0.749ns|2.8ns|0.00786| 0|0|576&nbsp;B|
|#2871|`RunOnMethodBegin`|net472|1.09μs|1.24ns|4.79ns|0.0844| 0|0|538&nbsp;B|
|#2871|`RunOnMethodBegin`|netcoreapp3.1|926ns|2.47ns|9.57ns|0.00783| 0|0|576&nbsp;B|
</details>

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #2871 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce) will **not change** line coverage
:heavy_check_mark: Merging #2871 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce) will **not change** branch coverage
:heavy_check_mark: Merging #2871 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce) will will **decrease** complexity by `4`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce) | #2871       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `14699` / `20164` | `14754` / `20162` |          |
| Lines %   | `73%`      | `73%`      |  `0%` :heavy_check_mark:  |
| Branches  | `9008` / `12822` | `9051` / `12818` |          |
| Branches %| `70%`      | `71%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `13673`      | `13669`        |  `-4`  :heavy_check_mark:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=101095&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/101095/artifacts?artifactName=Code%20Coverage%20Report_101095&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2871](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=101173&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/101173/artifacts?artifactName=Code%20Coverage%20Report_101173&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce) | #2871       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `73%`      | `73%`       |  `0%` :heavy_check_mark:  |
| Branches %| `70%`      | `71%`       |  `0%` :heavy_check_mark:  |
| Complexity| `13673`      | `13669`       |  `-4` :heavy_check_mark:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Ci.CIVisibility](https://github.com/DataDog/dd-trace-dotnet/tree/d7e685228bdba54f547bf9c9a28d15e72212f49a/tracer/src/Datadog.Trace/Ci/CIVisibility.cs) | `7%` :heavy_check_mark: | `7%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Telemetry.Transports.JsonTelemetryTransport](https://github.com/DataDog/dd-trace-dotnet/tree/d7e685228bdba54f547bf9c9a28d15e72212f49a/tracer/src/Datadog.Trace/Telemetry/Transports/JsonTelemetryTransport.cs) | `39%` :heavy_check_mark: | `54%` :heavy_check_mark:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=101095&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/101095/artifacts?artifactName=Code%20Coverage%20Report_101095&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2871](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=101173&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/101173/artifacts?artifactName=Code%20Coverage%20Report_101173&api-version=6.0&%24format=zip)

**Review by andrewlock — CHANGES_REQUESTED** [review]
The design of the Kafka integration is to support the common pattern used for consumers e.g.:

```csharp
while(!token.IsCancellationRequested)
{
    // will block until a message is available
    var consumeResult = _consumer.Consume(timeoutMilliSeconds);

    // ... do something with the consumerResult
    DoWork();
}
```

With the existing implementation, the scope is created when `_consumer.Consume()` _finishes_, and is closed when we loop back round the `while` loop and start a new blocking `Consume()` call. That way, the spans created in `DoWork()` are created as _children_ of the `Consume()` call (which they logically are).

With the change in this PR, the spans in `DoWork()` will become disconnected from the `Consume()` call, and hence from the propagated context. I don't think that is something we should do, and is definitely a breaking change.

The other change added in this PR of not creating a span if `KafkaCreateConsumerScopeEnabled=false` is debatable. I'm not passionate about creating it, but it _may_ have value. 

We chose to still create the `Consume` span to make sure we capture any auto headers etc that we should. It also serves as an indication to customers that the auto-instrumentation is actually working (otherwise they would have no way of telling). Arguably, this is another breaking change, but it's a more minor one.

**Comment by pierotibou** [comment]
Thanks Andrew. So If I sumup, we have different use cases:

1.  Do the computation of the message right after consuming the message
2. Enqueuing the message and compute it async
3. Enqueuing the message and compute it async with no access to the enqueuing part of that logic (ie Streamiz use case).

- The first use case is works out of the box. Indeed the span will be opened, any child span will descend from the consume one. We may not close the last consume span though, right?
- Second use case can be handled manually with custom tracing as they could access the active scope.
- The third case works if we do ContextExtraction and that we set `KafkaCreateConsumerScopeEnabled` to false. The only thing is that we get a sibling span. The hierarchy is good as they are indeed called one after the other. 

So the only thing I'd like to do in that case then is to rename the `KafkaCreateConsumerScopeEnabled` parameter as part of 3.0 (as we do create a scope anyway) and add a bit more documentation on this in our public docs.

**Comment by andrewlock** [comment]
> We may not close the last consume span though, right?

There's a _tiny_ possibility we won't, if they've written there consumer code incorrectly. If the consumer is closed or disposed, then we close that span. Realistically, it shouldn't be a problem.

> Do the computation of the message right after consuming the message
> Enqueuing the message and compute it async
> Enqueuing the message and compute it async 

I don't really follow the difference between these three cases. There's only two scenarios in my mind - either they're processing the method immediately (in which case it works out the box), or they're not (in which case they should set `KafkaCreateConsumerScopeEnabled=false` and use the context extractor.

> So the only thing I'd like to do in that case then is to rename the KafkaCreateConsumerScopeEnabled parameter as part of 3.0 (as we do create a scope anyway) and add a bit more documentation on this in our public docs.

We don't document it, so I say rename it now if you have something better, before you document it.

> one could argue we should also align this behaviour with other messaging systems like RabbitMQ? I assume the same scenarios could happen there

_Generally_ yes, but it depends. Some APIs take a `func` to run when a message is received. Those often _don't_ need this approach, as we have natural "start" and "end" points

**Pull request closed without merging**
