### PR TITLE
AgentWriter FlushTracesAsync changes

### PR DESCRIPTION
**Pull request by tonyredondo**
This PR's changes the behavior of the FlushTracesAsync method to enqueue flush continuations per buffer.

@DataDog/apm-dotnet

### CODE REVIEW

**Review by kevingosse — APPROVED** [review]
LGTM. Any chance you could write a unit test that reproduces the flush race condition that you're protecting against? (I'm not sure it's possible, so I'm approving this PR either way)

**Comment by tonyredondo** [comment]
> LGTM. Any chance you could write a unit test that reproduces the flush race condition that you're protecting against? (I'm not sure it's possible, so I'm approving this PR either way)

I'll try, but that's hard.

**Comment by kevingosse** [comment]
> > LGTM. Any chance you could write a unit test that reproduces the flush race condition that you're protecting against? (I'm not sure it's possible, so I'm approving this PR either way)
> 
> I'll try, but that's hard.

I think you can mock the `IApi` and use that to block the first flush. Then invoke another flush. I _think_ before your PR the other flush would complete synchronously.

**Comment by tonyredondo** [comment]
> > > LGTM. Any chance you could write a unit test that reproduces the flush race condition that you're protecting against? (I'm not sure it's possible, so I'm approving this PR either way)
> > 
> > 
> > I'll try, but that's hard.
> 
> I think you can mock the `IApi` and use that to block the first flush. Then invoke another flush. I _think_ that before your PR the other flush would complete synchronously without calling `IApi` again.

Done in https://github.com/DataDog/dd-trace-dotnet/pull/1501/commits/1208bf2bae3a71e06d67cb300a03ce46ac4d13d4

**Review by zacharycmontoya — APPROVED** [review]

**Pull request merged**
