### PR TITLE
Add support for Confluent.Kafka 2.x.x

### PR DESCRIPTION
**Pull request by andrewlock**
## Summary of changes

Updates the integrations to support Confluent.Kafka 2.x.x

## Reason for change

The 2.x version of the package was recently released

## Implementation details

Just bump some numbers. No change to the integrations, so an easy fix.

## Test coverage

Ran the integration tests across all FXs and no issues

## Other details
Spotted in https://github.com/DataDog/dd-trace-dotnet/pull/3691. We should merge this one and then rebase the bot PR

### CODE REVIEW

**Comment by andrewlock** [comment]
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (3710)](https://github.com/DataDog/dd-trace-dotnet/tree/0791d33a6e4ad6875cef836e0d3d1f5f5683907c)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (3710) - mean (3,322ms)  : 3257, 3388
     .   : milestone, 3322,
    master - mean (3,333ms)  : 3252, 3414
     .   : milestone, 3333,

    section CallTarget+Inlining+NGEN
    This PR (3710) - mean (3,320ms)  : 3266, 3375
     .   : milestone, 3320,
    master - mean (3,327ms)  : 3250, 3403
     .   : milestone, 3327,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (3710) - mean (3,376ms)  : 3290, 3461
     .   : milestone, 3376,
    master - mean (3,362ms)  : 3304, 3419
     .   : milestone, 3362,

    section CallTarget+Inlining+NGEN
    This PR (3710) - mean (3,380ms)  : 3287, 3473
     .   : milestone, 3380,
    master - mean (3,376ms)  : 3282, 3470
     .   : milestone, 3376,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (3710) - mean (3,334ms)  : 3255, 3412
     .   : milestone, 3334,
    master - mean (3,357ms)  : 3277, 3436
     .   : milestone, 3357,

    section CallTarget+Inlining+NGEN
    This PR (3710) - mean (3,340ms)  : 3257, 3422
     .   : milestone, 3340,
    master - mean (3,339ms)  : 3258, 3420
     .   : milestone, 3339,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (3710) - mean (199ms)  : 188, 211
     .   : milestone, 199,
    master - mean (198ms)  : 187, 210
     .   : milestone, 198,

    section CallTarget+Inlining+NGEN
    This PR (3710) - mean (198ms)  : 190, 205
     .   : milestone, 198,
    master - mean (200ms)  : 187, 212
     .   : milestone, 200,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (3710) - mean (266ms)  : 243, 289
     .   : milestone, 266,
    master - mean (265ms)  : 250, 281
     .   : milestone, 265,

    section CallTarget+Inlining+NGEN
    This PR (3710) - mean (270ms)  : 256, 285
     .   : milestone, 270,
    master - mean (267ms)  : 249, 285
     .   : milestone, 267,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (3710) - mean (252ms)  : 238, 266
     .   : milestone, 252,
    master - mean (252ms)  : 244, 260
     .   : milestone, 252,

    section CallTarget+Inlining+NGEN
    This PR (3710) - mean (250ms)  : 237, 264
     .   : milestone, 250,
    master - mean (250ms)  : 235, 265
     .   : milestone, 250,

```

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #3710 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c): 
* 1 benchmarks are **faster**, with geometric mean 1.154
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`WriteAndFlushEnrichedTraces`|net472|756μs|439ns|1.7μs|0.374| 0|0|3.22&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|549μs|187ns|700ns|0| 0|0|2.63&nbsp;KB|
|#3710|`WriteAndFlushEnrichedTraces`|net472|767μs|434ns|1.63μs|0.377| 0|0|3.22&nbsp;KB|
|#3710|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|554μs|166ns|642ns|0| 0|0|2.63&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`AllCycleSimpleBody`|net472|26μs|147ns|1.05μs|0.267| 0|0|1.75&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`AllCycleSimpleBody`|netcoreapp3.1|24.4μs|139ns|1.03μs|0.011| 0|0|1.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`AllCycleMoreComplexBody`|net472|196μs|526ns|2.04μs|2.05| 0|0|13&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`AllCycleMoreComplexBody`|netcoreapp3.1|187μs|61.7ns|231ns|0.0899| 0|0|12.07&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`ObjectExtractorSimpleBody`|net472|281ns|0.283ns|1.06ns|0.0573| 0|0|361&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`ObjectExtractorSimpleBody`|netcoreapp3.1|230ns|0.0696ns|0.251ns|0.0037| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`ObjectExtractorMoreComplexBody`|net472|15.6μs|19.3ns|74.9ns|1.21| 0.0155|0|7.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|13.1μs|4.66ns|18.1ns|0.0918| 0|0|6.75&nbsp;KB|
|#3710|`AllCycleSimpleBody`|net472|24.4μs|154ns|1.54μs|0.274| 0|0|1.75&nbsp;KB|
|#3710|`AllCycleSimpleBody`|netcoreapp3.1|23.1μs|49.2ns|190ns|0.0112| 0|0|1.62&nbsp;KB|
|#3710|`AllCycleMoreComplexBody`|net472|194μs|74.4ns|258ns|2.04| 0|0|13&nbsp;KB|
|#3710|`AllCycleMoreComplexBody`|netcoreapp3.1|186μs|434ns|1.68μs|0.0906| 0|0|12.07&nbsp;KB|
|#3710|`ObjectExtractorSimpleBody`|net472|301ns|0.194ns|0.726ns|0.0573| 0|0|361&nbsp;B|
|#3710|`ObjectExtractorSimpleBody`|netcoreapp3.1|232ns|0.122ns|0.473ns|0.00373| 0|0|272&nbsp;B|
|#3710|`ObjectExtractorMoreComplexBody`|net472|15.6μs|18.1ns|70.2ns|1.21| 0.0155|0|7.62&nbsp;KB|
|#3710|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|12.9μs|3.85ns|13.9ns|0.0903| 0|0|6.75&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`SendRequest`|netcoreapp3.1|180μs|196ns|758ns|0.27| 0|0|20.95&nbsp;KB|
|#3710|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#3710|`SendRequest`|netcoreapp3.1|180μs|108ns|404ns|0.269| 0|0|20.95&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`ExecuteNonQuery`|net472|1.58μs|0.749ns|2.8ns|0.163| 0|0|1.03&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`ExecuteNonQuery`|netcoreapp3.1|1.17μs|0.469ns|1.81ns|0.014| 0|0|1.02&nbsp;KB|
|#3710|`ExecuteNonQuery`|net472|1.59μs|0.504ns|1.82ns|0.163| 0.000793|0|1.03&nbsp;KB|
|#3710|`ExecuteNonQuery`|netcoreapp3.1|1.29μs|0.173ns|0.625ns|0.0135| 0|0|1.02&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`CallElasticsearch`|net472|2.26μs|0.808ns|3.13ns|0.196| 0|0|1.24&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`CallElasticsearch`|netcoreapp3.1|1.38μs|0.53ns|1.98ns|0.0158| 0|0|1.18&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`CallElasticsearchAsync`|net472|2.45μs|2.16ns|8.38ns|0.217| 0.00123|0|1.37&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`CallElasticsearchAsync`|netcoreapp3.1|1.46μs|0.425ns|1.65ns|0.0175| 0|0|1.3&nbsp;KB|
|#3710|`CallElasticsearch`|net472|2.22μs|0.575ns|2.15ns|0.196| 0|0|1.24&nbsp;KB|
|#3710|`CallElasticsearch`|netcoreapp3.1|1.36μs|0.766ns|2.97ns|0.0162| 0|0|1.18&nbsp;KB|
|#3710|`CallElasticsearchAsync`|net472|2.53μs|0.68ns|2.63ns|0.218| 0.00126|0|1.37&nbsp;KB|
|#3710|`CallElasticsearchAsync`|netcoreapp3.1|1.39μs|0.435ns|1.68ns|0.0174| 0|0|1.3&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`ExecuteAsync`|net472|2.42μs|1.02ns|3.95ns|0.238| 0.0012|0|1.5&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`ExecuteAsync`|netcoreapp3.1|1.56μs|0.423ns|1.64ns|0.0187| 0|0|1.42&nbsp;KB|
|#3710|`ExecuteAsync`|net472|2.67μs|0.825ns|2.97ns|0.238| 0|0|1.5&nbsp;KB|
|#3710|`ExecuteAsync`|netcoreapp3.1|1.61μs|0.986ns|3.82ns|0.0194| 0|0|1.42&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`SendAsync`|net472|7.03μs|2.17ns|8.42ns|0.558| 0.00351|0|3.52&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`SendAsync`|netcoreapp3.1|4.48μs|1.61ns|6.25ns|0.0428| 0|0|3.21&nbsp;KB|
|#3710|`SendAsync`|net472|7.05μs|2.37ns|9.19ns|0.558| 0|0|3.52&nbsp;KB|
|#3710|`SendAsync`|netcoreapp3.1|4.54μs|1.92ns|6.93ns|0.0431| 0|0|3.21&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`EnrichedLog`|net472|2.67μs|1.49ns|5.37ns|0.302| 0|0|1.9&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`EnrichedLog`|netcoreapp3.1|2μs|0.498ns|1.86ns|0.0261| 0|0|1.93&nbsp;KB|
|#3710|`EnrichedLog`|net472|2.59μs|3.48ns|13ns|0.301| 0|0|1.9&nbsp;KB|
|#3710|`EnrichedLog`|netcoreapp3.1|1.98μs|0.986ns|3.82ns|0.0267| 0|0|1.93&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`EnrichedLog`|net472|145μs|73.6ns|285ns|0.728| 0.218|0|4.74&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`EnrichedLog`|netcoreapp3.1|117μs|322ns|1.25μs|0.0576| 0|0|4.58&nbsp;KB|
|#3710|`EnrichedLog`|net472|146μs|179ns|692ns|0.728| 0.218|0|4.74&nbsp;KB|
|#3710|`EnrichedLog`|netcoreapp3.1|115μs|151ns|583ns|0.0572| 0|0|4.58&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`EnrichedLog`|net472|5.11μs|1.62ns|6.29ns|0.582| 0.00255|0|3.68&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`EnrichedLog`|netcoreapp3.1|3.91μs|3.72ns|13.4ns|0.053| 0|0|4&nbsp;KB|
|#3710|`EnrichedLog`|net472|5.1μs|1.13ns|4.07ns|0.584| 0.00255|0|3.68&nbsp;KB|
|#3710|`EnrichedLog`|netcoreapp3.1|4μs|1.13ns|4.36ns|0.0544| 0|0|4&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`SendReceive`|net472|2.04μs|0.947ns|3.28ns|0.231| 0|0|1.45&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`SendReceive`|netcoreapp3.1|1.66μs|2.74ns|9.89ns|0.0188| 0|0|1.4&nbsp;KB|
|#3710|`SendReceive`|net472|2.2μs|2.56ns|9.57ns|0.23| 0|0|1.45&nbsp;KB|
|#3710|`SendReceive`|netcoreapp3.1|1.68μs|0.529ns|1.91ns|0.0188| 0|0|1.4&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`EnrichedLog`|net472|4.53μs|1.53ns|5.93ns|0.367| 0|0|2.32&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`EnrichedLog`|netcoreapp3.1|3.74μs|1.77ns|6.84ns|0.0262| 0|0|1.89&nbsp;KB|
|#3710|`EnrichedLog`|net472|4.55μs|0.793ns|2.97ns|0.367| 0|0|2.32&nbsp;KB|
|#3710|`EnrichedLog`|netcoreapp3.1|3.67μs|2.03ns|7.58ns|0.0257| 0|0|1.89&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`StartFinishSpan`|net472|1.01μs|0.675ns|2.61ns|0.141| 0|0|891&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`StartFinishSpan`|netcoreapp3.1|763ns|0.294ns|1.1ns|0.0113| 0|0|840&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`StartFinishScope`|net472|1.17μs|0.635ns|2.46ns|0.154| 0|0|971&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`StartFinishScope`|netcoreapp3.1|928ns|0.33ns|1.28ns|0.013| 0|0|960&nbsp;B|
|#3710|`StartFinishSpan`|net472|992ns|0.242ns|0.937ns|0.141| 0|0|891&nbsp;B|
|#3710|`StartFinishSpan`|netcoreapp3.1|742ns|0.409ns|1.47ns|0.0116| 0|0|840&nbsp;B|
|#3710|`StartFinishScope`|net472|1.17μs|0.793ns|3.07ns|0.154| 0|0|971&nbsp;B|
|#3710|`StartFinishScope`|netcoreapp3.1|847ns|0.385ns|1.49ns|0.013| 0|0|960&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Faster :tada: Same allocations :heavy_check_mark:



#### Faster :tada: in #3710

|  Benchmark         | base/diff | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.TraceAnnotationsBenchmark.RunOnMethodBegin&#8209;net472 | 1.154 | 1,370.05 | 1,187.31 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`RunOnMethodBegin`|net472|1.37μs|0.77ns|2.98ns|0.154| 0|0|971&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)|`RunOnMethodBegin`|netcoreapp3.1|972ns|0.217ns|0.781ns|0.0131| 0|0|960&nbsp;B|
|#3710|`RunOnMethodBegin`|net472|1.19μs|0.491ns|1.77ns|0.154| 0|0|971&nbsp;B|
|#3710|`RunOnMethodBegin`|netcoreapp3.1|985ns|0.386ns|1.49ns|0.0128| 0|0|960&nbsp;B|
</details>

**Comment by andrewlock** [comment]
## Throughput/Crank Report:zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (3710)](https://github.com/DataDog/dd-trace-dotnet/tree/0791d33a6e4ad6875cef836e0d3d1f5f5683907c)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/f3170494f24b12bfb547895f47f2b54519d5302c)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/0d56b1d9f25673f5257b1b7df97a3754d2df63f4)
- [benchmarks/2.22.0](https://github.com/DataDog/dd-trace-dotnet/tree/6daab3ac0b9980d03b9b95a80df8a5ea886cf5b5)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (3710) (6.021M)   : 0, 6020590
    master (6.208M)   : 0, 6207627
    benchmarks/2.22.0 (6.297M)   : 0, 6297278
    benchmarks/2.9.0 (6.260M)   : 0, 6259887

    section Instrumented
    This PR (3710) (4.311M)   : 0, 4310560
    master (4.317M)   : 0, 4316588
    benchmarks/2.22.0 (4.224M)   : 0, 4223974
    benchmarks/2.9.0 (4.329M)   : 0, 4329362

    section Trace stats
    master (4.368M)   : 0, 4367610
    benchmarks/2.22.0 (4.214M)   : 0, 4214198

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (3710) (5.386M)   : 0, 5386446
    master (5.191M)   : 0, 5190890
    benchmarks/2.22.0 (5.139M)   : 0, 5138663
    benchmarks/2.9.0 (5.367M)   : 0, 5366658

    section Instrumented
    This PR (3710) (3.554M)   : crit ,0, 3553715
    master (3.753M)   : 0, 3752737
    benchmarks/2.22.0 (3.679M)   : 0, 3678597

    section Trace stats
    master (3.638M)   : 0, 3637651
    benchmarks/2.22.0 (3.555M)   : 0, 3555071

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (3710) (6.015M)   : 0, 6014983
    master (5.881M)   : 0, 5880859
    benchmarks/2.22.0 (5.949M)   : 0, 5948755
    benchmarks/2.9.0 (6.096M)   : 0, 6095590

    section Instrumented
    This PR (3710) (4.106M)   : 0, 4105514
    master (4.067M)   : 0, 4067447
    benchmarks/2.22.0 (4.080M)   : 0, 4080210
    benchmarks/2.9.0 (4.154M)   : 0, 4154113

    section Trace stats
    master (4.113M)   : 0, 4113322
    benchmarks/2.22.0 (4.041M)   : 0, 4041320

```
```mermaid
gantt
    title Throughput Linux x64 (ASM) (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (3710) (3.485M)   : 0, 3485123
    master (3.524M)   : 0, 3523639
    benchmarks/2.22.0 (3.447M)   : 0, 3446636
    benchmarks/2.9.0 (3.665M)   : 0, 3664975

    section No attack
    This PR (3710) (1.229M)   : 0, 1228574
    master (1.232M)   : 0, 1231683
    benchmarks/2.22.0 (1.260M)   : 0, 1260425
    benchmarks/2.9.0 (1.273M)   : 0, 1272820

    section Attack
    This PR (3710) (1.067M)   : 0, 1066625
    master (1.064M)   : 0, 1064010
    benchmarks/2.22.0 (1.081M)   : 0, 1080525
    benchmarks/2.9.0 (1.096M)   : 0, 1095663

    section Blocking
    This PR (3710) (2.090M)   : 0, 2090207
    master (2.114M)   : 0, 2113636
    benchmarks/2.22.0 (2.149M)   : 0, 2148877

```

**Review by zacharycmontoya — APPROVED** [review]
Thanks for updating this!

**Pull request merged**
