### PR TITLE
Remove .bat files from repository root

### PR DESCRIPTION
**Pull request by andrewlock**
This is obviously opinionated, but I don't use them, so noone else does either, right?! 😉 Also, `.bat`, `cmd`? What is this, 1997?

If anyone does use them, they should prob at least be relegated to the `/tracer` folder (they're broken after the tracer move anyway)

@DataDog/apm-dotnet

### CODE REVIEW

**Review by robertpi — APPROVED** [review]

**Review by tonyredondo — APPROVED** [review]

**Review by zacharycmontoya — APPROVED** [review]

**Comment by lucaspimentel** [comment]
I just used `devenv.bat` a few days ago to debug+instrument an ASP.NET app in IISExpress with VS. How do you all do it? 😅

**Review by lucaspimentel — APPROVED** [review]

**Comment by lucaspimentel** [comment]
@andrewlock can we merge this?

**Comment by andrewlock** [comment]
> @andrewlock can we merge this?

Yeah, I held off because I thought you were still using it 😉

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #1763 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/7f08c0c5aea0ec5af899b49f3683e39806219504) will will **increase** line coverage by `4%`
:heavy_check_mark: Merging #1763 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/7f08c0c5aea0ec5af899b49f3683e39806219504) will **not change** branch coverage
:heavy_check_mark: Merging #1763 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/7f08c0c5aea0ec5af899b49f3683e39806219504) will will **decrease** complexity by `575`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/7f08c0c5aea0ec5af899b49f3683e39806219504) | #1763       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `10489` / `15621` | `9089` / `12804` |          |
| Lines %   | `67%`      | `71%`      |  `4%` :heavy_check_mark:  |
| Branches  | `4597` / `6902` | `4058` / `6128` |          |
| Branches %| `67%`      | `66%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `8101`      | `7526`        |  `-575`  :heavy_check_mark:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=81310&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/81310/artifacts?artifactName=Code%20Coverage%20Report_81310&api-version=6.0&%24format=zip)  
* [HTML report for this PR #1763](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=81328&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/81328/artifacts?artifactName=Code%20Coverage%20Report_81328&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/7f08c0c5aea0ec5af899b49f3683e39806219504) | #1763       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `67%`      | `71%`       |  `4%` :heavy_check_mark:  |
| Branches %| `67%`      | `66%`       |  `0%` :heavy_check_mark:  |
| Complexity| `8101`      | `7526`       |  `-575` :heavy_check_mark:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.DuckTyping.DuckTypeProxyMethodsWithGenericParametersNotSupportedInNonPublicInstancesException](https://github.com/DataDog/dd-trace-dotnet/tree/c6120474cda31c27c849d2d1af822383dcded05f/tracer/src/Datadog.Trace/DuckTyping/DuckTypeExceptions.cs) | `-100%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.DuckTyping.DuckTypeTypeIsNotPublicException](https://github.com/DataDog/dd-trace-dotnet/tree/c6120474cda31c27c849d2d1af822383dcded05f/tracer/src/Datadog.Trace/DuckTyping/DuckTypeExceptions.cs) | `-100%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.PlatformHelpers.ServiceFabric](https://github.com/DataDog/dd-trace-dotnet/tree/c6120474cda31c27c849d2d1af822383dcded05f/tracer/src/Datadog.Trace/PlatformHelpers/ServiceFabric.cs) | `-100%` :no_entry: | `0%` :heavy_check_mark:   | `-1` :heavy_check_mark: |
| [Datadog.Trace.AppSec.Transports.Http.IpInfo](https://github.com/DataDog/dd-trace-dotnet/tree/c6120474cda31c27c849d2d1af822383dcded05f/tracer/src/Datadog.Trace/AppSec/Transports/Http/IpInfo.cs) | `-75%` :no_entry: | `0%` :heavy_check_mark:   | `1` :no_entry: |
| [Datadog.Trace.ClrProfiler.Helpers.PointerHelpers](https://github.com/DataDog/dd-trace-dotnet/tree/c6120474cda31c27c849d2d1af822383dcded05f/tracer/src/Datadog.Trace/ClrProfiler/Helpers/PointerHelpers.cs) | `-75%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.AppSec.InstrumentationGatewayEventArgs](https://github.com/DataDog/dd-trace-dotnet/tree/c6120474cda31c27c849d2d1af822383dcded05f/tracer/src/Datadog.Trace/AppSec/InstrumentationGatewayEventArgs.cs) | `-60%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.HttpOverStreams.HttpRequest](https://github.com/DataDog/dd-trace-dotnet/tree/c6120474cda31c27c849d2d1af822383dcded05f/tracer/src/Datadog.Trace/HttpOverStreams/HttpRequest.cs) | `-60%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.HttpOverStreams.HttpResponse](https://github.com/DataDog/dd-trace-dotnet/tree/c6120474cda31c27c849d2d1af822383dcded05f/tracer/src/Datadog.Trace/HttpOverStreams/HttpResponse.cs) | `-50%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Agent.Transports.HttpStreamResponse](https://github.com/DataDog/dd-trace-dotnet/tree/c6120474cda31c27c849d2d1af822383dcded05f/tracer/src/Datadog.Trace/Agent/Transports/HttpStreamResponse.cs) | `-33%` :no_entry: | `0%` :heavy_check_mark:   | `1` :no_entry: |
| [Datadog.Trace.SpanContext](https://github.com/DataDog/dd-trace-dotnet/tree/c6120474cda31c27c849d2d1af822383dcded05f/tracer/src/Datadog.Trace/SpanContext.cs) | `-27%` :no_entry: | `0%` :heavy_check_mark:   | `2` :no_entry: |
| ...And 47 more  | | | |


The following classes were added in #1763:

| File    | Line coverage | Branch coverage | Complexity |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.AppSec.AspNetCore.BlockingMiddleware](https://github.com/DataDog/dd-trace-dotnet/pull/1763/files) | `41%` | `19%` | `25` |
| [Datadog.Trace.AppSec.BlockActionException](https://github.com/DataDog/dd-trace-dotnet/pull/1763/files) | `0%` | `100%` | `4` |
| [Datadog.Trace.AppSec.PageBlockedByAppSecException](https://github.com/DataDog/dd-trace-dotnet/pull/1763/files) | `0%` | `100%` | `4` |
| [Datadog.Trace.Ci.CITracerManager](https://github.com/DataDog/dd-trace-dotnet/pull/1763/files) | `100%` | `100%` | `1` |
| [Datadog.Trace.Ci.CITracerManagerFactory](https://github.com/DataDog/dd-trace-dotnet/pull/1763/files) | `100%` | `100%` | `3` |
| ...And 19 more  | | | |


55 classes were removed from Datadog.Trace in #1763


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=81310&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/81310/artifacts?artifactName=Code%20Coverage%20Report_81310&api-version=6.0&%24format=zip)  
* [HTML report for this PR #1763](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=81328&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/81328/artifacts?artifactName=Code%20Coverage%20Report_81328&api-version=6.0&%24format=zip)

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #1763 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224): 
* 2 benchmarks are **slower**, with geometric mean 1.156
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #1763

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.AgentWriterBenchmark.WriteAndFlushEnrichedTraces&#8209;netcoreapp3.1 | 1.166 | 767,524.00 | 895,018.66 | 
| Benchmarks.Trace.AgentWriterBenchmark.WriteAndFlushEnrichedTraces&#8209;net472 | 1.146 | 965,909.33 | 1,107,159.46 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`WriteAndFlushEnrichedTraces`|net472|965.0&nbsp;μs|10.58&nbsp;μs|9.90&nbsp;μs|0.0000| 0.0000|0.0000|3.09&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|774.1&nbsp;μs|15.19&nbsp;μs|22.26&nbsp;μs|0.0000| 0.0000|0.0000|2.51&nbsp;KB|
|#1763|`WriteAndFlushEnrichedTraces`|net472|1,103.7&nbsp;μs|21.12&nbsp;μs|19.76&nbsp;μs|1.0870| 0.0000|0.0000|12.77&nbsp;KB|
|#1763|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|894.9&nbsp;μs|15.84&nbsp;μs|14.81&nbsp;μs|0.0000| 0.0000|0.0000|11.71&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`SendRequest`|net472|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000| 0.0000|0.0000|0&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`SendRequest`|netcoreapp3.1|315,786.0119&nbsp;ns|5,330.5573&nbsp;ns|8,758.2585&nbsp;ns|0.1510| 0.0000|0.0000|19833&nbsp;B|
|#1763|`SendRequest`|net472|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000| 0.0000|0.0000|0&nbsp;B|
|#1763|`SendRequest`|netcoreapp3.1|292,744.9231&nbsp;ns|5,321.8434&nbsp;ns|5,465.1414&nbsp;ns|0.1437| 0.0000|0.0000|19897&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`ExecuteNonQuery`|net472|2.368&nbsp;μs|0.0458&nbsp;μs|0.0428&nbsp;μs|0.1082| 0.0012|0.0000|682&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`ExecuteNonQuery`|netcoreapp3.1|2.025&nbsp;μs|0.0274&nbsp;μs|0.0256&nbsp;μs|0.0100| 0.0000|0.0000|712&nbsp;B|
|#1763|`ExecuteNonQuery`|net472|2.112&nbsp;μs|0.0408&nbsp;μs|0.0341&nbsp;μs|0.1083| 0.0011|0.0000|682&nbsp;B|
|#1763|`ExecuteNonQuery`|netcoreapp3.1|1.961&nbsp;μs|0.0310&nbsp;μs|0.0275&nbsp;μs|0.0096| 0.0000|0.0000|712&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`CallElasticsearch`|net472|3.372&nbsp;μs|0.0528&nbsp;μs|0.0494&nbsp;μs|0.1272| 0.0000|0.0000|827&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`CallElasticsearch`|netcoreapp3.1|1.632&nbsp;μs|0.0172&nbsp;μs|0.0161&nbsp;μs|0.0108| 0.0000|0.0000|768&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`CallElasticsearchAsync`|net472|3.686&nbsp;μs|0.0488&nbsp;μs|0.0456&nbsp;μs|0.1488| 0.0000|0.0000|963&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`CallElasticsearchAsync`|netcoreapp3.1|1.796&nbsp;μs|0.0204&nbsp;μs|0.0190&nbsp;μs|0.0126| 0.0000|0.0000|888&nbsp;B|
|#1763|`CallElasticsearch`|net472|3.285&nbsp;μs|0.0601&nbsp;μs|0.1021&nbsp;μs|0.1286| 0.0000|0.0000|827&nbsp;B|
|#1763|`CallElasticsearch`|netcoreapp3.1|1.733&nbsp;μs|0.0190&nbsp;μs|0.0178&nbsp;μs|0.0110| 0.0000|0.0000|768&nbsp;B|
|#1763|`CallElasticsearchAsync`|net472|3.437&nbsp;μs|0.0570&nbsp;μs|0.0534&nbsp;μs|0.1491| 0.0000|0.0000|963&nbsp;B|
|#1763|`CallElasticsearchAsync`|netcoreapp3.1|1.755&nbsp;μs|0.0253&nbsp;μs|0.0224&nbsp;μs|0.0125| 0.0000|0.0000|888&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`ExecuteAsync`|net472|3.719&nbsp;μs|0.0700&nbsp;μs|0.0655&nbsp;μs|0.1681| 0.0000|0.0000|1083&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`ExecuteAsync`|netcoreapp3.1|1.944&nbsp;μs|0.0330&nbsp;μs|0.0309&nbsp;μs|0.0144| 0.0000|0.0000|1008&nbsp;B|
|#1763|`ExecuteAsync`|net472|3.869&nbsp;μs|0.0761&nbsp;μs|0.1466&nbsp;μs|0.1677| 0.0000|0.0000|1083&nbsp;B|
|#1763|`ExecuteAsync`|netcoreapp3.1|1.937&nbsp;μs|0.0385&nbsp;μs|0.0611&nbsp;μs|0.0139| 0.0000|0.0000|1008&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`SendAsync`|net472|6.409&nbsp;μs|0.1117&nbsp;μs|0.1045&nbsp;μs|0.3511| 0.0000|0.0000|2.19&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`SendAsync`|netcoreapp3.1|4.476&nbsp;μs|0.0548&nbsp;μs|0.0513&nbsp;μs|0.0288| 0.0000|0.0000|2.09&nbsp;KB|
|#1763|`SendAsync`|net472|6.340&nbsp;μs|0.1227&nbsp;μs|0.1596&nbsp;μs|0.3495| 0.0000|0.0000|2.19&nbsp;KB|
|#1763|`SendAsync`|netcoreapp3.1|4.337&nbsp;μs|0.0512&nbsp;μs|0.0479&nbsp;μs|0.0301| 0.0000|0.0000|2.09&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`EnrichedLog`|net472|4.007&nbsp;μs|0.0682&nbsp;μs|0.0638&nbsp;μs|0.2873| 0.0000|0.0000|1.79&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`EnrichedLog`|netcoreapp3.1|3.879&nbsp;μs|0.0379&nbsp;μs|0.0317&nbsp;μs|0.0267| 0.0000|0.0000|1.94&nbsp;KB|
|#1763|`EnrichedLog`|net472|4.011&nbsp;μs|0.0720&nbsp;μs|0.0673&nbsp;μs|0.2861| 0.0000|0.0000|1.79&nbsp;KB|
|#1763|`EnrichedLog`|netcoreapp3.1|4.025&nbsp;μs|0.0424&nbsp;μs|0.0376&nbsp;μs|0.0281| 0.0000|0.0000|1.94&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`EnrichedLog`|net472|178.6&nbsp;μs|1.04&nbsp;μs|0.81&nbsp;μs|0.7082| 0.2656|0.0000|5.23&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`EnrichedLog`|netcoreapp3.1|151.0&nbsp;μs|2.28&nbsp;μs|2.13&nbsp;μs|0.0728| 0.0000|0.0000|5.05&nbsp;KB|
|#1763|`EnrichedLog`|net472|183.5&nbsp;μs|3.63&nbsp;μs|3.57&nbsp;μs|0.7062| 0.2648|0.0000|5.23&nbsp;KB|
|#1763|`EnrichedLog`|netcoreapp3.1|151.1&nbsp;μs|1.72&nbsp;μs|1.61&nbsp;μs|0.0740| 0.0000|0.0000|5.05&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`EnrichedLog`|net472|12.41&nbsp;μs|0.242&nbsp;μs|0.339&nbsp;μs|0.8521| 0.0000|0.0000|5.31&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`EnrichedLog`|netcoreapp3.1|10.74&nbsp;μs|0.214&nbsp;μs|0.339&nbsp;μs|0.0895| 0.0000|0.0000|6.28&nbsp;KB|
|#1763|`EnrichedLog`|net472|12.01&nbsp;μs|0.236&nbsp;μs|0.431&nbsp;μs|0.8513| 0.0000|0.0000|5.31&nbsp;KB|
|#1763|`EnrichedLog`|netcoreapp3.1|10.28&nbsp;μs|0.113&nbsp;μs|0.105&nbsp;μs|0.0902| 0.0000|0.0000|6.28&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`SendReceive`|net472|2.341&nbsp;μs|0.0405&nbsp;μs|0.0378&nbsp;μs|0.1551| 0.0000|0.0000|987&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`SendReceive`|netcoreapp3.1|2.003&nbsp;μs|0.0217&nbsp;μs|0.0192&nbsp;μs|0.0131| 0.0000|0.0000|984&nbsp;B|
|#1763|`SendReceive`|net472|2.258&nbsp;μs|0.0445&nbsp;μs|0.0624&nbsp;μs|0.1545| 0.0000|0.0000|987&nbsp;B|
|#1763|`SendReceive`|netcoreapp3.1|1.981&nbsp;μs|0.0243&nbsp;μs|0.0227&nbsp;μs|0.0138| 0.0000|0.0000|984&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`EnrichedLog`|net472|8.574&nbsp;μs|0.1218&nbsp;μs|0.1139&nbsp;μs|0.4447| 0.0000|0.0000|2.8&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`EnrichedLog`|netcoreapp3.1|7.060&nbsp;μs|0.1075&nbsp;μs|0.1005&nbsp;μs|0.0384| 0.0000|0.0000|2.61&nbsp;KB|
|#1763|`EnrichedLog`|net472|8.617&nbsp;μs|0.1708&nbsp;μs|0.3993&nbsp;μs|0.4462| 0.0000|0.0000|2.8&nbsp;KB|
|#1763|`EnrichedLog`|netcoreapp3.1|7.629&nbsp;μs|0.1224&nbsp;μs|0.1085&nbsp;μs|0.0354| 0.0000|0.0000|2.61&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`StartFinishSpan`|net472|938.1&nbsp;ns|12.39&nbsp;ns|11.59&nbsp;ns|0.0680| 0.0000|0.0000|433&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`StartFinishSpan`|netcoreapp3.1|888.7&nbsp;ns|11.83&nbsp;ns|10.49&nbsp;ns|0.0059| 0.0000|0.0000|432&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`StartFinishScope`|net472|1,073.1&nbsp;ns|12.23&nbsp;ns|10.84&nbsp;ns|0.0803| 0.0000|0.0000|514&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/01ac9090482adefc9566e6f3c496220694508224)|`StartFinishScope`|netcoreapp3.1|1,065.2&nbsp;ns|16.06&nbsp;ns|15.02&nbsp;ns|0.0074| 0.0000|0.0000|552&nbsp;B|
|#1763|`StartFinishSpan`|net472|923.1&nbsp;ns|17.09&nbsp;ns|16.78&nbsp;ns|0.0679| 0.0000|0.0000|433&nbsp;B|
|#1763|`StartFinishSpan`|netcoreapp3.1|895.0&nbsp;ns|9.30&nbsp;ns|8.70&nbsp;ns|0.0060| 0.0000|0.0000|432&nbsp;B|
|#1763|`StartFinishScope`|net472|1,100.1&nbsp;ns|19.88&nbsp;ns|18.60&nbsp;ns|0.0803| 0.0000|0.0000|514&nbsp;B|
|#1763|`StartFinishScope`|netcoreapp3.1|1,054.8&nbsp;ns|20.82&nbsp;ns|24.79&nbsp;ns|0.0078| 0.0000|0.0000|552&nbsp;B|
</details>

**Pull request merged**
