### PR TITLE
Fix snapshot filenames for ASP.NET and OWIN tests

### PR DESCRIPTION
**Pull request by zacharycmontoya**
Remove the CallSite and CallTarget qualifier in the snapshot test names
- AspNetMvc4Tests
- AspNetMvc5Tests
- AspNetWebApi2Tests
- OwinWebApi2Tests

@DataDog/apm-dotnet

### CODE REVIEW

**Review by andrewlock — APPROVED** [review]
This change implies the CallTarget and CallSite snapshots are identical? If so, we should remove the suffix entirely, and delete half of the snapshots 🙂

**Comment by robertpi** [comment]
I have to admit, this scared me a bit
2021-10-13 18_06_20-Fix snapshot filenames for ASP NET and OWIN tests by zacharycmontoya · Pull Requ
:

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #1871 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609): 
* 1 benchmarks are **faster**, with geometric mean 1.188
* 1 benchmarks are **slower**, with geometric mean 1.143
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`WriteAndFlushEnrichedTraces`|net472|956.5&nbsp;μs|16.50&nbsp;μs|16.95&nbsp;μs|0.0000| 0.0000|0.0000|3.09&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|728.9&nbsp;μs|12.86&nbsp;μs|17.17&nbsp;μs|0.0000| 0.0000|0.0000|2.51&nbsp;KB|
|#1871|`WriteAndFlushEnrichedTraces`|net472|948.9&nbsp;μs|18.55&nbsp;μs|21.36&nbsp;μs|0.0000| 0.0000|0.0000|3.09&nbsp;KB|
|#1871|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|765.6&nbsp;μs|14.13&nbsp;μs|15.70&nbsp;μs|0.0000| 0.0000|0.0000|2.51&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`SendRequest`|net472|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000| 0.0000|0.0000|0&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`SendRequest`|netcoreapp3.1|288,145.4104&nbsp;ns|5,575.7681&nbsp;ns|5,966.0094&nbsp;ns|0.1450| 0.0000|0.0000|19777&nbsp;B|
|#1871|`SendRequest`|net472|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000| 0.0000|0.0000|0&nbsp;B|
|#1871|`SendRequest`|netcoreapp3.1|291,500.5021&nbsp;ns|5,533.4797&nbsp;ns|6,150.4480&nbsp;ns|0.1430| 0.0000|0.0000|19778&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`ExecuteNonQuery`|net472|2.004&nbsp;μs|0.0378&nbsp;μs|0.0353&nbsp;μs|0.1082| 0.0010|0.0000|682&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`ExecuteNonQuery`|netcoreapp3.1|1.889&nbsp;μs|0.0375&nbsp;μs|0.0351&nbsp;μs|0.0102| 0.0000|0.0000|712&nbsp;B|
|#1871|`ExecuteNonQuery`|net472|1.979&nbsp;μs|0.0395&nbsp;μs|0.0470&nbsp;μs|0.1078| 0.0010|0.0000|682&nbsp;B|
|#1871|`ExecuteNonQuery`|netcoreapp3.1|1.942&nbsp;μs|0.0279&nbsp;μs|0.0261&nbsp;μs|0.0096| 0.0000|0.0000|712&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`CallElasticsearch`|net472|3.104&nbsp;μs|0.0602&nbsp;μs|0.0883&nbsp;μs|0.1284| 0.0000|0.0000|827&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`CallElasticsearch`|netcoreapp3.1|1.595&nbsp;μs|0.0315&nbsp;μs|0.0375&nbsp;μs|0.0109| 0.0000|0.0000|768&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`CallElasticsearchAsync`|net472|3.324&nbsp;μs|0.0642&nbsp;μs|0.0788&nbsp;μs|0.1501| 0.0000|0.0000|963&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`CallElasticsearchAsync`|netcoreapp3.1|1.678&nbsp;μs|0.0331&nbsp;μs|0.0354&nbsp;μs|0.0126| 0.0000|0.0000|888&nbsp;B|
|#1871|`CallElasticsearch`|net472|3.126&nbsp;μs|0.0596&nbsp;μs|0.0663&nbsp;μs|0.1283| 0.0000|0.0000|827&nbsp;B|
|#1871|`CallElasticsearch`|netcoreapp3.1|1.557&nbsp;μs|0.0305&nbsp;μs|0.0351&nbsp;μs|0.0100| 0.0000|0.0000|768&nbsp;B|
|#1871|`CallElasticsearchAsync`|net472|3.489&nbsp;μs|0.0654&nbsp;μs|0.0612&nbsp;μs|0.1485| 0.0000|0.0000|963&nbsp;B|
|#1871|`CallElasticsearchAsync`|netcoreapp3.1|1.743&nbsp;μs|0.0342&nbsp;μs|0.0366&nbsp;μs|0.0120| 0.0000|0.0000|888&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`ExecuteAsync`|net472|3.513&nbsp;μs|0.0602&nbsp;μs|0.0563&nbsp;μs|0.1692| 0.0000|0.0000|1083&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`ExecuteAsync`|netcoreapp3.1|1.826&nbsp;μs|0.0197&nbsp;μs|0.0184&nbsp;μs|0.0140| 0.0000|0.0000|1008&nbsp;B|
|#1871|`ExecuteAsync`|net472|3.456&nbsp;μs|0.0687&nbsp;μs|0.0818&nbsp;μs|0.1689| 0.0000|0.0000|1083&nbsp;B|
|#1871|`ExecuteAsync`|netcoreapp3.1|1.886&nbsp;μs|0.0371&nbsp;μs|0.0397&nbsp;μs|0.0138| 0.0000|0.0000|1008&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`SendAsync`|net472|6.013&nbsp;μs|0.0675&nbsp;μs|0.0564&nbsp;μs|0.3482| 0.0000|0.0000|2.19&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`SendAsync`|netcoreapp3.1|4.704&nbsp;μs|0.0689&nbsp;μs|0.0645&nbsp;μs|0.0301| 0.0000|0.0000|2.09&nbsp;KB|
|#1871|`SendAsync`|net472|6.031&nbsp;μs|0.1177&nbsp;μs|0.1356&nbsp;μs|0.3503| 0.0000|0.0000|2.19&nbsp;KB|
|#1871|`SendAsync`|netcoreapp3.1|4.238&nbsp;μs|0.0791&nbsp;μs|0.0777&nbsp;μs|0.0298| 0.0000|0.0000|2.09&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Faster :tada: Same allocations :heavy_check_mark:



#### Faster :tada: in #1871

|  Benchmark         | base/diff | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.ILoggerBenchmark.EnrichedLog&#8209;net472 | 1.188 | 4,637.78 | 3,903.24 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`EnrichedLog`|net472|4.636&nbsp;μs|0.0634&nbsp;μs|0.0594&nbsp;μs|0.2868| 0.0000|0.0000|1.79&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`EnrichedLog`|netcoreapp3.1|3.630&nbsp;μs|0.0670&nbsp;μs|0.0627&nbsp;μs|0.0280| 0.0000|0.0000|1.94&nbsp;KB|
|#1871|`EnrichedLog`|net472|3.910&nbsp;μs|0.0725&nbsp;μs|0.0679&nbsp;μs|0.2871| 0.0000|0.0000|1.79&nbsp;KB|
|#1871|`EnrichedLog`|netcoreapp3.1|3.587&nbsp;μs|0.0386&nbsp;μs|0.0361&nbsp;μs|0.0275| 0.0000|0.0000|1.94&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`EnrichedLog`|net472|180.6&nbsp;μs|3.55&nbsp;μs|6.58&nbsp;μs|0.7052| 0.2645|0.0000|5.23&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`EnrichedLog`|netcoreapp3.1|150.9&nbsp;μs|2.33&nbsp;μs|1.95&nbsp;μs|0.0757| 0.0000|0.0000|5.05&nbsp;KB|
|#1871|`EnrichedLog`|net472|172.0&nbsp;μs|2.46&nbsp;μs|2.30&nbsp;μs|0.6944| 0.2604|0.0000|5.23&nbsp;KB|
|#1871|`EnrichedLog`|netcoreapp3.1|150.3&nbsp;μs|2.65&nbsp;μs|2.83&nbsp;μs|0.0000| 0.0000|0.0000|5.05&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`EnrichedLog`|net472|11.31&nbsp;μs|0.224&nbsp;μs|0.210&nbsp;μs|0.8505| 0.0000|0.0000|5.31&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`EnrichedLog`|netcoreapp3.1|10.48&nbsp;μs|0.135&nbsp;μs|0.126&nbsp;μs|0.0885| 0.0000|0.0000|6.28&nbsp;KB|
|#1871|`EnrichedLog`|net472|11.190&nbsp;μs|0.1643&nbsp;μs|0.1537&nbsp;μs|0.8518| 0.0000|0.0000|5.31&nbsp;KB|
|#1871|`EnrichedLog`|netcoreapp3.1|9.927&nbsp;μs|0.1213&nbsp;μs|0.1013&nbsp;μs|0.0882| 0.0000|0.0000|6.28&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #1871

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.RedisBenchmark.SendReceive&#8209;net472 | 1.143 | 2,304.53 | 2,633.30 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`SendReceive`|net472|2.293&nbsp;μs|0.0428&nbsp;μs|0.0420&nbsp;μs|0.1541| 0.0000|0.0000|987&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`SendReceive`|netcoreapp3.1|2.029&nbsp;μs|0.0302&nbsp;μs|0.0283&nbsp;μs|0.0140| 0.0000|0.0000|984&nbsp;B|
|#1871|`SendReceive`|net472|2.634&nbsp;μs|0.0317&nbsp;μs|0.0297&nbsp;μs|0.1538| 0.0000|0.0000|987&nbsp;B|
|#1871|`SendReceive`|netcoreapp3.1|1.897&nbsp;μs|0.0320&nbsp;μs|0.0299&nbsp;μs|0.0137| 0.0000|0.0000|984&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`EnrichedLog`|net472|8.044&nbsp;μs|0.1409&nbsp;μs|0.1318&nbsp;μs|0.4465| 0.0000|0.0000|2.8&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`EnrichedLog`|netcoreapp3.1|7.306&nbsp;μs|0.1380&nbsp;μs|0.1417&nbsp;μs|0.0389| 0.0000|0.0000|2.61&nbsp;KB|
|#1871|`EnrichedLog`|net472|7.591&nbsp;μs|0.1276&nbsp;μs|0.1131&nbsp;μs|0.4460| 0.0000|0.0000|2.8&nbsp;KB|
|#1871|`EnrichedLog`|netcoreapp3.1|6.967&nbsp;μs|0.1381&nbsp;μs|0.1224&nbsp;μs|0.0364| 0.0000|0.0000|2.61&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`StartFinishSpan`|net472|910.5&nbsp;ns|18.17&nbsp;ns|28.81&nbsp;ns|0.0681| 0.0000|0.0000|433&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`StartFinishSpan`|netcoreapp3.1|885.6&nbsp;ns|17.12&nbsp;ns|20.38&nbsp;ns|0.0061| 0.0000|0.0000|432&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`StartFinishScope`|net472|1,094.0&nbsp;ns|21.54&nbsp;ns|33.54&nbsp;ns|0.0805| 0.0000|0.0000|514&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/05a12d301e1381942bbbab67a5a79413dd03b609)|`StartFinishScope`|netcoreapp3.1|1,028.6&nbsp;ns|17.65&nbsp;ns|16.51&nbsp;ns|0.0079| 0.0000|0.0000|552&nbsp;B|
|#1871|`StartFinishSpan`|net472|859.2&nbsp;ns|13.79&nbsp;ns|12.23&nbsp;ns|0.0679| 0.0000|0.0000|433&nbsp;B|
|#1871|`StartFinishSpan`|netcoreapp3.1|858.8&nbsp;ns|11.24&nbsp;ns|10.51&nbsp;ns|0.0060| 0.0000|0.0000|432&nbsp;B|
|#1871|`StartFinishScope`|net472|1,002.5&nbsp;ns|12.94&nbsp;ns|11.47&nbsp;ns|0.0808| 0.0000|0.0000|514&nbsp;B|
|#1871|`StartFinishScope`|netcoreapp3.1|993.6&nbsp;ns|9.90&nbsp;ns|8.78&nbsp;ns|0.0076| 0.0000|0.0000|552&nbsp;B|
</details>

**Comment by zacharycmontoya** [comment]
Closing this because

1. Many of these changes will already take place with `release/2.0`
2. Upgrading Verify to allow multiple tests to use the same snapshot introduces a bunch of other errors

**Pull request closed without merging**
