### PR TITLE
[Tracer] Support MySqlConnector from version 0.61.0

### PR DESCRIPTION
**Pull request by pierotibou**
## Summary of changes
Supporting MySQLConnector from version 0.61.0

## Reason for change
Was mentioned in APMS-7365 and didn't seem to be a lot of work

## Implementation details
Prior to version 1, the interfaces look relatively stable and only the namespace changes.

## Test coverage
Tried to run a pipeline with comprehensive testing (anyway not used anymore on the merge to master so not mandatory). I haven't been able to make it work so far as I've unrelated issues with Graphql versions that I need to understand but that are unrelevant to this PR

### CODE REVIEW

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #2870 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`WriteAndFlushEnrichedTraces`|net472|721μs|437ns|1.69μs|0| 0|0|3.16&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|470μs|165ns|573ns|0| 0|0|2.57&nbsp;KB|
|#2870|`WriteAndFlushEnrichedTraces`|net472|727μs|472ns|1.83μs|0| 0|0|3.16&nbsp;KB|
|#2870|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|472μs|318ns|1.15μs|0| 0|0|2.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`AllCycleSimpleBody`|net472|1.79μs|0.696ns|2.7ns|0.234| 0|0|1.48&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`AllCycleSimpleBody`|netcoreapp3.1|1.85μs|0.596ns|2.07ns|0.0184| 0|0|1.36&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`AllCycleMoreComplexBody`|net472|18.2μs|9.6ns|37.2ns|1.37| 0.0181|0|8.74&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`AllCycleMoreComplexBody`|netcoreapp3.1|14.7μs|5.49ns|19ns|0.103| 0|0|7.84&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`BodyExtractorSimpleBody`|net472|280ns|0.393ns|1.52ns|0.0571| 0|0|361&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`BodyExtractorSimpleBody`|netcoreapp3.1|237ns|0.181ns|0.701ns|0.00369| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`BodyExtractorMoreComplexBody`|net472|15.7μs|7.03ns|26.3ns|1.19| 0.0157|0|7.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`BodyExtractorMoreComplexBody`|netcoreapp3.1|13μs|6.86ns|25.7ns|0.0902| 0|0|6.75&nbsp;KB|
|#2870|`AllCycleSimpleBody`|net472|1.85μs|2.25ns|8.43ns|0.233| 0|0|1.48&nbsp;KB|
|#2870|`AllCycleSimpleBody`|netcoreapp3.1|1.91μs|1.14ns|4.43ns|0.0181| 0|0|1.36&nbsp;KB|
|#2870|`AllCycleMoreComplexBody`|net472|18.1μs|9.23ns|35.8ns|1.37| 0.0181|0|8.74&nbsp;KB|
|#2870|`AllCycleMoreComplexBody`|netcoreapp3.1|15.3μs|13ns|50.4ns|0.107| 0|0|7.84&nbsp;KB|
|#2870|`BodyExtractorSimpleBody`|net472|261ns|0.152ns|0.59ns|0.0571| 0|0|361&nbsp;B|
|#2870|`BodyExtractorSimpleBody`|netcoreapp3.1|237ns|0.0724ns|0.261ns|0.00364| 0|0|272&nbsp;B|
|#2870|`BodyExtractorMoreComplexBody`|net472|16.8μs|6.63ns|25.7ns|1.19| 0.0168|0|7.62&nbsp;KB|
|#2870|`BodyExtractorMoreComplexBody`|netcoreapp3.1|13.1μs|3.55ns|13.3ns|0.0919| 0|0|6.75&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Unknown :shrug: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`SendRequest`|netcoreapp3.1|172μs|97.3ns|377ns|0.258| 0|0|19.74&nbsp;KB|
|#2870|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#2870|`SendRequest`|netcoreapp3.1|173μs|102ns|383ns|0.262| 0|0|19.74&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`ExecuteNonQuery`|net472|1.37μs|0.869ns|3.36ns|0.0938| 0.000685|0|594&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`ExecuteNonQuery`|netcoreapp3.1|1.12μs|0.508ns|1.97ns|0.00833| 0|0|632&nbsp;B|
|#2870|`ExecuteNonQuery`|net472|1.36μs|0.883ns|3.31ns|0.0943| 0.000683|0|594&nbsp;B|
|#2870|`ExecuteNonQuery`|netcoreapp3.1|1.15μs|0.582ns|2.18ns|0.00859| 0|0|632&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`CallElasticsearch`|net472|2.02μs|0.829ns|3.21ns|0.126| 0|0|802&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`CallElasticsearch`|netcoreapp3.1|1.31μs|0.849ns|3.29ns|0.0105| 0|0|792&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`CallElasticsearchAsync`|net472|2.21μs|0.548ns|1.98ns|0.147| 0|0|939&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`CallElasticsearchAsync`|netcoreapp3.1|1.32μs|0.459ns|1.78ns|0.012| 0|0|912&nbsp;B|
|#2870|`CallElasticsearch`|net472|1.95μs|0.636ns|2.46ns|0.125| 0|0|802&nbsp;B|
|#2870|`CallElasticsearch`|netcoreapp3.1|1.23μs|0.641ns|2.48ns|0.0105| 0|0|792&nbsp;B|
|#2870|`CallElasticsearchAsync`|net472|2.24μs|0.769ns|2.88ns|0.147| 0|0|939&nbsp;B|
|#2870|`CallElasticsearchAsync`|netcoreapp3.1|1.3μs|0.586ns|2.27ns|0.0124| 0|0|912&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`ExecuteAsync`|net472|2.13μs|3.28ns|12.7ns|0.166| 0|0|1.06&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`ExecuteAsync`|netcoreapp3.1|1.39μs|3.69ns|14.3ns|0.0137| 0|0|1.03&nbsp;KB|
|#2870|`ExecuteAsync`|net472|2.21μs|3.86ns|14.5ns|0.166| 0|0|1.06&nbsp;KB|
|#2870|`ExecuteAsync`|netcoreapp3.1|1.43μs|3.32ns|12.4ns|0.014| 0|0|1.03&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`SendAsync`|net472|4.68μs|10.1ns|38.9ns|0.356| 0|0|2.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`SendAsync`|netcoreapp3.1|3.35μs|6ns|23.2ns|0.03| 0|0|2.21&nbsp;KB|
|#2870|`SendAsync`|net472|4.7μs|8.86ns|34.3ns|0.358| 0|0|2.28&nbsp;KB|
|#2870|`SendAsync`|netcoreapp3.1|3.27μs|8.3ns|32.1ns|0.0294| 0|0|2.21&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`EnrichedLog`|net472|2.79μs|1.11ns|4.3ns|0.228| 0|0|1.45&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`EnrichedLog`|netcoreapp3.1|2.19μs|0.791ns|2.96ns|0.0207| 0|0|1.53&nbsp;KB|
|#2870|`EnrichedLog`|net472|2.73μs|1.63ns|6.33ns|0.228| 0|0|1.45&nbsp;KB|
|#2870|`EnrichedLog`|netcoreapp3.1|2.27μs|0.839ns|3.14ns|0.0204| 0|0|1.53&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`EnrichedLog`|net472|149μs|141ns|546ns|0.519| 0.148|0|4.29&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`EnrichedLog`|netcoreapp3.1|112μs|83.1ns|311ns|0.0552| 0|0|4.18&nbsp;KB|
|#2870|`EnrichedLog`|net472|147μs|152ns|588ns|0.52| 0.149|0|4.29&nbsp;KB|
|#2870|`EnrichedLog`|netcoreapp3.1|113μs|171ns|663ns|0| 0|0|4.18&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`EnrichedLog`|net472|5.29μs|7.97ns|30.9ns|0.507| 0.00255|0|3.23&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`EnrichedLog`|netcoreapp3.1|4.09μs|5.38ns|20.8ns|0.0486| 0|0|3.6&nbsp;KB|
|#2870|`EnrichedLog`|net472|4.98μs|8.4ns|32.5ns|0.507| 0.00252|0|3.23&nbsp;KB|
|#2870|`EnrichedLog`|netcoreapp3.1|3.99μs|7.26ns|28.1ns|0.048| 0|0|3.6&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`SendReceive`|net472|1.84μs|0.658ns|2.46ns|0.159| 0|0|1.01&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`SendReceive`|netcoreapp3.1|1.44μs|0.4ns|1.55ns|0.0136| 0|0|1.01&nbsp;KB|
|#2870|`SendReceive`|net472|1.88μs|0.968ns|3.62ns|0.159| 0|0|1.01&nbsp;KB|
|#2870|`SendReceive`|netcoreapp3.1|1.49μs|1.06ns|4.09ns|0.0134| 0|0|1.01&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`EnrichedLog`|net472|4.54μs|1.49ns|5.58ns|0.292| 0|0|1.87&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`EnrichedLog`|netcoreapp3.1|3.93μs|1.55ns|5.79ns|0.0198| 0|0|1.49&nbsp;KB|
|#2870|`EnrichedLog`|net472|4.5μs|1.36ns|5.25ns|0.292| 0|0|1.87&nbsp;KB|
|#2870|`EnrichedLog`|netcoreapp3.1|4.04μs|1.9ns|7.35ns|0.0203| 0|0|1.49&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`StartFinishSpan`|net472|725ns|0.38ns|1.42ns|0.0719| 0|0|457&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`StartFinishSpan`|netcoreapp3.1|643ns|0.281ns|1.09ns|0.00632| 0|0|456&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`StartFinishScope`|net472|1.02μs|0.614ns|2.38ns|0.0842| 0|0|538&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`StartFinishScope`|netcoreapp3.1|790ns|2.06ns|7.97ns|0.00761| 0|0|576&nbsp;B|
|#2870|`StartFinishSpan`|net472|749ns|0.624ns|2.42ns|0.0717| 0|0|457&nbsp;B|
|#2870|`StartFinishSpan`|netcoreapp3.1|637ns|0.174ns|0.65ns|0.00602| 0|0|456&nbsp;B|
|#2870|`StartFinishScope`|net472|1.03μs|0.903ns|3.5ns|0.0842| 0|0|538&nbsp;B|
|#2870|`StartFinishScope`|netcoreapp3.1|737ns|0.313ns|1.17ns|0.0077| 0|0|576&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`RunOnMethodBegin`|net472|1.11μs|1.16ns|4.5ns|0.0844| 0|0|538&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce)|`RunOnMethodBegin`|netcoreapp3.1|920ns|0.749ns|2.8ns|0.00786| 0|0|576&nbsp;B|
|#2870|`RunOnMethodBegin`|net472|1.16μs|0.682ns|2.55ns|0.0842| 0|0|538&nbsp;B|
|#2870|`RunOnMethodBegin`|netcoreapp3.1|931ns|0.462ns|1.73ns|0.00793| 0|0|576&nbsp;B|
</details>

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #2870 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce) will **not change** line coverage
:heavy_check_mark: Merging #2870 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce) will **not change** branch coverage
:no_entry: Merging #2870 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce) will will **increase** complexity by `4`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce) | #2870       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `14699` / `20164` | `14724` / `20188` |          |
| Lines %   | `73%`      | `73%`      |  `0%` :heavy_check_mark:  |
| Branches  | `9008` / `12822` | `9039` / `12826` |          |
| Branches %| `70%`      | `70%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `13673`      | `13677`        |  `4`  :no_entry:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=101095&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/101095/artifacts?artifactName=Code%20Coverage%20Report_101095&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2870](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=101152&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/101152/artifacts?artifactName=Code%20Coverage%20Report_101152&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/4e528486931ec523a32f91f564a6a26b3b3b4fce) | #2870       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `73%`      | `73%`       |  `0%` :heavy_check_mark:  |
| Branches %| `70%`      | `70%`       |  `0%` :heavy_check_mark:  |
| Complexity| `13673`      | `13677`       |  `4` :no_entry:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Ci.GitInfo](https://github.com/DataDog/dd-trace-dotnet/tree/d52d192301ffba88dae3c4a1ba334ace500e368e/tracer/src/Datadog.Trace/Ci/GitInfo.cs) | `-17%` :no_entry: | `-11%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Ci.CIVisibility](https://github.com/DataDog/dd-trace-dotnet/tree/d52d192301ffba88dae3c4a1ba334ace500e368e/tracer/src/Datadog.Trace/Ci/CIVisibility.cs) | `7%` :heavy_check_mark: | `7%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Telemetry.Transports.JsonTelemetryTransport](https://github.com/DataDog/dd-trace-dotnet/tree/d52d192301ffba88dae3c4a1ba334ace500e368e/tracer/src/Datadog.Trace/Telemetry/Transports/JsonTelemetryTransport.cs) | `39%` :heavy_check_mark: | `54%` :heavy_check_mark:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=101095&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/101095/artifacts?artifactName=Code%20Coverage%20Report_101095&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2870](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=101152&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/101152/artifacts?artifactName=Code%20Coverage%20Report_101152&api-version=6.0&%24format=zip)

**Review by zacharycmontoya — APPROVED** [review]
LGTM

**Review by andrewlock — APPROVED** [review]
Grumpy me feels like we shouldn't be adding support for an obsolete 3 year old version of a library, but seeing as you've already done it, fine 😛

**Comment by pierotibou** [comment]
> Grumpy me feels like we shouldn't be adding support for an obsolete 3 year old version of a library

That was my first reflex too on the ticket. But then looking at the code as the lib's code and ours, I thought it was a pity not to offer that for a minimum amount of work. Also, I considered that this special use case shouldn't make maintenance more complicated for us.

**Pull request merged**
