### PR TITLE
Add NCrunch to gitignore and get it to work with the test runners

### PR DESCRIPTION
**Pull request by zippy1981**
Files that get created if you have nCrunch installed in Visual Studio

## Summary of changes

Added gitignore entries and tetrunner names

## Reason for change

I don't want to accidently commit my NCrunch config, and I want the unit tests that care about the testrunner name to pass.

## Implementation details

copied from http://gitignore.io, and fixed unit tests

## Test coverage

Technically not covered by CI/CD, but if you guys bought a license there is a CLI version of ncrunch that you might be able to get working in CI/CD

### CODE REVIEW

**Comment by zippy1981** [comment]
@pierotibou are those linux failure something I should investigate?

**Comment by zippy1981** [comment]
Can I get an update on this?

**Review by lucaspimentel — APPROVED** [review]

**Comment by lucaspimentel** [comment]
@zippy1981 we've been working on fixing several flaky tests. Can you update your branch with `master` and let CI run again? Thanks.

**Comment by lucaspimentel** [comment]
> we've been working on fixing several flaky tests. Can you update your branch with `master` and let CI run again? Thanks.

Oops, ignore my comment above. I forgot this is an external contribution.

**Comment by andrewlock** [comment]
Thanks @zippy1981, sorry for the delay 🤦‍♂️

**Pull request merged**
