### PR TITLE
Pin `StyleCop.Analzyers` to latest pre-release

### PR DESCRIPTION
**Pull request by bouwkast**
## Summary of changes

:sorry:

Pins `StyleCop.Analyzers` to the latest prerelease instead of a floating version.
Reverts ignoring `StyleCop.Analyzers` in Dependabot because that did nothing.

## Reason for change

Dependabot still struggling with ` error : '[1.2.0-beta.*]' is not a valid version string`

## Implementation details

Updated both locations of `StyleCop.Analzyer` to the latest pre-release
Dependabot will attempt to update this package again

## Test coverage

- Nothing

## Other details
If this doesn't fix it I'll find a better way to update/test this without having to PR and merge to run dependabot.

### CODE REVIEW

**Comment by bouwkast** [comment]
This attempt https://github.com/DataDog/dd-trace-dotnet/pull/5906 failed, so reverting it and trying to pin the version

And if this doesn't work I'll just spin up a dummy repo to test out the `.csproj` to not flood with PRs

**Comment by andrewlock** [comment]
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (5908)](https://github.com/DataDog/dd-trace-dotnet/tree/93c55b6c5a844e5956c490c51d74eeb6d6d7b955)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/4f308352dc677c93948e5be5423c974095d43d92)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).

**Review by andrewlock — APPROVED** [review]
🤞

**Comment by bouwkast** [comment]
I made a test app and repo with this version and then another outdated NuGet and dependabot failed with the same error. Pinning the version of `StyleCop.Analyzers` fixed it, so I think this should work. I'll probably poke around in the dependabot/NuGet repos to figure out if this is a known issue. I know PackageReference and floating versions of pre-release packages didn't really work several years ago and it may be the same case today.

**Comment by andrewlock** [comment]
## Benchmarks Report for tracer :snail:

Benchmarks for #5908 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.ActivityBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`StartStopWithChild`|net6.0|7.52μs|41.3ns|261ns|0.0189| 0.00755|0|5.43&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`StartStopWithChild`|netcoreapp3.1|9.96μs|53.9ns|290ns|0.0196| 0.00978|0|5.61&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`StartStopWithChild`|net472|16.1μs|44.4ns|172ns|1.01| 0.291|0.0889|6.07&nbsp;KB|
|#5908|`StartStopWithChild`|net6.0|7.81μs|43.5ns|272ns|0.0187| 0.00746|0|5.43&nbsp;KB|
|#5908|`StartStopWithChild`|netcoreapp3.1|9.88μs|50.8ns|264ns|0.02| 0.00998|0|5.62&nbsp;KB|
|#5908|`StartStopWithChild`|net472|16.2μs|57.6ns|199ns|1.02| 0.294|0.0953|6.07&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`WriteAndFlushEnrichedTraces`|net6.0|473μs|129ns|484ns|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|628μs|211ns|789ns|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`WriteAndFlushEnrichedTraces`|net472|853μs|365ns|1.41μs|0.425| 0|0|3.3&nbsp;KB|
|#5908|`WriteAndFlushEnrichedTraces`|net6.0|454μs|283ns|1.06μs|0| 0|0|2.7&nbsp;KB|
|#5908|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|629μs|388ns|1.5μs|0| 0|0|2.7&nbsp;KB|
|#5908|`WriteAndFlushEnrichedTraces`|net472|831μs|540ns|2.09μs|0.414| 0|0|3.3&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`SendRequest`|net6.0|193μs|1.09μs|7.24μs|0.183| 0|0|18.45&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`SendRequest`|netcoreapp3.1|214μs|1.21μs|8.81μs|0.2| 0|0|20.61&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`SendRequest`|net472|5.87E&#8209;05ns|5.87E&#8209;05ns|0.000212ns|0| 0|0|0&nbsp;b|
|#5908|`SendRequest`|net6.0|189μs|997ns|6.23μs|0.187| 0|0|18.45&nbsp;KB|
|#5908|`SendRequest`|netcoreapp3.1|216μs|1.24μs|9.5μs|0.204| 0|0|20.61&nbsp;KB|
|#5908|`SendRequest`|net472|0.000385ns|0.000253ns|0.000948ns|0| 0|0|0&nbsp;b|
</details>


<details><summary><strong>Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`WriteAndFlushEnrichedTraces`|net6.0|548μs|1.6μs|5.99μs|0.561| 0|0|41.59&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|689μs|3.79μs|22.4μs|0.34| 0|0|41.71&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`WriteAndFlushEnrichedTraces`|net472|868μs|3.25μs|11.7μs|8.3| 2.62|0.437|53.3&nbsp;KB|
|#5908|`WriteAndFlushEnrichedTraces`|net6.0|564μs|2.83μs|13μs|0.536| 0|0|41.5&nbsp;KB|
|#5908|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|694μs|3.21μs|12.4μs|0.342| 0|0|41.87&nbsp;KB|
|#5908|`WriteAndFlushEnrichedTraces`|net472|901μs|3.44μs|13.3μs|8.21| 2.28|0.456|53.29&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`ExecuteNonQuery`|net6.0|1.28μs|1.48ns|5.72ns|0.0142| 0|0|1.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`ExecuteNonQuery`|netcoreapp3.1|1.72μs|1.54ns|5.98ns|0.0136| 0|0|1.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`ExecuteNonQuery`|net472|1.98μs|1.53ns|5.94ns|0.156| 0|0|987&nbsp;B|
|#5908|`ExecuteNonQuery`|net6.0|1.32μs|0.688ns|2.57ns|0.0139| 0|0|1.02&nbsp;KB|
|#5908|`ExecuteNonQuery`|netcoreapp3.1|1.68μs|0.783ns|2.93ns|0.0136| 0|0|1.02&nbsp;KB|
|#5908|`ExecuteNonQuery`|net472|2.05μs|1.97ns|7.37ns|0.156| 0|0|987&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`CallElasticsearch`|net6.0|1.22μs|0.885ns|3.31ns|0.0134| 0|0|976&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`CallElasticsearch`|netcoreapp3.1|1.54μs|1.19ns|4.46ns|0.0133| 0|0|976&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`CallElasticsearch`|net472|2.51μs|9.7ns|36.3ns|0.157| 0|0|995&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`CallElasticsearchAsync`|net6.0|1.33μs|0.986ns|3.69ns|0.0133| 0|0|952&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`CallElasticsearchAsync`|netcoreapp3.1|1.68μs|0.944ns|3.53ns|0.0137| 0|0|1.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`CallElasticsearchAsync`|net472|2.6μs|4.59ns|17.8ns|0.166| 0|0|1.05&nbsp;KB|
|#5908|`CallElasticsearch`|net6.0|1.26μs|0.743ns|2.78ns|0.0139| 0|0|976&nbsp;B|
|#5908|`CallElasticsearch`|netcoreapp3.1|1.49μs|0.534ns|2.07ns|0.0134| 0|0|976&nbsp;B|
|#5908|`CallElasticsearch`|net472|2.43μs|1ns|3.88ns|0.158| 0|0|995&nbsp;B|
|#5908|`CallElasticsearchAsync`|net6.0|1.37μs|1.02ns|3.96ns|0.013| 0|0|952&nbsp;B|
|#5908|`CallElasticsearchAsync`|netcoreapp3.1|1.64μs|1.02ns|3.94ns|0.0139| 0|0|1.02&nbsp;KB|
|#5908|`CallElasticsearchAsync`|net472|2.69μs|1.33ns|5.16ns|0.167| 0|0|1.05&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`ExecuteAsync`|net6.0|1.34μs|0.737ns|2.85ns|0.0134| 0|0|952&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`ExecuteAsync`|netcoreapp3.1|1.72μs|0.568ns|2.12ns|0.0129| 0|0|952&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`ExecuteAsync`|net472|1.75μs|1.31ns|4.89ns|0.145| 0|0|915&nbsp;B|
|#5908|`ExecuteAsync`|net6.0|1.24μs|0.402ns|1.45ns|0.0131| 0|0|952&nbsp;B|
|#5908|`ExecuteAsync`|netcoreapp3.1|1.63μs|0.63ns|2.36ns|0.0122| 0|0|952&nbsp;B|
|#5908|`ExecuteAsync`|net472|1.78μs|1.28ns|4.97ns|0.145| 0|0|915&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`SendAsync`|net6.0|4.34μs|2.45ns|9.5ns|0.0304| 0|0|2.22&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`SendAsync`|netcoreapp3.1|5.1μs|2.27ns|8.48ns|0.038| 0|0|2.76&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`SendAsync`|net472|7.86μs|1.64ns|6.14ns|0.5| 0|0|3.15&nbsp;KB|
|#5908|`SendAsync`|net6.0|4.11μs|1.08ns|3.9ns|0.0309| 0|0|2.22&nbsp;KB|
|#5908|`SendAsync`|netcoreapp3.1|5.04μs|2.31ns|8.94ns|0.0351| 0|0|2.76&nbsp;KB|
|#5908|`SendAsync`|net472|7.8μs|1.18ns|4.57ns|0.499| 0|0|3.15&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`EnrichedLog`|net6.0|1.47μs|0.572ns|2.14ns|0.0228| 0|0|1.64&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`EnrichedLog`|netcoreapp3.1|2.42μs|1.18ns|4.56ns|0.0216| 0|0|1.64&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`EnrichedLog`|net472|2.69μs|1.14ns|4.4ns|0.249| 0|0|1.57&nbsp;KB|
|#5908|`EnrichedLog`|net6.0|1.58μs|0.67ns|2.59ns|0.023| 0|0|1.64&nbsp;KB|
|#5908|`EnrichedLog`|netcoreapp3.1|2.34μs|1.27ns|4.38ns|0.0225| 0|0|1.64&nbsp;KB|
|#5908|`EnrichedLog`|net472|2.67μs|1.73ns|6.69ns|0.249| 0|0|1.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`EnrichedLog`|net6.0|117μs|231ns|894ns|0.0579| 0|0|4.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`EnrichedLog`|netcoreapp3.1|121μs|318ns|1.19μs|0| 0|0|4.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`EnrichedLog`|net472|151μs|252ns|976ns|0.676| 0.225|0|4.46&nbsp;KB|
|#5908|`EnrichedLog`|net6.0|116μs|127ns|492ns|0.0578| 0|0|4.28&nbsp;KB|
|#5908|`EnrichedLog`|netcoreapp3.1|119μs|153ns|593ns|0| 0|0|4.28&nbsp;KB|
|#5908|`EnrichedLog`|net472|150μs|229ns|792ns|0.671| 0.224|0|4.46&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`EnrichedLog`|net6.0|3.15μs|0.726ns|2.81ns|0.0307| 0|0|2.2&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`EnrichedLog`|netcoreapp3.1|4.21μs|1.27ns|4.92ns|0.0296| 0|0|2.2&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`EnrichedLog`|net472|4.92μs|1.4ns|5.44ns|0.32| 0|0|2.02&nbsp;KB|
|#5908|`EnrichedLog`|net6.0|3.15μs|0.84ns|3.25ns|0.0299| 0|0|2.2&nbsp;KB|
|#5908|`EnrichedLog`|netcoreapp3.1|4.27μs|1.7ns|6.35ns|0.0283| 0|0|2.2&nbsp;KB|
|#5908|`EnrichedLog`|net472|4.77μs|2.03ns|7.85ns|0.319| 0|0|2.02&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`SendReceive`|net6.0|1.35μs|0.913ns|3.54ns|0.0156| 0|0|1.14&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`SendReceive`|netcoreapp3.1|1.85μs|1.21ns|4.67ns|0.0156| 0|0|1.14&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`SendReceive`|net472|2.18μs|1.75ns|6.79ns|0.183| 0|0|1.16&nbsp;KB|
|#5908|`SendReceive`|net6.0|1.3μs|1.16ns|4.49ns|0.0162| 0|0|1.14&nbsp;KB|
|#5908|`SendReceive`|netcoreapp3.1|1.79μs|0.86ns|3.33ns|0.0151| 0|0|1.14&nbsp;KB|
|#5908|`SendReceive`|net472|2.12μs|1.93ns|7.48ns|0.183| 0|0|1.16&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`EnrichedLog`|net6.0|2.86μs|0.697ns|2.61ns|0.0215| 0|0|1.6&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`EnrichedLog`|netcoreapp3.1|3.77μs|1.42ns|5.3ns|0.0207| 0|0|1.65&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`EnrichedLog`|net472|4.5μs|3.2ns|12.4ns|0.322| 0|0|2.04&nbsp;KB|
|#5908|`EnrichedLog`|net6.0|2.78μs|0.876ns|3.28ns|0.0223| 0|0|1.6&nbsp;KB|
|#5908|`EnrichedLog`|netcoreapp3.1|3.79μs|1.63ns|6.11ns|0.0211| 0|0|1.65&nbsp;KB|
|#5908|`EnrichedLog`|net472|4.34μs|2.06ns|7.96ns|0.322| 0|0|2.04&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`StartFinishSpan`|net6.0|399ns|0.0943ns|0.34ns|0.00803| 0|0|576&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`StartFinishSpan`|netcoreapp3.1|557ns|1.16ns|4.49ns|0.00796| 0|0|576&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`StartFinishSpan`|net472|635ns|0.427ns|1.65ns|0.0915| 0|0|578&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`StartFinishScope`|net6.0|493ns|1.19ns|4.62ns|0.00964| 0|0|696&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`StartFinishScope`|netcoreapp3.1|748ns|0.514ns|1.99ns|0.0094| 0|0|696&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`StartFinishScope`|net472|888ns|2.64ns|10.2ns|0.104| 0|0|658&nbsp;B|
|#5908|`StartFinishSpan`|net6.0|402ns|0.433ns|1.62ns|0.00801| 0|0|576&nbsp;B|
|#5908|`StartFinishSpan`|netcoreapp3.1|571ns|0.468ns|1.81ns|0.00792| 0|0|576&nbsp;B|
|#5908|`StartFinishSpan`|net472|644ns|0.218ns|0.843ns|0.0916| 0|0|578&nbsp;B|
|#5908|`StartFinishScope`|net6.0|529ns|0.57ns|2.21ns|0.00981| 0|0|696&nbsp;B|
|#5908|`StartFinishScope`|netcoreapp3.1|702ns|0.398ns|1.54ns|0.00924| 0|0|696&nbsp;B|
|#5908|`StartFinishScope`|net472|879ns|0.472ns|1.77ns|0.105| 0|0|658&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`RunOnMethodBegin`|net6.0|595ns|0.204ns|0.765ns|0.00967| 0|0|696&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`RunOnMethodBegin`|netcoreapp3.1|966ns|0.499ns|1.93ns|0.00923| 0|0|696&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)|`RunOnMethodBegin`|net472|1.11μs|0.454ns|1.57ns|0.104| 0|0|658&nbsp;B|
|#5908|`RunOnMethodBegin`|net6.0|657ns|0.776ns|3.01ns|0.00989| 0|0|696&nbsp;B|
|#5908|`RunOnMethodBegin`|netcoreapp3.1|876ns|0.539ns|2.02ns|0.00962| 0|0|696&nbsp;B|
|#5908|`RunOnMethodBegin`|net472|1.12μs|0.397ns|1.49ns|0.104| 0|0|658&nbsp;B|
</details>

**Comment by andrewlock** [comment]
## Throughput/Crank Report :zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (5908)](https://github.com/DataDog/dd-trace-dotnet/tree/0e4bcf3a658d4a021023249410dc7fb8962385c8)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/8e63384717cc1a2608815c661c13c65ed94ba965)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/89ae3f4ee7d85b824badda5873166707c9e560b4)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (5908) (11.344M)   : 0, 11344109
    master (11.626M)   : 0, 11625669
    benchmarks/2.9.0 (11.606M)   : 0, 11605731

    section Automatic
    This PR (5908) (7.696M)   : 0, 7695691
    master (7.741M)   : 0, 7740587
    benchmarks/2.9.0 (8.043M)   : 0, 8042658

    section Trace stats
    master (8.083M)   : 0, 8082727

    section Manual
    master (11.551M)   : 0, 11551010

    section Manual + Automatic
    This PR (5908) (7.033M)   : 0, 7032744
    master (7.207M)   : 0, 7206578

    section DD_TRACE_ENABLED=0
    master (10.731M)   : 0, 10731443

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (5908) (6.513M)   : 0, 6513438

    section Automatic
    This PR (5908) (6.589M)   : 0, 6589203

    section Manual + Automatic
    This PR (5908) (6.121M)   : 0, 6121133

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (5908) (10.174M)   : 0, 10174221
    benchmarks/2.9.0 (10.148M)   : 0, 10147897

    section Automatic
    This PR (5908) (6.851M)   : 0, 6850852
    benchmarks/2.9.0 (7.517M)   : 0, 7517128

    section Manual + Automatic
    This PR (5908) (6.437M)   : 0, 6436570

```

**Pull request merged**
