### PR TITLE
Fix MongoDB integration when BsonDocument throws an exception

### PR DESCRIPTION
**Pull request by tonyredondo**
This PR adds the try/catch we had before the integration rewrite to catch an exception calling `BsonDocument.ToString()`

Reference: https://groups.google.com/g/mongodb-user/c/-W36utrXflg/m/3f3kj1KFAgAJ

Also contains MongoDb snapshots, added in https://github.com/DataDog/dd-trace-dotnet/pull/2440

@DataDog/apm-dotnet

### CODE REVIEW

**Review by andrewlock — APPROVED** [review]
Thanks! I'll set a manual run of the ci going with the comprehensive tests variable, just to be sure

**Review by kevingosse — APPROVED** [review]

**Review by lucaspimentel — APPROVED** [review]

**Review by zacharycmontoya — APPROVED** [review]

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #2435 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`WriteAndFlushEnrichedTraces`|net472|830μs|2.64μs|9.88μs|0| 0|0|3.16&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|636μs|1.86μs|7.21μs|0| 0|0|2.57&nbsp;KB|
|#2435|`WriteAndFlushEnrichedTraces`|net472|846μs|3.85μs|14.4μs|0| 0|0|3.16&nbsp;KB|
|#2435|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|646μs|1.89μs|7.32μs|0| 0|0|2.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`SendRequest`|netcoreapp3.1|288μs|1.27μs|4.94μs|0.277| 0|0|19.71&nbsp;KB|
|#2435|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#2435|`SendRequest`|netcoreapp3.1|294μs|1.42μs|5.68μs|0.139| 0|0|19.71&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`ExecuteNonQuery`|net472|1.65μs|7.18ns|26.9ns|0.0925| 0.000811|0|586&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`ExecuteNonQuery`|netcoreapp3.1|1.46μs|6.98ns|28.8ns|0.0085| 0|0|624&nbsp;B|
|#2435|`ExecuteNonQuery`|net472|1.64μs|6.71ns|26ns|0.0927| 0|0|586&nbsp;B|
|#2435|`ExecuteNonQuery`|netcoreapp3.1|1.48μs|8.26ns|49.6ns|0.00876| 0|0|624&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`CallElasticsearch`|net472|2.45μs|13.2ns|71.1ns|0.126| 0|0|794&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`CallElasticsearch`|netcoreapp3.1|1.72μs|9.48ns|55.3ns|0.0106| 0|0|784&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`CallElasticsearchAsync`|net472|2.7μs|14.9ns|85.3ns|0.146| 0|0|931&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`CallElasticsearchAsync`|netcoreapp3.1|1.81μs|4.59ns|17.8ns|0.0128| 0|0|904&nbsp;B|
|#2435|`CallElasticsearch`|net472|2.45μs|11.8ns|50.1ns|0.125| 0|0|794&nbsp;B|
|#2435|`CallElasticsearch`|netcoreapp3.1|1.65μs|6.78ns|27.1ns|0.0108| 0|0|784&nbsp;B|
|#2435|`CallElasticsearchAsync`|net472|2.7μs|11.5ns|43.2ns|0.148| 0|0|931&nbsp;B|
|#2435|`CallElasticsearchAsync`|netcoreapp3.1|1.91μs|10.8ns|81.7ns|0.0128| 0|0|904&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`ExecuteAsync`|net472|2.96μs|13.3ns|49.9ns|0.167| 0|0|1.05&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`ExecuteAsync`|netcoreapp3.1|1.99μs|10.8ns|62.9ns|0.0143| 0|0|1.02&nbsp;KB|
|#2435|`ExecuteAsync`|net472|2.9μs|10.2ns|38.2ns|0.167| 0|0|1.05&nbsp;KB|
|#2435|`ExecuteAsync`|netcoreapp3.1|1.93μs|6.4ns|24.8ns|0.0141| 0|0|1.02&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`SendAsync`|net472|6.79μs|34.5ns|154ns|0.363| 0|0|2.3&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`SendAsync`|netcoreapp3.1|4.62μs|15.1ns|58.4ns|0.0299| 0|0|2.2&nbsp;KB|
|#2435|`SendAsync`|net472|6.76μs|24.9ns|93.1ns|0.365| 0|0|2.3&nbsp;KB|
|#2435|`SendAsync`|netcoreapp3.1|4.56μs|16.3ns|63.3ns|0.0316| 0|0|2.2&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`EnrichedLog`|net472|3.13μs|10.7ns|38.7ns|0.225| 0|0|1.44&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`EnrichedLog`|netcoreapp3.1|2.96μs|9.72ns|36.4ns|0.0204| 0|0|1.52&nbsp;KB|
|#2435|`EnrichedLog`|net472|3.24μs|16.2ns|72.4ns|0.224| 0|0|1.44&nbsp;KB|
|#2435|`EnrichedLog`|netcoreapp3.1|3.03μs|8.62ns|32.3ns|0.0209| 0|0|1.52&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`EnrichedLog`|net472|286μs|1.31μs|5.08μs|0.417| 0.139|0|4.31&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`EnrichedLog`|netcoreapp3.1|224μs|519ns|1.87μs|0| 0|0|4.19&nbsp;KB|
|#2435|`EnrichedLog`|net472|284μs|945ns|3.54μs|0.436| 0.145|0|4.31&nbsp;KB|
|#2435|`EnrichedLog`|netcoreapp3.1|231μs|1.26μs|7.13μs|0| 0|0|4.19&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`EnrichedLog`|net472|7.17μs|31.8ns|119ns|0.501| 0|0|3.21&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`EnrichedLog`|netcoreapp3.1|6.31μs|28.2ns|109ns|0.0499| 0|0|3.58&nbsp;KB|
|#2435|`EnrichedLog`|net472|7.25μs|35.1ns|149ns|0.504| 0|0|3.21&nbsp;KB|
|#2435|`EnrichedLog`|netcoreapp3.1|6.23μs|19.2ns|66.4ns|0.0494| 0|0|3.58&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`SendReceive`|net472|2.32μs|12.6ns|74.7ns|0.157| 0|0|1&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`SendReceive`|netcoreapp3.1|2.06μs|11.3ns|67.9ns|0.0133| 0|0|1&nbsp;KB|
|#2435|`SendReceive`|net472|2.2μs|10.5ns|61.1ns|0.157| 0|0|1&nbsp;KB|
|#2435|`SendReceive`|netcoreapp3.1|2.1μs|11.4ns|61.6ns|0.0141| 0|0|1&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`EnrichedLog`|net472|5.71μs|31.3ns|185ns|0.289| 0|0|1.85&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`EnrichedLog`|netcoreapp3.1|5.23μs|24.2ns|96.7ns|0.0189| 0|0|1.47&nbsp;KB|
|#2435|`EnrichedLog`|net472|5.71μs|17.8ns|69ns|0.289| 0|0|1.85&nbsp;KB|
|#2435|`EnrichedLog`|netcoreapp3.1|5.24μs|22ns|79.3ns|0.0208| 0|0|1.47&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`StartFinishSpan`|net472|889ns|3.63ns|14.1ns|0.0704| 0|0|449&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`StartFinishSpan`|netcoreapp3.1|880ns|2.36ns|8.83ns|0.0063| 0|0|448&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`StartFinishScope`|net472|1.03μs|4.01ns|15ns|0.0829| 0|0|530&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/3575b9d0426faad35a89d45af56c30ed148317fa)|`StartFinishScope`|netcoreapp3.1|1.04μs|3.08ns|11.9ns|0.00774| 0|0|568&nbsp;B|
|#2435|`StartFinishSpan`|net472|862ns|3.24ns|12.1ns|0.0705| 0|0|449&nbsp;B|
|#2435|`StartFinishSpan`|netcoreapp3.1|890ns|2.96ns|10.7ns|0.00626| 0|0|448&nbsp;B|
|#2435|`StartFinishScope`|net472|1.04μs|4.99ns|21.7ns|0.0829| 0|0|530&nbsp;B|
|#2435|`StartFinishScope`|netcoreapp3.1|1.03μs|4.51ns|20.2ns|0.00779| 0|0|568&nbsp;B|
</details>

**Comment by andrewlock** [comment]
@tonyredondo I merged the snapshot tests, and have run [the comprehensive integration tests on this branch](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=90575&view=results) so I think we're good to merge it whenever you're ready 🙂

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #2435 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/6989e88ce638ba1e4ee1b178d70e692a3a5499dd) will **not change** line coverage
:heavy_check_mark: Merging #2435 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/6989e88ce638ba1e4ee1b178d70e692a3a5499dd) will **not change** branch coverage
:no_entry: Merging #2435 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/6989e88ce638ba1e4ee1b178d70e692a3a5499dd) will will **increase** complexity by `9`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/6989e88ce638ba1e4ee1b178d70e692a3a5499dd) | #2435       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `11388` / `15822` | `11479` / `15857` |          |
| Lines %   | `72%`      | `72%`      |  `0%` :heavy_check_mark:  |
| Branches  | `6136` / `9264` | `6159` / `9272` |          |
| Branches %| `66%`      | `66%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `10465`      | `10474`        |  `9`  :no_entry:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/$dd-trace-dotnet/_build/results?buildId=90254&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/90254/artifacts?artifactName=Code%20Coverage%20Report_90254&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2435](https://dev.azure.com/datadoghq/$dd-trace-dotnet/_build/results?buildId=90573&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/90573/artifacts?artifactName=Code%20Coverage%20Report_90573&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/6989e88ce638ba1e4ee1b178d70e692a3a5499dd) | #2435       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `72%`      | `72%`       |  `0%` :heavy_check_mark:  |
| Branches %| `66%`      | `66%`       |  `0%` :heavy_check_mark:  |
| Complexity| `10465`      | `10474`       |  `9` :no_entry:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Telemetry.JsonWebRequestTelemetryTransport](https://github.com/DataDog/dd-trace-dotnet/tree/7464c2229301e5959bb1a58e404124d6e6d88de9/tracer/src/Datadog.Trace/Telemetry/Transports/JsonWebRequestTelemetryTransport.cs) | `-28%` :no_entry: | `-57%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Ci.CIVisibility](https://github.com/DataDog/dd-trace-dotnet/tree/7464c2229301e5959bb1a58e404124d6e6d88de9/tracer/src/Datadog.Trace/Ci/CIVisibility.cs) | `11%` :heavy_check_mark: | `2%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.MongoDbIntegration](https://github.com/DataDog/dd-trace-dotnet/tree/7464c2229301e5959bb1a58e404124d6e6d88de9/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/MongoDb/MongoDbIntegration.cs) | `83%` :heavy_check_mark: | `81%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_Execute_Integration](https://github.com/DataDog/dd-trace-dotnet/tree/7464c2229301e5959bb1a58e404124d6e6d88de9/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/MongoDb/IWireProtocol_Execute_Integration.cs) | `100%` :heavy_check_mark: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_ExecuteAsync_Integration](https://github.com/DataDog/dd-trace-dotnet/tree/7464c2229301e5959bb1a58e404124d6e6d88de9/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/MongoDb/IWireProtocol_ExecuteAsync_Integration.cs) | `100%` :heavy_check_mark: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.MongoDb.IWireProtocol_Generic_Execute_Integration](https://github.com/DataDog/dd-trace-dotnet/tree/7464c2229301e5959bb1a58e404124d6e6d88de9/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/MongoDb/IWireProtocol_Generic_Execute_Integration.cs) | `100%` :heavy_check_mark: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/$dd-trace-dotnet/_build/results?buildId=90254&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/90254/artifacts?artifactName=Code%20Coverage%20Report_90254&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2435](https://dev.azure.com/datadoghq/$dd-trace-dotnet/_build/results?buildId=90573&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/90573/artifacts?artifactName=Code%20Coverage%20Report_90573&api-version=6.0&%24format=zip)

**Pull request merged**
