### PR TITLE
Fix `ILogger` direct submission when formatter returns `null`

### PR DESCRIPTION
**Pull request by andrewlock**
## Summary of changes

Fixes an issue where the `ILogger` formatter returns null in direct log submission.

## Reason for change

If the `ILogger` formatter returns `null`, we were also returning `null`, but still adding that to the collection to be serialized. This could lead to broken `JSON`, as the array of objects contained something like this:

```json
{
  "key", "value"
}, , // <- double comma
{
 "key", "value"
}
```

This is very rare, as it doesn't happen when you log a `null` message, it only occurs when the log formatter (`Func<T, Exception> string>`) returns `null`. This isn't a scenario we tested (it makes no sense, and isn't the commonly used public API), but it looks like Azure Functions may be doing it by default somewhere.

## Implementation details

When the formatter returns `null`, I switched to using the exception message (if available) and using `"[null]"` if there's no exception. That's because `"[null]"` is what you get if you call `_log.LogInformation(null)`, so makes the most sense I think.

Alternatively, I could have skipped the message entirely (which is what we were _trying_ to do previously), but decided it's probably best not to skip logs entirely, as there could be relevant details in the scope objects and event ID.

## Test coverage

Added unit tests for a bunch of scenarios which could have potentially been problematic (e.g. json in json), but all appears to work as expected apart from this case. 

Used System.Text.Json in its strictest mode to verify the JSON we generate is valid.

## Other details

None of the other direct log submission integrations appear to have any issues AFAICT.

### CODE REVIEW

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #3398 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`WriteAndFlushEnrichedTraces`|net472|807μs|568ns|2.12μs|0.401| 0|0|3.22&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|547μs|2μs|7.75μs|0| 0|0|2.63&nbsp;KB|
|#3398|`WriteAndFlushEnrichedTraces`|net472|806μs|654ns|2.45μs|0.401| 0|0|3.22&nbsp;KB|
|#3398|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|543μs|202ns|757ns|0| 0|0|2.63&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`AllCycleSimpleBody`|net472|182ns|0.0699ns|0.252ns|0.0701| 9.15E-05|0|441&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`AllCycleSimpleBody`|netcoreapp3.1|241ns|0.181ns|0.653ns|0.00618| 0|0|440&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`AllCycleMoreComplexBody`|net472|181ns|0.0361ns|0.14ns|0.0662| 0|0|417&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`AllCycleMoreComplexBody`|netcoreapp3.1|239ns|0.207ns|0.8ns|0.00573| 0|0|416&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`BodyExtractorSimpleBody`|net472|291ns|0.453ns|1.57ns|0.0574| 0|0|361&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`BodyExtractorSimpleBody`|netcoreapp3.1|267ns|0.242ns|0.939ns|0.00376| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`BodyExtractorMoreComplexBody`|net472|16μs|16.1ns|62.3ns|1.21| 0.016|0|7.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`BodyExtractorMoreComplexBody`|netcoreapp3.1|13.2μs|12.7ns|47.4ns|0.0922| 0|0|6.75&nbsp;KB|
|#3398|`AllCycleSimpleBody`|net472|183ns|0.0632ns|0.228ns|0.0701| 9.16E-05|0|441&nbsp;B|
|#3398|`AllCycleSimpleBody`|netcoreapp3.1|240ns|0.143ns|0.534ns|0.00605| 0|0|440&nbsp;B|
|#3398|`AllCycleMoreComplexBody`|net472|181ns|0.0462ns|0.16ns|0.0662| 0|0|417&nbsp;B|
|#3398|`AllCycleMoreComplexBody`|netcoreapp3.1|238ns|0.16ns|0.621ns|0.00575| 0|0|416&nbsp;B|
|#3398|`BodyExtractorSimpleBody`|net472|305ns|0.321ns|1.24ns|0.0573| 0|0|361&nbsp;B|
|#3398|`BodyExtractorSimpleBody`|netcoreapp3.1|243ns|0.0833ns|0.312ns|0.00368| 0|0|272&nbsp;B|
|#3398|`BodyExtractorMoreComplexBody`|net472|16.6μs|10.9ns|40.9ns|1.2| 0.0165|0|7.62&nbsp;KB|
|#3398|`BodyExtractorMoreComplexBody`|netcoreapp3.1|12.7μs|4.6ns|17.8ns|0.0891| 0|0|6.75&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`SendRequest`|netcoreapp3.1|177μs|170ns|658ns|0.263| 0|0|20.44&nbsp;KB|
|#3398|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#3398|`SendRequest`|netcoreapp3.1|177μs|201ns|779ns|0.264| 0|0|20.44&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`ExecuteNonQuery`|net472|1.8μs|1.63ns|6.11ns|0.158| 0.000895|0|995&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`ExecuteNonQuery`|netcoreapp3.1|1.41μs|2.54ns|9.5ns|0.0132| 0|0|984&nbsp;B|
|#3398|`ExecuteNonQuery`|net472|1.77μs|1.37ns|5.32ns|0.158| 0.000887|0|995&nbsp;B|
|#3398|`ExecuteNonQuery`|netcoreapp3.1|1.4μs|1.05ns|3.79ns|0.0132| 0|0|984&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`CallElasticsearch`|net472|2.48μs|1.06ns|4.12ns|0.19| 0|0|1.2&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`CallElasticsearch`|netcoreapp3.1|1.58μs|0.393ns|1.47ns|0.0158| 0|0|1.14&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`CallElasticsearchAsync`|net472|2.8μs|0.563ns|2.18ns|0.212| 0|0|1.34&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`CallElasticsearchAsync`|netcoreapp3.1|1.59μs|0.536ns|2ns|0.0166| 0|0|1.26&nbsp;KB|
|#3398|`CallElasticsearch`|net472|2.44μs|0.664ns|2.48ns|0.19| 0|0|1.2&nbsp;KB|
|#3398|`CallElasticsearch`|netcoreapp3.1|1.53μs|0.443ns|1.66ns|0.0153| 0|0|1.14&nbsp;KB|
|#3398|`CallElasticsearchAsync`|net472|2.64μs|0.868ns|3.13ns|0.213| 0|0|1.34&nbsp;KB|
|#3398|`CallElasticsearchAsync`|netcoreapp3.1|1.63μs|0.434ns|1.62ns|0.0171| 0|0|1.26&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`ExecuteAsync`|net472|2.72μs|3ns|11.6ns|0.233| 0|0|1.47&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`ExecuteAsync`|netcoreapp3.1|1.77μs|0.759ns|2.63ns|0.0185| 0|0|1.39&nbsp;KB|
|#3398|`ExecuteAsync`|net472|2.67μs|3.38ns|12.6ns|0.233| 0|0|1.47&nbsp;KB|
|#3398|`ExecuteAsync`|netcoreapp3.1|1.73μs|0.918ns|3.55ns|0.0193| 0|0|1.39&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`SendAsync`|net472|5.9μs|3.56ns|13.8ns|0.447| 0|0|2.82&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`SendAsync`|netcoreapp3.1|3.63μs|3.75ns|14.5ns|0.0357| 0|0|2.65&nbsp;KB|
|#3398|`SendAsync`|net472|5.86μs|2.14ns|8.02ns|0.446| 0|0|2.82&nbsp;KB|
|#3398|`SendAsync`|netcoreapp3.1|3.72μs|1.26ns|4.71ns|0.0354| 0|0|2.65&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`EnrichedLog`|net472|3.12μs|4.6ns|17.8ns|0.298| 0|0|1.88&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`EnrichedLog`|netcoreapp3.1|2.49μs|1.64ns|6.12ns|0.0259| 0|0|1.91&nbsp;KB|
|#3398|`EnrichedLog`|net472|3.17μs|1.67ns|6.26ns|0.298| 0|0|1.88&nbsp;KB|
|#3398|`EnrichedLog`|netcoreapp3.1|2.47μs|1.93ns|7.46ns|0.0258| 0|0|1.91&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`EnrichedLog`|net472|151μs|116ns|448ns|0.68| 0.227|0|4.72&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`EnrichedLog`|netcoreapp3.1|119μs|178ns|688ns|0.0593| 0|0|4.55&nbsp;KB|
|#3398|`EnrichedLog`|net472|151μs|88.8ns|332ns|0.683| 0.228|0|4.72&nbsp;KB|
|#3398|`EnrichedLog`|netcoreapp3.1|120μs|244ns|880ns|0| 0|0|4.55&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`EnrichedLog`|net472|5.75μs|3.22ns|12.1ns|0.578| 0.00286|0|3.65&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`EnrichedLog`|netcoreapp3.1|4.41μs|2.27ns|8.81ns|0.0549| 0|0|3.98&nbsp;KB|
|#3398|`EnrichedLog`|net472|5.75μs|2.1ns|7.87ns|0.578| 0.00287|0|3.65&nbsp;KB|
|#3398|`EnrichedLog`|netcoreapp3.1|4.54μs|1.31ns|4.9ns|0.0544| 0|0|3.98&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`SendReceive`|net472|2.25μs|2.83ns|11ns|0.225| 0|0|1.42&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`SendReceive`|netcoreapp3.1|1.82μs|0.829ns|2.87ns|0.0182| 0|0|1.37&nbsp;KB|
|#3398|`SendReceive`|net472|2.17μs|1.4ns|5.25ns|0.225| 0|0|1.42&nbsp;KB|
|#3398|`SendReceive`|netcoreapp3.1|1.78μs|0.613ns|2.3ns|0.0187| 0|0|1.37&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`EnrichedLog`|net472|4.9μs|1.02ns|3.96ns|0.363| 0|0|2.3&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`EnrichedLog`|netcoreapp3.1|4.21μs|2.81ns|10.5ns|0.0252| 0|0|1.86&nbsp;KB|
|#3398|`EnrichedLog`|net472|5.17μs|2.44ns|9.44ns|0.363| 0|0|2.3&nbsp;KB|
|#3398|`EnrichedLog`|netcoreapp3.1|4.28μs|1.47ns|5.68ns|0.0236| 0|0|1.86&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`StartFinishSpan`|net472|1.16μs|0.649ns|2.43ns|0.136| 0|0|859&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`StartFinishSpan`|netcoreapp3.1|923ns|1.33ns|4.99ns|0.0111| 0|0|808&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`StartFinishScope`|net472|1.31μs|0.438ns|1.58ns|0.149| 0|0|939&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`StartFinishScope`|netcoreapp3.1|1.06μs|0.735ns|2.85ns|0.0126| 0|0|928&nbsp;B|
|#3398|`StartFinishSpan`|net472|1.15μs|0.427ns|1.65ns|0.136| 0|0|859&nbsp;B|
|#3398|`StartFinishSpan`|netcoreapp3.1|884ns|0.544ns|1.96ns|0.011| 0|0|808&nbsp;B|
|#3398|`StartFinishScope`|net472|1.38μs|0.848ns|3.28ns|0.149| 0|0|939&nbsp;B|
|#3398|`StartFinishScope`|netcoreapp3.1|1.12μs|0.374ns|1.45ns|0.0128| 0|0|928&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`RunOnMethodBegin`|net472|1.44μs|0.26ns|0.939ns|0.149| 0|0|939&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/58a459f58f35470228b1fd6c769a5f829d578ad4)|`RunOnMethodBegin`|netcoreapp3.1|1.13μs|0.513ns|1.78ns|0.0126| 0|0|928&nbsp;B|
|#3398|`RunOnMethodBegin`|net472|1.53μs|0.401ns|1.5ns|0.149| 0|0|939&nbsp;B|
|#3398|`RunOnMethodBegin`|netcoreapp3.1|1.14μs|0.359ns|1.3ns|0.0125| 0|0|928&nbsp;B|
</details>

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #3398 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/3ec470898a0733411b6d35f2d5b9d803953fc191) will will **increase** line coverage by `5%`
:heavy_check_mark: Merging #3398 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/3ec470898a0733411b6d35f2d5b9d803953fc191) will will **increase** branch coverage by `5%`
:no_entry: Merging #3398 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/3ec470898a0733411b6d35f2d5b9d803953fc191) will will **increase** complexity by `36`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/3ec470898a0733411b6d35f2d5b9d803953fc191) | #3398       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `18769` / `27153` | `20196` / `27203` |          |
| Lines %   | `69%`      | `74%`      |  `5%` :heavy_check_mark:  |
| Branches  | `10933` / `16832` | `11818` / `16868` |          |
| Branches %| `65%`      | `70%`      |  `5%` :heavy_check_mark:  |
| Complexity|   `18222`      | `18258`        |  `36`  :no_entry:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=116543&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/116543/artifacts?artifactName=Code%20Coverage%20Report_116543&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3398](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=116806&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/116806/artifacts?artifactName=Code%20Coverage%20Report_116806&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/3ec470898a0733411b6d35f2d5b9d803953fc191) | #3398       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `69%`      | `74%`       |  `5%` :heavy_check_mark:  |
| Branches %| `65%`      | `70%`       |  `5%` :heavy_check_mark:  |
| Complexity| `18222`      | `18258`       |  `36` :no_entry:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Ci.GitInfo](https://github.com/DataDog/dd-trace-dotnet/tree/ef33826964737be56e214928e5cddcaa41a5dd43/tracer/src/Datadog.Trace/Ci/GitInfo.cs) | `-17%` :no_entry: | `-11%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Ci.Processors.OriginTagTraceProcessor](https://github.com/DataDog/dd-trace-dotnet/tree/ef33826964737be56e214928e5cddcaa41a5dd43/tracer/src/Datadog.Trace/Ci/Processors/OriginTagTraceProcessor.cs) | `0%` :heavy_check_mark: | `8%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.DuckTyping.TypesTuple](https://github.com/DataDog/dd-trace-dotnet/tree/ef33826964737be56e214928e5cddcaa41a5dd43/tracer/src/Datadog.Trace/DuckTyping/TypesTuple.cs) | `0%` :heavy_check_mark: | `17%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ExtensionMethods.SpanExtensions](https://github.com/DataDog/dd-trace-dotnet/tree/ef33826964737be56e214928e5cddcaa41a5dd43/tracer/src/Datadog.Trace/ExtensionMethods/SpanExtensions.cs) | `4%` :heavy_check_mark: | `7%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Span](https://github.com/DataDog/dd-trace-dotnet/tree/ef33826964737be56e214928e5cddcaa41a5dd43/tracer/src/Datadog.Trace/Span.ISpan.cs) | `6%` :heavy_check_mark: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Ci.Processors.TestSuiteVisibilityProcessor](https://github.com/DataDog/dd-trace-dotnet/tree/ef33826964737be56e214928e5cddcaa41a5dd43/tracer/src/Datadog.Trace/Ci/Processors/TestSuiteVisibilityProcessor.cs) | `6%` :heavy_check_mark: | `11%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Scope](https://github.com/DataDog/dd-trace-dotnet/tree/ef33826964737be56e214928e5cddcaa41a5dd43/tracer/src/Datadog.Trace/Scope.cs) | `7%` :heavy_check_mark: | `67%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Ci.CITracerManagerFactory](https://github.com/DataDog/dd-trace-dotnet/tree/ef33826964737be56e214928e5cddcaa41a5dd43/tracer/src/Datadog.Trace/Ci/CITracerManagerFactory.cs) | `8%` :heavy_check_mark: | `17%` :heavy_check_mark:   | `1` :no_entry: |
| [Datadog.Trace.Headers.Ip.RequestIpExtractor](https://github.com/DataDog/dd-trace-dotnet/tree/ef33826964737be56e214928e5cddcaa41a5dd43/tracer/src/Datadog.Trace/Headers/Ip/RequestIpExtractor.cs) | `10%` :heavy_check_mark: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Logging.NLog.DirectSubmission.NLogCommon`1](https://github.com/DataDog/dd-trace-dotnet/tree/ef33826964737be56e214928e5cddcaa41a5dd43/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Logging/NLog/DirectSubmission/NLogCommon.cs) | `14%` :heavy_check_mark: | `7%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| ...And 50 more  | | | |


The following classes were added in #3398:

| File    | Line coverage | Branch coverage | Complexity |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Ci.Agent.ApmAgentWriter](https://github.com/DataDog/dd-trace-dotnet/pull/3398/files) | `50%` | `0%` | `10` |
| [Datadog.Trace.Ci.Agent.CIVisibilityProtocolWriter](https://github.com/DataDog/dd-trace-dotnet/pull/3398/files) | `72%` | `57%` | `59` |


2 classes were removed from Datadog.Trace in #3398


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=116543&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/116543/artifacts?artifactName=Code%20Coverage%20Report_116543&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3398](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=116806&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/116806/artifacts?artifactName=Code%20Coverage%20Report_116806&api-version=6.0&%24format=zip)

**Review by bouwkast — APPROVED** [review]
Looks good to me, the tests looked good!

**Review by pierotibou — APPROVED** [review]
Thanks for jumping on it

**Pull request merged**
