### PR TITLE
[Profiler] Bump profiler version to 2.5.0.0

### PR DESCRIPTION
**Pull request by chrisnas**
## Summary of changes
Bump profiler version to 2.5.0.0

## Reason for change
Prepare for new release

### CODE REVIEW

**Review by gleocadie — APPROVED** [review]
LGTM

**Review by andrewlock — CHANGES_REQUESTED** [review]
For the merge to master, we want to bump this to match the Tracer, which is in 2.5.0 in `master`

**Comment by gleocadie** [comment]
> For the merge to master, we want to bump this to match the Tracer, which is in 2.5.0 in `master`

done https://github.com/DataDog/dd-trace-dotnet/pull/2520/commits/c1ee35c18cd99be82a48024f5e9476c91b0cdf71

**Review by andrewlock — APPROVED** [review]
LGTM

**Pull request merged**
