### PR TITLE
[Dynamic Instrumentation] DEBUG-2320 Support pointer and pinned local

### PR DESCRIPTION
**Pull request by dudikeleti**
## Summary of changes
Support this:

```
fixed (char* p = "hello")
{
    Console.WriteLine(*p);
}
```

## Test coverage
`PinnedLocal.cs`

### CODE REVIEW

**Review by daniel-romano-DD — APPROVED** [review]
LGTM

**Comment by andrewlock** [comment]
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (5464)](https://github.com/DataDog/dd-trace-dotnet/tree/05b92fd748167bb0180dd9725ef6b56012bfcbac)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/aa84cf5bf428ff86cc52287413b099b3cc002861)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5464) - mean (76ms)  : 62, 90
     .   : milestone, 76,
    master - mean (73ms)  : 65, 81
     .   : milestone, 73,

    section CallTarget+Inlining+NGEN
    This PR (5464) - mean (1,016ms)  : 995, 1037
     .   : milestone, 1016,
    master - mean (1,017ms)  : 996, 1037
     .   : milestone, 1017,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5464) - mean (109ms)  : 107, 112
     .   : milestone, 109,
    master - mean (110ms)  : 106, 113
     .   : milestone, 110,

    section CallTarget+Inlining+NGEN
    This PR (5464) - mean (733ms)  : 709, 757
     .   : milestone, 733,
    master - mean (736ms)  : 712, 760
     .   : milestone, 736,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5464) - mean (93ms)  : 90, 97
     .   : milestone, 93,
    master - mean (93ms)  : 90, 97
     .   : milestone, 93,

    section CallTarget+Inlining+NGEN
    This PR (5464) - mean (686ms)  : 669, 703
     .   : milestone, 686,
    master - mean (690ms)  : 666, 714
     .   : milestone, 690,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5464) - mean (192ms)  : 188, 196
     .   : milestone, 192,
    master - mean (194ms)  : 188, 200
     .   : milestone, 194,

    section CallTarget+Inlining+NGEN
    This PR (5464) - mean (1,097ms)  : 1077, 1117
     .   : milestone, 1097,
    master - mean (1,101ms)  : 1075, 1126
     .   : milestone, 1101,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5464) - mean (277ms)  : 272, 283
     .   : milestone, 277,
    master - mean (281ms)  : 275, 287
     .   : milestone, 281,

    section CallTarget+Inlining+NGEN
    This PR (5464) - mean (893ms)  : 877, 910
     .   : milestone, 893,
    master - mean (891ms)  : 862, 920
     .   : milestone, 891,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5464) - mean (266ms)  : 261, 272
     .   : milestone, 266,
    master - mean (265ms)  : 259, 270
     .   : milestone, 265,

    section CallTarget+Inlining+NGEN
    This PR (5464) - mean (878ms)  : 846, 910
     .   : milestone, 878,
    master - mean (864ms)  : 837, 892
     .   : milestone, 864,

```

**Comment by andrewlock** [comment]
## Throughput/Crank Report:zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (5464)](https://github.com/DataDog/dd-trace-dotnet/tree/05b92fd748167bb0180dd9725ef6b56012bfcbac)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/aa84cf5bf428ff86cc52287413b099b3cc002861)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/89ae3f4ee7d85b824badda5873166707c9e560b4)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (5464) (10.908M)   : 0, 10908415
    master (10.750M)   : 0, 10749523
    benchmarks/2.9.0 (11.333M)   : 0, 11332977

    section Automatic
    This PR (5464) (7.770M)   : 0, 7769581
    master (7.431M)   : 0, 7430972
    benchmarks/2.9.0 (8.000M)   : 0, 7999601

    section Trace stats
    master (7.683M)   : 0, 7683090

    section Manual
    This PR (5464) (9.912M)   : 0, 9911807
    master (9.425M)   : 0, 9425375

    section Manual + Automatic
    This PR (5464) (7.393M)   : 0, 7392682
    master (6.952M)   : 0, 6951515

    section Version Conflict
    master (6.304M)   : 0, 6303951

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (5464) (9.359M)   : 0, 9358911
    master (9.635M)   : 0, 9634862
    benchmarks/2.9.0 (9.632M)   : 0, 9631577

    section Automatic
    This PR (5464) (6.333M)   : crit ,0, 6332522
    master (6.694M)   : 0, 6694297

    section Trace stats
    master (6.891M)   : 0, 6890569

    section Manual
    This PR (5464) (8.299M)   : 0, 8298649
    master (8.440M)   : 0, 8439984

    section Manual + Automatic
    This PR (5464) (6.244M)   : 0, 6243571
    master (6.214M)   : 0, 6214078

    section Version Conflict
    master (5.736M)   : 0, 5735865

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (5464) (9.906M)   : 0, 9905725
    master (9.841M)   : 0, 9841269
    benchmarks/2.9.0 (9.877M)   : 0, 9877323

    section Automatic
    This PR (5464) (7.103M)   : 0, 7103430
    master (6.973M)   : 0, 6972622
    benchmarks/2.9.0 (7.231M)   : 0, 7230665

    section Trace stats
    master (7.399M)   : 0, 7399394

    section Manual
    This PR (5464) (8.898M)   : 0, 8897772
    master (8.569M)   : 0, 8568841

    section Manual + Automatic
    This PR (5464) (6.930M)   : 0, 6930191
    master (6.726M)   : 0, 6725988

    section Version Conflict
    master (6.077M)   : 0, 6077130

```

**Review by shurivich — APPROVED** [review]

**Review by andrewlock — APPROVED** [review]
:blinfold:

**Pull request merged**
