### PR TITLE
Fix parser null ref and upgrade rule-set

### PR DESCRIPTION
**Pull request by robertpi**
Fixes #

Changes proposed in this pull request:

@DataDog/apm-dotnet

### CODE REVIEW

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #2167 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52): 
* 1 benchmarks are **faster**, with geometric mean 1.222
* 1 benchmarks have **fewer** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`WriteAndFlushEnrichedTraces`|net472|988.3&nbsp;μs|16.36&nbsp;μs|13.66&nbsp;μs|0.0000| 0.0000|0.0000|3.09&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|778.1&nbsp;μs|10.81&nbsp;μs|9.58&nbsp;μs|0.0000| 0.0000|0.0000|2.51&nbsp;KB|
|#2167|`WriteAndFlushEnrichedTraces`|net472|955.1&nbsp;μs|18.53&nbsp;μs|21.34&nbsp;μs|0.0000| 0.0000|0.0000|3.09&nbsp;KB|
|#2167|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|711.1&nbsp;μs|8.41&nbsp;μs|7.46&nbsp;μs|0.0000| 0.0000|0.0000|2.51&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Fewer allocations :tada:



#### Fewer allocations :tada: in #2167

|  Benchmark         | Base Allocated | Diff Allocated | Change   | Change % |
|:----------|-----------:|-----------:|--------:|--------:|
| SendRequest&#8209;netcoreapp3.1 | 19593 B | 19592 B | -1 B | -0.01%

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`SendRequest`|net472|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000| 0.0000|0.0000|0&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`SendRequest`|netcoreapp3.1|294,643.9905&nbsp;ns|5,796.1029&nbsp;ns|9,023.8339&nbsp;ns|0.1447| 0.0000|0.0000|19593&nbsp;B|
|#2167|`SendRequest`|net472|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000| 0.0000|0.0000|0&nbsp;B|
|#2167|`SendRequest`|netcoreapp3.1|278,320.2863&nbsp;ns|4,842.0766&nbsp;ns|4,292.3748&nbsp;ns|0.1386| 0.0000|0.0000|19592&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`ExecuteNonQuery`|net472|393.3&nbsp;ns|3.23&nbsp;ns|2.87&nbsp;ns|0.0000| 0.0000|0.0000|0&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`ExecuteNonQuery`|netcoreapp3.1|352.7&nbsp;ns|7.01&nbsp;ns|11.91&nbsp;ns|0.0000| 0.0000|0.0000|0&nbsp;B|
|#2167|`ExecuteNonQuery`|net472|374.4&nbsp;ns|5.11&nbsp;ns|4.27&nbsp;ns|0.0000| 0.0000|0.0000|0&nbsp;B|
|#2167|`ExecuteNonQuery`|netcoreapp3.1|329.9&nbsp;ns|6.51&nbsp;ns|12.07&nbsp;ns|0.0000| 0.0000|0.0000|0&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`CallElasticsearch`|net472|3.478&nbsp;μs|0.0684&nbsp;μs|0.1124&nbsp;μs|0.1283| 0.0000|0.0000|827&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`CallElasticsearch`|netcoreapp3.1|1.740&nbsp;μs|0.0315&nbsp;μs|0.0630&nbsp;μs|0.0105| 0.0000|0.0000|768&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`CallElasticsearchAsync`|net472|4.223&nbsp;μs|0.0833&nbsp;μs|0.1296&nbsp;μs|0.1481| 0.0000|0.0000|963&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`CallElasticsearchAsync`|netcoreapp3.1|1.792&nbsp;μs|0.0286&nbsp;μs|0.0268&nbsp;μs|0.0124| 0.0000|0.0000|888&nbsp;B|
|#2167|`CallElasticsearch`|net472|3.111&nbsp;μs|0.0580&nbsp;μs|0.0921&nbsp;μs|0.1281| 0.0000|0.0000|827&nbsp;B|
|#2167|`CallElasticsearch`|netcoreapp3.1|1.546&nbsp;μs|0.0301&nbsp;μs|0.0267&nbsp;μs|0.0106| 0.0000|0.0000|768&nbsp;B|
|#2167|`CallElasticsearchAsync`|net472|3.814&nbsp;μs|0.0653&nbsp;μs|0.0579&nbsp;μs|0.1482| 0.0000|0.0000|963&nbsp;B|
|#2167|`CallElasticsearchAsync`|netcoreapp3.1|1.637&nbsp;μs|0.0251&nbsp;μs|0.0235&nbsp;μs|0.0123| 0.0000|0.0000|888&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`ExecuteAsync`|net472|3.761&nbsp;μs|0.0644&nbsp;μs|0.0602&nbsp;μs|0.1687| 0.0000|0.0000|1083&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`ExecuteAsync`|netcoreapp3.1|1.956&nbsp;μs|0.0356&nbsp;μs|0.0333&nbsp;μs|0.0137| 0.0000|0.0000|1008&nbsp;B|
|#2167|`ExecuteAsync`|net472|3.614&nbsp;μs|0.0718&nbsp;μs|0.1530&nbsp;μs|0.1690| 0.0000|0.0000|1083&nbsp;B|
|#2167|`ExecuteAsync`|netcoreapp3.1|1.954&nbsp;μs|0.0367&nbsp;μs|0.0377&nbsp;μs|0.0142| 0.0000|0.0000|1008&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`SendAsync`|net472|7.719&nbsp;μs|0.1033&nbsp;μs|0.0916&nbsp;μs|0.3461| 0.0000|0.0000|2.19&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`SendAsync`|netcoreapp3.1|4.441&nbsp;μs|0.0288&nbsp;μs|0.0256&nbsp;μs|0.0289| 0.0000|0.0000|2.09&nbsp;KB|
|#2167|`SendAsync`|net472|7.469&nbsp;μs|0.1279&nbsp;μs|0.1197&nbsp;μs|0.3486| 0.0000|0.0000|2.19&nbsp;KB|
|#2167|`SendAsync`|netcoreapp3.1|4.581&nbsp;μs|0.0885&nbsp;μs|0.1351&nbsp;μs|0.0292| 0.0000|0.0000|2.09&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`EnrichedLog`|net472|4.278&nbsp;μs|0.0786&nbsp;μs|0.0697&nbsp;μs|0.2875| 0.0000|0.0000|1.79&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`EnrichedLog`|netcoreapp3.1|4.016&nbsp;μs|0.0344&nbsp;μs|0.0322&nbsp;μs|0.0277| 0.0000|0.0000|1.94&nbsp;KB|
|#2167|`EnrichedLog`|net472|4.315&nbsp;μs|0.0860&nbsp;μs|0.0844&nbsp;μs|0.2865| 0.0000|0.0000|1.79&nbsp;KB|
|#2167|`EnrichedLog`|netcoreapp3.1|3.895&nbsp;μs|0.0378&nbsp;μs|0.0295&nbsp;μs|0.0275| 0.0000|0.0000|1.94&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`EnrichedLog`|net472|185.9&nbsp;μs|3.64&nbsp;μs|4.04&nbsp;μs|0.6406| 0.1830|0.0000|5.23&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`EnrichedLog`|netcoreapp3.1|155.3&nbsp;μs|2.70&nbsp;μs|2.53&nbsp;μs|0.0773| 0.0000|0.0000|5.05&nbsp;KB|
|#2167|`EnrichedLog`|net472|184.6&nbsp;μs|2.73&nbsp;μs|2.42&nbsp;μs|0.6481| 0.1852|0.0000|5.23&nbsp;KB|
|#2167|`EnrichedLog`|netcoreapp3.1|154.2&nbsp;μs|3.00&nbsp;μs|4.75&nbsp;μs|0.0758| 0.0000|0.0000|5.05&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`EnrichedLog`|net472|13.48&nbsp;μs|0.268&nbsp;μs|0.375&nbsp;μs|0.8483| 0.0000|0.0000|5.31&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`EnrichedLog`|netcoreapp3.1|10.60&nbsp;μs|0.096&nbsp;μs|0.080&nbsp;μs|0.0898| 0.0000|0.0000|6.28&nbsp;KB|
|#2167|`EnrichedLog`|net472|12.43&nbsp;μs|0.236&nbsp;μs|0.271&nbsp;μs|0.8542| 0.0000|0.0000|5.31&nbsp;KB|
|#2167|`EnrichedLog`|netcoreapp3.1|10.99&nbsp;μs|0.177&nbsp;μs|0.148&nbsp;μs|0.0898| 0.0000|0.0000|6.28&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`SendReceive`|net472|2.406&nbsp;μs|0.0283&nbsp;μs|0.0265&nbsp;μs|0.1550| 0.0000|0.0000|987&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`SendReceive`|netcoreapp3.1|2.106&nbsp;μs|0.0204&nbsp;μs|0.0181&nbsp;μs|0.0136| 0.0000|0.0000|984&nbsp;B|
|#2167|`SendReceive`|net472|2.245&nbsp;μs|0.0312&nbsp;μs|0.0292&nbsp;μs|0.1546| 0.0000|0.0000|987&nbsp;B|
|#2167|`SendReceive`|netcoreapp3.1|2.012&nbsp;μs|0.0311&nbsp;μs|0.0291&nbsp;μs|0.0142| 0.0000|0.0000|984&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Faster :tada: Same allocations :heavy_check_mark:



#### Faster :tada: in #2167

|  Benchmark         | base/diff | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.SerilogBenchmark.EnrichedLog&#8209;net472 | 1.222 | 9,285.20 | 7,597.96 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`EnrichedLog`|net472|9.289&nbsp;μs|0.0906&nbsp;μs|0.0803&nbsp;μs|0.4475| 0.0000|0.0000|2.8&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`EnrichedLog`|netcoreapp3.1|7.592&nbsp;μs|0.0892&nbsp;μs|0.0790&nbsp;μs|0.0376| 0.0000|0.0000|2.61&nbsp;KB|
|#2167|`EnrichedLog`|net472|7.605&nbsp;μs|0.1178&nbsp;μs|0.1045&nbsp;μs|0.4461| 0.0000|0.0000|2.8&nbsp;KB|
|#2167|`EnrichedLog`|netcoreapp3.1|7.019&nbsp;μs|0.1336&nbsp;μs|0.1538&nbsp;μs|0.0385| 0.0000|0.0000|2.61&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`StartFinishSpan`|net472|1,000.3&nbsp;ns|13.45&nbsp;ns|12.58&nbsp;ns|0.0681| 0.0000|0.0000|433&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`StartFinishSpan`|netcoreapp3.1|944.3&nbsp;ns|11.52&nbsp;ns|10.78&nbsp;ns|0.0061| 0.0000|0.0000|432&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`StartFinishScope`|net472|1,211.6&nbsp;ns|11.53&nbsp;ns|10.22&nbsp;ns|0.0805| 0.0000|0.0000|514&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52)|`StartFinishScope`|netcoreapp3.1|1,133.0&nbsp;ns|15.62&nbsp;ns|13.84&nbsp;ns|0.0077| 0.0000|0.0000|552&nbsp;B|
|#2167|`StartFinishSpan`|net472|947.1&nbsp;ns|15.73&nbsp;ns|18.12&nbsp;ns|0.0679| 0.0000|0.0000|433&nbsp;B|
|#2167|`StartFinishSpan`|netcoreapp3.1|1,024.3&nbsp;ns|20.04&nbsp;ns|20.58&nbsp;ns|0.0061| 0.0000|0.0000|432&nbsp;B|
|#2167|`StartFinishScope`|net472|1,166.1&nbsp;ns|22.48&nbsp;ns|32.24&nbsp;ns|0.0807| 0.0000|0.0000|514&nbsp;B|
|#2167|`StartFinishScope`|netcoreapp3.1|1,101.7&nbsp;ns|10.67&nbsp;ns|9.98&nbsp;ns|0.0077| 0.0000|0.0000|552&nbsp;B|
</details>

**Review by anna-git — APPROVED** [review]

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #2167 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52) will **not change** line coverage
:heavy_check_mark: Merging #2167 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52) will **not change** branch coverage
:no_entry: Merging #2167 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52) will will **increase** complexity by `6`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52) | #2167       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `9187` / `12694` | `9178` / `12695` |          |
| Lines %   | `72%`      | `72%`      |  `0%` :heavy_check_mark:  |
| Branches  | `4139` / `6161` | `4137` / `6167` |          |
| Branches %| `67%`      | `67%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `7330`      | `7336`        |  `6`  :no_entry:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=83607&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/83607/artifacts?artifactName=Code%20Coverage%20Report_83607&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2167](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=83788&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/83788/artifacts?artifactName=Code%20Coverage%20Report_83788&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/b9357bd74f3bd5016ac1baf81584e13a78fc2e52) | #2167       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `72%`      | `72%`       |  `0%` :heavy_check_mark:  |
| Branches %| `67%`      | `67%`       |  `0%` :heavy_check_mark:  |
| Complexity| `7330`      | `7336`       |  `6` :no_entry:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteIntegrationBis](https://github.com/DataDog/dd-trace-dotnet/tree/03b984ce3b3b7f199d72ba704210b1a4a5b5c18f/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Couchbase/IIOServiceExecuteIntegrationBis.cs) | `-100%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.MsTestV2.TestMethodRunnerExecuteIntegration](https://github.com/DataDog/dd-trace-dotnet/tree/03b984ce3b3b7f199d72ba704210b1a4a5b5c18f/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Testing/MsTestV2/TestMethodRunnerExecuteIntegration.cs) | `-33%` :no_entry: | `-19%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.NUnit.NUnitCompositeWorkItemSkipChildrenIntegration](https://github.com/DataDog/dd-trace-dotnet/tree/03b984ce3b3b7f199d72ba704210b1a4a5b5c18f/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Testing/NUnit/NUnitCompositeWorkItemSkipChildrenIntegration.cs) | `-8%` :no_entry: | `-8%` :no_entry:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=83607&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/83607/artifacts?artifactName=Code%20Coverage%20Report_83607&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2167](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=83788&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/83788/artifacts?artifactName=Code%20Coverage%20Report_83788&api-version=6.0&%24format=zip)

**Review by pierotibou — COMMENTED** [review]
Shouldn't this change impact existing tests?

**Comment by robertpi** [comment]
@pierotibou it doesn't break any tests, but it probably should. I've added https://datadoghq.atlassian.net/browse/APPSEC-2590 to do some more testing around this.

**Pull request merged**
