### PR TITLE
Improve installer smoke tests

### PR DESCRIPTION
**Pull request by andrewlock**
## Summary of changes

Adds installer testing for more distros, including verifying that the tracer logs don't have errors.

## Reason for change

We discovered a regression on CentOS, but realised we aren't testing on there. We want to make sure we at least have minimal coverage. This also improves the coverage for existing distros by explicitly checking the logs for errors.

## Implementation details

Switched from doing a simple `docker run` and checking the exit code to using `docker-compose` to stand up a test agent. I wanted to use the [existing test agent](https://github.com/DataDog/dd-apm-test-agent) but [there's a bug there which makes it unusable with the .NET Tracer](https://github.com/DataDog/dd-apm-test-agent/issues/65) at the moment, so resorted to using [Wiremock](https://wiremock.org/) instead for now, and we can switch it out once the bug is fixed. 

## Test coverage

For additional distros, I pushed docker images for 15 new combinations:

- CentOS 7: `netcoreapp2.1`, `netcoreapp3.1`, `net5.0`, `net6.0`
- RHEL 8 UBI: `netcoreapp3.1`,`net5.0`, `net6.0`
- CentOS Stream 8: `netcoreapp3.1`,`net5.0`, `net6.0`
- CentOS Stream 9: `net6.0`
- OpenSUSE 15: `netcoreapp2.1`, `netcoreapp3.1`, `net5.0`, `net6.0`

We now test on all the distros the Microsoft support which don't require specific licensing (i.e. not RHEL and SLES).

I have only pushed the docker images for x64 currently. We can look at adding the equivalent for arm64, but that requires additional work to create arm64 compatible images, and can be pushed to later I think.

## Other details
As expected, the CentOS installer tests fail, so we can't merge this until we have a fix

### CODE REVIEW

**Review by pierotibou — APPROVED** [review]

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #2726 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/e3be3b4d9da6d02902e0aa14025bea0e92fca211) will **not change** line coverage
:heavy_check_mark: Merging #2726 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/e3be3b4d9da6d02902e0aa14025bea0e92fca211) will **not change** branch coverage
:no_entry: Merging #2726 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/e3be3b4d9da6d02902e0aa14025bea0e92fca211) will will **increase** complexity by `2`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/e3be3b4d9da6d02902e0aa14025bea0e92fca211) | #2726       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `13651` / `19217` | `13686` / `19227` |          |
| Lines %   | `71%`      | `71%`      |  `0%` :heavy_check_mark:  |
| Branches  | `7760` / `11403` | `7783` / `11405` |          |
| Branches %| `68%`      | `68%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `12690`      | `12692`        |  `2`  :no_entry:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=97370&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/97370/artifacts?artifactName=Code%20Coverage%20Report_97370&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2726](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=97432&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/97432/artifacts?artifactName=Code%20Coverage%20Report_97432&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/e3be3b4d9da6d02902e0aa14025bea0e92fca211) | #2726       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `71%`      | `71%`       |  `0%` :heavy_check_mark:  |
| Branches %| `68%`      | `68%`       |  `0%` :heavy_check_mark:  |
| Complexity| `12690`      | `12692`       |  `2` :no_entry:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Ci.CIVisibility](https://github.com/DataDog/dd-trace-dotnet/tree/746355bafc11d71c751186e9dbe75183e7da169b/tracer/src/Datadog.Trace/Ci/CIVisibility.cs) | `7%` :heavy_check_mark: | `7%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Telemetry.JsonHttpClientTelemetryTransport](https://github.com/DataDog/dd-trace-dotnet/tree/746355bafc11d71c751186e9dbe75183e7da169b/tracer/src/Datadog.Trace/Telemetry/Transports/JsonHttpClientTelemetryTransport.cs) | `26%` :heavy_check_mark: | `38%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ContinuousProfiler.NativeInterop](https://github.com/DataDog/dd-trace-dotnet/tree/746355bafc11d71c751186e9dbe75183e7da169b/tracer/src/Datadog.Trace/ContinuousProfiler/NativeInterop.cs) | `30%` :heavy_check_mark: | `17%` :heavy_check_mark:   | `2` :no_entry: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=97370&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/97370/artifacts?artifactName=Code%20Coverage%20Report_97370&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2726](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=97432&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/97432/artifacts?artifactName=Code%20Coverage%20Report_97432&api-version=6.0&%24format=zip)

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #2726 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce): 
* 2 benchmarks are **slower**, with geometric mean 1.152
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`WriteAndFlushEnrichedTraces`|net472|955μs|5.14μs|29.1μs|0| 0|0|3.16&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|727μs|2.14μs|8μs|0| 0|0|2.57&nbsp;KB|
|#2726|`WriteAndFlushEnrichedTraces`|net472|949μs|4.84μs|21.6μs|0| 0|0|3.16&nbsp;KB|
|#2726|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|707μs|2.97μs|10.3μs|0| 0|0|2.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`AllCycleSimpleBody`|net472|330ns|1.78ns|9.74ns|0.066| 0|0|417&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`AllCycleSimpleBody`|netcoreapp3.1|424ns|2.4ns|15.9ns|0.00571| 0|0|416&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`AllCycleMoreComplexBody`|net472|313ns|1.06ns|3.83ns|0.0622| 0|0|393&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`AllCycleMoreComplexBody`|netcoreapp3.1|410ns|1.15ns|4.31ns|0.0054| 0|0|392&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`BodyExtractorSimpleBody`|net472|436ns|1.97ns|10ns|0.057| 0|0|361&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`BodyExtractorSimpleBody`|netcoreapp3.1|503ns|2.64ns|14ns|0.0037| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`BodyExtractorMoreComplexBody`|net472|24.6μs|125ns|601ns|1.19| 0.0129|0|7.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`BodyExtractorMoreComplexBody`|netcoreapp3.1|22.6μs|124ns|754ns|0.0921| 0|0|6.75&nbsp;KB|
|#2726|`AllCycleSimpleBody`|net472|327ns|1.79ns|9.64ns|0.066| 0|0|417&nbsp;B|
|#2726|`AllCycleSimpleBody`|netcoreapp3.1|434ns|2.45ns|16.2ns|0.00581| 0|0|416&nbsp;B|
|#2726|`AllCycleMoreComplexBody`|net472|314ns|1.45ns|5.61ns|0.0622| 0|0|393&nbsp;B|
|#2726|`AllCycleMoreComplexBody`|netcoreapp3.1|428ns|1.93ns|6.98ns|0.00549| 0|0|392&nbsp;B|
|#2726|`BodyExtractorSimpleBody`|net472|441ns|1.92ns|6.93ns|0.0569| 0|0|361&nbsp;B|
|#2726|`BodyExtractorSimpleBody`|netcoreapp3.1|521ns|8.83ns|88.3ns|0.0037| 0|0|272&nbsp;B|
|#2726|`BodyExtractorMoreComplexBody`|net472|25.7μs|147ns|1.18μs|1.18| 0.0129|0|7.62&nbsp;KB|
|#2726|`BodyExtractorMoreComplexBody`|netcoreapp3.1|21.3μs|70.2ns|272ns|0.0942| 0|0|6.75&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Unknown :shrug: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`SendRequest`|netcoreapp3.1|303μs|1.63μs|8.63μs|0.151| 0|0|19.74&nbsp;KB|
|#2726|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#2726|`SendRequest`|netcoreapp3.1|299μs|676ns|2.34μs|0.151| 0|0|19.74&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #2726

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.DbCommandBenchmark.ExecuteNonQuery&#8209;netcoreapp3.1 | 1.141 | 1,607.06 | 1,834.32 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`ExecuteNonQuery`|net472|2.05μs|10.4ns|46.5ns|0.0936| 0.000996|0|594&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`ExecuteNonQuery`|netcoreapp3.1|1.61μs|3.6ns|13.5ns|0.0088| 0|0|632&nbsp;B|
|#2726|`ExecuteNonQuery`|net472|1.95μs|11.2ns|86.3ns|0.0935| 0.000945|0|594&nbsp;B|
|#2726|`ExecuteNonQuery`|netcoreapp3.1|1.83μs|9.79ns|48.9ns|0.0091| 0|0|632&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #2726

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.ElasticsearchBenchmark.CallElasticsearch&#8209;netcoreapp3.1 | 1.162 | 1,833.86 | 2,131.69 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`CallElasticsearch`|net472|3.2μs|15.6ns|66.4ns|0.127| 0|0|803&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`CallElasticsearch`|netcoreapp3.1|1.83μs|9.54ns|43.7ns|0.0106| 0|0|792&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`CallElasticsearchAsync`|net472|3.02μs|13.6ns|50.8ns|0.149| 0|0|939&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`CallElasticsearchAsync`|netcoreapp3.1|1.97μs|10.5ns|57.3ns|0.0124| 0|0|912&nbsp;B|
|#2726|`CallElasticsearch`|net472|3.41μs|18.6ns|114ns|0.125| 0|0|802&nbsp;B|
|#2726|`CallElasticsearch`|netcoreapp3.1|2.13μs|10.6ns|43.5ns|0.0115| 0|0|792&nbsp;B|
|#2726|`CallElasticsearchAsync`|net472|3.05μs|14.9ns|66.7ns|0.148| 0.00158|0|939&nbsp;B|
|#2726|`CallElasticsearchAsync`|netcoreapp3.1|2.06μs|9.04ns|35ns|0.0123| 0|0|912&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`ExecuteAsync`|net472|3.96μs|19.8ns|84ns|0.168| 0|0|1.06&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`ExecuteAsync`|netcoreapp3.1|2.19μs|12.3ns|85.3ns|0.0149| 0|0|1.03&nbsp;KB|
|#2726|`ExecuteAsync`|net472|3.92μs|21.4ns|123ns|0.167| 0.00197|0|1.06&nbsp;KB|
|#2726|`ExecuteAsync`|netcoreapp3.1|2.17μs|9.92ns|42.1ns|0.0144| 0|0|1.03&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`SendAsync`|net472|7.25μs|35.4ns|141ns|0.36| 0|0|2.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`SendAsync`|netcoreapp3.1|4.84μs|21.8ns|81.4ns|0.0312| 0|0|2.21&nbsp;KB|
|#2726|`SendAsync`|net472|7.53μs|42ns|252ns|0.356| 0|0|2.28&nbsp;KB|
|#2726|`SendAsync`|netcoreapp3.1|4.93μs|23.9ns|95.7ns|0.0303| 0|0|2.21&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`EnrichedLog`|net472|3.67μs|19.4ns|106ns|0.227| 0|0|1.45&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`EnrichedLog`|netcoreapp3.1|3.28μs|15.1ns|58.5ns|0.0218| 0|0|1.53&nbsp;KB|
|#2726|`EnrichedLog`|net472|3.5μs|19.9ns|135ns|0.228| 0|0|1.45&nbsp;KB|
|#2726|`EnrichedLog`|netcoreapp3.1|3.39μs|17.7ns|83.1ns|0.0211| 0|0|1.53&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`EnrichedLog`|net472|292μs|1.32μs|5.1μs|0.431| 0.144|0|4.33&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`EnrichedLog`|netcoreapp3.1|245μs|1.33μs|7.62μs|0| 0|0|4.21&nbsp;KB|
|#2726|`EnrichedLog`|net472|301μs|1.7μs|11.4μs|0.432| 0.144|0|4.33&nbsp;KB|
|#2726|`EnrichedLog`|netcoreapp3.1|234μs|1.14μs|4.95μs|0| 0|0|4.21&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`EnrichedLog`|net472|8.19μs|30.3ns|117ns|0.505| 0|0|3.23&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`EnrichedLog`|netcoreapp3.1|6.99μs|36.8ns|202ns|0.0495| 0|0|3.6&nbsp;KB|
|#2726|`EnrichedLog`|net472|7.58μs|41.4ns|238ns|0.504| 0|0|3.23&nbsp;KB|
|#2726|`EnrichedLog`|netcoreapp3.1|6.54μs|31.2ns|149ns|0.0505| 0|0|3.6&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`SendReceive`|net472|2.61μs|14.3ns|82.3ns|0.161| 0.0013|0|1.01&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`SendReceive`|netcoreapp3.1|2.12μs|11.6ns|66.4ns|0.0137| 0|0|1.01&nbsp;KB|
|#2726|`SendReceive`|net472|2.36μs|10.4ns|40.2ns|0.16| 0.00116|0|1.01&nbsp;KB|
|#2726|`SendReceive`|netcoreapp3.1|2.09μs|8.41ns|33.6ns|0.0136| 0|0|1.01&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`EnrichedLog`|net472|6.79μs|38.6ns|276ns|0.291| 0|0|1.87&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`EnrichedLog`|netcoreapp3.1|5.45μs|23.3ns|90.3ns|0.0191| 0|0|1.49&nbsp;KB|
|#2726|`EnrichedLog`|net472|6.27μs|32.4ns|162ns|0.291| 0|0|1.87&nbsp;KB|
|#2726|`EnrichedLog`|netcoreapp3.1|5.3μs|20.8ns|75.1ns|0.0208| 0|0|1.49&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`StartFinishSpan`|net472|966ns|4.62ns|17.9ns|0.0718| 0|0|457&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`StartFinishSpan`|netcoreapp3.1|945ns|4.99ns|24.9ns|0.00599| 0|0|456&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`StartFinishScope`|net472|1.24μs|7.02ns|46.6ns|0.0844| 0|0|538&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`StartFinishScope`|netcoreapp3.1|1.1μs|5.91ns|32.4ns|0.008| 0|0|576&nbsp;B|
|#2726|`StartFinishSpan`|net472|1.02μs|5.81ns|42.7ns|0.0716| 0|0|457&nbsp;B|
|#2726|`StartFinishSpan`|netcoreapp3.1|972ns|5.67ns|48.1ns|0.00605| 0|0|456&nbsp;B|
|#2726|`StartFinishScope`|net472|1.15μs|3.46ns|12.9ns|0.084| 0|0|538&nbsp;B|
|#2726|`StartFinishScope`|netcoreapp3.1|1.13μs|4.09ns|15.3ns|0.00775| 0|0|576&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`RunOnMethodBegin`|net472|1.42μs|7.34ns|33.6ns|0.0839| 0|0|538&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fa58893a81893269eed4f5f7445dadd4c334a2ce)|`RunOnMethodBegin`|netcoreapp3.1|1.3μs|7.4ns|55.4ns|0.00747| 0|0|576&nbsp;B|
|#2726|`RunOnMethodBegin`|net472|1.32μs|4.3ns|16.1ns|0.0839| 0|0|538&nbsp;B|
|#2726|`RunOnMethodBegin`|netcoreapp3.1|1.26μs|7.16ns|49.6ns|0.00802| 0|0|576&nbsp;B|
</details>

**Review by robertpi — APPROVED** [review]
Compiles, ship it 😉

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #2726 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/e3be3b4d9da6d02902e0aa14025bea0e92fca211) will **not change** line coverage
:heavy_check_mark: Merging #2726 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/e3be3b4d9da6d02902e0aa14025bea0e92fca211) will **not change** branch coverage
:no_entry: Merging #2726 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/e3be3b4d9da6d02902e0aa14025bea0e92fca211) will will **increase** complexity by `2`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/e3be3b4d9da6d02902e0aa14025bea0e92fca211) | #2726       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `13651` / `19217` | `13705` / `19227` |          |
| Lines %   | `71%`      | `71%`      |  `0%` :heavy_check_mark:  |
| Branches  | `7760` / `11403` | `7792` / `11405` |          |
| Branches %| `68%`      | `68%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `12690`      | `12692`        |  `2`  :no_entry:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=97370&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/97370/artifacts?artifactName=Code%20Coverage%20Report_97370&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2726](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=97505&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/97505/artifacts?artifactName=Code%20Coverage%20Report_97505&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/e3be3b4d9da6d02902e0aa14025bea0e92fca211) | #2726       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `71%`      | `71%`       |  `0%` :heavy_check_mark:  |
| Branches %| `68%`      | `68%`       |  `0%` :heavy_check_mark:  |
| Complexity| `12690`      | `12692`       |  `2` :no_entry:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Ci.CIVisibility](https://github.com/DataDog/dd-trace-dotnet/tree/3d2d286a810792ce8c098686267fb511b7c91dda/tracer/src/Datadog.Trace/Ci/CIVisibility.cs) | `7%` :heavy_check_mark: | `7%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Telemetry.JsonHttpClientTelemetryTransport](https://github.com/DataDog/dd-trace-dotnet/tree/3d2d286a810792ce8c098686267fb511b7c91dda/tracer/src/Datadog.Trace/Telemetry/Transports/JsonHttpClientTelemetryTransport.cs) | `26%` :heavy_check_mark: | `38%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ContinuousProfiler.NativeInterop](https://github.com/DataDog/dd-trace-dotnet/tree/3d2d286a810792ce8c098686267fb511b7c91dda/tracer/src/Datadog.Trace/ContinuousProfiler/NativeInterop.cs) | `30%` :heavy_check_mark: | `17%` :heavy_check_mark:   | `2` :no_entry: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=97370&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/97370/artifacts?artifactName=Code%20Coverage%20Report_97370&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2726](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=97505&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/97505/artifacts?artifactName=Code%20Coverage%20Report_97505&api-version=6.0&%24format=zip)

**Pull request merged**
