### PR TITLE
Display the crash tests stdout live

### PR DESCRIPTION
**Pull request by kevingosse**
## Summary of changes

In the crashtracking installer smoke-tests, display the output as it comes instead of all at once when it finishes.

## Reason for change

The job sometimes hangs. When it happens, it gets killed after the timeout elapses, and we see no output because the command didn't complete.

## Implementation details

Bash.

### CODE REVIEW

**Comment by andrewlock** [comment]
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (5964)](https://github.com/DataDog/dd-trace-dotnet/tree/dc21e1cb24ff1f5c109de934b24c0652ee53272d)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/c8a41a29e1349a05bbba50945f4d22893d70fd51)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).

**Comment by andrewlock** [comment]
## Benchmarks Report for tracer :snail:

Benchmarks for #5964 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b): 
* 1 benchmarks are **faster**, with geometric mean 1.134
* 1 benchmarks are **slower**, with geometric mean 1.124
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.ActivityBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`StartStopWithChild`|net6.0|7.76μs|43.7ns|303ns|0.0148| 0.00738|0|5.43&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`StartStopWithChild`|netcoreapp3.1|9.78μs|55.1ns|389ns|0.0241| 0.00963|0|5.61&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`StartStopWithChild`|net472|15.8μs|46.9ns|175ns|1.02| 0.302|0.103|6.07&nbsp;KB|
|#5964|`StartStopWithChild`|net6.0|7.52μs|42.9ns|319ns|0.0145| 0.00726|0|5.43&nbsp;KB|
|#5964|`StartStopWithChild`|netcoreapp3.1|9.65μs|51.3ns|308ns|0.0143| 0.00476|0|5.62&nbsp;KB|
|#5964|`StartStopWithChild`|net472|15.8μs|59.3ns|230ns|1.03| 0.311|0.0956|6.07&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`WriteAndFlushEnrichedTraces`|net6.0|476μs|256ns|990ns|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|645μs|131ns|473ns|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`WriteAndFlushEnrichedTraces`|net472|839μs|659ns|2.55μs|0.417| 0|0|3.3&nbsp;KB|
|#5964|`WriteAndFlushEnrichedTraces`|net6.0|503μs|390ns|1.51μs|0| 0|0|2.7&nbsp;KB|
|#5964|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|636μs|235ns|911ns|0| 0|0|2.7&nbsp;KB|
|#5964|`WriteAndFlushEnrichedTraces`|net472|836μs|247ns|892ns|0.419| 0|0|3.3&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`SendRequest`|net6.0|187μs|884ns|3.54μs|0.183| 0|0|18.45&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`SendRequest`|netcoreapp3.1|207μs|1.1μs|5.91μs|0.209| 0|0|20.61&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`SendRequest`|net472|0.0059ns|0.00211ns|0.00818ns|0| 0|0|0&nbsp;b|
|#5964|`SendRequest`|net6.0|183μs|885ns|3.76μs|0.267| 0|0|18.45&nbsp;KB|
|#5964|`SendRequest`|netcoreapp3.1|205μs|1.06μs|4.87μs|0.199| 0|0|20.61&nbsp;KB|
|#5964|`SendRequest`|net472|0.000693ns|0.00036ns|0.00135ns|0| 0|0|0&nbsp;b|
</details>


<details><summary><strong>Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`WriteAndFlushEnrichedTraces`|net6.0|543μs|1.82μs|6.83μs|0.546| 0|0|41.52&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|677μs|3.19μs|14.6μs|0.329| 0|0|41.73&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`WriteAndFlushEnrichedTraces`|net472|875μs|3.56μs|13.8μs|8.13| 2.57|0.428|53.27&nbsp;KB|
|#5964|`WriteAndFlushEnrichedTraces`|net6.0|544μs|1.06μs|3.82μs|0.558| 0|0|41.63&nbsp;KB|
|#5964|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|701μs|3.44μs|15μs|0.34| 0|0|41.71&nbsp;KB|
|#5964|`WriteAndFlushEnrichedTraces`|net472|891μs|4.48μs|20.5μs|8.68| 2.6|0.434|53.32&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`ExecuteNonQuery`|net6.0|1.35μs|1.31ns|5.06ns|0.0142| 0|0|1.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`ExecuteNonQuery`|netcoreapp3.1|1.72μs|1.68ns|6.5ns|0.0138| 0|0|1.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`ExecuteNonQuery`|net472|2.02μs|0.813ns|2.93ns|0.157| 0|0|987&nbsp;B|
|#5964|`ExecuteNonQuery`|net6.0|1.31μs|1.2ns|4.65ns|0.0142| 0|0|1.02&nbsp;KB|
|#5964|`ExecuteNonQuery`|netcoreapp3.1|1.7μs|0.638ns|2.39ns|0.0135| 0|0|1.02&nbsp;KB|
|#5964|`ExecuteNonQuery`|net472|1.99μs|1.53ns|5.74ns|0.157| 0|0|987&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`CallElasticsearch`|net6.0|1.19μs|0.497ns|1.86ns|0.0137| 0|0|976&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`CallElasticsearch`|netcoreapp3.1|1.46μs|0.583ns|2.1ns|0.0132| 0|0|976&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`CallElasticsearch`|net472|2.47μs|1.59ns|5.97ns|0.158| 0|0|995&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`CallElasticsearchAsync`|net6.0|1.35μs|1.64ns|6.37ns|0.0135| 0|0|952&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`CallElasticsearchAsync`|netcoreapp3.1|1.65μs|0.594ns|2.3ns|0.0142| 0|0|1.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`CallElasticsearchAsync`|net472|2.51μs|1.25ns|4.67ns|0.166| 0|0|1.05&nbsp;KB|
|#5964|`CallElasticsearch`|net6.0|1.22μs|0.598ns|2.32ns|0.0135| 0|0|976&nbsp;B|
|#5964|`CallElasticsearch`|netcoreapp3.1|1.62μs|0.636ns|2.46ns|0.0129| 0|0|976&nbsp;B|
|#5964|`CallElasticsearch`|net472|2.54μs|1.8ns|6.98ns|0.157| 0|0|995&nbsp;B|
|#5964|`CallElasticsearchAsync`|net6.0|1.26μs|0.537ns|2.01ns|0.0133| 0|0|952&nbsp;B|
|#5964|`CallElasticsearchAsync`|netcoreapp3.1|1.67μs|0.695ns|2.69ns|0.0142| 0|0|1.02&nbsp;KB|
|#5964|`CallElasticsearchAsync`|net472|2.62μs|1.54ns|5.75ns|0.166| 0|0|1.05&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`ExecuteAsync`|net6.0|1.34μs|0.561ns|2.1ns|0.013| 0|0|952&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`ExecuteAsync`|netcoreapp3.1|1.57μs|0.783ns|2.82ns|0.0127| 0|0|952&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`ExecuteAsync`|net472|1.73μs|0.546ns|2.04ns|0.145| 0|0|915&nbsp;B|
|#5964|`ExecuteAsync`|net6.0|1.25μs|1.34ns|5.2ns|0.0132| 0|0|952&nbsp;B|
|#5964|`ExecuteAsync`|netcoreapp3.1|1.61μs|0.607ns|2.35ns|0.0129| 0|0|952&nbsp;B|
|#5964|`ExecuteAsync`|net472|1.7μs|0.579ns|2.17ns|0.145| 0|0|915&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`SendAsync`|net6.0|4.14μs|0.957ns|3.58ns|0.0311| 0|0|2.22&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`SendAsync`|netcoreapp3.1|5.1μs|2.15ns|8.05ns|0.0359| 0|0|2.76&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`SendAsync`|net472|7.75μs|2.41ns|9.35ns|0.496| 0|0|3.15&nbsp;KB|
|#5964|`SendAsync`|net6.0|4.35μs|1.15ns|4.47ns|0.0301| 0|0|2.22&nbsp;KB|
|#5964|`SendAsync`|netcoreapp3.1|5.14μs|1.91ns|6.88ns|0.0359| 0|0|2.76&nbsp;KB|
|#5964|`SendAsync`|net472|7.8μs|3.57ns|13.4ns|0.499| 0|0|3.15&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`EnrichedLog`|net6.0|1.47μs|0.435ns|1.68ns|0.0229| 0|0|1.64&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`EnrichedLog`|netcoreapp3.1|2.38μs|0.732ns|2.74ns|0.0225| 0|0|1.64&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`EnrichedLog`|net472|2.71μs|1.55ns|5.99ns|0.249| 0|0|1.57&nbsp;KB|
|#5964|`EnrichedLog`|net6.0|1.48μs|0.649ns|2.51ns|0.0229| 0|0|1.64&nbsp;KB|
|#5964|`EnrichedLog`|netcoreapp3.1|2.32μs|0.8ns|2.99ns|0.022| 0|0|1.64&nbsp;KB|
|#5964|`EnrichedLog`|net472|2.81μs|2.06ns|7.97ns|0.25| 0|0|1.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`EnrichedLog`|net6.0|117μs|134ns|502ns|0.0589| 0|0|4.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`EnrichedLog`|netcoreapp3.1|121μs|386ns|1.5μs|0| 0|0|4.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`EnrichedLog`|net472|151μs|215ns|832ns|0.682| 0.227|0|4.46&nbsp;KB|
|#5964|`EnrichedLog`|net6.0|116μs|318ns|1.23μs|0.0584| 0|0|4.28&nbsp;KB|
|#5964|`EnrichedLog`|netcoreapp3.1|121μs|268ns|1.04μs|0| 0|0|4.28&nbsp;KB|
|#5964|`EnrichedLog`|net472|150μs|168ns|652ns|0.67| 0.223|0|4.46&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`EnrichedLog`|net6.0|3.07μs|0.986ns|3.69ns|0.0305| 0|0|2.2&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`EnrichedLog`|netcoreapp3.1|4.39μs|0.973ns|3.77ns|0.0305| 0|0|2.2&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`EnrichedLog`|net472|4.85μs|1.03ns|4.01ns|0.32| 0|0|2.02&nbsp;KB|
|#5964|`EnrichedLog`|net6.0|3.1μs|0.671ns|2.42ns|0.0311| 0|0|2.2&nbsp;KB|
|#5964|`EnrichedLog`|netcoreapp3.1|4.28μs|10.5ns|40.7ns|0.0294| 0|0|2.2&nbsp;KB|
|#5964|`EnrichedLog`|net472|4.93μs|1.14ns|4.27ns|0.319| 0|0|2.02&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`SendReceive`|net6.0|1.31μs|0.747ns|2.79ns|0.0164| 0|0|1.14&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`SendReceive`|netcoreapp3.1|1.75μs|0.965ns|3.48ns|0.0158| 0|0|1.14&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`SendReceive`|net472|2.14μs|1.44ns|5.38ns|0.183| 0|0|1.16&nbsp;KB|
|#5964|`SendReceive`|net6.0|1.29μs|0.677ns|2.53ns|0.0161| 0|0|1.14&nbsp;KB|
|#5964|`SendReceive`|netcoreapp3.1|1.76μs|1.01ns|3.91ns|0.015| 0|0|1.14&nbsp;KB|
|#5964|`SendReceive`|net472|2.14μs|1.06ns|3.98ns|0.183| 0.00106|0|1.16&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`EnrichedLog`|net6.0|2.79μs|1.15ns|4.44ns|0.0224| 0|0|1.6&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`EnrichedLog`|netcoreapp3.1|3.94μs|2.01ns|7.77ns|0.0218| 0|0|1.65&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`EnrichedLog`|net472|4.35μs|1.25ns|4.67ns|0.322| 0|0|2.04&nbsp;KB|
|#5964|`EnrichedLog`|net6.0|2.75μs|0.607ns|2.19ns|0.022| 0|0|1.6&nbsp;KB|
|#5964|`EnrichedLog`|netcoreapp3.1|3.85μs|1.17ns|4.38ns|0.0212| 0|0|1.65&nbsp;KB|
|#5964|`EnrichedLog`|net472|4.34μs|1.8ns|6.96ns|0.323| 0|0|2.04&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Faster :tada: Same allocations :heavy_check_mark:



#### Faster :tada: in #5964

|  Benchmark         | base/diff | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.SpanBenchmark.StartFinishScope&#8209;net6.0 | 1.134 | 537.55 | 474.23 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`StartFinishSpan`|net6.0|400ns|0.257ns|0.993ns|0.00803| 0|0|576&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`StartFinishSpan`|netcoreapp3.1|574ns|1.16ns|4.5ns|0.00761| 0|0|576&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`StartFinishSpan`|net472|618ns|0.706ns|2.73ns|0.0916| 0|0|578&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`StartFinishScope`|net6.0|537ns|0.549ns|2.05ns|0.00971| 0|0|696&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`StartFinishScope`|netcoreapp3.1|685ns|1.12ns|4.33ns|0.00929| 0|0|696&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`StartFinishScope`|net472|809ns|0.641ns|2.48ns|0.104| 0|0|658&nbsp;B|
|#5964|`StartFinishSpan`|net6.0|383ns|0.203ns|0.787ns|0.0081| 0|0|576&nbsp;B|
|#5964|`StartFinishSpan`|netcoreapp3.1|554ns|0.577ns|2.23ns|0.00753| 0|0|576&nbsp;B|
|#5964|`StartFinishSpan`|net472|594ns|1.22ns|4.73ns|0.0917| 0|0|578&nbsp;B|
|#5964|`StartFinishScope`|net6.0|474ns|0.594ns|2.3ns|0.00981| 0|0|696&nbsp;B|
|#5964|`StartFinishScope`|netcoreapp3.1|694ns|0.91ns|3.52ns|0.00913| 0|0|696&nbsp;B|
|#5964|`StartFinishScope`|net472|760ns|1.3ns|5.02ns|0.105| 0|0|658&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #5964

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.TraceAnnotationsBenchmark.RunOnMethodBegin&#8209;net6.0 | 1.124 | 582.23 | 654.17 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`RunOnMethodBegin`|net6.0|582ns|0.413ns|1.6ns|0.00987| 0|0|696&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`RunOnMethodBegin`|netcoreapp3.1|899ns|1.01ns|3.77ns|0.00949| 0|0|696&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)|`RunOnMethodBegin`|net472|1.02μs|1.54ns|5.96ns|0.104| 0|0|658&nbsp;B|
|#5964|`RunOnMethodBegin`|net6.0|654ns|0.817ns|3.17ns|0.00957| 0|0|696&nbsp;B|
|#5964|`RunOnMethodBegin`|netcoreapp3.1|914ns|0.807ns|3.12ns|0.00927| 0|0|696&nbsp;B|
|#5964|`RunOnMethodBegin`|net472|1.07μs|1.18ns|4.59ns|0.104| 0|0|658&nbsp;B|
</details>

**Comment by andrewlock** [comment]
## Throughput/Crank Report :zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (5964)](https://github.com/DataDog/dd-trace-dotnet/tree/dc21e1cb24ff1f5c109de934b24c0652ee53272d)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/61563101dccc3f057ad98dcbe65a58558fada13b)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/89ae3f4ee7d85b824badda5873166707c9e560b4)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (5964) (11.122M)   : 0, 11122021
    master (11.247M)   : 0, 11246521
    benchmarks/2.9.0 (11.120M)   : 0, 11120231

    section Automatic
    This PR (5964) (7.474M)   : 0, 7474281
    master (7.508M)   : 0, 7508439
    benchmarks/2.9.0 (7.874M)   : 0, 7874046

    section Trace stats
    master (7.707M)   : 0, 7707332

    section Manual
    master (11.233M)   : 0, 11232811

    section Manual + Automatic
    This PR (5964) (6.912M)   : 0, 6911976
    master (6.892M)   : 0, 6891553

    section DD_TRACE_ENABLED=0
    master (10.225M)   : 0, 10225326

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (5964) (9.742M)   : 0, 9741774
    benchmarks/2.9.0 (9.342M)   : 0, 9341974

    section Automatic
    This PR (5964) (6.756M)   : 0, 6755665

    section Manual + Automatic
    This PR (5964) (6.146M)   : 0, 6146238

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (5964) (10.083M)   : 0, 10082868
    master (10.060M)   : 0, 10059520
    benchmarks/2.9.0 (10.105M)   : 0, 10105239

    section Automatic
    This PR (5964) (6.599M)   : 0, 6599259
    master (6.690M)   : 0, 6690107
    benchmarks/2.9.0 (7.518M)   : 0, 7517801

    section Trace stats
    master (7.324M)   : 0, 7324117

    section Manual
    master (10.131M)   : 0, 10131126

    section Manual + Automatic
    This PR (5964) (6.008M)   : 0, 6007541
    master (6.279M)   : 0, 6279338

    section DD_TRACE_ENABLED=0
    master (9.441M)   : 0, 9441325

```

**Review by andrewlock — APPROVED** [review]
Yup. That's definitely bash.

**Review by gleocadie — APPROVED** [review]
LGTM

**Pull request merged**
