### PR TITLE
[CI Visibility] - Refactor and changes to improve debugging and to help the datadog logger to extract env-vars.

### PR DESCRIPTION
**Pull request by tonyredondo**
## Summary of changes

This PR made some modifications to help debugging and to help the DatadogTestLogger to extract the environment variables required for collecting git metadata by keeping all constants together in a single class.

The logger now can take that class and get the value of all constants as a list of variables that can be shown for debugging purposes.

### CODE REVIEW

**Review by andrewlock — APPROVED** [review]
LGTM

**Comment by andrewlock** [comment]
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (3990)](https://github.com/DataDog/dd-trace-dotnet/tree/078b0da3791d5be6ddf578c0cd0e1a812c655d98)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (3990) - mean (3,016ms)  : 2901, 3131
     .   : milestone, 3016,
    master - mean (3,027ms)  : 2897, 3156
     .   : milestone, 3027,

    section CallTarget+Inlining+NGEN
    This PR (3990) - mean (3,642ms)  : 3580, 3705
     .   : milestone, 3642,
    master - mean (3,650ms)  : 3561, 3740
     .   : milestone, 3650,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (3990) - mean (3,160ms)  : 3021, 3299
     .   : milestone, 3160,
    master - mean (3,168ms)  : 3027, 3309
     .   : milestone, 3168,

    section CallTarget+Inlining+NGEN
    This PR (3990) - mean (3,505ms)  : 3398, 3613
     .   : milestone, 3505,
    master - mean (3,528ms)  : 3436, 3620
     .   : milestone, 3528,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (3990) - mean (3,159ms)  : 2999, 3318
     .   : milestone, 3159,
    master - mean (3,150ms)  : 3020, 3280
     .   : milestone, 3150,

    section CallTarget+Inlining+NGEN
    This PR (3990) - mean (3,497ms)  : 3415, 3579
     .   : milestone, 3497,
    master - mean (3,484ms)  : 3372, 3596
     .   : milestone, 3484,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (3990) - mean (187ms)  : 183, 191
     .   : milestone, 187,
    master - mean (187ms)  : 184, 191
     .   : milestone, 187,

    section CallTarget+Inlining+NGEN
    This PR (3990) - mean (914ms)  : 879, 948
     .   : milestone, 914,
    master - mean (912ms)  : 882, 943
     .   : milestone, 912,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (3990) - mean (365ms)  : 361, 369
     .   : milestone, 365,
    master - mean (365ms)  : 361, 370
     .   : milestone, 365,

    section CallTarget+Inlining+NGEN
    This PR (3990) - mean (1,051ms)  : 1030, 1071
     .   : milestone, 1051,
    master - mean (1,051ms)  : 1024, 1078
     .   : milestone, 1051,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (3990) - mean (354ms)  : 350, 359
     .   : milestone, 354,
    master - mean (354ms)  : 350, 358
     .   : milestone, 354,

    section CallTarget+Inlining+NGEN
    This PR (3990) - mean (999ms)  : 976, 1021
     .   : milestone, 999,
    master - mean (1,005ms)  : 976, 1034
     .   : milestone, 1005,

```

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #3990 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9): 
* 1 benchmarks are **slower**, with geometric mean 1.165
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|600μs|142ns|550ns|0| 0|0|2.63&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`WriteAndFlushEnrichedTraces`|net472|792μs|253ns|948ns|0.396| 0|0|3.22&nbsp;KB|
|#3990|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|608μs|89.5ns|310ns|0| 0|0|2.62&nbsp;KB|
|#3990|`WriteAndFlushEnrichedTraces`|net472|797μs|166ns|620ns|0.398| 0|0|3.22&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #3990

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.AppSecBodyBenchmark.ObjectExtractorSimpleBody&#8209;netcoreapp3.1 | 1.165 | 182.08 | 212.15 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`AllCycleSimpleBody`|netcoreapp3.1|102μs|568ns|3.59μs|0| 0|0|1.66&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`AllCycleSimpleBody`|net472|104μs|60.8ns|235ns|0.235| 0|0|1.71&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`AllCycleMoreComplexBody`|netcoreapp3.1|277μs|619ns|3.76μs|0| 0|0|9.14&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`AllCycleMoreComplexBody`|net472|268μs|184ns|713ns|1.35| 0|0|9.31&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`ObjectExtractorSimpleBody`|netcoreapp3.1|182ns|0.124ns|0.479ns|0.00367| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`ObjectExtractorSimpleBody`|net472|144ns|0.147ns|0.569ns|0.0446| 0|0|281&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|4.05μs|2.64ns|9.52ns|0.0507| 0|0|3.78&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`ObjectExtractorMoreComplexBody`|net472|3.99μs|2.99ns|11.6ns|0.617| 0.00599|0|3.89&nbsp;KB|
|#3990|`AllCycleSimpleBody`|netcoreapp3.1|94.8μs|597ns|5.97μs|0| 0|0|1.66&nbsp;KB|
|#3990|`AllCycleSimpleBody`|net472|97.7μs|216ns|838ns|0.242| 0|0|1.71&nbsp;KB|
|#3990|`AllCycleMoreComplexBody`|netcoreapp3.1|272μs|1.37μs|7.65μs|0| 0|0|9.14&nbsp;KB|
|#3990|`AllCycleMoreComplexBody`|net472|272μs|82.4ns|308ns|1.36| 0|0|9.31&nbsp;KB|
|#3990|`ObjectExtractorSimpleBody`|netcoreapp3.1|212ns|0.158ns|0.592ns|0.00369| 0|0|272&nbsp;B|
|#3990|`ObjectExtractorSimpleBody`|net472|147ns|0.179ns|0.694ns|0.0446| 0|0|281&nbsp;B|
|#3990|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|4.17μs|1.22ns|4.58ns|0.0522| 0|0|3.78&nbsp;KB|
|#3990|`ObjectExtractorMoreComplexBody`|net472|4.08μs|3.63ns|14.1ns|0.618| 0.00614|0|3.89&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`SendRequest`|netcoreapp3.1|186μs|239ns|925ns|0.185| 0|0|20.36&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`SendRequest`|net472|0.000309ns|0.000176ns|0.00066ns|0| 0|0|0&nbsp;b|
|#3990|`SendRequest`|netcoreapp3.1|180μs|195ns|755ns|0.18| 0|0|20.36&nbsp;KB|
|#3990|`SendRequest`|net472|0.000893ns|0.000219ns|0.000821ns|0| 0|0|0&nbsp;b|
</details>


<details><summary><strong>Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|617μs|1.5μs|5.82μs|0.3| 0|0|41.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`WriteAndFlushEnrichedTraces`|net472|781μs|3.22μs|12.5μs|8.25| 2.36|0.393|53.21&nbsp;KB|
|#3990|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|610μs|1μs|3.74μs|0.306| 0|0|41.85&nbsp;KB|
|#3990|`WriteAndFlushEnrichedTraces`|net472|813μs|2.45μs|9.51μs|8.06| 2.42|0.403|53.27&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`ExecuteNonQuery`|netcoreapp3.1|1.25μs|0.879ns|3.41ns|0.0126| 0|0|904&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`ExecuteNonQuery`|net472|1.65μs|0.505ns|1.95ns|0.143| 0.000825|0|907&nbsp;B|
|#3990|`ExecuteNonQuery`|netcoreapp3.1|1.26μs|0.757ns|2.73ns|0.012| 0|0|904&nbsp;B|
|#3990|`ExecuteNonQuery`|net472|1.64μs|0.528ns|1.97ns|0.144| 0|0|907&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`CallElasticsearch`|netcoreapp3.1|1.3μs|0.67ns|2.51ns|0.0143| 0|0|1.06&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`CallElasticsearch`|net472|2.24μs|0.472ns|1.76ns|0.175| 0|0|1.11&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`CallElasticsearchAsync`|netcoreapp3.1|1.32μs|0.414ns|1.55ns|0.0159| 0|0|1.18&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`CallElasticsearchAsync`|net472|2.38μs|1.62ns|6.29ns|0.197| 0.00118|0|1.24&nbsp;KB|
|#3990|`CallElasticsearch`|netcoreapp3.1|1.27μs|0.549ns|1.98ns|0.014| 0|0|1.06&nbsp;KB|
|#3990|`CallElasticsearch`|net472|2.25μs|1ns|3.62ns|0.176| 0|0|1.11&nbsp;KB|
|#3990|`CallElasticsearchAsync`|netcoreapp3.1|1.39μs|0.492ns|1.84ns|0.0161| 0|0|1.18&nbsp;KB|
|#3990|`CallElasticsearchAsync`|net472|2.42μs|2.6ns|9.37ns|0.197| 0.0012|0|1.24&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`ExecuteAsync`|netcoreapp3.1|1.47μs|0.348ns|1.3ns|0.0175| 0|0|1.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`ExecuteAsync`|net472|1.84μs|0.365ns|1.41ns|0.206| 0.000916|0|1.3&nbsp;KB|
|#3990|`ExecuteAsync`|netcoreapp3.1|1.41μs|0.914ns|3.29ns|0.0176| 0|0|1.28&nbsp;KB|
|#3990|`ExecuteAsync`|net472|1.86μs|0.737ns|2.86ns|0.206| 0.000934|0|1.3&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`SendAsync`|netcoreapp3.1|4.26μs|1.22ns|4.4ns|0.0363| 0|0|2.66&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`SendAsync`|net472|6.92μs|1.14ns|4.25ns|0.478| 0|0|3.03&nbsp;KB|
|#3990|`SendAsync`|netcoreapp3.1|4.29μs|2.53ns|9.78ns|0.0364| 0|0|2.66&nbsp;KB|
|#3990|`SendAsync`|net472|6.88μs|2.22ns|8.32ns|0.479| 0|0|3.03&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`EnrichedLog`|netcoreapp3.1|2.01μs|1.73ns|6.49ns|0.025| 0|0|1.83&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`EnrichedLog`|net472|2.54μs|1.23ns|4.43ns|0.283| 0|0|1.79&nbsp;KB|
|#3990|`EnrichedLog`|netcoreapp3.1|2.01μs|0.875ns|3.27ns|0.0253| 0|0|1.83&nbsp;KB|
|#3990|`EnrichedLog`|net472|2.56μs|1ns|3.76ns|0.284| 0|0|1.79&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`EnrichedLog`|netcoreapp3.1|116μs|86.3ns|299ns|0.0579| 0|0|4.42&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`EnrichedLog`|net472|146μs|101ns|363ns|0.73| 0.219|0|4.63&nbsp;KB|
|#3990|`EnrichedLog`|netcoreapp3.1|117μs|90.5ns|350ns|0.0583| 0|0|4.42&nbsp;KB|
|#3990|`EnrichedLog`|net472|150μs|65.3ns|253ns|0.664| 0.221|0|4.63&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`EnrichedLog`|netcoreapp3.1|3.94μs|1.17ns|4.39ns|0.0532| 0|0|3.9&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`EnrichedLog`|net472|5.05μs|1.09ns|4.07ns|0.565| 0.00252|0|3.56&nbsp;KB|
|#3990|`EnrichedLog`|netcoreapp3.1|3.95μs|1.76ns|6.57ns|0.0532| 0|0|3.9&nbsp;KB|
|#3990|`EnrichedLog`|net472|5.06μs|0.992ns|3.71ns|0.565| 0.00253|0|3.56&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`SendReceive`|netcoreapp3.1|1.53μs|0.339ns|1.22ns|0.0176| 0|0|1.3&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`SendReceive`|net472|1.93μs|1.39ns|5.19ns|0.212| 0.000961|0|1.34&nbsp;KB|
|#3990|`SendReceive`|netcoreapp3.1|1.6μs|1.23ns|4.62ns|0.0176| 0|0|1.3&nbsp;KB|
|#3990|`SendReceive`|net472|1.92μs|1.08ns|4.19ns|0.212| 0|0|1.34&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`EnrichedLog`|netcoreapp3.1|3.69μs|1.17ns|4.39ns|0.0239| 0|0|1.78&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`EnrichedLog`|net472|4.33μs|1.29ns|4.48ns|0.351| 0|0|2.21&nbsp;KB|
|#3990|`EnrichedLog`|netcoreapp3.1|3.73μs|1.52ns|5.89ns|0.0244| 0|0|1.78&nbsp;KB|
|#3990|`EnrichedLog`|net472|4.32μs|0.884ns|3.19ns|0.349| 0|0|2.21&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`StartFinishSpan`|netcoreapp3.1|709ns|2.09ns|8.11ns|0.00952| 0|0|720&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`StartFinishSpan`|net472|954ns|0.448ns|1.68ns|0.121| 0|0|762&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`StartFinishScope`|netcoreapp3.1|799ns|0.488ns|1.83ns|0.0115| 0|0|840&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`StartFinishScope`|net472|1.11μs|1.3ns|5.02ns|0.134| 0|0|842&nbsp;B|
|#3990|`StartFinishSpan`|netcoreapp3.1|735ns|0.391ns|1.46ns|0.00957| 0|0|720&nbsp;B|
|#3990|`StartFinishSpan`|net472|860ns|0.263ns|0.983ns|0.121| 0|0|762&nbsp;B|
|#3990|`StartFinishScope`|netcoreapp3.1|800ns|0.232ns|0.868ns|0.0115| 0|0|840&nbsp;B|
|#3990|`StartFinishScope`|net472|1.07μs|0.317ns|1.23ns|0.134| 0|0|842&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`RunOnMethodBegin`|netcoreapp3.1|888ns|0.537ns|2.08ns|0.0111| 0|0|840&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/930b0a8c605beffd9939dae6f6312cb69bc938c9)|`RunOnMethodBegin`|net472|1.3μs|0.323ns|1.21ns|0.134| 0|0|842&nbsp;B|
|#3990|`RunOnMethodBegin`|netcoreapp3.1|906ns|0.418ns|1.57ns|0.0113| 0|0|840&nbsp;B|
|#3990|`RunOnMethodBegin`|net472|1.19μs|0.484ns|1.88ns|0.133| 0|0|842&nbsp;B|
</details>

**Review by zacharycmontoya — APPROVED** [review]

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #3990 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/647b93378e56c68cbbdd0f5e2765f49f26a96c4d) will **not change** line coverage
:heavy_check_mark: Merging #3990 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/647b93378e56c68cbbdd0f5e2765f49f26a96c4d) will **not change** branch coverage
:heavy_check_mark: Merging #3990 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/647b93378e56c68cbbdd0f5e2765f49f26a96c4d) will will **decrease** complexity by `1`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/647b93378e56c68cbbdd0f5e2765f49f26a96c4d) | #3990       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `23487` / `33742` | `23410` / `33749` |          |
| Lines %   | `70%`      | `69%`      |  `0%` :heavy_check_mark:  |
| Branches  | `14281` / `22063` | `14247` / `22061` |          |
| Branches %| `65%`      | `65%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `23776`      | `23775`        |  `-1`  :heavy_check_mark:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=133608&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/133608/artifacts?artifactName=Code%20Coverage%20Report_133608&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3990](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=133667&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/133667/artifacts?artifactName=Code%20Coverage%20Report_133667&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/647b93378e56c68cbbdd0f5e2765f49f26a96c4d) | #3990       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `70%`      | `69%`       |  `0%` :heavy_check_mark:  |
| Branches %| `65%`      | `65%`       |  `0%` :heavy_check_mark:  |
| Complexity| `23776`      | `23775`       |  `-1` :heavy_check_mark:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Ci.GitInfo](https://github.com/DataDog/dd-trace-dotnet/tree/4d200c7dc535e1c97c3d1ffc6bdd5c601c7fffda/tracer/src/Datadog.Trace/Ci/GitInfo.cs) | `-17%` :no_entry: | `-10%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Util.AsyncUtil](https://github.com/DataDog/dd-trace-dotnet/tree/4d200c7dc535e1c97c3d1ffc6bdd5c601c7fffda/tracer/src/Datadog.Trace/Util/AsyncUtil.cs) | `-9%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Ci.Configuration.CIGitMetadataTagsProvider](https://github.com/DataDog/dd-trace-dotnet/tree/4d200c7dc535e1c97c3d1ffc6bdd5c601c7fffda/tracer/src/Datadog.Trace/Ci/Configuration/CIGitMetadataTagsProvider.cs) | `0%` :heavy_check_mark: | `-30%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Util.Http.QueryStringObfuscation.ObfuscatorFactory](https://github.com/DataDog/dd-trace-dotnet/tree/4d200c7dc535e1c97c3d1ffc6bdd5c601c7fffda/tracer/src/Datadog.Trace/Util/Http/QueryStringObfuscation/ObfuscatorFactory.cs) | `0%` :heavy_check_mark: | `-17%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Util.Http.QueryStringManager](https://github.com/DataDog/dd-trace-dotnet/tree/4d200c7dc535e1c97c3d1ffc6bdd5c601c7fffda/tracer/src/Datadog.Trace/Util/Http/QueryStringManager.cs) | `0%` :heavy_check_mark: | `25%` :heavy_check_mark:   | `3` :no_entry: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=133608&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/133608/artifacts?artifactName=Code%20Coverage%20Report_133608&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3990](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=133667&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/133667/artifacts?artifactName=Code%20Coverage%20Report_133667&api-version=6.0&%24format=zip)

**Pull request merged**
