### PR TITLE
Remove _W string operator from the native profiler

### PR DESCRIPTION
**Pull request by tonyredondo**
This `PR` removes the `_W` string operator from the profiler and replace it with a new `WStr` macro that redirects to a `L` prefix on windows and an `u` prefix on non windows. Simplifying the wide string declaration and reducing the `_W` overhead.

@DataDog/apm-dotnet

### CODE REVIEW

**Comment by macrogreg** [comment]
Minor: Instead of calling it `_LU(..)` we could consider `WideStr(..)` or `WStr(..)`?

**Comment by tonyredondo** [comment]
> Minor: Instead of calling it `_LU(..)` we could consider `WideStr(..)` or `WStr(..)`?

Sure, I’ll change it to WStr()

**Comment by tonyredondo** [comment]
> Minor: Instead of calling it `_LU(..)` we could consider `WideStr(..)` or `WStr(..)`?

done in 5bd15f8

**Review by zacharycmontoya — APPROVED** [review]
LGTM! Nice clean up!

**Review by lucaspimentel — APPROVED** [review]

**Pull request merged**
