### PR TITLE
[Tests] De-Flake ASM Tests by fixing one of the symptoms

### PR DESCRIPTION
**Pull request by zacharycmontoya**
## Summary of changes
Doesn't root cause the ObjectDisposedException in ASM tests, but fixes the results so we don't end up with duplicate spans, which messes up the snapshot comparisons.

## Reason for change
We want to minimize flake in our test suites

## Implementation details
This does not solve the underlying issue for ASM flaky tests, but it mitigates one of the symptoms. One common cause of flakiness is when the MockTracerAgent processes the first span, adds it to the Spans list, and then throws an ObjectDisposedException when writing a response back to the application under test. This causes the span exporter loop to retry and re-send the span to the MockTracerAgent, which results in the span being added twice to the list of collected spans.

This PR fixes the symptom by skipping the addition of duplicate spans into the Spans list, by checking the traceId and spanId of each span that the MockTracerAgent stores.

## Test coverage
Runs existing tests

## Other details
N/A

### CODE REVIEW

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #3644 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`WriteAndFlushEnrichedTraces`|net472|766μs|711ns|2.75μs|0.381| 0|0|3.22&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|556μs|510ns|1.98μs|0| 0|0|2.63&nbsp;KB|
|#3644|`WriteAndFlushEnrichedTraces`|net472|762μs|941ns|3.65μs|0.381| 0|0|3.22&nbsp;KB|
|#3644|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|562μs|412ns|1.49μs|0| 0|0|2.63&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`AllCycleSimpleBody`|net472|24.8μs|126ns|578ns|0.275| 0|0|1.78&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`AllCycleSimpleBody`|netcoreapp3.1|22.2μs|22.6ns|120ns|0.0217| 0|0|1.65&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`AllCycleMoreComplexBody`|net472|195μs|831ns|3.52μs|2.01| 0|0|13.03&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`AllCycleMoreComplexBody`|netcoreapp3.1|180μs|56ns|194ns|0.0901| 0|0|12.11&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`ObjectExtractorSimpleBody`|net472|277ns|0.122ns|0.455ns|0.0573| 0|0|361&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`ObjectExtractorSimpleBody`|netcoreapp3.1|241ns|0.152ns|0.587ns|0.00364| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`ObjectExtractorMoreComplexBody`|net472|16.3μs|7.43ns|27.8ns|1.21| 0.0164|0|7.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|12.9μs|5.16ns|20ns|0.0904| 0|0|6.75&nbsp;KB|
|#3644|`AllCycleSimpleBody`|net472|25μs|21ns|81.3ns|0.282| 0|0|1.78&nbsp;KB|
|#3644|`AllCycleSimpleBody`|netcoreapp3.1|23.6μs|26.6ns|103ns|0.0119| 0|0|1.65&nbsp;KB|
|#3644|`AllCycleMoreComplexBody`|net472|194μs|450ns|1.74μs|2.01| 0|0|13.03&nbsp;KB|
|#3644|`AllCycleMoreComplexBody`|netcoreapp3.1|182μs|535ns|2.07μs|0.0907| 0|0|12.11&nbsp;KB|
|#3644|`ObjectExtractorSimpleBody`|net472|307ns|0.194ns|0.727ns|0.0573| 0|0|361&nbsp;B|
|#3644|`ObjectExtractorSimpleBody`|netcoreapp3.1|262ns|0.111ns|0.429ns|0.00369| 0|0|272&nbsp;B|
|#3644|`ObjectExtractorMoreComplexBody`|net472|16.5μs|11ns|42.6ns|1.2| 0.0166|0|7.62&nbsp;KB|
|#3644|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|12.7μs|7.12ns|27.6ns|0.0889| 0|0|6.75&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`SendRequest`|netcoreapp3.1|275μs|1.59μs|12.4μs|0.283| 0|0|20.96&nbsp;KB|
|#3644|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#3644|`SendRequest`|netcoreapp3.1|291μs|1.52μs|9.39μs|0.144| 0|0|20.96&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`ExecuteNonQuery`|net472|1.81μs|1.81ns|6.77ns|0.163| 0.00179|0.000896|1.03&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`ExecuteNonQuery`|netcoreapp3.1|1.4μs|3.27ns|12.7ns|0.0139| 0|0|1.02&nbsp;KB|
|#3644|`ExecuteNonQuery`|net472|1.84μs|2.09ns|7.83ns|0.162| 0.000918|0|1.03&nbsp;KB|
|#3644|`ExecuteNonQuery`|netcoreapp3.1|1.47μs|2.22ns|8.61ns|0.0139| 0|0|1.02&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`CallElasticsearch`|net472|2.38μs|0.857ns|3.21ns|0.196| 0|0|1.24&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`CallElasticsearch`|netcoreapp3.1|1.52μs|1.79ns|6.68ns|0.0159| 0|0|1.18&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`CallElasticsearchAsync`|net472|2.58μs|0.834ns|3.23ns|0.218| 0|0|1.37&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`CallElasticsearchAsync`|netcoreapp3.1|1.55μs|0.558ns|2.09ns|0.0171| 0|0|1.3&nbsp;KB|
|#3644|`CallElasticsearch`|net472|2.44μs|0.521ns|1.88ns|0.195| 0|0|1.24&nbsp;KB|
|#3644|`CallElasticsearch`|netcoreapp3.1|1.49μs|0.908ns|3.4ns|0.0158| 0|0|1.18&nbsp;KB|
|#3644|`CallElasticsearchAsync`|net472|2.52μs|0.864ns|3.35ns|0.218| 0|0|1.37&nbsp;KB|
|#3644|`CallElasticsearchAsync`|netcoreapp3.1|1.64μs|2.28ns|8.85ns|0.0178| 0|0|1.3&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`ExecuteAsync`|net472|2.74μs|1.13ns|4.24ns|0.238| 0|0|1.5&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`ExecuteAsync`|netcoreapp3.1|1.71μs|0.82ns|3.07ns|0.0189| 0|0|1.42&nbsp;KB|
|#3644|`ExecuteAsync`|net472|2.68μs|1.27ns|4.77ns|0.238| 0|0|1.5&nbsp;KB|
|#3644|`ExecuteAsync`|netcoreapp3.1|1.72μs|0.758ns|2.84ns|0.0197| 0|0|1.42&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`SendAsync`|net472|7.16μs|2.33ns|9.03ns|0.557| 0|0|3.51&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`SendAsync`|netcoreapp3.1|4.68μs|1.83ns|6.84ns|0.0421| 0|0|3.21&nbsp;KB|
|#3644|`SendAsync`|net472|7.33μs|2.28ns|8.82ns|0.558| 0|0|3.51&nbsp;KB|
|#3644|`SendAsync`|netcoreapp3.1|4.68μs|2.01ns|7.77ns|0.0422| 0|0|3.21&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`EnrichedLog`|net472|2.77μs|3.01ns|11.7ns|0.301| 0|0|1.9&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`EnrichedLog`|netcoreapp3.1|2.27μs|5.49ns|20.6ns|0.0262| 0|0|1.93&nbsp;KB|
|#3644|`EnrichedLog`|net472|2.78μs|4.11ns|15.9ns|0.301| 0|0|1.9&nbsp;KB|
|#3644|`EnrichedLog`|netcoreapp3.1|2.23μs|1.44ns|5.56ns|0.0256| 0|0|1.93&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`EnrichedLog`|net472|147μs|80.9ns|303ns|0.735| 0.221|0|4.74&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`EnrichedLog`|netcoreapp3.1|118μs|142ns|531ns|0.0591| 0|0|4.58&nbsp;KB|
|#3644|`EnrichedLog`|net472|147μs|144ns|557ns|0.729| 0.219|0|4.74&nbsp;KB|
|#3644|`EnrichedLog`|netcoreapp3.1|117μs|51.3ns|198ns|0.0584| 0|0|4.58&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`EnrichedLog`|net472|5.49μs|1.44ns|5.38ns|0.582| 0.00275|0|3.68&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`EnrichedLog`|netcoreapp3.1|4.13μs|1.15ns|4.29ns|0.0538| 0|0|4&nbsp;KB|
|#3644|`EnrichedLog`|net472|5.52μs|2.41ns|9.34ns|0.583| 0.00275|0|3.68&nbsp;KB|
|#3644|`EnrichedLog`|netcoreapp3.1|4.28μs|2.14ns|7.73ns|0.0533| 0|0|4&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`SendReceive`|net472|2.2μs|1.38ns|5.15ns|0.23| 0|0|1.45&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`SendReceive`|netcoreapp3.1|1.85μs|0.556ns|2ns|0.0191| 0|0|1.4&nbsp;KB|
|#3644|`SendReceive`|net472|2.18μs|0.64ns|2.4ns|0.23| 0|0|1.45&nbsp;KB|
|#3644|`SendReceive`|netcoreapp3.1|1.8μs|0.48ns|1.8ns|0.0188| 0|0|1.4&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`EnrichedLog`|net472|4.73μs|1.83ns|7.07ns|0.366| 0|0|2.32&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`EnrichedLog`|netcoreapp3.1|4.07μs|0.962ns|3.47ns|0.0244| 0|0|1.89&nbsp;KB|
|#3644|`EnrichedLog`|net472|4.81μs|1.77ns|6.64ns|0.367| 0|0|2.32&nbsp;KB|
|#3644|`EnrichedLog`|netcoreapp3.1|3.95μs|1.4ns|5.23ns|0.0256| 0|0|1.89&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`StartFinishSpan`|net472|1.18μs|0.51ns|1.98ns|0.142| 0|0|891&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`StartFinishSpan`|netcoreapp3.1|885ns|0.595ns|2.23ns|0.0116| 0|0|840&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`StartFinishScope`|net472|1.33μs|0.459ns|1.72ns|0.154| 0|0|971&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`StartFinishScope`|netcoreapp3.1|1.06μs|0.459ns|1.65ns|0.0128| 0|0|960&nbsp;B|
|#3644|`StartFinishSpan`|net472|1.09μs|0.977ns|3.78ns|0.141| 0|0|891&nbsp;B|
|#3644|`StartFinishSpan`|netcoreapp3.1|901ns|0.248ns|0.96ns|0.0113| 0|0|840&nbsp;B|
|#3644|`StartFinishScope`|net472|1.32μs|0.627ns|2.26ns|0.154| 0|0|971&nbsp;B|
|#3644|`StartFinishScope`|netcoreapp3.1|1.09μs|0.442ns|1.65ns|0.013| 0|0|960&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`RunOnMethodBegin`|net472|1.5μs|0.599ns|2.32ns|0.154| 0|0|971&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)|`RunOnMethodBegin`|netcoreapp3.1|1.11μs|1.6ns|5.99ns|0.0131| 0|0|960&nbsp;B|
|#3644|`RunOnMethodBegin`|net472|1.47μs|0.555ns|2.15ns|0.154| 0|0|971&nbsp;B|
|#3644|`RunOnMethodBegin`|netcoreapp3.1|1.12μs|0.585ns|2.27ns|0.013| 0|0|960&nbsp;B|
</details>

**Comment by andrewlock** [comment]
## Throughput/Crank Report:zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (3644)](https://github.com/DataDog/dd-trace-dotnet/tree/65ae8ac32207ad7c5de0543a941475d1b3b5de5c)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/1108ec8b03b8253183bdacda226152fe5327eabd)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/0d56b1d9f25673f5257b1b7df97a3754d2df63f4)
- [benchmarks/2.21.0](https://github.com/DataDog/dd-trace-dotnet/tree/994d914bd3a83ab18a13a54b2a0907dc1d7e6b86)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (3644) (5.967M)   : 0, 5966751
    master (5.942M)   : 0, 5942049
    benchmarks/2.21.0 (6.205M)   : 0, 6204945
    benchmarks/2.9.0 (5.909M)   : 0, 5909222

    section Instrumented
    This PR (3644) (4.115M)   : 0, 4114709
    master (4.094M)   : 0, 4093647
    benchmarks/2.21.0 (4.215M)   : 0, 4214747
    benchmarks/2.9.0 (4.137M)   : 0, 4137460

    section Trace stats
    master (4.133M)   : 0, 4132754
    benchmarks/2.21.0 (4.162M)   : 0, 4161894

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (3644) (5.422M)   : 0, 5422269
    master (5.347M)   : 0, 5346864
    benchmarks/2.21.0 (5.432M)   : 0, 5431773
    benchmarks/2.9.0 (5.296M)   : 0, 5296208

    section Instrumented
    This PR (3644) (3.604M)   : 0, 3603505
    master (3.609M)   : 0, 3608602
    benchmarks/2.21.0 (3.825M)   : 0, 3824781

    section Trace stats
    master (3.547M)   : 0, 3546731
    benchmarks/2.21.0 (3.789M)   : 0, 3788842

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (3644) (6.569M)   : 0, 6568820
    master (6.272M)   : 0, 6271923
    benchmarks/2.21.0 (6.515M)   : 0, 6515100
    benchmarks/2.9.0 (6.179M)   : 0, 6179312

    section Instrumented
    This PR (3644) (4.507M)   : 0, 4507083
    master (4.138M)   : 0, 4137793
    benchmarks/2.21.0 (4.425M)   : 0, 4424541
    benchmarks/2.9.0 (4.239M)   : 0, 4238635

    section Trace stats
    master (4.188M)   : 0, 4188403
    benchmarks/2.21.0 (4.435M)   : 0, 4434564

```
```mermaid
gantt
    title Throughput Linux x64 (ASM) (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (3644) (3.580M)   : 0, 3579516
    master (3.499M)   : 0, 3498847
    benchmarks/2.21.0 (3.540M)   : 0, 3540047
    benchmarks/2.9.0 (3.741M)   : 0, 3741221

    section No attack
    This PR (3644) (1.266M)   : 0, 1266003
    master (1.256M)   : 0, 1256402
    benchmarks/2.21.0 (1.265M)   : 0, 1264590
    benchmarks/2.9.0 (1.282M)   : 0, 1282301

    section Attack
    This PR (3644) (1.094M)   : 0, 1094295
    master (1.088M)   : 0, 1088407
    benchmarks/2.21.0 (1.106M)   : 0, 1105920
    benchmarks/2.9.0 (1.093M)   : 0, 1092994

    section Blocking
    This PR (3644) (2.174M)   : 0, 2173940
    master (2.085M)   : 0, 2085127
    benchmarks/2.21.0 (2.171M)   : 0, 2170880

```

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #3644 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/e6cd4766dce7a8a9c3d730c64683809d036ec160) will **not change** line coverage
:heavy_check_mark: Merging #3644 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/e6cd4766dce7a8a9c3d730c64683809d036ec160) will **not change** branch coverage
:no_entry: Merging #3644 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/e6cd4766dce7a8a9c3d730c64683809d036ec160) will will **increase** complexity by `155`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/e6cd4766dce7a8a9c3d730c64683809d036ec160) | #3644       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `20996` / `29519` | `21023` / `29717` |          |
| Lines %   | `71%`      | `71%`      |  `0%` :heavy_check_mark:  |
| Branches  | `12579` / `19013` | `12645` / `19155` |          |
| Branches %| `66%`      | `66%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `20512`      | `20667`        |  `155`  :no_entry:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=124169&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/124169/artifacts?artifactName=Code%20Coverage%20Report_124169&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3644](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=124524&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/124524/artifacts?artifactName=Code%20Coverage%20Report_124524&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/e6cd4766dce7a8a9c3d730c64683809d036ec160) | #3644       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `71%`      | `71%`       |  `0%` :heavy_check_mark:  |
| Branches %| `66%`      | `66%`       |  `0%` :heavy_check_mark:  |
| Complexity| `20512`      | `20667`       |  `155` :no_entry:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Util.AsyncUtil](https://github.com/DataDog/dd-trace-dotnet/tree/d851f42b256638228595f9aaa7e3f040a14512bf/tracer/src/Datadog.Trace/Util/AsyncUtil.cs) | `-19%` :no_entry: | `-100%` :no_entry:   | `6` :no_entry: |
| [Datadog.Trace.Ci.GitInfo](https://github.com/DataDog/dd-trace-dotnet/tree/d851f42b256638228595f9aaa7e3f040a14512bf/tracer/src/Datadog.Trace/Ci/GitInfo.cs) | `-17%` :no_entry: | `-11%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.MsTestV2.TestClassInfoRunClassCleanupIntegration](https://github.com/DataDog/dd-trace-dotnet/tree/d851f42b256638228595f9aaa7e3f040a14512bf/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Testing/MsTestV2/TestClassInfoRunClassCleanupIntegration.cs) | `70%` :heavy_check_mark: | `58%` :heavy_check_mark:   | `0` :heavy_check_mark: |


The following classes were added in #3644:

| File    | Line coverage | Branch coverage | Complexity |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Redis.StackExchange.ConnectionMultiplexerSelectServerIntegration](https://github.com/DataDog/dd-trace-dotnet/pull/3644/files) | `100%` | `100%` | `14` |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.MsTestV2.TestAssemblyInfoExecuteAssemblyCleanupIntegration](https://github.com/DataDog/dd-trace-dotnet/pull/3644/files) | `75%` | `60%` | `10` |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.MsTestV2.TestClassInfoExecuteClassCleanupIntegration](https://github.com/DataDog/dd-trace-dotnet/pull/3644/files) | `75%` | `60%` | `10` |
| [Datadog.Trace.ClrProfiler.TracerDebugger](https://github.com/DataDog/dd-trace-dotnet/pull/3644/files) | `0%` | `0%` | `20` |
| [Datadog.Trace.Util.AsyncCountdownEvent](https://github.com/DataDog/dd-trace-dotnet/pull/3644/files) | `59%` | `63%` | `24` |
| ...And 1 more  | | | |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=124169&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/124169/artifacts?artifactName=Code%20Coverage%20Report_124169&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3644](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=124524&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/124524/artifacts?artifactName=Code%20Coverage%20Report_124524&api-version=6.0&%24format=zip)

**Review by bouwkast — APPROVED** [review]

**Comment by zacharycmontoya** [comment]
This PR is no longer needed thanks to https://github.com/DataDog/dd-trace-dotnet/pull/3657. Closing

**Pull request closed without merging**
