### PR TITLE
[Profiler] Check profiler log files for smoke tests

### PR DESCRIPTION
**Pull request by gleocadie**
## Summary of changes

The goal is to ensure that the profiler actually works without errors while  running the smoke tests.

### CODE REVIEW

**Review by andrewlock — APPROVED** [review]
Awesome, 🤞 it doesn't find any 😄 

It would be nice to do an additional run in which we explicitly mis-configure something for the profiler in the smoke tests, and assert that this step catches the errors 🙂

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #3038 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`WriteAndFlushEnrichedTraces`|net472|711μs|439ns|1.64μs|0.353| 0|0|3.18&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|461μs|414ns|1.55μs|0| 0|0|2.58&nbsp;KB|
|#3038|`WriteAndFlushEnrichedTraces`|net472|717μs|333ns|1.29μs|0.355| 0|0|3.18&nbsp;KB|
|#3038|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|448μs|186ns|721ns|0| 0|0|2.58&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`AllCycleSimpleBody`|net472|1.69μs|1.18ns|4.43ns|0.237| 0|0|1.49&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`AllCycleSimpleBody`|netcoreapp3.1|1.82μs|4.03ns|15.1ns|0.0189| 0|0|1.37&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`AllCycleMoreComplexBody`|net472|17.1μs|16.4ns|63.4ns|1.38| 0.025|0|8.75&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`AllCycleMoreComplexBody`|netcoreapp3.1|14.1μs|20.2ns|72.7ns|0.106| 0|0|7.85&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`BodyExtractorSimpleBody`|net472|257ns|0.255ns|0.989ns|0.0574| 0|0|361&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`BodyExtractorSimpleBody`|netcoreapp3.1|220ns|0.383ns|1.43ns|0.00367| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`BodyExtractorMoreComplexBody`|net472|15.4μs|12.3ns|47.5ns|1.21| 0.0154|0|7.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`BodyExtractorMoreComplexBody`|netcoreapp3.1|11.7μs|10.9ns|40.7ns|0.0875| 0|0|6.75&nbsp;KB|
|#3038|`AllCycleSimpleBody`|net472|1.7μs|1.47ns|5.49ns|0.237| 0|0|1.49&nbsp;KB|
|#3038|`AllCycleSimpleBody`|netcoreapp3.1|1.88μs|4.39ns|15.8ns|0.0185| 0|0|1.37&nbsp;KB|
|#3038|`AllCycleMoreComplexBody`|net472|16.6μs|12.9ns|46.6ns|1.39| 0.0248|0|8.75&nbsp;KB|
|#3038|`AllCycleMoreComplexBody`|netcoreapp3.1|14μs|36.2ns|136ns|0.106| 0|0|7.85&nbsp;KB|
|#3038|`BodyExtractorSimpleBody`|net472|252ns|0.298ns|1.11ns|0.0574| 0|0|361&nbsp;B|
|#3038|`BodyExtractorSimpleBody`|netcoreapp3.1|219ns|0.278ns|1.04ns|0.00365| 0|0|272&nbsp;B|
|#3038|`BodyExtractorMoreComplexBody`|net472|14.8μs|9.14ns|34.2ns|1.21| 0.0221|0|7.62&nbsp;KB|
|#3038|`BodyExtractorMoreComplexBody`|netcoreapp3.1|11.7μs|14.7ns|55.1ns|0.0876| 0|0|6.75&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`SendRequest`|netcoreapp3.1|179μs|180ns|697ns|0.269| 0|0|20.37&nbsp;KB|
|#3038|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#3038|`SendRequest`|netcoreapp3.1|178μs|130ns|502ns|0.266| 0|0|20.37&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`ExecuteNonQuery`|net472|1.52μs|0.586ns|2.19ns|0.126| 0.000766|0|794&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`ExecuteNonQuery`|netcoreapp3.1|1.28μs|0.624ns|2.42ns|0.0109| 0|0|824&nbsp;B|
|#3038|`ExecuteNonQuery`|net472|1.59μs|0.381ns|1.43ns|0.126| 0.000797|0|794&nbsp;B|
|#3038|`ExecuteNonQuery`|netcoreapp3.1|1.23μs|0.292ns|1.13ns|0.0111| 0|0|824&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`CallElasticsearch`|net472|2.12μs|1.08ns|4.17ns|0.159| 0|0|1&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`CallElasticsearch`|netcoreapp3.1|1.43μs|2.45ns|9.49ns|0.0134| 0|0|984&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`CallElasticsearchAsync`|net472|2.34μs|0.834ns|3.12ns|0.18| 0|0|1.14&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`CallElasticsearchAsync`|netcoreapp3.1|1.49μs|0.656ns|2.54ns|0.0149| 0|0|1.1&nbsp;KB|
|#3038|`CallElasticsearch`|net472|2.23μs|0.633ns|2.37ns|0.159| 0|0|1&nbsp;KB|
|#3038|`CallElasticsearch`|netcoreapp3.1|1.46μs|1.24ns|4.63ns|0.0132| 0|0|984&nbsp;B|
|#3038|`CallElasticsearchAsync`|net472|2.27μs|2.11ns|8.18ns|0.181| 0|0|1.14&nbsp;KB|
|#3038|`CallElasticsearchAsync`|netcoreapp3.1|1.51μs|0.927ns|3.59ns|0.0151| 0|0|1.1&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`ExecuteAsync`|net472|2.53μs|1.39ns|5.36ns|0.2| 0|0|1.26&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`ExecuteAsync`|netcoreapp3.1|1.6μs|1.1ns|4.12ns|0.0161| 0|0|1.22&nbsp;KB|
|#3038|`ExecuteAsync`|net472|2.53μs|2.91ns|11.3ns|0.2| 0|0|1.26&nbsp;KB|
|#3038|`ExecuteAsync`|netcoreapp3.1|1.69μs|0.601ns|2.25ns|0.0162| 0|0|1.22&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`SendAsync`|net472|5.11μs|2.09ns|7.81ns|0.393| 0|0|2.48&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`SendAsync`|netcoreapp3.1|3.36μs|2.13ns|7.95ns|0.0318| 0|0|2.4&nbsp;KB|
|#3038|`SendAsync`|net472|4.9μs|1.19ns|4.45ns|0.392| 0|0|2.48&nbsp;KB|
|#3038|`SendAsync`|netcoreapp3.1|3.41μs|1.4ns|5.24ns|0.0325| 0|0|2.4&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`EnrichedLog`|net472|2.78μs|1.8ns|6.97ns|0.263| 0|0|1.66&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`EnrichedLog`|netcoreapp3.1|2.27μs|0.595ns|2.06ns|0.0239| 0|0|1.73&nbsp;KB|
|#3038|`EnrichedLog`|net472|2.75μs|1.46ns|5.67ns|0.263| 0|0|1.66&nbsp;KB|
|#3038|`EnrichedLog`|netcoreapp3.1|2.27μs|0.807ns|3.02ns|0.0227| 0|0|1.73&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`EnrichedLog`|net472|144μs|101ns|391ns|0.651| 0.217|0|4.5&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`EnrichedLog`|netcoreapp3.1|110μs|90.6ns|351ns|0.0551| 0|0|4.38&nbsp;KB|
|#3038|`EnrichedLog`|net472|148μs|128ns|496ns|0.659| 0.22|0|4.5&nbsp;KB|
|#3038|`EnrichedLog`|netcoreapp3.1|111μs|82.2ns|308ns|0.056| 0|0|4.38&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`EnrichedLog`|net472|5.45μs|1.63ns|6.32ns|0.545| 0.00273|0|3.43&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`EnrichedLog`|netcoreapp3.1|4.23μs|7.92ns|30.7ns|0.0524| 0|0|3.8&nbsp;KB|
|#3038|`EnrichedLog`|net472|5.39μs|1.54ns|5.96ns|0.545| 0.0027|0|3.43&nbsp;KB|
|#3038|`EnrichedLog`|netcoreapp3.1|4.39μs|1.51ns|5.85ns|0.0524| 0|0|3.8&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`SendReceive`|net472|1.99μs|0.447ns|1.73ns|0.193| 0|0|1.22&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`SendReceive`|netcoreapp3.1|1.58μs|1.15ns|4.32ns|0.0165| 0|0|1.21&nbsp;KB|
|#3038|`SendReceive`|net472|1.97μs|1.36ns|5.28ns|0.193| 0|0|1.22&nbsp;KB|
|#3038|`SendReceive`|netcoreapp3.1|1.67μs|1.29ns|4.99ns|0.0165| 0|0|1.21&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`EnrichedLog`|net472|4.75μs|1.56ns|5.82ns|0.33| 0|0|2.08&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`EnrichedLog`|netcoreapp3.1|4.1μs|2.39ns|9.24ns|0.0226| 0|0|1.69&nbsp;KB|
|#3038|`EnrichedLog`|net472|4.68μs|1.42ns|5.51ns|0.328| 0|0|2.08&nbsp;KB|
|#3038|`EnrichedLog`|netcoreapp3.1|4.11μs|2.13ns|7.96ns|0.0225| 0|0|1.69&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`StartFinishSpan`|net472|870ns|0.129ns|0.464ns|0.104| 0|0|658&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`StartFinishSpan`|netcoreapp3.1|820ns|0.891ns|3.33ns|0.00864| 0|0|648&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`StartFinishScope`|net472|1.02μs|0.411ns|1.59ns|0.117| 0|0|738&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`StartFinishScope`|netcoreapp3.1|902ns|0.35ns|1.26ns|0.0104| 0|0|768&nbsp;B|
|#3038|`StartFinishSpan`|net472|849ns|0.167ns|0.626ns|0.105| 0|0|658&nbsp;B|
|#3038|`StartFinishSpan`|netcoreapp3.1|805ns|0.679ns|2.35ns|0.00851| 0|0|648&nbsp;B|
|#3038|`StartFinishScope`|net472|1.02μs|0.23ns|0.828ns|0.117| 0|0|738&nbsp;B|
|#3038|`StartFinishScope`|netcoreapp3.1|857ns|0.354ns|1.32ns|0.0103| 0|0|768&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`RunOnMethodBegin`|net472|1.23μs|0.493ns|1.91ns|0.117| 0|0|738&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5)|`RunOnMethodBegin`|netcoreapp3.1|1.04μs|0.449ns|1.74ns|0.0104| 0|0|768&nbsp;B|
|#3038|`RunOnMethodBegin`|net472|1.23μs|0.318ns|1.23ns|0.117| 0|0|738&nbsp;B|
|#3038|`RunOnMethodBegin`|netcoreapp3.1|1.03μs|0.397ns|1.48ns|0.0103| 0|0|768&nbsp;B|
</details>

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #3038 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/1711980dd2be18e66928aaceaf4c2d143dd66e2f) will **not change** line coverage
:heavy_check_mark: Merging #3038 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/1711980dd2be18e66928aaceaf4c2d143dd66e2f) will **not change** branch coverage
:heavy_check_mark: Merging #3038 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/1711980dd2be18e66928aaceaf4c2d143dd66e2f) will **not change** complexity


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/1711980dd2be18e66928aaceaf4c2d143dd66e2f) | #3038       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `16808` / `22853` | `16766` / `22853` |          |
| Lines %   | `74%`      | `73%`      |  `0%` :heavy_check_mark:  |
| Branches  | `10013` / `14174` | `10005` / `14174` |          |
| Branches %| `71%`      | `71%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `15236`      | `15236`        |  `0`  :heavy_check_mark:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=106390&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/106390/artifacts?artifactName=Code%20Coverage%20Report_106390&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3038](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=106440&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/106440/artifacts?artifactName=Code%20Coverage%20Report_106440&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/1711980dd2be18e66928aaceaf4c2d143dd66e2f) | #3038       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `74%`      | `73%`       |  `0%` :heavy_check_mark:  |
| Branches %| `71%`      | `71%`       |  `0%` :heavy_check_mark:  |
| Complexity| `15236`      | `15236`       |  `0` :heavy_check_mark:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Ci.GitInfo](https://github.com/DataDog/dd-trace-dotnet/tree/5c237acf78f3e70d130c89bf9a08b1b152532e82/tracer/src/Datadog.Trace/Ci/GitInfo.cs) | `-17%` :no_entry: | `-11%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Ci.CIVisibility](https://github.com/DataDog/dd-trace-dotnet/tree/5c237acf78f3e70d130c89bf9a08b1b152532e82/tracer/src/Datadog.Trace/Ci/CIVisibility.cs) | `7%` :heavy_check_mark: | `7%` :heavy_check_mark:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=106390&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/106390/artifacts?artifactName=Code%20Coverage%20Report_106390&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3038](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=106440&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/106440/artifacts?artifactName=Code%20Coverage%20Report_106440&api-version=6.0&%24format=zip)

**Comment by gleocadie** [comment]
The code finds error message in the log :)
image

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #3038 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5) will **not change** line coverage
:heavy_check_mark: Merging #3038 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5) will **not change** branch coverage
:heavy_check_mark: Merging #3038 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5) will **not change** complexity


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5) | #3038       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `16774` / `22853` | `16796` / `22853` |          |
| Lines %   | `73%`      | `73%`      |  `0%` :heavy_check_mark:  |
| Branches  | `9993` / `14174` | `10006` / `14174` |          |
| Branches %| `71%`      | `71%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `15236`      | `15236`        |  `0`  :heavy_check_mark:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=106434&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/106434/artifacts?artifactName=Code%20Coverage%20Report_106434&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3038](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=106470&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/106470/artifacts?artifactName=Code%20Coverage%20Report_106470&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/98667ed402d0875e7ed8ce85f399e750b49a34e5) | #3038       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `73%`      | `73%`       |  `0%` :heavy_check_mark:  |
| Branches %| `71%`      | `71%`       |  `0%` :heavy_check_mark:  |
| Complexity| `15236`      | `15236`       |  `0` :heavy_check_mark:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Ci.CIVisibility](https://github.com/DataDog/dd-trace-dotnet/tree/bbcb3123256af16185057f2fed946c41daca894e/tracer/src/Datadog.Trace/Ci/CIVisibility.cs) | `7%` :heavy_check_mark: | `7%` :heavy_check_mark:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=106434&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/106434/artifacts?artifactName=Code%20Coverage%20Report_106434&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3038](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=106470&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/106470/artifacts?artifactName=Code%20Coverage%20Report_106470&api-version=6.0&%24format=zip)

**Pull request merged**
