### PR TITLE
Allow running ITests locally on Mac

### PR DESCRIPTION
**Pull request by pierotibou**
@DataDog/apm-dotnet

### CODE REVIEW

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #2063 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/4153faab84949d48bcec08c96e9d237dad63f508) will will **increase** line coverage by `4%`
:heavy_check_mark: Merging #2063 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/4153faab84949d48bcec08c96e9d237dad63f508) will **not change** branch coverage
:heavy_check_mark: Merging #2063 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/4153faab84949d48bcec08c96e9d237dad63f508) will will **decrease** complexity by `589`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/4153faab84949d48bcec08c96e9d237dad63f508) | #2063       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `10490` / `15636` | `9092` / `12795` |          |
| Lines %   | `67%`      | `71%`      |  `4%` :heavy_check_mark:  |
| Branches  | `4585` / `6890` | `4054` / `6110` |          |
| Branches %| `67%`      | `66%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `8098`      | `7509`        |  `-589`  :heavy_check_mark:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=81540&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/81540/artifacts?artifactName=Code%20Coverage%20Report_81540&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2063](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=81595&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/81595/artifacts?artifactName=Code%20Coverage%20Report_81595&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/4153faab84949d48bcec08c96e9d237dad63f508) | #2063       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `67%`      | `71%`       |  `4%` :heavy_check_mark:  |
| Branches %| `67%`      | `66%`       |  `0%` :heavy_check_mark:  |
| Complexity| `8098`      | `7509`       |  `-589` :heavy_check_mark:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.DuckTyping.DuckTypeProxyMethodsWithGenericParametersNotSupportedInNonPublicInstancesException](https://github.com/DataDog/dd-trace-dotnet/tree/426c929abdac799387024835b63d0d919d65faec/tracer/src/Datadog.Trace/DuckTyping/DuckTypeExceptions.cs) | `-100%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.PlatformHelpers.ServiceFabric](https://github.com/DataDog/dd-trace-dotnet/tree/426c929abdac799387024835b63d0d919d65faec/tracer/src/Datadog.Trace/PlatformHelpers/ServiceFabric.cs) | `-100%` :no_entry: | `0%` :heavy_check_mark:   | `-1` :heavy_check_mark: |
| [Datadog.Trace.AppSec.Transports.Http.IpInfo](https://github.com/DataDog/dd-trace-dotnet/tree/426c929abdac799387024835b63d0d919d65faec/tracer/src/Datadog.Trace/AppSec/Transports/Http/IpInfo.cs) | `-75%` :no_entry: | `0%` :heavy_check_mark:   | `1` :no_entry: |
| [Datadog.Trace.ClrProfiler.Helpers.PointerHelpers](https://github.com/DataDog/dd-trace-dotnet/tree/426c929abdac799387024835b63d0d919d65faec/tracer/src/Datadog.Trace/ClrProfiler/Helpers/PointerHelpers.cs) | `-75%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.AppSec.InstrumentationGatewayEventArgs](https://github.com/DataDog/dd-trace-dotnet/tree/426c929abdac799387024835b63d0d919d65faec/tracer/src/Datadog.Trace/AppSec/InstrumentationGatewayEventArgs.cs) | `-60%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.HttpOverStreams.HttpRequest](https://github.com/DataDog/dd-trace-dotnet/tree/426c929abdac799387024835b63d0d919d65faec/tracer/src/Datadog.Trace/HttpOverStreams/HttpRequest.cs) | `-60%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.HttpOverStreams.HttpResponse](https://github.com/DataDog/dd-trace-dotnet/tree/426c929abdac799387024835b63d0d919d65faec/tracer/src/Datadog.Trace/HttpOverStreams/HttpResponse.cs) | `-50%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Agent.Transports.HttpStreamResponse](https://github.com/DataDog/dd-trace-dotnet/tree/426c929abdac799387024835b63d0d919d65faec/tracer/src/Datadog.Trace/Agent/Transports/HttpStreamResponse.cs) | `-33%` :no_entry: | `0%` :heavy_check_mark:   | `1` :no_entry: |
| [Datadog.Trace.SpanContext](https://github.com/DataDog/dd-trace-dotnet/tree/426c929abdac799387024835b63d0d919d65faec/tracer/src/Datadog.Trace/SpanContext.cs) | `-27%` :no_entry: | `0%` :heavy_check_mark:   | `2` :no_entry: |
| [Datadog.Trace.DuckTyping.DuckType](https://github.com/DataDog/dd-trace-dotnet/tree/426c929abdac799387024835b63d0d919d65faec/tracer/src/Datadog.Trace/DuckTyping/DuckType.Properties.cs) | `-24%` :no_entry: | `-30%` :no_entry:   | `0` :heavy_check_mark: |
| ...And 49 more  | | | |


The following classes were added in #2063:

| File    | Line coverage | Branch coverage | Complexity |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.AppSec.AspNetCore.BlockingMiddleware](https://github.com/DataDog/dd-trace-dotnet/pull/2063/files) | `41%` | `19%` | `25` |
| [Datadog.Trace.AppSec.BlockActionException](https://github.com/DataDog/dd-trace-dotnet/pull/2063/files) | `0%` | `100%` | `4` |
| [Datadog.Trace.AppSec.PageBlockedByAppSecException](https://github.com/DataDog/dd-trace-dotnet/pull/2063/files) | `0%` | `100%` | `4` |
| [Datadog.Trace.Ci.CITracerManager](https://github.com/DataDog/dd-trace-dotnet/pull/2063/files) | `100%` | `100%` | `1` |
| [Datadog.Trace.Ci.CITracerManagerFactory](https://github.com/DataDog/dd-trace-dotnet/pull/2063/files) | `100%` | `100%` | `3` |
| ...And 36 more  | | | |


77 classes were removed from Datadog.Trace in #2063


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=81540&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/81540/artifacts?artifactName=Code%20Coverage%20Report_81540&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2063](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=81595&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/81595/artifacts?artifactName=Code%20Coverage%20Report_81595&api-version=6.0&%24format=zip)

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #2063 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d): 
* 2 benchmarks are **faster**, with geometric mean 1.235
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`WriteAndFlushEnrichedTraces`|net472|944.3&nbsp;μs|15.72&nbsp;μs|13.13&nbsp;μs|0.0000| 0.0000|0.0000|3.09&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|743.9&nbsp;μs|6.37&nbsp;μs|5.65&nbsp;μs|0.0000| 0.0000|0.0000|2.51&nbsp;KB|
|#2063|`WriteAndFlushEnrichedTraces`|net472|1,017.5&nbsp;μs|18.78&nbsp;μs|28.10&nbsp;μs|1.0163| 0.0000|0.0000|12.77&nbsp;KB|
|#2063|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|822.1&nbsp;μs|12.74&nbsp;μs|11.29&nbsp;μs|0.0000| 0.0000|0.0000|11.71&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Faster :tada: Same allocations :heavy_check_mark:



#### Faster :tada: in #2063

|  Benchmark         | base/diff | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.AspNetCoreBenchmark.SendRequest&#8209;netcoreapp3.1 | 1.146 | 311,415.78 | 271,775.75 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`SendRequest`|net472|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000| 0.0000|0.0000|0&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`SendRequest`|netcoreapp3.1|310,531.2087&nbsp;ns|5,327.8193&nbsp;ns|5,921.8570&nbsp;ns|0.1539| 0.0000|0.0000|19833&nbsp;B|
|#2063|`SendRequest`|net472|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000| 0.0000|0.0000|0&nbsp;B|
|#2063|`SendRequest`|netcoreapp3.1|273,218.4132&nbsp;ns|5,357.4414&nbsp;ns|4,749.2322&nbsp;ns|0.1359| 0.0000|0.0000|19618&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`ExecuteNonQuery`|net472|1.982&nbsp;μs|0.0278&nbsp;μs|0.0260&nbsp;μs|0.1079| 0.0010|0.0000|682&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`ExecuteNonQuery`|netcoreapp3.1|1.917&nbsp;μs|0.0219&nbsp;μs|0.0194&nbsp;μs|0.0096| 0.0000|0.0000|712&nbsp;B|
|#2063|`ExecuteNonQuery`|net472|2.001&nbsp;μs|0.0387&nbsp;μs|0.0362&nbsp;μs|0.1083| 0.0010|0.0000|682&nbsp;B|
|#2063|`ExecuteNonQuery`|netcoreapp3.1|1.841&nbsp;μs|0.0333&nbsp;μs|0.0311&nbsp;μs|0.0099| 0.0000|0.0000|712&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`CallElasticsearch`|net472|3.246&nbsp;μs|0.0591&nbsp;μs|0.0921&nbsp;μs|0.1289| 0.0000|0.0000|827&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`CallElasticsearch`|netcoreapp3.1|1.622&nbsp;μs|0.0244&nbsp;μs|0.0228&nbsp;μs|0.0110| 0.0000|0.0000|768&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`CallElasticsearchAsync`|net472|3.523&nbsp;μs|0.0701&nbsp;μs|0.1919&nbsp;μs|0.1495| 0.0000|0.0000|963&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`CallElasticsearchAsync`|netcoreapp3.1|1.738&nbsp;μs|0.0285&nbsp;μs|0.0238&nbsp;μs|0.0124| 0.0000|0.0000|888&nbsp;B|
|#2063|`CallElasticsearch`|net472|3.077&nbsp;μs|0.0387&nbsp;μs|0.0362&nbsp;μs|0.1288| 0.0000|0.0000|827&nbsp;B|
|#2063|`CallElasticsearch`|netcoreapp3.1|1.578&nbsp;μs|0.0314&nbsp;μs|0.0746&nbsp;μs|0.0103| 0.0000|0.0000|768&nbsp;B|
|#2063|`CallElasticsearchAsync`|net472|3.368&nbsp;μs|0.0658&nbsp;μs|0.1044&nbsp;μs|0.1500| 0.0000|0.0000|963&nbsp;B|
|#2063|`CallElasticsearchAsync`|netcoreapp3.1|1.607&nbsp;μs|0.0231&nbsp;μs|0.0216&nbsp;μs|0.0119| 0.0000|0.0000|888&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`ExecuteAsync`|net472|3.594&nbsp;μs|0.0716&nbsp;μs|0.0880&nbsp;μs|0.1693| 0.0000|0.0000|1083&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`ExecuteAsync`|netcoreapp3.1|1.871&nbsp;μs|0.0287&nbsp;μs|0.0269&nbsp;μs|0.0142| 0.0000|0.0000|1008&nbsp;B|
|#2063|`ExecuteAsync`|net472|3.208&nbsp;μs|0.0441&nbsp;μs|0.0412&nbsp;μs|0.1698| 0.0000|0.0000|1083&nbsp;B|
|#2063|`ExecuteAsync`|netcoreapp3.1|1.765&nbsp;μs|0.0238&nbsp;μs|0.0223&nbsp;μs|0.0141| 0.0000|0.0000|1008&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`SendAsync`|net472|6.041&nbsp;μs|0.0807&nbsp;μs|0.0715&nbsp;μs|0.3493| 0.0000|0.0000|2.19&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`SendAsync`|netcoreapp3.1|4.280&nbsp;μs|0.0537&nbsp;μs|0.0502&nbsp;μs|0.0295| 0.0000|0.0000|2.09&nbsp;KB|
|#2063|`SendAsync`|net472|6.100&nbsp;μs|0.1022&nbsp;μs|0.0956&nbsp;μs|0.3503| 0.0000|0.0000|2.19&nbsp;KB|
|#2063|`SendAsync`|netcoreapp3.1|4.134&nbsp;μs|0.0743&nbsp;μs|0.0659&nbsp;μs|0.0289| 0.0000|0.0000|2.09&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Faster :tada: Same allocations :heavy_check_mark:



#### Faster :tada: in #2063

|  Benchmark         | base/diff | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.ILoggerBenchmark.EnrichedLog&#8209;net472 | 1.331 | 4,890.20 | 3,674.28 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`EnrichedLog`|net472|4.876&nbsp;μs|0.0902&nbsp;μs|0.0885&nbsp;μs|0.2853| 0.0000|0.0000|1.79&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`EnrichedLog`|netcoreapp3.1|3.742&nbsp;μs|0.0748&nbsp;μs|0.0800&nbsp;μs|0.0282| 0.0000|0.0000|1.94&nbsp;KB|
|#2063|`EnrichedLog`|net472|3.691&nbsp;μs|0.0620&nbsp;μs|0.0550&nbsp;μs|0.2876| 0.0000|0.0000|1.79&nbsp;KB|
|#2063|`EnrichedLog`|netcoreapp3.1|3.650&nbsp;μs|0.0670&nbsp;μs|0.0983&nbsp;μs|0.0272| 0.0000|0.0000|1.94&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`EnrichedLog`|net472|177.9&nbsp;μs|3.39&nbsp;μs|3.00&nbsp;μs|0.7072| 0.2652|0.0000|5.23&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`EnrichedLog`|netcoreapp3.1|149.5&nbsp;μs|1.91&nbsp;μs|1.78&nbsp;μs|0.0743| 0.0000|0.0000|5.05&nbsp;KB|
|#2063|`EnrichedLog`|net472|168.1&nbsp;μs|2.51&nbsp;μs|2.35&nbsp;μs|0.6757| 0.2534|0.0000|5.23&nbsp;KB|
|#2063|`EnrichedLog`|netcoreapp3.1|146.4&nbsp;μs|2.37&nbsp;μs|2.22&nbsp;μs|0.0739| 0.0000|0.0000|5.05&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`EnrichedLog`|net472|11.67&nbsp;μs|0.216&nbsp;μs|0.202&nbsp;μs|0.8556| 0.0000|0.0000|5.31&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`EnrichedLog`|netcoreapp3.1|10.32&nbsp;μs|0.161&nbsp;μs|0.231&nbsp;μs|0.0911| 0.0000|0.0000|6.28&nbsp;KB|
|#2063|`EnrichedLog`|net472|10.90&nbsp;μs|0.193&nbsp;μs|0.180&nbsp;μs|0.8542| 0.0000|0.0000|5.31&nbsp;KB|
|#2063|`EnrichedLog`|netcoreapp3.1|10.31&nbsp;μs|0.205&nbsp;μs|0.354&nbsp;μs|0.0885| 0.0000|0.0000|6.28&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`SendReceive`|net472|2.306&nbsp;μs|0.0443&nbsp;μs|0.1028&nbsp;μs|0.1550| 0.0000|0.0000|987&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`SendReceive`|netcoreapp3.1|1.923&nbsp;μs|0.0301&nbsp;μs|0.0267&nbsp;μs|0.0137| 0.0000|0.0000|984&nbsp;B|
|#2063|`SendReceive`|net472|2.165&nbsp;μs|0.0427&nbsp;μs|0.0919&nbsp;μs|0.1552| 0.0000|0.0000|987&nbsp;B|
|#2063|`SendReceive`|netcoreapp3.1|1.972&nbsp;μs|0.0294&nbsp;μs|0.0275&nbsp;μs|0.0136| 0.0000|0.0000|984&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`EnrichedLog`|net472|8.052&nbsp;μs|0.1606&nbsp;μs|0.1649&nbsp;μs|0.4463| 0.0000|0.0000|2.8&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`EnrichedLog`|netcoreapp3.1|7.187&nbsp;μs|0.1248&nbsp;μs|0.1107&nbsp;μs|0.0391| 0.0000|0.0000|2.61&nbsp;KB|
|#2063|`EnrichedLog`|net472|7.217&nbsp;μs|0.0829&nbsp;μs|0.0775&nbsp;μs|0.4498| 0.0000|0.0000|2.8&nbsp;KB|
|#2063|`EnrichedLog`|netcoreapp3.1|6.951&nbsp;μs|0.0733&nbsp;μs|0.0650&nbsp;μs|0.0377| 0.0000|0.0000|2.61&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`StartFinishSpan`|net472|891.1&nbsp;ns|13.67&nbsp;ns|12.79&nbsp;ns|0.0681| 0.0000|0.0000|433&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`StartFinishSpan`|netcoreapp3.1|919.2&nbsp;ns|18.00&nbsp;ns|31.99&nbsp;ns|0.0062| 0.0000|0.0000|432&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`StartFinishScope`|net472|1,048.8&nbsp;ns|12.74&nbsp;ns|10.64&nbsp;ns|0.0805| 0.0000|0.0000|514&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b05248df1cd8fafaeaae7ef6b1b8bd9770e5316d)|`StartFinishScope`|netcoreapp3.1|1,048.6&nbsp;ns|19.13&nbsp;ns|16.96&nbsp;ns|0.0075| 0.0000|0.0000|552&nbsp;B|
|#2063|`StartFinishSpan`|net472|866.3&nbsp;ns|16.12&nbsp;ns|32.93&nbsp;ns|0.0680| 0.0000|0.0000|433&nbsp;B|
|#2063|`StartFinishSpan`|netcoreapp3.1|838.0&nbsp;ns|15.75&nbsp;ns|14.73&nbsp;ns|0.0058| 0.0000|0.0000|432&nbsp;B|
|#2063|`StartFinishScope`|net472|1,019.1&nbsp;ns|15.23&nbsp;ns|11.89&nbsp;ns|0.0808| 0.0000|0.0000|514&nbsp;B|
|#2063|`StartFinishScope`|netcoreapp3.1|981.2&nbsp;ns|16.49&nbsp;ns|15.43&nbsp;ns|0.0073| 0.0000|0.0000|552&nbsp;B|
</details>

**Review by lucaspimentel — APPROVED** [review]
LGTM, as long as it works on your Mac

**Review by andrewlock — APPROVED** [review]
Thanks!

**Pull request merged**
