### PR TITLE
Add retry to cosmosdb initialization

### PR DESCRIPTION
**Pull request by andrewlock**
We've had a lot of failures for cosmosdb not starting. Add some retries

@DataDog/apm-dotnet

### CODE REVIEW

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #2348 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701) will **not change** line coverage
:heavy_check_mark: Merging #2348 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701) will **not change** branch coverage
:heavy_check_mark: Merging #2348 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701) will **not change** complexity


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701) | #2348       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `10429` / `14678` | `10386` / `14678` |          |
| Lines %   | `71%`      | `71%`      |  `0%` :heavy_check_mark:  |
| Branches  | `5361` / `7739` | `5336` / `7739` |          |
| Branches %| `69%`      | `69%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `8850`      | `8850`        |  `0`  :heavy_check_mark:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=88012&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/88012/artifacts?artifactName=Code%20Coverage%20Report_88012&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2348](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=88022&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/88022/artifacts?artifactName=Code%20Coverage%20Report_88022&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701) | #2348       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `71%`      | `71%`       |  `0%` :heavy_check_mark:  |
| Branches %| `69%`      | `69%`       |  `0%` :heavy_check_mark:  |
| Complexity| `8850`      | `8850`       |  `0` :heavy_check_mark:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Couchbase.IIOServiceExecuteIntegrationBis](https://github.com/DataDog/dd-trace-dotnet/tree/3d5744f318074b69750a7853e836d908faa972f9/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Couchbase/IIOServiceExecuteIntegrationBis.cs) | `-100%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.MsTestV2.TestMethodRunnerExecuteIntegration](https://github.com/DataDog/dd-trace-dotnet/tree/3d5744f318074b69750a7853e836d908faa972f9/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Testing/MsTestV2/TestMethodRunnerExecuteIntegration.cs) | `-33%` :no_entry: | `-19%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Ci.Agent.CIAgentWriter](https://github.com/DataDog/dd-trace-dotnet/tree/3d5744f318074b69750a7853e836d908faa972f9/tracer/src/Datadog.Trace/Ci/Agent/CIAgentWriter.cs) | `-14%` :no_entry: | `-21%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.NUnit.NUnitCompositeWorkItemSkipChildrenIntegration](https://github.com/DataDog/dd-trace-dotnet/tree/3d5744f318074b69750a7853e836d908faa972f9/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Testing/NUnit/NUnitCompositeWorkItemSkipChildrenIntegration.cs) | `-8%` :no_entry: | `-8%` :no_entry:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=88012&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/88012/artifacts?artifactName=Code%20Coverage%20Report_88012&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2348](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=88022&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/88022/artifacts?artifactName=Code%20Coverage%20Report_88022&api-version=6.0&%24format=zip)

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #2348 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701): 
* 2 benchmarks are **faster**, with geometric mean 1.200
* 2 benchmarks are **slower**, with geometric mean 1.196
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`WriteAndFlushEnrichedTraces`|net472|938μs|4.78μs|21.4μs|0| 0|0|3.16&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|726μs|1.46μs|5.48μs|0| 0|0|2.57&nbsp;KB|
|#2348|`WriteAndFlushEnrichedTraces`|net472|930μs|4.34μs|16.8μs|0| 0|0|3.16&nbsp;KB|
|#2348|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|720μs|2.29μs|8.58μs|0| 0|0|2.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`SendRequest`|netcoreapp3.1|357μs|1.23μs|5.79μs|0.172| 0|0|19.67&nbsp;KB|
|#2348|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#2348|`SendRequest`|netcoreapp3.1|350μs|665ns|2.49μs|0.174| 0|0|19.67&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`ExecuteNonQuery`|net472|1.75μs|7.67ns|28.7ns|0.093| 0.000894|0|586&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`ExecuteNonQuery`|netcoreapp3.1|1.6μs|4.32ns|16.2ns|0.00876| 0|0|624&nbsp;B|
|#2348|`ExecuteNonQuery`|net472|1.84μs|13ns|124ns|0.0924| 0.00088|0|586&nbsp;B|
|#2348|`ExecuteNonQuery`|netcoreapp3.1|1.59μs|9.27ns|80.3ns|0.00884| 0|0|624&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Faster :tada: Same allocations :heavy_check_mark:



#### Faster :tada: in #2348

|  Benchmark         | base/diff | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.ElasticsearchBenchmark.CallElasticsearchAsync&#8209;net472 | 1.220 | 3,326.52 | 2,726.43 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`CallElasticsearch`|net472|2.52μs|8.7ns|33.7ns|0.124| 0|0|794&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`CallElasticsearch`|netcoreapp3.1|1.89μs|10.4ns|67.3ns|0.0113| 0|0|784&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`CallElasticsearchAsync`|net472|3.33μs|13.4ns|50.1ns|0.145| 0|0|931&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`CallElasticsearchAsync`|netcoreapp3.1|2.03μs|11.7ns|88ns|0.0124| 0|0|904&nbsp;B|
|#2348|`CallElasticsearch`|net472|2.58μs|8.78ns|32.8ns|0.123| 0|0|794&nbsp;B|
|#2348|`CallElasticsearch`|netcoreapp3.1|1.87μs|6.75ns|24.3ns|0.0107| 0|0|784&nbsp;B|
|#2348|`CallElasticsearchAsync`|net472|2.78μs|16.1ns|126ns|0.145| 0|0|931&nbsp;B|
|#2348|`CallElasticsearchAsync`|netcoreapp3.1|1.87μs|6.24ns|23.3ns|0.0125| 0|0|904&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #2348

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.GraphQLBenchmark.ExecuteAsync&#8209;net472 | 1.164 | 2,995.49 | 3,488.20 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`ExecuteAsync`|net472|3.03μs|16.4ns|111ns|0.165| 0|0|1.05&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`ExecuteAsync`|netcoreapp3.1|2.16μs|7.18ns|26.9ns|0.0138| 0|0|1.02&nbsp;KB|
|#2348|`ExecuteAsync`|net472|3.48μs|10.9ns|40.7ns|0.164| 0|0|1.05&nbsp;KB|
|#2348|`ExecuteAsync`|netcoreapp3.1|2.13μs|9.29ns|36ns|0.0149| 0|0|1.02&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`SendAsync`|net472|6.78μs|31.1ns|124ns|0.352| 0|0|2.26&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`SendAsync`|netcoreapp3.1|4.89μs|18.8ns|70.3ns|0.0288| 0|0|2.16&nbsp;KB|
|#2348|`SendAsync`|net472|6.79μs|37.3ns|279ns|0.353| 0|0|2.26&nbsp;KB|
|#2348|`SendAsync`|netcoreapp3.1|5.01μs|28.1ns|180ns|0.0306| 0|0|2.16&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`EnrichedLog`|net472|3.75μs|17.9ns|71.6ns|0.224| 0|0|1.44&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`EnrichedLog`|netcoreapp3.1|3.41μs|10.9ns|42.2ns|0.02| 0|0|1.52&nbsp;KB|
|#2348|`EnrichedLog`|net472|3.64μs|17.1ns|113ns|0.224| 0|0|1.44&nbsp;KB|
|#2348|`EnrichedLog`|netcoreapp3.1|3.35μs|10.1ns|37.7ns|0.02| 0|0|1.52&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`EnrichedLog`|net472|313μs|1.22μs|4.73μs|0.316| 0.158|0|4.31&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`EnrichedLog`|netcoreapp3.1|251μs|1.01μs|3.79μs|0| 0|0|4.19&nbsp;KB|
|#2348|`EnrichedLog`|net472|313μs|1.1μs|3.82μs|0.306| 0.153|0|4.31&nbsp;KB|
|#2348|`EnrichedLog`|netcoreapp3.1|260μs|983ns|3.68μs|0| 0|0|4.19&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`EnrichedLog`|net472|8.39μs|35.1ns|136ns|0.5| 0|0|3.21&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`EnrichedLog`|netcoreapp3.1|6.93μs|36.9ns|248ns|0.0502| 0|0|3.58&nbsp;KB|
|#2348|`EnrichedLog`|net472|8.73μs|46.8ns|247ns|0.502| 0|0|3.21&nbsp;KB|
|#2348|`EnrichedLog`|netcoreapp3.1|6.53μs|11ns|39.6ns|0.0489| 0|0|3.58&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Faster :tada: Same allocations :heavy_check_mark:



#### Faster :tada: in #2348

|  Benchmark         | base/diff | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.RedisBenchmark.SendReceive&#8209;net472 | 1.180 | 2,773.95 | 2,350.59 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`SendReceive`|net472|2.76μs|15.2ns|98.7ns|0.156| 0|0|1&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`SendReceive`|netcoreapp3.1|2.15μs|12ns|82.2ns|0.0139| 0|0|1&nbsp;KB|
|#2348|`SendReceive`|net472|2.36μs|7.79ns|29.2ns|0.157| 0|0|1&nbsp;KB|
|#2348|`SendReceive`|netcoreapp3.1|2.15μs|6.99ns|27.1ns|0.0141| 0|0|1&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #2348

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.SerilogBenchmark.EnrichedLog&#8209;netcoreapp3.1 | 1.229 | 5,502.52 | 6,761.65 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`EnrichedLog`|net472|6.99μs|31.9ns|119ns|0.286| 0|0|1.85&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`EnrichedLog`|netcoreapp3.1|5.49μs|16.7ns|64.7ns|0.0197| 0|0|1.47&nbsp;KB|
|#2348|`EnrichedLog`|net472|6.35μs|31.4ns|247ns|0.289| 0|0|1.85&nbsp;KB|
|#2348|`EnrichedLog`|netcoreapp3.1|6.75μs|31.2ns|121ns|0.0203| 0|0|1.47&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`StartFinishSpan`|net472|1.02μs|4.89ns|19.6ns|0.0702| 0|0|449&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`StartFinishSpan`|netcoreapp3.1|961ns|3.29ns|12.3ns|0.00615| 0|0|448&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`StartFinishScope`|net472|1.23μs|4.46ns|16.7ns|0.0829| 0|0|530&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/872a15956cf369773d48b25c7eab644b08d74701)|`StartFinishScope`|netcoreapp3.1|1.11μs|2.52ns|9.76ns|0.00773| 0|0|568&nbsp;B|
|#2348|`StartFinishSpan`|net472|1.04μs|5.9ns|40ns|0.0702| 0|0|449&nbsp;B|
|#2348|`StartFinishSpan`|netcoreapp3.1|962ns|3.03ns|11.4ns|0.00623| 0|0|448&nbsp;B|
|#2348|`StartFinishScope`|net472|1.22μs|4.92ns|18.4ns|0.0831| 0|0|530&nbsp;B|
|#2348|`StartFinishScope`|netcoreapp3.1|1.18μs|2.51ns|9.03ns|0.00815| 0|0|568&nbsp;B|
</details>

**Review by anna-git — APPROVED** [review]

**Review by tonyredondo — APPROVED** [review]
LGTM Coooooosmmmmooooosss

**Review by zacharycmontoya — APPROVED** [review]

**Comment by andrewlock** [comment]
image

**Pull request merged**
