### PR TITLE
[Profiler] Rename tests apps with "Samples." prefix instead of "Datadog.Demos."

### PR DESCRIPTION
**Pull request by chrisnas**
## Summary of changes
Rename test applications assemblies prefix from "Datadog.Demos." to "Samples".

## Reason for change
The "Only My Code" features uses library definition where "Datatog." prefix in assemblies name is used to identify Datadog code. In order to be able to test the feature with our test application, they need to be renamed. 
Last but not least, the new "Samples." prefix is consistent with Tracer.

## Implementation details
Rename projects, folders, namespaces and assemblies of tests applications

## Test coverage
Integration tests have been updated accordingly

### CODE REVIEW

**Review by andrewlock — APPROVED** [review]

**Review by gleocadie — COMMENTED** [review]
Do not forget to modify the Demo solution file ;)

**Comment by chrisnas** [comment]
> Do not forget to modify the Demo solution file ;)

✅

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #2788 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`WriteAndFlushEnrichedTraces`|net472|728μs|1.18μs|4.41μs|0| 0|0|3.16&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|461μs|275ns|991ns|0| 0|0|2.57&nbsp;KB|
|#2788|`WriteAndFlushEnrichedTraces`|net472|728μs|343ns|1.28μs|0| 0|0|3.16&nbsp;KB|
|#2788|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|468μs|469ns|1.76μs|0| 0|0|2.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`AllCycleSimpleBody`|net472|197ns|0.0159ns|0.0594ns|0.0661| 0|0|417&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`AllCycleSimpleBody`|netcoreapp3.1|247ns|0.0755ns|0.282ns|0.00563| 0|0|416&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`AllCycleMoreComplexBody`|net472|193ns|0.0184ns|0.0664ns|0.0623| 0|0|393&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`AllCycleMoreComplexBody`|netcoreapp3.1|248ns|0.0651ns|0.244ns|0.0054| 0|0|392&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`BodyExtractorSimpleBody`|net472|267ns|0.177ns|0.687ns|0.0571| 0|0|361&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`BodyExtractorSimpleBody`|netcoreapp3.1|236ns|0.0943ns|0.365ns|0.00373| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`BodyExtractorMoreComplexBody`|net472|15.8μs|10.1ns|37.6ns|1.2| 0.0158|0|7.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`BodyExtractorMoreComplexBody`|netcoreapp3.1|13.1μs|46.5ns|180ns|0.0906| 0|0|6.75&nbsp;KB|
|#2788|`AllCycleSimpleBody`|net472|194ns|0.0479ns|0.173ns|0.0661| 0|0|417&nbsp;B|
|#2788|`AllCycleSimpleBody`|netcoreapp3.1|247ns|0.0872ns|0.326ns|0.00568| 0|0|416&nbsp;B|
|#2788|`AllCycleMoreComplexBody`|net472|192ns|0.0395ns|0.148ns|0.0623| 0|0|393&nbsp;B|
|#2788|`AllCycleMoreComplexBody`|netcoreapp3.1|247ns|0.0803ns|0.301ns|0.00558| 0|0|392&nbsp;B|
|#2788|`BodyExtractorSimpleBody`|net472|258ns|0.102ns|0.367ns|0.0571| 0|0|361&nbsp;B|
|#2788|`BodyExtractorSimpleBody`|netcoreapp3.1|245ns|0.421ns|1.63ns|0.00366| 0|0|272&nbsp;B|
|#2788|`BodyExtractorMoreComplexBody`|net472|15.8μs|5.88ns|22ns|1.19| 0.0157|0|7.62&nbsp;KB|
|#2788|`BodyExtractorMoreComplexBody`|netcoreapp3.1|12.9μs|4.1ns|15.9ns|0.0899| 0|0|6.75&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`SendRequest`|netcoreapp3.1|172μs|149ns|577ns|0.257| 0|0|19.74&nbsp;KB|
|#2788|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#2788|`SendRequest`|netcoreapp3.1|171μs|103ns|399ns|0.256| 0|0|19.74&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`ExecuteNonQuery`|net472|1.32μs|0.707ns|2.65ns|0.0938| 0.000656|0|594&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`ExecuteNonQuery`|netcoreapp3.1|1.12μs|0.285ns|1.07ns|0.00843| 0|0|632&nbsp;B|
|#2788|`ExecuteNonQuery`|net472|1.41μs|0.485ns|1.88ns|0.0937| 0.000704|0|594&nbsp;B|
|#2788|`ExecuteNonQuery`|netcoreapp3.1|1.09μs|0.219ns|0.818ns|0.00875| 0|0|632&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`CallElasticsearch`|net472|2.04μs|1.09ns|4.21ns|0.125| 0|0|802&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`CallElasticsearch`|netcoreapp3.1|1.22μs|1.52ns|5.89ns|0.0103| 0|0|792&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`CallElasticsearchAsync`|net472|2.17μs|0.657ns|2.46ns|0.147| 0|0|939&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`CallElasticsearchAsync`|netcoreapp3.1|1.35μs|0.405ns|1.57ns|0.0122| 0|0|912&nbsp;B|
|#2788|`CallElasticsearch`|net472|2.16μs|0.993ns|3.72ns|0.125| 0|0|802&nbsp;B|
|#2788|`CallElasticsearch`|netcoreapp3.1|1.35μs|2.93ns|11.4ns|0.0106| 0|0|792&nbsp;B|
|#2788|`CallElasticsearchAsync`|net472|2.15μs|0.978ns|3.53ns|0.147| 0|0|939&nbsp;B|
|#2788|`CallElasticsearchAsync`|netcoreapp3.1|1.33μs|0.679ns|2.54ns|0.0125| 0|0|912&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`ExecuteAsync`|net472|2.19μs|4.25ns|15.9ns|0.165| 0|0|1.06&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`ExecuteAsync`|netcoreapp3.1|1.43μs|0.507ns|1.83ns|0.0138| 0|0|1.03&nbsp;KB|
|#2788|`ExecuteAsync`|net472|2.26μs|1.01ns|3.79ns|0.166| 0|0|1.06&nbsp;KB|
|#2788|`ExecuteAsync`|netcoreapp3.1|1.46μs|0.775ns|2.9ns|0.0135| 0|0|1.03&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`SendAsync`|net472|4.98μs|2.04ns|7.89ns|0.357| 0|0|2.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`SendAsync`|netcoreapp3.1|3.22μs|1.64ns|6.15ns|0.0289| 0|0|2.21&nbsp;KB|
|#2788|`SendAsync`|net472|4.83μs|1.74ns|6.76ns|0.358| 0|0|2.28&nbsp;KB|
|#2788|`SendAsync`|netcoreapp3.1|3.24μs|1.8ns|6.75ns|0.0308| 0|0|2.21&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`EnrichedLog`|net472|2.76μs|0.814ns|3.05ns|0.227| 0|0|1.45&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`EnrichedLog`|netcoreapp3.1|2.12μs|1.89ns|7.07ns|0.0213| 0|0|1.53&nbsp;KB|
|#2788|`EnrichedLog`|net472|2.65μs|0.974ns|3.64ns|0.228| 0|0|1.45&nbsp;KB|
|#2788|`EnrichedLog`|netcoreapp3.1|2.11μs|0.547ns|1.97ns|0.021| 0|0|1.53&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`EnrichedLog`|net472|149μs|108ns|418ns|0.522| 0.149|0|4.29&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`EnrichedLog`|netcoreapp3.1|113μs|220ns|850ns|0.0556| 0|0|4.18&nbsp;KB|
|#2788|`EnrichedLog`|net472|149μs|145ns|524ns|0.518| 0.148|0|4.29&nbsp;KB|
|#2788|`EnrichedLog`|netcoreapp3.1|111μs|240ns|929ns|0.0554| 0|0|4.18&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`EnrichedLog`|net472|5.25μs|2.05ns|7.66ns|0.508| 0.00263|0|3.23&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`EnrichedLog`|netcoreapp3.1|4.26μs|1.79ns|6.44ns|0.0486| 0|0|3.6&nbsp;KB|
|#2788|`EnrichedLog`|net472|5.37μs|2.4ns|9.31ns|0.506| 0.00268|0|3.23&nbsp;KB|
|#2788|`EnrichedLog`|netcoreapp3.1|4.1μs|1.31ns|5.09ns|0.0492| 0|0|3.6&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`SendReceive`|net472|1.86μs|0.893ns|3.46ns|0.159| 0|0|1.01&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`SendReceive`|netcoreapp3.1|1.51μs|0.334ns|1.25ns|0.0136| 0|0|1.01&nbsp;KB|
|#2788|`SendReceive`|net472|1.84μs|0.653ns|2.44ns|0.158| 0|0|1.01&nbsp;KB|
|#2788|`SendReceive`|netcoreapp3.1|1.53μs|0.661ns|2.56ns|0.013| 0|0|1.01&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`EnrichedLog`|net472|4.49μs|1.91ns|7.16ns|0.293| 0|0|1.87&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`EnrichedLog`|netcoreapp3.1|3.82μs|0.854ns|2.96ns|0.0192| 0|0|1.49&nbsp;KB|
|#2788|`EnrichedLog`|net472|4.63μs|1.79ns|6.93ns|0.291| 0|0|1.87&nbsp;KB|
|#2788|`EnrichedLog`|netcoreapp3.1|3.95μs|0.769ns|2.88ns|0.0197| 0|0|1.49&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`StartFinishSpan`|net472|770ns|0.23ns|0.859ns|0.0718| 0|0|457&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`StartFinishSpan`|netcoreapp3.1|626ns|0.207ns|0.8ns|0.00597| 0|0|456&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`StartFinishScope`|net472|1.05μs|0.528ns|2.04ns|0.0844| 0|0|538&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`StartFinishScope`|netcoreapp3.1|766ns|0.395ns|1.42ns|0.00772| 0|0|576&nbsp;B|
|#2788|`StartFinishSpan`|net472|735ns|0.343ns|1.33ns|0.072| 0|0|457&nbsp;B|
|#2788|`StartFinishSpan`|netcoreapp3.1|642ns|0.182ns|0.683ns|0.00611| 0|0|456&nbsp;B|
|#2788|`StartFinishScope`|net472|1.04μs|0.394ns|1.53ns|0.0844| 0|0|538&nbsp;B|
|#2788|`StartFinishScope`|netcoreapp3.1|772ns|0.179ns|0.67ns|0.00772| 0|0|576&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`RunOnMethodBegin`|net472|1.14μs|0.488ns|1.89ns|0.0841| 0|0|538&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/13f566022faacf0a1bccf05b1b0341771e0beb2f)|`RunOnMethodBegin`|netcoreapp3.1|936ns|1.2ns|4.48ns|0.00794| 0|0|576&nbsp;B|
|#2788|`RunOnMethodBegin`|net472|1.1μs|0.758ns|2.84ns|0.0843| 0|0|538&nbsp;B|
|#2788|`RunOnMethodBegin`|netcoreapp3.1|893ns|0.252ns|0.942ns|0.00767| 0|0|576&nbsp;B|
</details>

**Review by gleocadie — APPROVED** [review]
LGTM

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #2788 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/ad57f5cdba0453dad63376bd5a9700181f8705f2) will **not change** line coverage
:heavy_check_mark: Merging #2788 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/ad57f5cdba0453dad63376bd5a9700181f8705f2) will **not change** branch coverage
:heavy_check_mark: Merging #2788 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/ad57f5cdba0453dad63376bd5a9700181f8705f2) will will **decrease** complexity by `1`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/ad57f5cdba0453dad63376bd5a9700181f8705f2) | #2788       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `14103` / `19513` | `14057` / `19510` |          |
| Lines %   | `72%`      | `72%`      |  `0%` :heavy_check_mark:  |
| Branches  | `8248` / `11859` | `8245` / `11859` |          |
| Branches %| `70%`      | `70%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `13134`      | `13133`        |  `-1`  :heavy_check_mark:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=99174&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/99174/artifacts?artifactName=Code%20Coverage%20Report_99174&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2788](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=99173&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/99173/artifacts?artifactName=Code%20Coverage%20Report_99173&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/ad57f5cdba0453dad63376bd5a9700181f8705f2) | #2788       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `72%`      | `72%`       |  `0%` :heavy_check_mark:  |
| Branches %| `70%`      | `70%`       |  `0%` :heavy_check_mark:  |
| Complexity| `13134`      | `13133`       |  `-1` :heavy_check_mark:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Ci.GitInfo](https://github.com/DataDog/dd-trace-dotnet/tree/39307f5e4068c01fc82443bbe2600bf9a2d46ea0/tracer/src/Datadog.Trace/Ci/GitInfo.cs) | `-17%` :no_entry: | `-11%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Ci.Processors.OriginTagTraceProcessor](https://github.com/DataDog/dd-trace-dotnet/tree/39307f5e4068c01fc82443bbe2600bf9a2d46ea0/tracer/src/Datadog.Trace/Ci/Processors/OriginTagTraceProcessor.cs) | `-9%` :no_entry: | `-17%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Agent.Transports.SocketHandlerRequestFactory](https://github.com/DataDog/dd-trace-dotnet/tree/39307f5e4068c01fc82443bbe2600bf9a2d46ea0/tracer/src/Datadog.Trace/Agent/Transports/SocketHandlerRequestFactory.cs) | `7%` :heavy_check_mark: | `0%` :heavy_check_mark:   | `-1` :heavy_check_mark: |
| [Datadog.Trace.Ci.CIVisibility](https://github.com/DataDog/dd-trace-dotnet/tree/39307f5e4068c01fc82443bbe2600bf9a2d46ea0/tracer/src/Datadog.Trace/Ci/CIVisibility.cs) | `7%` :heavy_check_mark: | `7%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Telemetry.JsonHttpClientTelemetryTransport](https://github.com/DataDog/dd-trace-dotnet/tree/39307f5e4068c01fc82443bbe2600bf9a2d46ea0/tracer/src/Datadog.Trace/Telemetry/Transports/JsonHttpClientTelemetryTransport.cs) | `26%` :heavy_check_mark: | `38%` :heavy_check_mark:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=99174&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/99174/artifacts?artifactName=Code%20Coverage%20Report_99174&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2788](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=99173&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/99173/artifacts?artifactName=Code%20Coverage%20Report_99173&api-version=6.0&%24format=zip)

**Pull request merged**
