### PR TITLE
Robert/release/1.x v next

### PR DESCRIPTION
**Pull request by robertpi**
Fixes #

Changes proposed in this pull request:

@DataDog/apm-dotnet

### CODE REVIEW

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:no_entry: Merging #2102 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/d96e262a76966d87848d70d5180edfdef7170a46) will will **decrease** line coverage by `5%`
:heavy_check_mark: Merging #2102 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/d96e262a76966d87848d70d5180edfdef7170a46) will **not change** branch coverage
:no_entry: Merging #2102 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/d96e262a76966d87848d70d5180edfdef7170a46) will will **increase** complexity by `904`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/d96e262a76966d87848d70d5180edfdef7170a46) | #2102       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `8912` / `12391` | `10329` / `15506` |          |
| Lines %   | `72%`      | `67%`      |  `-5%` :no_entry:  |
| Branches  | `3973` / `5979` | `4511` / `6830` |          |
| Branches %| `66%`      | `66%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `7109`      | `8013`        |  `904`  :no_entry:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=82539&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/82539/artifacts?artifactName=Code%20Coverage%20Report_82539&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2102](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=82565&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/82565/artifacts?artifactName=Code%20Coverage%20Report_82565&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :no_entry:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/d96e262a76966d87848d70d5180edfdef7170a46) | #2102       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `72%`      | `67%`       |  `-5%` :no_entry:  |
| Branches %| `66%`      | `66%`       |  `0%` :heavy_check_mark:  |
| Complexity| `7109`      | `8013`       |  `904` :no_entry:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Logging.ILogger.LoggerIntegrationCommon](https://github.com/DataDog/dd-trace-dotnet/tree/b04d131974b446fd50c0e79515f6142121d1371e/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Logging/ILogger/LoggerIntegrationCommon.cs) | `-10%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.DuckTyping.DuckTypeExtensions](https://github.com/DataDog/dd-trace-dotnet/tree/b04d131974b446fd50c0e79515f6142121d1371e/tracer/src/Datadog.Trace/DuckTyping/DuckTypeExtensions.cs) | `-9%` :no_entry: | `-15%` :no_entry:   | `22` :no_entry: |
| [Datadog.Trace.ClrProfiler.CallTarget.Handlers.BeginMethodHandler`10](https://github.com/DataDog/dd-trace-dotnet/tree/b04d131974b446fd50c0e79515f6142121d1371e/tracer/src/Datadog.Trace/ClrProfiler/CallTarget/Handlers/BeginMethodHandler`8.cs) | `-9%` :no_entry: | `20%` :heavy_check_mark:   | `-16` :heavy_check_mark: |
| [Datadog.Trace.Util.Http.HttpRequestExtensions](https://github.com/DataDog/dd-trace-dotnet/tree/b04d131974b446fd50c0e79515f6142121d1371e/tracer/src/Datadog.Trace/Util/Http/HttpRequestExtensions.Core.cs) | `-8%` :no_entry: | `-18%` :no_entry:   | `9` :no_entry: |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Testing.NUnit.NUnitCompositeWorkItemSkipChildrenIntegration](https://github.com/DataDog/dd-trace-dotnet/tree/b04d131974b446fd50c0e79515f6142121d1371e/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Testing/NUnit/NUnitCompositeWorkItemSkipChildrenIntegration.cs) | `-8%` :no_entry: | `-8%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Util.UriHelpers](https://github.com/DataDog/dd-trace-dotnet/tree/b04d131974b446fd50c0e79515f6142121d1371e/tracer/src/Datadog.Trace/Util/UriHelpers.cs) | `-8%` :no_entry: | `-5%` :no_entry:   | `4` :no_entry: |
| [Datadog.Trace.ClrProfiler.CallTarget.Handlers.BeginMethodHandler`8](https://github.com/DataDog/dd-trace-dotnet/tree/b04d131974b446fd50c0e79515f6142121d1371e/tracer/src/Datadog.Trace/ClrProfiler/CallTarget/Handlers/BeginMethodHandler`6.cs) | `-8%` :no_entry: | `19%` :heavy_check_mark:   | `-12` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.CallTarget.Handlers.BeginMethodHandler`9](https://github.com/DataDog/dd-trace-dotnet/tree/b04d131974b446fd50c0e79515f6142121d1371e/tracer/src/Datadog.Trace/ClrProfiler/CallTarget/Handlers/BeginMethodHandler`7.cs) | `-8%` :no_entry: | `19%` :heavy_check_mark:   | `-14` :heavy_check_mark: |
| [Datadog.Trace.DiagnosticListeners.DiagnosticObserver](https://github.com/DataDog/dd-trace-dotnet/tree/b04d131974b446fd50c0e79515f6142121d1371e/tracer/src/Datadog.Trace/DiagnosticListeners/DiagnosticObserver.cs) | `-7%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.ClrProfiler.CallTarget.Handlers.BeginMethodHandler`7](https://github.com/DataDog/dd-trace-dotnet/tree/b04d131974b446fd50c0e79515f6142121d1371e/tracer/src/Datadog.Trace/ClrProfiler/CallTarget/Handlers/BeginMethodHandler`5.cs) | `-7%` :no_entry: | `18%` :heavy_check_mark:   | `-10` :heavy_check_mark: |
| ...And 29 more  | | | |


The following classes were added in #2102:

| File    | Line coverage | Branch coverage | Complexity |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.AppSec.Waf.WafHandle](https://github.com/DataDog/dd-trace-dotnet/pull/2102/files) | `23%` | `0%` | `6` |
| [Datadog.Trace.AsyncLocalCompat\`1](https://github.com/DataDog/dd-trace-dotnet/pull/2102/files) | `100%` | `100%` | `8` |
| [Datadog.Trace.Ci.CITracer](https://github.com/DataDog/dd-trace-dotnet/pull/2102/files) | `100%` | `100%` | `1` |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.AWS.AwsConstants](https://github.com/DataDog/dd-trace-dotnet/pull/2102/files) | `0%` | `100%` | `1` |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.Elasticsearch.V5.ElasticsearchV5Constants](https://github.com/DataDog/dd-trace-dotnet/pull/2102/files) | `100%` | `100%` | `1` |
| ...And 69 more  | | | |


48 classes were removed from Datadog.Trace in #2102


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=82539&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/82539/artifacts?artifactName=Code%20Coverage%20Report_82539&api-version=6.0&%24format=zip)  
* [HTML report for this PR #2102](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=82565&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/82565/artifacts?artifactName=Code%20Coverage%20Report_82565&api-version=6.0&%24format=zip)

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #2102 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752): 
* 2 benchmarks are **slower**, with geometric mean 6.600
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`WriteAndFlushEnrichedTraces`|net472|918.0&nbsp;μs|13.63&nbsp;μs|12.75&nbsp;μs|0.0000| 0.0000|0.0000|3.09&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|743.7&nbsp;μs|12.34&nbsp;μs|11.54&nbsp;μs|0.0000| 0.0000|0.0000|2.51&nbsp;KB|
|#2102|`WriteAndFlushEnrichedTraces`|net472|917.8&nbsp;μs|13.17&nbsp;μs|11.67&nbsp;μs|0.0000| 0.0000|0.0000|3.1&nbsp;KB|
|#2102|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|726.6&nbsp;μs|13.39&nbsp;μs|12.53&nbsp;μs|0.0000| 0.0000|0.0000|2.51&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`SendRequest`|net472|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000| 0.0000|0.0000|0&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`SendRequest`|netcoreapp3.1|283,227.9152&nbsp;ns|5,654.4741&nbsp;ns|6,944.2020&nbsp;ns|0.1433| 0.0000|0.0000|19616&nbsp;B|
|#2102|`SendRequest`|net472|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000&nbsp;ns|0.0000| 0.0000|0.0000|0&nbsp;B|
|#2102|`SendRequest`|netcoreapp3.1|297,316.9995&nbsp;ns|5,065.6179&nbsp;ns|4,490.5383&nbsp;ns|0.1450| 0.0000|0.0000|19833&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #2102

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.DbCommandBenchmark.ExecuteNonQuery&#8209;net472 | 6.659 | 326.33 | 2,172.90 | 
| Benchmarks.Trace.DbCommandBenchmark.ExecuteNonQuery&#8209;netcoreapp3.1 | 6.541 | 287.72 | 1,882.02 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`ExecuteNonQuery`|net472|327.2&nbsp;ns|6.32&nbsp;ns|7.53&nbsp;ns|0.0000| 0.0000|0.0000|0&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`ExecuteNonQuery`|netcoreapp3.1|289.8&nbsp;ns|5.39&nbsp;ns|5.04&nbsp;ns|0.0000| 0.0000|0.0000|0&nbsp;B|
|#2102|`ExecuteNonQuery`|net472|2.181&nbsp;μs|0.0431&nbsp;μs|0.0631&nbsp;μs|0.1076| 0.0011|0.0000|682&nbsp;B|
|#2102|`ExecuteNonQuery`|netcoreapp3.1|1.888&nbsp;μs|0.0363&nbsp;μs|0.0303&nbsp;μs|0.0094| 0.0000|0.0000|712&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`CallElasticsearch`|net472|3.128&nbsp;μs|0.0612&nbsp;μs|0.0705&nbsp;μs|0.1282| 0.0000|0.0000|827&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`CallElasticsearch`|netcoreapp3.1|1.557&nbsp;μs|0.0306&nbsp;μs|0.0314&nbsp;μs|0.0107| 0.0000|0.0000|768&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`CallElasticsearchAsync`|net472|3.275&nbsp;μs|0.0485&nbsp;μs|0.0430&nbsp;μs|0.1496| 0.0000|0.0000|963&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`CallElasticsearchAsync`|netcoreapp3.1|1.625&nbsp;μs|0.0168&nbsp;μs|0.0157&nbsp;μs|0.0122| 0.0000|0.0000|888&nbsp;B|
|#2102|`CallElasticsearch`|net472|3.037&nbsp;μs|0.0589&nbsp;μs|0.0604&nbsp;μs|0.1277| 0.0000|0.0000|827&nbsp;B|
|#2102|`CallElasticsearch`|netcoreapp3.1|1.651&nbsp;μs|0.0209&nbsp;μs|0.0185&nbsp;μs|0.0105| 0.0000|0.0000|768&nbsp;B|
|#2102|`CallElasticsearchAsync`|net472|3.452&nbsp;μs|0.0682&nbsp;μs|0.0955&nbsp;μs|0.1490| 0.0000|0.0000|963&nbsp;B|
|#2102|`CallElasticsearchAsync`|netcoreapp3.1|1.640&nbsp;μs|0.0322&nbsp;μs|0.0419&nbsp;μs|0.0126| 0.0000|0.0000|888&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`ExecuteAsync`|net472|3.302&nbsp;μs|0.0464&nbsp;μs|0.0411&nbsp;μs|0.1681| 0.0000|0.0000|1083&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`ExecuteAsync`|netcoreapp3.1|1.911&nbsp;μs|0.0366&nbsp;μs|0.0375&nbsp;μs|0.0143| 0.0000|0.0000|1008&nbsp;B|
|#2102|`ExecuteAsync`|net472|3.448&nbsp;μs|0.0680&nbsp;μs|0.0783&nbsp;μs|0.1686| 0.0000|0.0000|1083&nbsp;B|
|#2102|`ExecuteAsync`|netcoreapp3.1|1.866&nbsp;μs|0.0352&nbsp;μs|0.0329&nbsp;μs|0.0140| 0.0000|0.0000|1008&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`SendAsync`|net472|6.087&nbsp;μs|0.0655&nbsp;μs|0.0613&nbsp;μs|0.3507| 0.0000|0.0000|2.19&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`SendAsync`|netcoreapp3.1|4.278&nbsp;μs|0.0496&nbsp;μs|0.0464&nbsp;μs|0.0297| 0.0000|0.0000|2.09&nbsp;KB|
|#2102|`SendAsync`|net472|5.961&nbsp;μs|0.0891&nbsp;μs|0.0744&nbsp;μs|0.3493| 0.0000|0.0000|2.19&nbsp;KB|
|#2102|`SendAsync`|netcoreapp3.1|4.225&nbsp;μs|0.0318&nbsp;μs|0.0266&nbsp;μs|0.0301| 0.0000|0.0000|2.09&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`EnrichedLog`|net472|3.831&nbsp;μs|0.0698&nbsp;μs|0.0653&nbsp;μs|0.2872| 0.0000|0.0000|1.79&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`EnrichedLog`|netcoreapp3.1|3.931&nbsp;μs|0.0783&nbsp;μs|0.1371&nbsp;μs|0.0278| 0.0000|0.0000|1.94&nbsp;KB|
|#2102|`EnrichedLog`|net472|3.819&nbsp;μs|0.0759&nbsp;μs|0.0634&nbsp;μs|0.2870| 0.0000|0.0000|1.79&nbsp;KB|
|#2102|`EnrichedLog`|netcoreapp3.1|3.608&nbsp;μs|0.0366&nbsp;μs|0.0325&nbsp;μs|0.0270| 0.0000|0.0000|1.94&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`EnrichedLog`|net472|179.9&nbsp;μs|3.47&nbsp;μs|4.98&nbsp;μs|0.7003| 0.2626|0.0000|5.23&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`EnrichedLog`|netcoreapp3.1|149.5&nbsp;μs|2.32&nbsp;μs|2.17&nbsp;μs|0.0000| 0.0000|0.0000|5.05&nbsp;KB|
|#2102|`EnrichedLog`|net472|173.0&nbsp;μs|3.06&nbsp;μs|2.86&nbsp;μs|0.6935| 0.2601|0.0000|5.23&nbsp;KB|
|#2102|`EnrichedLog`|netcoreapp3.1|144.5&nbsp;μs|2.74&nbsp;μs|2.29&nbsp;μs|0.0000| 0.0000|0.0000|5.05&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`EnrichedLog`|net472|11.362&nbsp;μs|0.1608&nbsp;μs|0.1504&nbsp;μs|0.8558| 0.0000|0.0000|5.31&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`EnrichedLog`|netcoreapp3.1|9.828&nbsp;μs|0.1218&nbsp;μs|0.1079&nbsp;μs|0.0867| 0.0000|0.0000|6.28&nbsp;KB|
|#2102|`EnrichedLog`|net472|11.65&nbsp;μs|0.179&nbsp;μs|0.159&nbsp;μs|0.8559| 0.0000|0.0000|5.31&nbsp;KB|
|#2102|`EnrichedLog`|netcoreapp3.1|10.40&nbsp;μs|0.203&nbsp;μs|0.234&nbsp;μs|0.0874| 0.0000|0.0000|6.28&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`SendReceive`|net472|2.172&nbsp;μs|0.0314&nbsp;μs|0.0245&nbsp;μs|0.1547| 0.0000|0.0000|987&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`SendReceive`|netcoreapp3.1|1.914&nbsp;μs|0.0260&nbsp;μs|0.0243&nbsp;μs|0.0135| 0.0000|0.0000|984&nbsp;B|
|#2102|`SendReceive`|net472|2.118&nbsp;μs|0.0383&nbsp;μs|0.0393&nbsp;μs|0.1550| 0.0000|0.0000|987&nbsp;B|
|#2102|`SendReceive`|netcoreapp3.1|2.123&nbsp;μs|0.0416&nbsp;μs|0.0584&nbsp;μs|0.0130| 0.0000|0.0000|984&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`EnrichedLog`|net472|7.795&nbsp;μs|0.1529&nbsp;μs|0.1431&nbsp;μs|0.4488| 0.0000|0.0000|2.8&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`EnrichedLog`|netcoreapp3.1|7.280&nbsp;μs|0.1004&nbsp;μs|0.0939&nbsp;μs|0.0358| 0.0000|0.0000|2.61&nbsp;KB|
|#2102|`EnrichedLog`|net472|7.760&nbsp;μs|0.1520&nbsp;μs|0.2780&nbsp;μs|0.4478| 0.0000|0.0000|2.8&nbsp;KB|
|#2102|`EnrichedLog`|netcoreapp3.1|7.177&nbsp;μs|0.1351&nbsp;μs|0.1263&nbsp;μs|0.0358| 0.0000|0.0000|2.61&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean |    Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`StartFinishSpan`|net472|901.7&nbsp;ns|17.81&nbsp;ns|21.21&nbsp;ns|0.0679| 0.0000|0.0000|433&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`StartFinishSpan`|netcoreapp3.1|868.6&nbsp;ns|14.92&nbsp;ns|13.96&nbsp;ns|0.0060| 0.0000|0.0000|432&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`StartFinishScope`|net472|1,076.3&nbsp;ns|15.14&nbsp;ns|14.16&nbsp;ns|0.0805| 0.0000|0.0000|514&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/5696ae14dfba604c3ab8dee66a318361d8bc9752)|`StartFinishScope`|netcoreapp3.1|1,019.6&nbsp;ns|19.81&nbsp;ns|18.53&nbsp;ns|0.0076| 0.0000|0.0000|552&nbsp;B|
|#2102|`StartFinishSpan`|net472|901.2&nbsp;ns|17.06&nbsp;ns|18.26&nbsp;ns|0.0679| 0.0000|0.0000|433&nbsp;B|
|#2102|`StartFinishSpan`|netcoreapp3.1|862.7&nbsp;ns|11.89&nbsp;ns|11.12&nbsp;ns|0.0059| 0.0000|0.0000|432&nbsp;B|
|#2102|`StartFinishScope`|net472|1,059.1&nbsp;ns|21.03&nbsp;ns|20.66&nbsp;ns|0.0804| 0.0000|0.0000|514&nbsp;B|
|#2102|`StartFinishScope`|netcoreapp3.1|1,027.8&nbsp;ns|17.60&nbsp;ns|16.46&nbsp;ns|0.0076| 0.0000|0.0000|552&nbsp;B|
</details>

**Review by pierotibou — APPROVED** [review]
Approved but It's more a blind review than a real one :)
Are all those commits that are in master already, thus already reviewed?

**Comment by robertpi** [comment]
Yes, all the changes are in master, therefore already reviewed. I guess the release/1.x still requires approval because someone might want to release a change on 1.x that wasn't already in master.

As this isn't the case for this PR, I'm going to go ahead and merge it with one approval, rather waiting for the customary two.

**Pull request merged**
