### PR TITLE
Change MaxVersion to MaxVersionInclusive in the NuGetPackageHelper tool

### PR DESCRIPTION
**Pull request by zacharycmontoya**

### CODE REVIEW

**Comment by lucaspimentel** [comment]
With this change, when a new (minor) version of a NuGet package is released, will we test it automatically? Did we do that before this change?

I think we want to test newer version as they get released without having to update the JSON file.

**Comment by zacharycmontoya** [comment]
Neither before/after will automatically test new versions.

*Before* has the advantage that we can just run the GeneratePackageVersions without updating the JSON file and we can pull down the latest minor updates for testing.

I think that is the better approach here...I will just modify the schema to indicate that the version is MaxExclusive.

**Comment by zacharycmontoya** [comment]
Another thought, what do you think of adding a new boolean field to the JSON schema that says whether or not the max version is inclusive? For instance, `MaxVersionIsInclusive`

**Comment by lucaspimentel** [comment]
I would be fine with reverting these changes and instead renaming the property to `MaxVersionExclusive` to avoid confusion.

Another option (that requires more refactoring) is to use a single field with [NuGet's own versioning notation](https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards), e.g. `[1.0,2.0)`. See https://www.nuget.org/packages/NuGet.Versioning/

Aside from that, we should think about how we want to run `GeneratePackageVersions` in CI to automatically include newer NuGet package versions.

**Pull request merged**
