### PR TITLE
[IAST] Update evidence redaction suite . yml and fixes accordingly

### PR DESCRIPTION
**Pull request by anna-git**
## Summary of changes

Update to the new test file: https://github.com/DataDog/experimental/blob/malvarez/iast-redaction-test-suite/teams/asm/iast/redaction/suite/evidence-redaction-suite.yml

Adapt regex for Oracle, Command tokenizer.
Map Unvalidated redirect vulnerability to Url tokenizer

## Reason for change

New tests and file and [RFC](https://docs.google.com/document/d/1eHfZuCQJbPb1VvERdbhRXZhH7PHVlGoAP2-LNKfFNFI/edit#heading=h.lq3n19z70wbp)

## Test coverage

Same tests should now pass

### CODE REVIEW

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #4205 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/3488e611564fd9819e18f6aae885a34151bee05f): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details

**Comment by andrewlock** [comment]
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (4205)](https://github.com/DataDog/dd-trace-dotnet/tree/10c10c49d3941c0a28e612ea461ec2bda52fb167)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/3488e611564fd9819e18f6aae885a34151bee05f)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (3,020ms)  : 2929, 3112
     .   : milestone, 3020,
    master - mean (3,013ms)  : 2917, 3110
     .   : milestone, 3013,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (3,764ms)  : 3671, 3856
     .   : milestone, 3764,
    master - mean (3,763ms)  : 3660, 3865
     .   : milestone, 3763,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (3,142ms)  : 3050, 3234
     .   : milestone, 3142,
    master - mean (3,122ms)  : 2966, 3277
     .   : milestone, 3122,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (3,616ms)  : 3537, 3696
     .   : milestone, 3616,
    master - mean (3,595ms)  : 3517, 3674
     .   : milestone, 3595,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (3,128ms)  : 2983, 3273
     .   : milestone, 3128,
    master - mean (3,129ms)  : 2983, 3275
     .   : milestone, 3129,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (3,575ms)  : 3491, 3659
     .   : milestone, 3575,
    master - mean (3,578ms)  : 3496, 3661
     .   : milestone, 3578,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (191ms)  : 181, 200
     .   : milestone, 191,
    master - mean (189ms)  : 184, 194
     .   : milestone, 189,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (1,116ms)  : crit, 1083, 1150
     .   : crit, milestone, 1116,
    master - mean (1,038ms)  : 1008, 1069
     .   : milestone, 1038,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (382ms)  : 364, 399
     .   : milestone, 382,
    master - mean (356ms)  : 352, 360
     .   : milestone, 356,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (1,368ms)  : crit, 1312, 1425
     .   : crit, milestone, 1368,
    master - mean (1,099ms)  : 1069, 1129
     .   : milestone, 1099,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    master - mean (368ms)  : 363, 374
     .   : milestone, 368,

    section CallTarget+Inlining+NGEN
    master - mean (1,135ms)  : 1110, 1160
     .   : milestone, 1135,

```

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #4205 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/b1c5f9c4c8da986685d4a391929cc4f699b27a1a): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details

**Comment by andrewlock** [comment]
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (4205)](https://github.com/DataDog/dd-trace-dotnet/tree/0ea91c9984156b76dd3113e9848691d12091eb43)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/b1c5f9c4c8da986685d4a391929cc4f699b27a1a)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (3,038ms)  : 2931, 3145
     .   : milestone, 3038,
    master - mean (3,013ms)  : 2923, 3102
     .   : milestone, 3013,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (3,759ms)  : 3687, 3830
     .   : milestone, 3759,
    master - mean (3,772ms)  : 3684, 3861
     .   : milestone, 3772,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (3,171ms)  : 3042, 3301
     .   : milestone, 3171,
    master - mean (3,141ms)  : 3008, 3275
     .   : milestone, 3141,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (3,610ms)  : 3534, 3685
     .   : milestone, 3610,
    master - mean (3,607ms)  : 3519, 3695
     .   : milestone, 3607,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (3,104ms)  : 2987, 3221
     .   : milestone, 3104,
    master - mean (3,122ms)  : 2974, 3271
     .   : milestone, 3122,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (3,582ms)  : 3510, 3653
     .   : milestone, 3582,
    master - mean (3,586ms)  : 3513, 3658
     .   : milestone, 3586,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (188ms)  : 184, 192
     .   : milestone, 188,
    master - mean (189ms)  : 185, 193
     .   : milestone, 189,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (1,026ms)  : 946, 1106
     .   : milestone, 1026,
    master - mean (1,032ms)  : 988, 1075
     .   : milestone, 1032,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (368ms)  : 364, 373
     .   : milestone, 368,
    master - mean (369ms)  : 363, 375
     .   : milestone, 369,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (1,136ms)  : 1107, 1166
     .   : milestone, 1136,
    master - mean (1,135ms)  : 1110, 1160
     .   : milestone, 1135,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (356ms)  : 350, 362
     .   : milestone, 356,
    master - mean (357ms)  : 351, 363
     .   : milestone, 357,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (1,100ms)  : 1072, 1128
     .   : milestone, 1100,
    master - mean (1,100ms)  : 1069, 1131
     .   : milestone, 1100,

```

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #4205 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/b1c5f9c4c8da986685d4a391929cc4f699b27a1a): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details

**Comment by andrewlock** [comment]
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (4205)](https://github.com/DataDog/dd-trace-dotnet/tree/ac9eacaf204574bf6207475ece9357c28796d001)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/b1c5f9c4c8da986685d4a391929cc4f699b27a1a)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (3,036ms)  : 2905, 3167
     .   : milestone, 3036,
    master - mean (3,013ms)  : 2923, 3102
     .   : milestone, 3013,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (3,763ms)  : 3675, 3851
     .   : milestone, 3763,
    master - mean (3,772ms)  : 3684, 3861
     .   : milestone, 3772,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (3,162ms)  : 3030, 3293
     .   : milestone, 3162,
    master - mean (3,141ms)  : 3008, 3275
     .   : milestone, 3141,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (3,616ms)  : 3537, 3696
     .   : milestone, 3616,
    master - mean (3,607ms)  : 3519, 3695
     .   : milestone, 3607,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (3,156ms)  : 3051, 3261
     .   : milestone, 3156,
    master - mean (3,122ms)  : 2974, 3271
     .   : milestone, 3122,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (3,583ms)  : 3531, 3635
     .   : milestone, 3583,
    master - mean (3,586ms)  : 3513, 3658
     .   : milestone, 3586,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (188ms)  : 183, 193
     .   : milestone, 188,
    master - mean (189ms)  : 185, 193
     .   : milestone, 189,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (1,022ms)  : 959, 1085
     .   : milestone, 1022,
    master - mean (1,032ms)  : 988, 1075
     .   : milestone, 1032,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (366ms)  : 363, 369
     .   : milestone, 366,
    master - mean (369ms)  : 363, 375
     .   : milestone, 369,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (1,137ms)  : 1105, 1170
     .   : milestone, 1137,
    master - mean (1,135ms)  : 1110, 1160
     .   : milestone, 1135,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4205) - mean (356ms)  : 351, 361
     .   : milestone, 356,
    master - mean (357ms)  : 351, 363
     .   : milestone, 357,

    section CallTarget+Inlining+NGEN
    This PR (4205) - mean (1,097ms)  : 1068, 1126
     .   : milestone, 1097,
    master - mean (1,100ms)  : 1069, 1131
     .   : milestone, 1100,

```

**Comment by andrewlock** [comment]
## Throughput/Crank Report:zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (4205)](https://github.com/DataDog/dd-trace-dotnet/tree/ac9eacaf204574bf6207475ece9357c28796d001)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/b1048f9a0acbced1d06850e14d2669228a029626)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/0d56b1d9f25673f5257b1b7df97a3754d2df63f4)
- [benchmarks/2.31.0](https://github.com/DataDog/dd-trace-dotnet/tree/5a0f7f5a6023b3b0761baa6b1bcd53b8f3af5655)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4205) (11.217M)   : 0, 11217254
    master (11.129M)   : 0, 11129079
    benchmarks/2.31.0 (11.338M)   : 0, 11338235
    benchmarks/2.9.0 (11.162M)   : 0, 11161538

    section Automatic
    This PR (4205) (8.014M)   : 0, 8014182
    master (7.818M)   : 0, 7817888
    benchmarks/2.31.0 (7.431M)   : 0, 7431225
    benchmarks/2.9.0 (8.099M)   : 0, 8099075

    section Trace stats
    master (7.759M)   : 0, 7759000
    benchmarks/2.31.0 (7.663M)   : 0, 7663176

    section Manual
    This PR (4205) (9.693M)   : 0, 9692618
    master (9.838M)   : 0, 9837746
    benchmarks/2.31.0 (7.351M)   : 0, 7350869

    section Manual + Automatic
    This PR (4205) (7.367M)   : 0, 7367083
    master (7.488M)   : 0, 7487977
    benchmarks/2.31.0 (5.741M)   : 0, 5741089

    section Version Conflict
    master (6.641M)   : 0, 6640970
    benchmarks/2.31.0 (6.913M)   : 0, 6913078

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4205) (9.626M)   : 0, 9626384
    master (9.538M)   : 0, 9538088
    benchmarks/2.31.0 (9.679M)   : 0, 9678682
    benchmarks/2.9.0 (9.705M)   : 0, 9704781

    section Automatic
    This PR (4205) (6.933M)   : 0, 6932906
    master (6.870M)   : 0, 6869569
    benchmarks/2.31.0 (6.855M)   : 0, 6854574

    section Trace stats
    master (6.886M)   : 0, 6885885
    benchmarks/2.31.0 (6.924M)   : 0, 6924210

    section Manual
    This PR (4205) (8.435M)   : 0, 8435228
    master (8.672M)   : 0, 8672003
    benchmarks/2.31.0 (8.386M)   : 0, 8386139

    section Manual + Automatic
    This PR (4205) (6.785M)   : 0, 6785484
    master (6.622M)   : 0, 6621657
    benchmarks/2.31.0 (6.325M)   : 0, 6325089

    section Version Conflict
    master (5.839M)   : 0, 5839183
    benchmarks/2.31.0 (5.955M)   : 0, 5954718

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4205) (10.320M)   : 0, 10319806
    master (10.267M)   : 0, 10266995
    benchmarks/2.31.0 (10.320M)   : 0, 10319575
    benchmarks/2.9.0 (9.827M)   : 0, 9827121

    section Automatic
    This PR (4205) (7.507M)   : 0, 7507450
    master (7.490M)   : 0, 7489696
    benchmarks/2.31.0 (7.410M)   : 0, 7410117
    benchmarks/2.9.0 (7.246M)   : 0, 7246397

    section Trace stats
    master (7.404M)   : 0, 7403504
    benchmarks/2.31.0 (7.559M)   : 0, 7559264

    section Manual
    This PR (4205) (9.292M)   : 0, 9291989
    master (9.348M)   : 0, 9348295
    benchmarks/2.31.0 (9.387M)   : 0, 9386685

    section Manual + Automatic
    This PR (4205) (7.210M)   : 0, 7209500
    master (7.265M)   : 0, 7265026
    benchmarks/2.31.0 (7.176M)   : 0, 7175876

    section Version Conflict
    master (6.600M)   : 0, 6600296
    benchmarks/2.31.0 (6.446M)   : 0, 6446354

```
```mermaid
gantt
    title Throughput Linux x64 (ASM) (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4205) (7.501M)   : 0, 7500822
    master (7.485M)   : 0, 7485430
    benchmarks/2.31.0 (7.475M)   : 0, 7475399
    benchmarks/2.9.0 (7.748M)   : 0, 7748029

    section No attack
    This PR (4205) (2.409M)   : 0, 2409285
    master (2.423M)   : 0, 2422503
    benchmarks/2.31.0 (2.389M)   : 0, 2388686
    benchmarks/2.9.0 (3.274M)   : 0, 3273699

    section Attack
    This PR (4205) (2.043M)   : 0, 2043435
    master (2.044M)   : 0, 2043519
    benchmarks/2.31.0 (2.039M)   : 0, 2038865
    benchmarks/2.9.0 (2.598M)   : 0, 2597950

    section Blocking
    This PR (4205) (4.078M)   : 0, 4078116
    master (4.095M)   : 0, 4094566
    benchmarks/2.31.0 (4.079M)   : 0, 4079419

```

**Review by daniel-romano-DD — APPROVED** [review]
Great first contribution to IAST

**Pull request merged**
