### PR TITLE
[ASM] improve custom rules tests

### PR DESCRIPTION
**Pull request by robertpi**
## Summary of changes

Add another request to the custom rule tests

## Reason for change

Suggestion in https://github.com/DataDog/dd-trace-dotnet/pull/4077 that was forgotten.

### CODE REVIEW

**Comment by andrewlock** [comment]
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (4081)](https://github.com/DataDog/dd-trace-dotnet/tree/e81ef7ef6fe687eeaee4705d07bede0b869b2ca2)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/33364b247ffd1d5181b1abb726cef68ce75fd593)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4081) - mean (2,996ms)  : 2860, 3132
     .   : milestone, 2996,
    master - mean (3,046ms)  : 2960, 3131
     .   : milestone, 3046,

    section CallTarget+Inlining+NGEN
    This PR (4081) - mean (3,668ms)  : 3603, 3732
     .   : milestone, 3668,
    master - mean (3,664ms)  : 3614, 3714
     .   : milestone, 3664,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4081) - mean (3,122ms)  : 2999, 3244
     .   : milestone, 3122,
    master - mean (3,135ms)  : 3021, 3249
     .   : milestone, 3135,

    section CallTarget+Inlining+NGEN
    This PR (4081) - mean (3,539ms)  : 3452, 3625
     .   : milestone, 3539,
    master - mean (3,553ms)  : 3443, 3664
     .   : milestone, 3553,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4081) - mean (3,116ms)  : 2987, 3245
     .   : milestone, 3116,
    master - mean (3,100ms)  : 2968, 3232
     .   : milestone, 3100,

    section CallTarget+Inlining+NGEN
    This PR (4081) - mean (3,512ms)  : 3419, 3605
     .   : milestone, 3512,
    master - mean (3,512ms)  : 3435, 3589
     .   : milestone, 3512,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4081) - mean (187ms)  : 184, 191
     .   : milestone, 187,
    master - mean (188ms)  : 184, 192
     .   : milestone, 188,

    section CallTarget+Inlining+NGEN
    This PR (4081) - mean (947ms)  : 907, 987
     .   : milestone, 947,
    master - mean (947ms)  : 924, 970
     .   : milestone, 947,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4081) - mean (367ms)  : 363, 371
     .   : milestone, 367,
    master - mean (367ms)  : 360, 373
     .   : milestone, 367,

    section CallTarget+Inlining+NGEN
    This PR (4081) - mean (1,091ms)  : 1058, 1124
     .   : milestone, 1091,
    master - mean (1,086ms)  : 1062, 1110
     .   : milestone, 1086,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4081) - mean (356ms)  : 352, 360
     .   : milestone, 356,
    master - mean (356ms)  : 349, 364
     .   : milestone, 356,

    section CallTarget+Inlining+NGEN
    This PR (4081) - mean (1,035ms)  : 1007, 1063
     .   : milestone, 1035,
    master - mean (1,033ms)  : 1005, 1061
     .   : milestone, 1033,

```

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #4081 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/b1048f9a0acbced1d06850e14d2669228a029626): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details

**Comment by andrewlock** [comment]
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (4081)](https://github.com/DataDog/dd-trace-dotnet/tree/eaf3b4b52ac8b81879d1ead83d373ee7becbcea5)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/b1048f9a0acbced1d06850e14d2669228a029626)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4081) - mean (3,020ms)  : 2913, 3128
     .   : milestone, 3020,
    master - mean (3,009ms)  : 2894, 3124
     .   : milestone, 3009,

    section CallTarget+Inlining+NGEN
    This PR (4081) - mean (3,750ms)  : 3678, 3822
     .   : milestone, 3750,
    master - mean (3,763ms)  : 3654, 3873
     .   : milestone, 3763,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4081) - mean (3,164ms)  : 3060, 3268
     .   : milestone, 3164,
    master - mean (3,123ms)  : 2990, 3257
     .   : milestone, 3123,

    section CallTarget+Inlining+NGEN
    This PR (4081) - mean (3,596ms)  : 3549, 3644
     .   : milestone, 3596,
    master - mean (3,602ms)  : 3519, 3685
     .   : milestone, 3602,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4081) - mean (3,101ms)  : 2966, 3236
     .   : milestone, 3101,
    master - mean (3,127ms)  : 3026, 3229
     .   : milestone, 3127,

    section CallTarget+Inlining+NGEN
    This PR (4081) - mean (3,569ms)  : 3497, 3641
     .   : milestone, 3569,
    master - mean (3,580ms)  : 3493, 3667
     .   : milestone, 3580,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4081) - mean (187ms)  : 184, 189
     .   : milestone, 187,
    master - mean (188ms)  : 183, 193
     .   : milestone, 188,

    section CallTarget+Inlining+NGEN
    This PR (4081) - mean (1,039ms)  : 1005, 1073
     .   : milestone, 1039,
    master - mean (1,022ms)  : 943, 1101
     .   : milestone, 1022,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4081) - mean (368ms)  : 362, 373
     .   : milestone, 368,
    master - mean (368ms)  : 363, 374
     .   : milestone, 368,

    section CallTarget+Inlining+NGEN
    This PR (4081) - mean (1,134ms)  : 1104, 1164
     .   : milestone, 1134,
    master - mean (1,131ms)  : 1104, 1158
     .   : milestone, 1131,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4081) - mean (359ms)  : 351, 366
     .   : milestone, 359,
    master - mean (356ms)  : 351, 362
     .   : milestone, 356,

    section CallTarget+Inlining+NGEN
    This PR (4081) - mean (1,100ms)  : 1071, 1129
     .   : milestone, 1100,
    master - mean (1,096ms)  : 1077, 1114
     .   : milestone, 1096,

```

**Review by anna-git — APPROVED** [review]

**Comment by andrewlock** [comment]
## Throughput/Crank Report:zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (4081)](https://github.com/DataDog/dd-trace-dotnet/tree/eaf3b4b52ac8b81879d1ead83d373ee7becbcea5)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/b1048f9a0acbced1d06850e14d2669228a029626)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/0d56b1d9f25673f5257b1b7df97a3754d2df63f4)
- [benchmarks/2.31.0](https://github.com/DataDog/dd-trace-dotnet/tree/5a0f7f5a6023b3b0761baa6b1bcd53b8f3af5655)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4081) (10.953M)   : 0, 10952942
    master (11.048M)   : 0, 11047571
    benchmarks/2.31.0 (10.896M)   : 0, 10895796
    benchmarks/2.9.0 (11.162M)   : 0, 11161538

    section Automatic
    This PR (4081) (7.633M)   : 0, 7633108
    master (7.860M)   : 0, 7859614
    benchmarks/2.31.0 (7.738M)   : 0, 7738313
    benchmarks/2.9.0 (8.099M)   : 0, 8099075

    section Trace stats
    master (7.751M)   : 0, 7750523
    benchmarks/2.31.0 (7.787M)   : 0, 7787068

    section Manual
    This PR (4081) (9.712M)   : 0, 9712011
    master (9.904M)   : 0, 9903750
    benchmarks/2.31.0 (9.875M)   : 0, 9875109

    section Manual + Automatic
    This PR (4081) (7.228M)   : 0, 7228398
    master (7.402M)   : 0, 7402371
    benchmarks/2.31.0 (7.366M)   : 0, 7365538

    section Version Conflict
    master (6.717M)   : 0, 6717053
    benchmarks/2.31.0 (6.710M)   : 0, 6709883

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4081) (9.612M)   : 0, 9612139
    master (9.572M)   : 0, 9571503
    benchmarks/2.31.0 (9.814M)   : 0, 9813836
    benchmarks/2.9.0 (9.705M)   : 0, 9704781

    section Automatic
    This PR (4081) (6.916M)   : 0, 6916014
    master (6.532M)   : 0, 6531546
    benchmarks/2.31.0 (6.770M)   : 0, 6769990

    section Trace stats
    master (6.761M)   : 0, 6761162
    benchmarks/2.31.0 (6.939M)   : 0, 6939471

    section Manual
    This PR (4081) (8.579M)   : 0, 8578585
    master (8.660M)   : 0, 8660414
    benchmarks/2.31.0 (8.599M)   : 0, 8599301

    section Manual + Automatic
    This PR (4081) (6.661M)   : 0, 6661471
    master (6.653M)   : 0, 6652772
    benchmarks/2.31.0 (6.540M)   : 0, 6540185

    section Version Conflict
    master (5.972M)   : 0, 5971759
    benchmarks/2.31.0 (5.947M)   : 0, 5947078

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4081) (10.902M)   : 0, 10902337
    master (10.547M)   : 0, 10547441
    benchmarks/2.31.0 (10.769M)   : 0, 10768879
    benchmarks/2.9.0 (9.827M)   : 0, 9827121

    section Automatic
    This PR (4081) (7.870M)   : 0, 7869768
    master (7.684M)   : 0, 7684227
    benchmarks/2.31.0 (7.839M)   : 0, 7838964
    benchmarks/2.9.0 (7.246M)   : 0, 7246397

    section Trace stats
    master (7.691M)   : 0, 7690592
    benchmarks/2.31.0 (7.687M)   : 0, 7686748

    section Manual
    This PR (4081) (9.473M)   : 0, 9473231
    master (9.764M)   : 0, 9763782
    benchmarks/2.31.0 (9.763M)   : 0, 9763304

    section Manual + Automatic
    This PR (4081) (7.663M)   : 0, 7663040
    master (7.663M)   : 0, 7662672
    benchmarks/2.31.0 (7.415M)   : 0, 7414603

    section Version Conflict
    master (6.699M)   : 0, 6699287
    benchmarks/2.31.0 (6.700M)   : 0, 6699805

```
```mermaid
gantt
    title Throughput Linux x64 (ASM) (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4081) (7.505M)   : 0, 7504639
    master (7.571M)   : 0, 7570601
    benchmarks/2.31.0 (7.274M)   : 0, 7273901
    benchmarks/2.9.0 (7.748M)   : 0, 7748029

    section No attack
    This PR (4081) (2.414M)   : 0, 2413643
    master (2.389M)   : 0, 2389349
    benchmarks/2.31.0 (2.361M)   : 0, 2361219
    benchmarks/2.9.0 (3.274M)   : 0, 3273699

    section Attack
    This PR (4081) (2.038M)   : 0, 2038105
    master (2.053M)   : 0, 2053301
    benchmarks/2.31.0 (2.004M)   : 0, 2004410
    benchmarks/2.9.0 (2.598M)   : 0, 2597950

    section Blocking
    This PR (4081) (4.160M)   : 0, 4159704
    master (3.995M)   : 0, 3995030
    benchmarks/2.31.0 (3.972M)   : 0, 3971693

```

**Pull request closed without merging**
