### PR TITLE
remove useless param in SQL Server test

### PR DESCRIPTION
**Pull request by vandonr**
I think I got confused between DSM and DBM when I added that.
It's not playing any role in this test, it just has the effect that we're running the same tests twice.

### CODE REVIEW

**Review by andrewlock — COMMENTED** [review]
Was this not added to make sure that things didn't break when we enable DBM? 🤔

**Comment by andrewlock** [comment]
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (6162)](https://github.com/DataDog/dd-trace-dotnet/tree/30bfdfba0674b03256d5fb8e9fd63cad092581aa)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (6162) - mean (70ms)  : 68, 73
     .   : milestone, 70,
    master - mean (71ms)  : 67, 75
     .   : milestone, 71,

    section CallTarget+Inlining+NGEN
    This PR (6162) - mean (1,117ms)  : 1093, 1141
     .   : milestone, 1117,
    master - mean (1,118ms)  : 1097, 1138
     .   : milestone, 1118,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (6162) - mean (110ms)  : 106, 115
     .   : milestone, 110,
    master - mean (111ms)  : 107, 114
     .   : milestone, 111,

    section CallTarget+Inlining+NGEN
    This PR (6162) - mean (777ms)  : 759, 796
     .   : milestone, 777,
    master - mean (780ms)  : 766, 794
     .   : milestone, 780,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (6162) - mean (93ms)  : 90, 96
     .   : milestone, 93,
    master - mean (93ms)  : 90, 96
     .   : milestone, 93,

    section CallTarget+Inlining+NGEN
    This PR (6162) - mean (734ms)  : 717, 750
     .   : milestone, 734,
    master - mean (732ms)  : 719, 746
     .   : milestone, 732,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (6162) - mean (190ms)  : 186, 194
     .   : milestone, 190,
    master - mean (191ms)  : 187, 194
     .   : milestone, 191,

    section CallTarget+Inlining+NGEN
    This PR (6162) - mean (1,200ms)  : 1169, 1232
     .   : milestone, 1200,
    master - mean (1,196ms)  : 1168, 1223
     .   : milestone, 1196,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (6162) - mean (275ms)  : 272, 279
     .   : milestone, 275,
    master - mean (276ms)  : 270, 281
     .   : milestone, 276,

    section CallTarget+Inlining+NGEN
    This PR (6162) - mean (940ms)  : 918, 963
     .   : milestone, 940,
    master - mean (944ms)  : 921, 968
     .   : milestone, 944,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (6162) - mean (265ms)  : 260, 270
     .   : milestone, 265,
    master - mean (264ms)  : 261, 268
     .   : milestone, 264,

    section CallTarget+Inlining+NGEN
    This PR (6162) - mean (929ms)  : 911, 948
     .   : milestone, 929,
    master - mean (928ms)  : 909, 948
     .   : milestone, 928,

```

**Comment by vandonr** [comment]
> Was this not added to make sure that things didn't break when we enable DBM? 🤔

I just went over this with Steven, it says "DBM enabled" but the env variable we set is to enable DSM (which has nothing to do with DBs). There is no global flag for DBM, it's just whether you propagate or not.

**Review by bouwkast — APPROVED** [review]
Thanks!

**Comment by andrewlock** [comment]
## Benchmarks Report for tracer :snail:

Benchmarks for #6162 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043): 
* 1 benchmarks are **faster**, with geometric mean 1.186
* 1 benchmarks are **slower**, with geometric mean 1.173
* 1 benchmarks have **more** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.ActivityBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`StartStopWithChild`|net6.0|7.86μs|43.9ns|295ns|0.0117| 0.00391|0|5.43&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`StartStopWithChild`|netcoreapp3.1|10.1μs|55.6ns|319ns|0.0207| 0.00516|0|5.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`StartStopWithChild`|net472|16.8μs|44.7ns|173ns|1.01| 0.294|0.0898|6.07&nbsp;KB|
|#6162|`StartStopWithChild`|net6.0|7.8μs|43.7ns|293ns|0.0158| 0.00789|0|5.42&nbsp;KB|
|#6162|`StartStopWithChild`|netcoreapp3.1|10.1μs|56.3ns|356ns|0.0197| 0.00987|0|5.62&nbsp;KB|
|#6162|`StartStopWithChild`|net472|18μs|104ns|934ns|1.02| 0.308|0.0993|6.08&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`WriteAndFlushEnrichedTraces`|net6.0|481μs|718ns|2.78μs|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|629μs|219ns|818ns|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`WriteAndFlushEnrichedTraces`|net472|840μs|324ns|1.26μs|0.417| 0|0|3.3&nbsp;KB|
|#6162|`WriteAndFlushEnrichedTraces`|net6.0|478μs|292ns|1.09μs|0| 0|0|2.7&nbsp;KB|
|#6162|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|653μs|274ns|1.06μs|0| 0|0|2.7&nbsp;KB|
|#6162|`WriteAndFlushEnrichedTraces`|net472|835μs|464ns|1.74μs|0.419| 0|0|3.3&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`SendRequest`|net6.0|196μs|1.12μs|8.66μs|0.189| 0|0|18.45&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`SendRequest`|netcoreapp3.1|218μs|1.25μs|9.87μs|0.159| 0|0|20.61&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`SendRequest`|net472|5.49E&#8209;05ns|5.49E&#8209;05ns|0.000206ns|0| 0|0|0&nbsp;b|
|#6162|`SendRequest`|net6.0|196μs|1.12μs|8.05μs|0.182| 0|0|18.45&nbsp;KB|
|#6162|`SendRequest`|netcoreapp3.1|216μs|1.22μs|9.25μs|0.216| 0|0|20.61&nbsp;KB|
|#6162|`SendRequest`|net472|2.73E&#8209;05ns|2.73E&#8209;05ns|0.000102ns|0| 0|0|0&nbsp;b|
</details>


<details><summary><strong>Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark</strong> - Same speed :heavy_check_mark: More allocations :warning:



#### More allocations :warning: in #6162

|  Benchmark         | Base Allocated | Diff Allocated | Change   | Change % |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark.WriteAndFlushEnrichedTraces&#8209;net6.0 | 41.51 KB | 41.75 KB | 244 B | 0.59%

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`WriteAndFlushEnrichedTraces`|net6.0|572μs|2.89μs|13.6μs|0.534| 0|0|41.51&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|672μs|2.89μs|11.9μs|0.343| 0|0|41.76&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`WriteAndFlushEnrichedTraces`|net472|881μs|4.09μs|16.3μs|8.3| 2.62|0.437|53.36&nbsp;KB|
|#6162|`WriteAndFlushEnrichedTraces`|net6.0|576μs|1.84μs|6.89μs|0.576| 0|0|41.75&nbsp;KB|
|#6162|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|676μs|3.2μs|12.8μs|0.334| 0|0|41.75&nbsp;KB|
|#6162|`WriteAndFlushEnrichedTraces`|net472|870μs|3.15μs|11.8μs|8.3| 2.62|0.437|53.35&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`ExecuteNonQuery`|net6.0|1.32μs|1.5ns|5.81ns|0.0139| 0|0|1.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`ExecuteNonQuery`|netcoreapp3.1|1.76μs|0.682ns|2.64ns|0.0134| 0|0|1.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`ExecuteNonQuery`|net472|2.08μs|1.73ns|6.71ns|0.156| 0|0|987&nbsp;B|
|#6162|`ExecuteNonQuery`|net6.0|1.35μs|1.11ns|4.16ns|0.0142| 0|0|1.02&nbsp;KB|
|#6162|`ExecuteNonQuery`|netcoreapp3.1|1.71μs|1.25ns|4.51ns|0.0138| 0|0|1.02&nbsp;KB|
|#6162|`ExecuteNonQuery`|net472|2.05μs|1.57ns|6.1ns|0.156| 0|0|987&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`CallElasticsearch`|net6.0|1.25μs|2.43ns|9.4ns|0.0138| 0|0|976&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`CallElasticsearch`|netcoreapp3.1|1.58μs|0.764ns|2.96ns|0.0134| 0|0|976&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`CallElasticsearch`|net472|2.33μs|1.55ns|6.02ns|0.157| 0|0|995&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`CallElasticsearchAsync`|net6.0|1.31μs|0.719ns|2.69ns|0.0131| 0|0|952&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`CallElasticsearchAsync`|netcoreapp3.1|1.67μs|0.932ns|3.49ns|0.0133| 0|0|1.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`CallElasticsearchAsync`|net472|2.67μs|1.67ns|6.48ns|0.166| 0|0|1.05&nbsp;KB|
|#6162|`CallElasticsearch`|net6.0|1.21μs|0.604ns|2.34ns|0.0133| 0|0|976&nbsp;B|
|#6162|`CallElasticsearch`|netcoreapp3.1|1.59μs|2.25ns|8.43ns|0.013| 0|0|976&nbsp;B|
|#6162|`CallElasticsearch`|net472|2.36μs|0.967ns|3.62ns|0.158| 0|0|995&nbsp;B|
|#6162|`CallElasticsearchAsync`|net6.0|1.31μs|0.919ns|3.56ns|0.0137| 0|0|952&nbsp;B|
|#6162|`CallElasticsearchAsync`|netcoreapp3.1|1.62μs|0.563ns|2.11ns|0.0136| 0|0|1.02&nbsp;KB|
|#6162|`CallElasticsearchAsync`|net472|2.53μs|1.68ns|6.52ns|0.167| 0|0|1.05&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`ExecuteAsync`|net6.0|1.27μs|0.379ns|1.47ns|0.0133| 0|0|952&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`ExecuteAsync`|netcoreapp3.1|1.6μs|0.893ns|3.34ns|0.0125| 0|0|952&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`ExecuteAsync`|net472|1.85μs|1.54ns|5.95ns|0.145| 0|0|915&nbsp;B|
|#6162|`ExecuteAsync`|net6.0|1.36μs|0.64ns|2.48ns|0.0129| 0|0|952&nbsp;B|
|#6162|`ExecuteAsync`|netcoreapp3.1|1.6μs|0.816ns|3.16ns|0.0128| 0|0|952&nbsp;B|
|#6162|`ExecuteAsync`|net472|1.84μs|0.69ns|2.58ns|0.145| 0|0|915&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`SendAsync`|net6.0|4.17μs|2.79ns|10.4ns|0.0313| 0|0|2.22&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`SendAsync`|netcoreapp3.1|5.1μs|1.84ns|6.89ns|0.0381| 0|0|2.76&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`SendAsync`|net472|7.92μs|2.67ns|10.3ns|0.499| 0|0|3.15&nbsp;KB|
|#6162|`SendAsync`|net6.0|4.1μs|1.66ns|5.76ns|0.0308| 0|0|2.22&nbsp;KB|
|#6162|`SendAsync`|netcoreapp3.1|5.06μs|1.31ns|5.07ns|0.0379| 0|0|2.76&nbsp;KB|
|#6162|`SendAsync`|net472|7.69μs|2.55ns|9.87ns|0.499| 0|0|3.15&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`EnrichedLog`|net6.0|1.59μs|1.02ns|3.94ns|0.0228| 0|0|1.64&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`EnrichedLog`|netcoreapp3.1|2.24μs|0.673ns|2.61ns|0.0225| 0|0|1.64&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`EnrichedLog`|net472|2.62μs|1.42ns|5.5ns|0.249| 0|0|1.57&nbsp;KB|
|#6162|`EnrichedLog`|net6.0|1.47μs|0.846ns|3.17ns|0.0226| 0|0|1.64&nbsp;KB|
|#6162|`EnrichedLog`|netcoreapp3.1|2.25μs|1.87ns|7.26ns|0.0213| 0|0|1.64&nbsp;KB|
|#6162|`EnrichedLog`|net472|2.44μs|1.34ns|5.19ns|0.249| 0|0|1.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`EnrichedLog`|net6.0|116μs|180ns|696ns|0| 0|0|4.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`EnrichedLog`|netcoreapp3.1|121μs|278ns|1.08μs|0| 0|0|4.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`EnrichedLog`|net472|152μs|122ns|473ns|0.684| 0.228|0|4.46&nbsp;KB|
|#6162|`EnrichedLog`|net6.0|117μs|184ns|711ns|0.0581| 0|0|4.28&nbsp;KB|
|#6162|`EnrichedLog`|netcoreapp3.1|122μs|149ns|578ns|0.0611| 0|0|4.28&nbsp;KB|
|#6162|`EnrichedLog`|net472|152μs|155ns|600ns|0.684| 0.228|0|4.46&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`EnrichedLog`|net6.0|3.18μs|0.875ns|3.16ns|0.0305| 0|0|2.2&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`EnrichedLog`|netcoreapp3.1|4.2μs|1.98ns|7.67ns|0.0293| 0|0|2.2&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`EnrichedLog`|net472|4.94μs|3ns|11.6ns|0.319| 0|0|2.02&nbsp;KB|
|#6162|`EnrichedLog`|net6.0|3.3μs|1.07ns|4ns|0.0308| 0|0|2.2&nbsp;KB|
|#6162|`EnrichedLog`|netcoreapp3.1|4.13μs|1.49ns|5.76ns|0.0288| 0|0|2.2&nbsp;KB|
|#6162|`EnrichedLog`|net472|4.91μs|1.15ns|4.29ns|0.319| 0|0|2.02&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`SendReceive`|net6.0|1.44μs|1.04ns|4.04ns|0.0157| 0|0|1.14&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`SendReceive`|netcoreapp3.1|1.72μs|1.27ns|4.76ns|0.0156| 0|0|1.14&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`SendReceive`|net472|2.21μs|1.02ns|3.68ns|0.183| 0.00111|0|1.16&nbsp;KB|
|#6162|`SendReceive`|net6.0|1.31μs|0.78ns|3.02ns|0.0157| 0|0|1.14&nbsp;KB|
|#6162|`SendReceive`|netcoreapp3.1|1.78μs|1.82ns|7.06ns|0.0152| 0|0|1.14&nbsp;KB|
|#6162|`SendReceive`|net472|2.15μs|1.53ns|5.94ns|0.183| 0.00108|0|1.16&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`EnrichedLog`|net6.0|2.75μs|0.656ns|2.45ns|0.0219| 0|0|1.6&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`EnrichedLog`|netcoreapp3.1|3.84μs|1.52ns|5.7ns|0.0211| 0|0|1.65&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`EnrichedLog`|net472|4.32μs|1.93ns|7.21ns|0.323| 0|0|2.04&nbsp;KB|
|#6162|`EnrichedLog`|net6.0|2.67μs|4.45ns|17.2ns|0.0215| 0|0|1.6&nbsp;KB|
|#6162|`EnrichedLog`|netcoreapp3.1|3.94μs|1.85ns|7.15ns|0.0217| 0|0|1.65&nbsp;KB|
|#6162|`EnrichedLog`|net472|4.44μs|2.43ns|9.41ns|0.322| 0|0|2.04&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #6162

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.SpanBenchmark.StartFinishSpan&#8209;netcoreapp3.1 | 1.173 | 546.49 | 641.30 | 



#### Faster :tada: in #6162

|  Benchmark         | base/diff | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.SpanBenchmark.StartFinishScope&#8209;netcoreapp3.1 | 1.186 | 792.51 | 668.14 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`StartFinishSpan`|net6.0|460ns|0.236ns|0.913ns|0.00806| 0|0|576&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`StartFinishSpan`|netcoreapp3.1|546ns|0.32ns|1.24ns|0.00797| 0|0|576&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`StartFinishSpan`|net472|700ns|0.281ns|1.05ns|0.0918| 0|0|578&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`StartFinishScope`|net6.0|484ns|0.211ns|0.816ns|0.0097| 0|0|696&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`StartFinishScope`|netcoreapp3.1|792ns|0.54ns|2.09ns|0.00914| 0|0|696&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`StartFinishScope`|net472|831ns|1.11ns|4.29ns|0.104| 0|0|658&nbsp;B|
|#6162|`StartFinishSpan`|net6.0|492ns|0.229ns|0.888ns|0.00816| 0|0|576&nbsp;B|
|#6162|`StartFinishSpan`|netcoreapp3.1|642ns|0.458ns|1.77ns|0.00784| 0|0|576&nbsp;B|
|#6162|`StartFinishSpan`|net472|650ns|0.886ns|3.43ns|0.0918| 0|0|578&nbsp;B|
|#6162|`StartFinishScope`|net6.0|482ns|0.151ns|0.583ns|0.00965| 0|0|696&nbsp;B|
|#6162|`StartFinishScope`|netcoreapp3.1|668ns|0.365ns|1.41ns|0.00938| 0|0|696&nbsp;B|
|#6162|`StartFinishScope`|net472|848ns|0.788ns|2.95ns|0.104| 0|0|658&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`RunOnMethodBegin`|net6.0|656ns|0.302ns|1.13ns|0.00983| 0|0|696&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`RunOnMethodBegin`|netcoreapp3.1|935ns|0.469ns|1.69ns|0.00903| 0|0|696&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/a200693cd84f3bbf8c1c13867b323e9909b56043)|`RunOnMethodBegin`|net472|1.18μs|0.843ns|3.04ns|0.104| 0|0|658&nbsp;B|
|#6162|`RunOnMethodBegin`|net6.0|640ns|0.368ns|1.38ns|0.00963| 0|0|696&nbsp;B|
|#6162|`RunOnMethodBegin`|netcoreapp3.1|918ns|0.466ns|1.74ns|0.00933| 0|0|696&nbsp;B|
|#6162|`RunOnMethodBegin`|net472|1.19μs|0.71ns|2.75ns|0.104| 0|0|658&nbsp;B|
</details>

**Comment by vandonr** [comment]
got merged as commit 3f0d900ebeaccf666cbc346f0b63148d4a9c4fd8 but somehow this PR's status didn't get updated 🤔

**Pull request closed without merging**
