### PR TITLE
run pipelines in release branches

### PR DESCRIPTION
**Pull request by lucaspimentel**
As we plan for the next major release (2.0), we will use release branches (e.g. `release/1.x`) as the main development branch for older versions of the tracer. Release branches such as `release/1.27.1` can also be used for hotfixes that will not include changes already merged into the main development branch. As such, we should treat `release/*` branches similar to `master` (use PRs to merge changes, run the same pipelines, etc).

Tracer version | Main development branch
-|-
2.x | `master`
1.x | `release/1.x`
hotfix | `hotfix/<version>`

### CODE REVIEW

**Review by andrewlock — APPROVED** [review]

**Review by tonyredondo — APPROVED** [review]

**Comment by andrewlock** [comment]
> Shouldn't you do the same for the consolidated pipeline?

Yeah, totally missed this wasn't included. Also, the Crank and Benchmarks pipelines shouldn't be running for release branches, as that's handled by the consolidated pipeline. Not sure why they are 🤔

**Comment by lucaspimentel** [comment]
> Shouldn't you do the same for the consolidated pipeline?

Done in 1e2d1087706ec7463fc71f2430e3f6a7206373a1

**Comment by lucaspimentel** [comment]
> Crank and Benchmarks pipelines shouldn't be running for release branches, as that's handled by the consolidated pipeline. Not sure why they are 

PRs were not explicitly excluded in `benchmarks.yaml`, and there's a default value.
PRs for `master` and `release/*` we explicitly included in `crank.yaml`.

Fixed both in 2d87b80622c37c81ed9b399d7579c0dccea5fa30.

**Comment by lucaspimentel** [comment]
Oh, looks like those were fixed in `master` after 1.27.0.

**Comment by lucaspimentel** [comment]
I copied the pipeline triggers from `master` and included branch `release/*` where needed. See f5ad9bf15710316e29dc98c0c9a6684b5c9a0e71.

**Review by zacharycmontoya — APPROVED** [review]

**Pull request merged**
