### PR TITLE
[Tests] Enable the parametric test suite from the system-tests repo

### PR DESCRIPTION
**Pull request by zacharycmontoya**
## Summary of changes
Runs the parametric test suite during the system-tests stage

## Reason for change
The new parametric test suite validates additional scenarios like spans sampling and distributed tracing headers.

## Implementation details
Adds a script to run the parametric tests.

## Test coverage
This runs the new tests.

## Other details
N/A

### CODE REVIEW

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #3675 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`WriteAndFlushEnrichedTraces`|net472|780μs|788ns|3.05μs|0.388| 0|0|3.22&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|577μs|485ns|1.88μs|0| 0|0|2.62&nbsp;KB|
|#3675|`WriteAndFlushEnrichedTraces`|net472|780μs|1.42μs|5.3μs|0.388| 0|0|3.22&nbsp;KB|
|#3675|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|560μs|811ns|3.14μs|0| 0|0|2.62&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`AllCycleSimpleBody`|net472|49.1μs|44.9ns|168ns|1.24| 0|0|7.83&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`AllCycleSimpleBody`|netcoreapp3.1|61.3μs|59.7ns|231ns|0.0615| 0|0|6.63&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`AllCycleMoreComplexBody`|net472|71.9μs|48.3ns|181ns|2.36| 0.0358|0|15.08&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`AllCycleMoreComplexBody`|netcoreapp3.1|81.2μs|135ns|488ns|0.162| 0|0|13.11&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`ObjectExtractorSimpleBody`|net472|274ns|0.166ns|0.621ns|0.0574| 0|0|361&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`ObjectExtractorSimpleBody`|netcoreapp3.1|240ns|0.128ns|0.495ns|0.00372| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`ObjectExtractorMoreComplexBody`|net472|16μs|14.3ns|55.2ns|1.21| 0.0159|0|7.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|12.6μs|5.19ns|19.4ns|0.0878| 0|0|6.75&nbsp;KB|
|#3675|`AllCycleSimpleBody`|net472|48.9μs|39.9ns|154ns|1.24| 0|0|7.83&nbsp;KB|
|#3675|`AllCycleSimpleBody`|netcoreapp3.1|61.1μs|45.7ns|165ns|0.0611| 0|0|6.63&nbsp;KB|
|#3675|`AllCycleMoreComplexBody`|net472|71.6μs|41.9ns|162ns|2.39| 0.0357|0|15.08&nbsp;KB|
|#3675|`AllCycleMoreComplexBody`|netcoreapp3.1|80.1μs|52.2ns|188ns|0.16| 0|0|13.11&nbsp;KB|
|#3675|`ObjectExtractorSimpleBody`|net472|275ns|0.165ns|0.638ns|0.0573| 0|0|361&nbsp;B|
|#3675|`ObjectExtractorSimpleBody`|netcoreapp3.1|240ns|0.138ns|0.535ns|0.00374| 0|0|272&nbsp;B|
|#3675|`ObjectExtractorMoreComplexBody`|net472|15.4μs|15.9ns|61.6ns|1.2| 0.0154|0|7.62&nbsp;KB|
|#3675|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|12.6μs|7.14ns|27.7ns|0.0884| 0|0|6.75&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`SendRequest`|netcoreapp3.1|299μs|1.74μs|16μs|0.147| 0|0|20.96&nbsp;KB|
|#3675|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#3675|`SendRequest`|netcoreapp3.1|291μs|1.63μs|10.3μs|0.15| 0|0|20.96&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`ExecuteNonQuery`|net472|1.81μs|3.41ns|12.7ns|0.163| 0|0|1.03&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`ExecuteNonQuery`|netcoreapp3.1|1.48μs|2.97ns|11.5ns|0.0135| 0|0|1.02&nbsp;KB|
|#3675|`ExecuteNonQuery`|net472|1.94μs|3.97ns|15.4ns|0.162| 0.000944|0|1.03&nbsp;KB|
|#3675|`ExecuteNonQuery`|netcoreapp3.1|1.52μs|2.52ns|9.75ns|0.0135| 0|0|1.02&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`CallElasticsearch`|net472|2.39μs|1.01ns|3.9ns|0.195| 0|0|1.24&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`CallElasticsearch`|netcoreapp3.1|1.49μs|0.828ns|2.87ns|0.0158| 0|0|1.18&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`CallElasticsearchAsync`|net472|2.64μs|0.623ns|2.25ns|0.218| 0.00133|0|1.37&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`CallElasticsearchAsync`|netcoreapp3.1|1.58μs|0.64ns|2.4ns|0.0174| 0|0|1.3&nbsp;KB|
|#3675|`CallElasticsearch`|net472|2.59μs|0.829ns|3.21ns|0.196| 0|0|1.24&nbsp;KB|
|#3675|`CallElasticsearch`|netcoreapp3.1|1.53μs|1.08ns|4.04ns|0.016| 0|0|1.18&nbsp;KB|
|#3675|`CallElasticsearchAsync`|net472|2.52μs|0.777ns|2.91ns|0.217| 0|0|1.37&nbsp;KB|
|#3675|`CallElasticsearchAsync`|netcoreapp3.1|1.59μs|0.539ns|2.02ns|0.0175| 0|0|1.3&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`ExecuteAsync`|net472|2.73μs|1.66ns|6.44ns|0.238| 0.00136|0|1.5&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`ExecuteAsync`|netcoreapp3.1|1.77μs|0.641ns|2.22ns|0.0195| 0|0|1.42&nbsp;KB|
|#3675|`ExecuteAsync`|net472|2.85μs|0.994ns|3.85ns|0.238| 0|0|1.5&nbsp;KB|
|#3675|`ExecuteAsync`|netcoreapp3.1|1.68μs|0.492ns|1.91ns|0.0194| 0|0|1.42&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`SendAsync`|net472|7.28μs|2.81ns|10.5ns|0.557| 0|0|3.52&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`SendAsync`|netcoreapp3.1|4.62μs|2.29ns|8.87ns|0.0438| 0|0|3.21&nbsp;KB|
|#3675|`SendAsync`|net472|7.31μs|2.19ns|8.47ns|0.555| 0|0|3.52&nbsp;KB|
|#3675|`SendAsync`|netcoreapp3.1|4.63μs|1.86ns|7.19ns|0.044| 0|0|3.21&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`EnrichedLog`|net472|2.94μs|1.09ns|4.07ns|0.301| 0|0|1.9&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`EnrichedLog`|netcoreapp3.1|2.35μs|0.664ns|2.49ns|0.0258| 0|0|1.93&nbsp;KB|
|#3675|`EnrichedLog`|net472|2.9μs|3.92ns|15.2ns|0.301| 0|0|1.9&nbsp;KB|
|#3675|`EnrichedLog`|netcoreapp3.1|2.3μs|1.18ns|4.4ns|0.0265| 0|0|1.93&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`EnrichedLog`|net472|149μs|269ns|1.04μs|0.733| 0.22|0|4.74&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`EnrichedLog`|netcoreapp3.1|118μs|140ns|525ns|0| 0|0|4.58&nbsp;KB|
|#3675|`EnrichedLog`|net472|147μs|153ns|551ns|0.73| 0.219|0|4.74&nbsp;KB|
|#3675|`EnrichedLog`|netcoreapp3.1|117μs|189ns|732ns|0.0586| 0|0|4.58&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`EnrichedLog`|net472|5.48μs|2.17ns|8.12ns|0.584| 0.00275|0|3.68&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`EnrichedLog`|netcoreapp3.1|4.29μs|1.3ns|5.04ns|0.0536| 0|0|4&nbsp;KB|
|#3675|`EnrichedLog`|net472|5.38μs|1.91ns|7.39ns|0.582| 0.00269|0|3.68&nbsp;KB|
|#3675|`EnrichedLog`|netcoreapp3.1|4.34μs|1.67ns|6.48ns|0.0542| 0|0|4&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`SendReceive`|net472|2.09μs|1.41ns|5.47ns|0.23| 0|0|1.45&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`SendReceive`|netcoreapp3.1|1.78μs|1.54ns|5.95ns|0.0195| 0|0|1.4&nbsp;KB|
|#3675|`SendReceive`|net472|2.18μs|2.05ns|7.96ns|0.23| 0|0|1.45&nbsp;KB|
|#3675|`SendReceive`|netcoreapp3.1|1.77μs|0.773ns|2.89ns|0.0185| 0|0|1.4&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`EnrichedLog`|net472|4.79μs|1.8ns|6.97ns|0.366| 0|0|2.32&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`EnrichedLog`|netcoreapp3.1|4.16μs|4.83ns|18.7ns|0.0246| 0|0|1.89&nbsp;KB|
|#3675|`EnrichedLog`|net472|4.81μs|1.47ns|5.68ns|0.368| 0|0|2.32&nbsp;KB|
|#3675|`EnrichedLog`|netcoreapp3.1|4.09μs|2ns|7.22ns|0.0246| 0|0|1.89&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`StartFinishSpan`|net472|1.12μs|0.741ns|2.77ns|0.141| 0|0|891&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`StartFinishSpan`|netcoreapp3.1|906ns|0.74ns|2.77ns|0.0113| 0|0|840&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`StartFinishScope`|net472|1.36μs|0.345ns|1.24ns|0.154| 0|0|971&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`StartFinishScope`|netcoreapp3.1|1.05μs|0.643ns|2.49ns|0.0132| 0|0|960&nbsp;B|
|#3675|`StartFinishSpan`|net472|1.1μs|0.455ns|1.76ns|0.141| 0|0|891&nbsp;B|
|#3675|`StartFinishSpan`|netcoreapp3.1|894ns|0.549ns|2.12ns|0.0112| 0|0|840&nbsp;B|
|#3675|`StartFinishScope`|net472|1.38μs|0.374ns|1.4ns|0.154| 0|0|971&nbsp;B|
|#3675|`StartFinishScope`|netcoreapp3.1|1.08μs|0.413ns|1.54ns|0.0129| 0|0|960&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`RunOnMethodBegin`|net472|1.46μs|0.387ns|1.45ns|0.154| 0|0|971&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)|`RunOnMethodBegin`|netcoreapp3.1|1.15μs|0.506ns|1.96ns|0.0133| 0|0|960&nbsp;B|
|#3675|`RunOnMethodBegin`|net472|1.4μs|0.729ns|2.73ns|0.154| 0|0|971&nbsp;B|
|#3675|`RunOnMethodBegin`|netcoreapp3.1|1.1μs|0.367ns|1.37ns|0.0132| 0|0|960&nbsp;B|
</details>

**Comment by andrewlock** [comment]
## Throughput/Crank Report:zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (3675)](https://github.com/DataDog/dd-trace-dotnet/tree/e8c54791927d19ef14fc26f5b22860c51bcfec9b)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/0d56b1d9f25673f5257b1b7df97a3754d2df63f4)
- [benchmarks/2.21.0](https://github.com/DataDog/dd-trace-dotnet/tree/994d914bd3a83ab18a13a54b2a0907dc1d7e6b86)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (3675) (6.280M)   : 0, 6280019
    master (6.278M)   : 0, 6278355
    benchmarks/2.21.0 (6.315M)   : 0, 6314687
    benchmarks/2.9.0 (6.127M)   : 0, 6126687

    section Instrumented
    This PR (3675) (4.262M)   : 0, 4261778
    master (4.158M)   : 0, 4158440
    benchmarks/2.21.0 (4.155M)   : 0, 4155203
    benchmarks/2.9.0 (4.364M)   : 0, 4364278

    section Trace stats
    master (4.209M)   : 0, 4209341
    benchmarks/2.21.0 (4.169M)   : 0, 4169242

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (3675) (5.356M)   : 0, 5355785
    master (5.455M)   : 0, 5455185
    benchmarks/2.21.0 (5.198M)   : 0, 5198264
    benchmarks/2.9.0 (5.331M)   : 0, 5330526

    section Instrumented
    This PR (3675) (3.599M)   : 0, 3598547
    master (3.675M)   : 0, 3674865
    benchmarks/2.21.0 (3.560M)   : 0, 3559587

    section Trace stats
    master (3.394M)   : 0, 3393691
    benchmarks/2.21.0 (3.636M)   : 0, 3636212

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (3675) (5.845M)   : 0, 5845492
    master (5.640M)   : 0, 5640017
    benchmarks/2.21.0 (5.548M)   : 0, 5548457
    benchmarks/2.9.0 (5.729M)   : 0, 5728901

    section Instrumented
    This PR (3675) (4.038M)   : 0, 4038323
    master (4.027M)   : 0, 4027495
    benchmarks/2.21.0 (3.959M)   : 0, 3958960
    benchmarks/2.9.0 (4.059M)   : 0, 4059389

    section Trace stats
    master (3.965M)   : 0, 3965364
    benchmarks/2.21.0 (3.955M)   : 0, 3954947

```
```mermaid
gantt
    title Throughput Linux x64 (ASM) (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (3675) (3.564M)   : 0, 3564061
    master (3.496M)   : 0, 3495757
    benchmarks/2.21.0 (3.426M)   : 0, 3426048
    benchmarks/2.9.0 (3.599M)   : 0, 3599221

    section No attack
    This PR (3675) (1.266M)   : 0, 1266392
    master (1.261M)   : 0, 1260699
    benchmarks/2.21.0 (1.269M)   : 0, 1268849
    benchmarks/2.9.0 (1.259M)   : 0, 1259142

    section Attack
    This PR (3675) (1.071M)   : 0, 1070885
    master (1.088M)   : 0, 1088066
    benchmarks/2.21.0 (1.087M)   : 0, 1086575
    benchmarks/2.9.0 (1.100M)   : 0, 1100050

    section Blocking
    This PR (3675) (2.158M)   : 0, 2158487
    master (2.152M)   : 0, 2151540
    benchmarks/2.21.0 (2.133M)   : 0, 2133259

```

**Review by andrewlock — APPROVED** [review]
Nice, thanks 👍

**Review by pierotibou — APPROVED** [review]
Thanks a lot for doing it. Working on 2 teams has its perks, we can sometimes realize what we haven't done in the other :p 
Note that there's an error in the test run [ERROR: launchpadlib 1.10.13 requires testresources, which is not installed](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=125247&view=logs&j=7845e05c-45c7-5cf8-7d92-177d8b545c9b&t=7eb2e6e0-3ce1-533b-ea78-b1628e5139e8&l=113). Doesn't seem to prevent the tests from running, but 🤷

**Pull request merged**
