### PR TITLE
Log the PID in more test paths

### PR DESCRIPTION
**Pull request by kevingosse**
## Summary of changes

Some tests (for instance `Datadog.Trace.Debugger.IntegrationTests.ProbesTests.MethodProbeTest`) are not logging the PID, making it harder to find the relevant log files. Move the log message to cover more cases.

## Reason for change

CIs are red
Violets are blue
Test is flaky
And so are you (?)

### CODE REVIEW

**Review by pierotibou — APPROVED** [review]
> CIs are red
> Violets are blue
> Test is flaky
> And so are you (?)

🤣

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #3677 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`WriteAndFlushEnrichedTraces`|net472|784μs|712ns|2.66μs|0.386| 0|0|3.22&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|573μs|776ns|3μs|0| 0|0|2.63&nbsp;KB|
|#3677|`WriteAndFlushEnrichedTraces`|net472|780μs|550ns|2.06μs|0.393| 0|0|3.22&nbsp;KB|
|#3677|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|575μs|914ns|3.42μs|0| 0|0|2.63&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`AllCycleSimpleBody`|net472|48.6μs|44.9ns|168ns|1.23| 0|0|7.83&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`AllCycleSimpleBody`|netcoreapp3.1|60.1μs|48ns|180ns|0.0605| 0|0|6.63&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`AllCycleMoreComplexBody`|net472|71.9μs|59.2ns|222ns|2.37| 0.0359|0|15.08&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`AllCycleMoreComplexBody`|netcoreapp3.1|81.8μs|82.1ns|318ns|0.164| 0|0|13.11&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`ObjectExtractorSimpleBody`|net472|271ns|0.108ns|0.388ns|0.0573| 0|0|361&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`ObjectExtractorSimpleBody`|netcoreapp3.1|257ns|0.128ns|0.496ns|0.00374| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`ObjectExtractorMoreComplexBody`|net472|16μs|8.64ns|33.5ns|1.21| 0.016|0|7.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|12.8μs|6.1ns|22.8ns|0.0897| 0|0|6.75&nbsp;KB|
|#3677|`AllCycleSimpleBody`|net472|49μs|43.9ns|170ns|1.22| 0|0|7.83&nbsp;KB|
|#3677|`AllCycleSimpleBody`|netcoreapp3.1|61.3μs|63.3ns|237ns|0.0618| 0|0|6.63&nbsp;KB|
|#3677|`AllCycleMoreComplexBody`|net472|72.2μs|64.2ns|249ns|2.39| 0.0362|0|15.09&nbsp;KB|
|#3677|`AllCycleMoreComplexBody`|netcoreapp3.1|81.9μs|90.2ns|338ns|0.162| 0|0|13.11&nbsp;KB|
|#3677|`ObjectExtractorSimpleBody`|net472|270ns|0.076ns|0.285ns|0.0574| 0|0|361&nbsp;B|
|#3677|`ObjectExtractorSimpleBody`|netcoreapp3.1|232ns|0.243ns|0.941ns|0.0037| 0|0|272&nbsp;B|
|#3677|`ObjectExtractorMoreComplexBody`|net472|16μs|13.1ns|48.9ns|1.21| 0.016|0|7.62&nbsp;KB|
|#3677|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|12.7μs|8.33ns|31.2ns|0.0884| 0|0|6.75&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Unknown :shrug: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`SendRequest`|netcoreapp3.1|295μs|1.71μs|14.6μs|0.148| 0|0|20.96&nbsp;KB|
|#3677|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#3677|`SendRequest`|netcoreapp3.1|260μs|1.46μs|9.47μs|0.246| 0|0|20.96&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`ExecuteNonQuery`|net472|1.93μs|3.75ns|14.5ns|0.163| 0|0|1.03&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`ExecuteNonQuery`|netcoreapp3.1|1.5μs|2.69ns|10.1ns|0.0136| 0|0|1.02&nbsp;KB|
|#3677|`ExecuteNonQuery`|net472|1.81μs|3.17ns|12.3ns|0.163| 0|0|1.03&nbsp;KB|
|#3677|`ExecuteNonQuery`|netcoreapp3.1|1.46μs|2.5ns|9.67ns|0.0138| 0|0|1.02&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`CallElasticsearch`|net472|2.48μs|1.01ns|3.93ns|0.196| 0|0|1.24&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`CallElasticsearch`|netcoreapp3.1|1.56μs|1.05ns|4.05ns|0.0157| 0|0|1.18&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`CallElasticsearchAsync`|net472|2.59μs|0.804ns|3.12ns|0.218| 0.0013|0|1.37&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`CallElasticsearchAsync`|netcoreapp3.1|1.57μs|0.838ns|3.14ns|0.0173| 0|0|1.3&nbsp;KB|
|#3677|`CallElasticsearch`|net472|2.47μs|0.741ns|2.87ns|0.195| 0|0|1.24&nbsp;KB|
|#3677|`CallElasticsearch`|netcoreapp3.1|1.55μs|0.61ns|2.28ns|0.0163| 0|0|1.18&nbsp;KB|
|#3677|`CallElasticsearchAsync`|net472|2.69μs|1.19ns|4.6ns|0.218| 0|0|1.37&nbsp;KB|
|#3677|`CallElasticsearchAsync`|netcoreapp3.1|1.6μs|1.63ns|6.29ns|0.0174| 0|0|1.3&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`ExecuteAsync`|net472|2.73μs|0.723ns|2.71ns|0.238| 0|0|1.5&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`ExecuteAsync`|netcoreapp3.1|1.75μs|0.562ns|2.1ns|0.0191| 0|0|1.42&nbsp;KB|
|#3677|`ExecuteAsync`|net472|2.73μs|1.64ns|6.13ns|0.237| 0|0|1.5&nbsp;KB|
|#3677|`ExecuteAsync`|netcoreapp3.1|1.68μs|3.04ns|11.8ns|0.0193| 0|0|1.42&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`SendAsync`|net472|7.22μs|2.42ns|9.07ns|0.556| 0|0|3.52&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`SendAsync`|netcoreapp3.1|4.61μs|2.69ns|9.31ns|0.0416| 0|0|3.21&nbsp;KB|
|#3677|`SendAsync`|net472|7.24μs|2.69ns|10.4ns|0.558| 0|0|3.52&nbsp;KB|
|#3677|`SendAsync`|netcoreapp3.1|4.8μs|3ns|11.2ns|0.0429| 0|0|3.21&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`EnrichedLog`|net472|2.94μs|0.978ns|3.66ns|0.302| 0|0|1.9&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`EnrichedLog`|netcoreapp3.1|2.23μs|0.604ns|2.18ns|0.0256| 0|0|1.93&nbsp;KB|
|#3677|`EnrichedLog`|net472|2.81μs|0.793ns|2.75ns|0.301| 0|0|1.9&nbsp;KB|
|#3677|`EnrichedLog`|netcoreapp3.1|2.29μs|0.505ns|1.82ns|0.0263| 0|0|1.93&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`EnrichedLog`|net472|146μs|105ns|408ns|0.733| 0.22|0|4.74&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`EnrichedLog`|netcoreapp3.1|117μs|178ns|691ns|0.0583| 0|0|4.58&nbsp;KB|
|#3677|`EnrichedLog`|net472|150μs|128ns|497ns|0.751| 0.225|0|4.74&nbsp;KB|
|#3677|`EnrichedLog`|netcoreapp3.1|119μs|136ns|528ns|0| 0|0|4.58&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`EnrichedLog`|net472|5.6μs|1.48ns|5.72ns|0.584| 0.00279|0|3.68&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`EnrichedLog`|netcoreapp3.1|4.19μs|1.84ns|7.11ns|0.0545| 0|0|4&nbsp;KB|
|#3677|`EnrichedLog`|net472|5.52μs|2.35ns|8.47ns|0.581| 0.00277|0|3.68&nbsp;KB|
|#3677|`EnrichedLog`|netcoreapp3.1|4.11μs|2.48ns|9.6ns|0.0537| 0|0|4&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`SendReceive`|net472|2.24μs|1.24ns|4.46ns|0.231| 0|0|1.45&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`SendReceive`|netcoreapp3.1|1.8μs|0.76ns|2.95ns|0.0191| 0|0|1.4&nbsp;KB|
|#3677|`SendReceive`|net472|2.31μs|0.836ns|3.02ns|0.231| 0|0|1.45&nbsp;KB|
|#3677|`SendReceive`|netcoreapp3.1|1.88μs|0.565ns|2.11ns|0.0188| 0|0|1.4&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`EnrichedLog`|net472|4.81μs|1.83ns|6.87ns|0.367| 0|0|2.32&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`EnrichedLog`|netcoreapp3.1|3.96μs|1.19ns|4.63ns|0.0257| 0|0|1.89&nbsp;KB|
|#3677|`EnrichedLog`|net472|4.67μs|2.15ns|8.33ns|0.367| 0|0|2.32&nbsp;KB|
|#3677|`EnrichedLog`|netcoreapp3.1|4.01μs|2.05ns|7.95ns|0.024| 0|0|1.89&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`StartFinishSpan`|net472|1.16μs|0.361ns|1.4ns|0.141| 0|0|891&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`StartFinishSpan`|netcoreapp3.1|913ns|4.65ns|21.3ns|0.0113| 0|0|840&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`StartFinishScope`|net472|1.38μs|0.493ns|1.84ns|0.154| 0|0|971&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`StartFinishScope`|netcoreapp3.1|1.06μs|0.997ns|3.86ns|0.0132| 0|0|960&nbsp;B|
|#3677|`StartFinishSpan`|net472|1.17μs|0.221ns|0.797ns|0.141| 0|0|891&nbsp;B|
|#3677|`StartFinishSpan`|netcoreapp3.1|876ns|0.268ns|0.966ns|0.0114| 0|0|840&nbsp;B|
|#3677|`StartFinishScope`|net472|1.35μs|0.483ns|1.81ns|0.154| 0|0|971&nbsp;B|
|#3677|`StartFinishScope`|netcoreapp3.1|1.07μs|0.443ns|1.66ns|0.0129| 0|0|960&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`RunOnMethodBegin`|net472|1.48μs|0.763ns|2.96ns|0.154| 0|0|971&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)|`RunOnMethodBegin`|netcoreapp3.1|1.07μs|0.237ns|0.82ns|0.0129| 0|0|960&nbsp;B|
|#3677|`RunOnMethodBegin`|net472|1.42μs|0.467ns|1.75ns|0.154| 0|0|971&nbsp;B|
|#3677|`RunOnMethodBegin`|netcoreapp3.1|1.13μs|0.511ns|1.91ns|0.013| 0|0|960&nbsp;B|
</details>

**Comment by andrewlock** [comment]
## Throughput/Crank Report:zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (3677)](https://github.com/DataDog/dd-trace-dotnet/tree/15fe0b67a08c922b680e8944493b2b21db2aafe0)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/615273fa090487ed20387fa2b4f38bb2e98b6f95)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/0d56b1d9f25673f5257b1b7df97a3754d2df63f4)
- [benchmarks/2.21.0](https://github.com/DataDog/dd-trace-dotnet/tree/994d914bd3a83ab18a13a54b2a0907dc1d7e6b86)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (3677) (6.146M)   : 0, 6145704
    master (6.263M)   : 0, 6263489
    benchmarks/2.21.0 (6.315M)   : 0, 6314687
    benchmarks/2.9.0 (6.127M)   : 0, 6126687

    section Instrumented
    This PR (3677) (4.184M)   : 0, 4184296
    master (4.301M)   : 0, 4301159
    benchmarks/2.21.0 (4.155M)   : 0, 4155203
    benchmarks/2.9.0 (4.364M)   : 0, 4364278

    section Trace stats
    master (4.255M)   : 0, 4254511
    benchmarks/2.21.0 (4.169M)   : 0, 4169242

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (3677) (5.192M)   : 0, 5191796
    master (5.237M)   : 0, 5236518
    benchmarks/2.21.0 (5.198M)   : 0, 5198264
    benchmarks/2.9.0 (5.331M)   : 0, 5330526

    section Instrumented
    This PR (3677) (3.639M)   : 0, 3639045
    master (3.754M)   : 0, 3754129
    benchmarks/2.21.0 (3.560M)   : 0, 3559587

    section Trace stats
    master (3.613M)   : 0, 3612845
    benchmarks/2.21.0 (3.636M)   : 0, 3636212

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (3677) (6.115M)   : 0, 6114883
    master (5.765M)   : 0, 5764738
    benchmarks/2.21.0 (5.548M)   : 0, 5548457
    benchmarks/2.9.0 (5.729M)   : 0, 5728901

    section Instrumented
    This PR (3677) (4.142M)   : 0, 4142215
    master (3.935M)   : 0, 3935142
    benchmarks/2.21.0 (3.959M)   : 0, 3958960
    benchmarks/2.9.0 (4.059M)   : 0, 4059389

    section Trace stats
    master (3.905M)   : 0, 3905002
    benchmarks/2.21.0 (3.955M)   : 0, 3954947

```
```mermaid
gantt
    title Throughput Linux x64 (ASM) (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (3677) (3.486M)   : 0, 3486141
    master (3.541M)   : 0, 3541497
    benchmarks/2.21.0 (3.426M)   : 0, 3426048
    benchmarks/2.9.0 (3.599M)   : 0, 3599221

    section No attack
    This PR (3677) (1.261M)   : 0, 1260631
    master (1.273M)   : 0, 1273095
    benchmarks/2.21.0 (1.269M)   : 0, 1268849
    benchmarks/2.9.0 (1.259M)   : 0, 1259142

    section Attack
    This PR (3677) (1.084M)   : 0, 1083881
    master (1.095M)   : 0, 1094950
    benchmarks/2.21.0 (1.087M)   : 0, 1086575
    benchmarks/2.9.0 (1.100M)   : 0, 1100050

    section Blocking
    This PR (3677) (2.121M)   : 0, 2121411
    master (2.156M)   : 0, 2155997
    benchmarks/2.21.0 (2.133M)   : 0, 2133259

```

**Review by andrewlock — APPROVED** [review]
why are you flaking yourself?

**Comment by andrewlock** [comment]
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #3677 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4) will **not change** line coverage
:heavy_check_mark: Merging #3677 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4) will **not change** branch coverage
:no_entry: Merging #3677 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4) will will **increase** complexity by `2`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4) | #3677       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `21334` / `29858` | `21348` / `29854` |          |
| Lines %   | `71%`      | `72%`      |  `0%` :heavy_check_mark:  |
| Branches  | `12757` / `19259` | `12755` / `19259` |          |
| Branches %| `66%`      | `66%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `20779`      | `20781`        |  `2`  :no_entry:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=125243&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/125243/artifacts?artifactName=Code%20Coverage%20Report_125243&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3677](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=125303&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/125303/artifacts?artifactName=Code%20Coverage%20Report_125303&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/08c5300e78841a3c61c725887f39e1b73b9649b4) | #3677       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `71%`      | `72%`       |  `0%` :heavy_check_mark:  |
| Branches %| `66%`      | `66%`       |  `0%` :heavy_check_mark:  |
| Complexity| `20779`      | `20781`       |  `2` :no_entry:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Ci.GitInfo](https://github.com/DataDog/dd-trace-dotnet/tree/f3535b1acfeb20d4f4ed94237ee592ede0497dec/tracer/src/Datadog.Trace/Ci/GitInfo.cs) | `8%` :heavy_check_mark: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=125243&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/125243/artifacts?artifactName=Code%20Coverage%20Report_125243&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3677](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=125303&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/125303/artifacts?artifactName=Code%20Coverage%20Report_125303&api-version=6.0&%24format=zip)

**Pull request merged**
