### PR TITLE
Remove direct reference to Samples.AspNetCore.RazorPages from integration test project

### PR DESCRIPTION
**Pull request by andrewlock**
## Summary of changes

Removes the direct reference to Samples.AspNetCore.RazorPages from Datadog.Trace.IntegrationTests

## Reason for change

It makes the build more complicated, it adds coupling between tests that we may not want, and it's overall not necessary.

## Implementation details

Remove the reference, add explicit Razor Pages to the test project directly

## Test coverage

Unchanged

## Other details

I tried linking in files from the test app instead, but that required updating a bunch of the files (the sample apps aren't covered by the same analyzers, so requires moving a bunch of stuff around). It would also mean the separate tests are coupled too.

### CODE REVIEW

**Comment by lucaspimentel** [comment]
Thank you! Just one small comment. Instead of `Pages` in `tracer/test/Datadog.Trace.IntegrationTests/Pages/`, can we expand that name? Maybe `.../AspNetCoreRazorPages/`, or at least `.../RazorPages/`. "Pages" alone seems too ambiguous.

**Review by lucaspimentel — APPROVED** [review]
THANK YOU

**Comment by andrewlock** [comment]
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (5402)](https://github.com/DataDog/dd-trace-dotnet/tree/6c8b5c4763e6ef1e68507e87fd30256cfc8d1e89)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/49f7b03c56ea6c3799e3087ba540fc481f644325)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5402) - mean (74ms)  : 66, 82
     .   : milestone, 74,
    master - mean (74ms)  : 65, 83
     .   : milestone, 74,

    section CallTarget+Inlining+NGEN
    This PR (5402) - mean (1,000ms)  : 973, 1028
     .   : milestone, 1000,
    master - mean (994ms)  : 973, 1014
     .   : milestone, 994,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5402) - mean (110ms)  : 106, 114
     .   : milestone, 110,
    master - mean (110ms)  : 107, 112
     .   : milestone, 110,

    section CallTarget+Inlining+NGEN
    This PR (5402) - mean (717ms)  : 692, 742
     .   : milestone, 717,
    master - mean (713ms)  : 693, 733
     .   : milestone, 713,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5402) - mean (94ms)  : 91, 96
     .   : milestone, 94,
    master - mean (93ms)  : 91, 96
     .   : milestone, 93,

    section CallTarget+Inlining+NGEN
    This PR (5402) - mean (668ms)  : 642, 694
     .   : milestone, 668,
    master - mean (672ms)  : 646, 697
     .   : milestone, 672,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5402) - mean (188ms)  : 185, 191
     .   : milestone, 188,
    master - mean (188ms)  : 184, 193
     .   : milestone, 188,

    section CallTarget+Inlining+NGEN
    This PR (5402) - mean (1,075ms)  : 1052, 1097
     .   : milestone, 1075,
    master - mean (1,072ms)  : 1048, 1096
     .   : milestone, 1072,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5402) - mean (271ms)  : 267, 274
     .   : milestone, 271,
    master - mean (272ms)  : 265, 279
     .   : milestone, 272,

    section CallTarget+Inlining+NGEN
    This PR (5402) - mean (867ms)  : 839, 894
     .   : milestone, 867,
    master - mean (868ms)  : 846, 891
     .   : milestone, 868,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5402) - mean (261ms)  : 256, 265
     .   : milestone, 261,
    master - mean (259ms)  : 254, 264
     .   : milestone, 259,

    section CallTarget+Inlining+NGEN
    This PR (5402) - mean (853ms)  : 829, 876
     .   : milestone, 853,
    master - mean (855ms)  : 835, 875
     .   : milestone, 855,

```

**Comment by andrewlock** [comment]
## Benchmarks Report for tracer :snail:

Benchmarks for #5402 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b): 
* 1 benchmarks are **faster**, with geometric mean 1.153
* 3 benchmarks are **slower**, with geometric mean 1.128
* 1 benchmarks have **fewer** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.ActivityBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`StartStopWithChild`|net6.0|8.64μs|46.7ns|247ns|0.0435| 0.0174|0|7.51&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`StartStopWithChild`|netcoreapp3.1|10.8μs|54ns|333ns|0.0213| 0.0107|0|7.6&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`StartStopWithChild`|net472|16.9μs|74.7ns|289ns|1.35| 0.351|0.114|8.05&nbsp;KB|
|#5402|`StartStopWithChild`|net6.0|8.81μs|48.2ns|277ns|0.0257| 0.0129|0.00429|7.5&nbsp;KB|
|#5402|`StartStopWithChild`|netcoreapp3.1|10.7μs|56.5ns|277ns|0.0309| 0.0155|0|7.6&nbsp;KB|
|#5402|`StartStopWithChild`|net472|16.8μs|63.9ns|239ns|1.36| 0.352|0.117|8.07&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`WriteAndFlushEnrichedTraces`|net6.0|459μs|292ns|1.13μs|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|590μs|119ns|462ns|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`WriteAndFlushEnrichedTraces`|net472|814μs|284ns|1.02μs|0.408| 0|0|3.3&nbsp;KB|
|#5402|`WriteAndFlushEnrichedTraces`|net6.0|454μs|120ns|450ns|0| 0|0|2.7&nbsp;KB|
|#5402|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|612μs|267ns|1.04μs|0| 0|0|2.7&nbsp;KB|
|#5402|`WriteAndFlushEnrichedTraces`|net472|840μs|163ns|587ns|0.408| 0|0|3.3&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`SendRequest`|net6.0|171μs|189ns|734ns|0.257| 0|0|18.33&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`SendRequest`|netcoreapp3.1|192μs|249ns|964ns|0.19| 0|0|20.49&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`SendRequest`|net472|0.000417ns|0.000208ns|0.000777ns|0| 0|0|0&nbsp;b|
|#5402|`SendRequest`|net6.0|170μs|173ns|671ns|0.169| 0|0|18.33&nbsp;KB|
|#5402|`SendRequest`|netcoreapp3.1|192μs|266ns|1.03μs|0.192| 0|0|20.49&nbsp;KB|
|#5402|`SendRequest`|net472|0.0012ns|0.000381ns|0.00137ns|0| 0|0|0&nbsp;b|
</details>


<details><summary><strong>Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark</strong> - Same speed :heavy_check_mark: Fewer allocations :tada:



#### Fewer allocations :tada: in #5402

|  Benchmark         | Base Allocated | Diff Allocated | Change   | Change % |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark.WriteAndFlushEnrichedTraces&#8209;netcoreapp3.1 | 42.03 KB | 41.77 KB | -260 B | -0.62%

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`WriteAndFlushEnrichedTraces`|net6.0|561μs|1.78μs|6.89μs|0.546| 0|0|41.88&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|658μs|2.26μs|8.75μs|0.322| 0|0|42.03&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`WriteAndFlushEnrichedTraces`|net472|865μs|3.82μs|14.8μs|8.04| 2.23|0.446|53.23&nbsp;KB|
|#5402|`WriteAndFlushEnrichedTraces`|net6.0|567μs|222ns|860ns|0.541| 0|0|41.69&nbsp;KB|
|#5402|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|650μs|711ns|2.75μs|0.321| 0|0|41.77&nbsp;KB|
|#5402|`WriteAndFlushEnrichedTraces`|net472|859μs|2.18μs|8.14μs|8.28| 2.48|0.414|53.24&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`ExecuteNonQuery`|net6.0|1.22μs|0.944ns|3.66ns|0.0111| 0|0|784&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`ExecuteNonQuery`|netcoreapp3.1|1.46μs|0.814ns|3.15ns|0.0102| 0|0|784&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`ExecuteNonQuery`|net472|1.83μs|0.728ns|2.72ns|0.118| 0|0|746&nbsp;B|
|#5402|`ExecuteNonQuery`|net6.0|1.21μs|1.04ns|4.01ns|0.0109| 0|0|784&nbsp;B|
|#5402|`ExecuteNonQuery`|netcoreapp3.1|1.56μs|4.23ns|15.8ns|0.0106| 0|0|784&nbsp;B|
|#5402|`ExecuteNonQuery`|net472|1.82μs|1.52ns|5.9ns|0.118| 0|0|746&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`CallElasticsearch`|net6.0|1.3μs|0.855ns|3.31ns|0.0137| 0|0|1.01&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`CallElasticsearch`|netcoreapp3.1|1.62μs|4.24ns|16.4ns|0.0136| 0|0|1.01&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`CallElasticsearch`|net472|2.46μs|1.65ns|6.37ns|0.161| 0|0|1.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`CallElasticsearchAsync`|net6.0|1.33μs|0.71ns|2.75ns|0.014| 0|0|984&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`CallElasticsearchAsync`|netcoreapp3.1|1.71μs|0.719ns|2.78ns|0.0146| 0|0|1.06&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`CallElasticsearchAsync`|net472|2.5μs|2.51ns|9.39ns|0.17| 0|0|1.08&nbsp;KB|
|#5402|`CallElasticsearch`|net6.0|1.29μs|0.947ns|3.67ns|0.0141| 0|0|1.01&nbsp;KB|
|#5402|`CallElasticsearch`|netcoreapp3.1|1.67μs|2.25ns|8.7ns|0.0135| 0|0|1.01&nbsp;KB|
|#5402|`CallElasticsearch`|net472|2.46μs|1.63ns|6.31ns|0.161| 0|0|1.02&nbsp;KB|
|#5402|`CallElasticsearchAsync`|net6.0|1.43μs|0.515ns|1.93ns|0.0136| 0|0|984&nbsp;B|
|#5402|`CallElasticsearchAsync`|netcoreapp3.1|1.65μs|0.815ns|3.16ns|0.0141| 0|0|1.06&nbsp;KB|
|#5402|`CallElasticsearchAsync`|net472|2.69μs|2.61ns|10.1ns|0.171| 0|0|1.08&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #5402

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.GraphQLBenchmark.ExecuteAsync&#8209;net6.0 | 1.132 | 1,244.17 | 1,408.45 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`ExecuteAsync`|net6.0|1.24μs|0.739ns|2.76ns|0.0131| 0|0|928&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`ExecuteAsync`|netcoreapp3.1|1.79μs|1.2ns|4.64ns|0.0125| 0|0|928&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`ExecuteAsync`|net472|1.97μs|0.538ns|2.01ns|0.141| 0|0|891&nbsp;B|
|#5402|`ExecuteAsync`|net6.0|1.41μs|1.07ns|4ns|0.0127| 0|0|928&nbsp;B|
|#5402|`ExecuteAsync`|netcoreapp3.1|1.69μs|1.05ns|4.05ns|0.0119| 0|0|928&nbsp;B|
|#5402|`ExecuteAsync`|net472|1.92μs|1.73ns|6.7ns|0.141| 0|0|891&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`SendAsync`|net6.0|4.12μs|1.32ns|4.93ns|0.0309| 0|0|2.16&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`SendAsync`|netcoreapp3.1|5.18μs|2.9ns|10.9ns|0.0361| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`SendAsync`|net472|7.64μs|2.42ns|9.36ns|0.484| 0|0|3.05&nbsp;KB|
|#5402|`SendAsync`|net6.0|4.1μs|4.02ns|15ns|0.0307| 0|0|2.16&nbsp;KB|
|#5402|`SendAsync`|netcoreapp3.1|5.08μs|2.5ns|9.02ns|0.0356| 0|0|2.7&nbsp;KB|
|#5402|`SendAsync`|net472|7.68μs|2.06ns|7.96ns|0.484| 0.00384|0|3.05&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`EnrichedLog`|net6.0|1.48μs|0.804ns|3.01ns|0.0229| 0|0|1.65&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`EnrichedLog`|netcoreapp3.1|2.28μs|0.925ns|3.46ns|0.0227| 0|0|1.65&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`EnrichedLog`|net472|2.67μs|1.31ns|5.08ns|0.249| 0|0|1.57&nbsp;KB|
|#5402|`EnrichedLog`|net6.0|1.51μs|0.749ns|2.9ns|0.0232| 0|0|1.65&nbsp;KB|
|#5402|`EnrichedLog`|netcoreapp3.1|2.15μs|1.93ns|6.68ns|0.0217| 0|0|1.65&nbsp;KB|
|#5402|`EnrichedLog`|net472|2.66μs|1.29ns|4.83ns|0.249| 0|0|1.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`EnrichedLog`|net6.0|112μs|234ns|908ns|0.056| 0|0|4.23&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`EnrichedLog`|netcoreapp3.1|117μs|118ns|458ns|0.0584| 0|0|4.23&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`EnrichedLog`|net472|146μs|57.5ns|215ns|0.657| 0.219|0|4.41&nbsp;KB|
|#5402|`EnrichedLog`|net6.0|112μs|206ns|797ns|0.0558| 0|0|4.23&nbsp;KB|
|#5402|`EnrichedLog`|netcoreapp3.1|119μs|124ns|447ns|0.0592| 0|0|4.23&nbsp;KB|
|#5402|`EnrichedLog`|net472|147μs|47.4ns|171ns|0.662| 0.221|0|4.41&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`EnrichedLog`|net6.0|2.99μs|1.85ns|6.94ns|0.0313| 0|0|2.21&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`EnrichedLog`|netcoreapp3.1|4.4μs|2.58ns|9.99ns|0.0285| 0|0|2.21&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`EnrichedLog`|net472|5μs|3.1ns|12ns|0.319| 0|0|2.02&nbsp;KB|
|#5402|`EnrichedLog`|net6.0|2.99μs|5.25ns|20.3ns|0.03| 0|0|2.21&nbsp;KB|
|#5402|`EnrichedLog`|netcoreapp3.1|4.26μs|1.71ns|6.41ns|0.0298| 0|0|2.21&nbsp;KB|
|#5402|`EnrichedLog`|net472|4.93μs|1.4ns|5.42ns|0.32| 0|0|2.02&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`SendReceive`|net6.0|1.47μs|0.829ns|3.21ns|0.0162| 0|0|1.18&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`SendReceive`|netcoreapp3.1|1.81μs|0.744ns|2.78ns|0.0155| 0|0|1.18&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`SendReceive`|net472|2.24μs|1.67ns|6.45ns|0.187| 0|0|1.18&nbsp;KB|
|#5402|`SendReceive`|net6.0|1.39μs|0.968ns|3.75ns|0.0167| 0|0|1.18&nbsp;KB|
|#5402|`SendReceive`|netcoreapp3.1|1.79μs|0.545ns|2.04ns|0.0161| 0|0|1.18&nbsp;KB|
|#5402|`SendReceive`|net472|2.3μs|1.9ns|7.1ns|0.187| 0|0|1.18&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`EnrichedLog`|net6.0|2.71μs|0.754ns|2.72ns|0.0217| 0|0|1.55&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`EnrichedLog`|netcoreapp3.1|4.06μs|1.83ns|7.08ns|0.0203| 0|0|1.6&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`EnrichedLog`|net472|4.58μs|2.07ns|8.03ns|0.315| 0|0|1.99&nbsp;KB|
|#5402|`EnrichedLog`|net6.0|2.68μs|1.4ns|5.24ns|0.0216| 0|0|1.55&nbsp;KB|
|#5402|`EnrichedLog`|netcoreapp3.1|3.98μs|1.02ns|3.96ns|0.0219| 0|0|1.6&nbsp;KB|
|#5402|`EnrichedLog`|net472|4.54μs|1.1ns|4.1ns|0.314| 0|0|1.99&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #5402

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.SpanBenchmark.StartFinishSpan&#8209;netcoreapp3.1 | 1.129 | 697.62 | 787.35 | 
| Benchmarks.Trace.SpanBenchmark.StartFinishScope&#8209;net6.0 | 1.125 | 600.67 | 675.49 | 



#### Faster :tada: in #5402

|  Benchmark         | base/diff | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.SpanBenchmark.StartFinishSpan&#8209;net6.0 | 1.153 | 523.91 | 454.45 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`StartFinishSpan`|net6.0|521ns|1.39ns|5.36ns|0.00764| 0|0|552&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`StartFinishSpan`|netcoreapp3.1|697ns|0.835ns|3.23ns|0.00752| 0|0|552&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`StartFinishSpan`|net472|769ns|1.9ns|7.34ns|0.0877| 0|0|554&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`StartFinishScope`|net6.0|602ns|0.793ns|2.97ns|0.00941| 0|0|672&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`StartFinishScope`|netcoreapp3.1|800ns|1.84ns|7.12ns|0.00914| 0|0|672&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`StartFinishScope`|net472|979ns|1.65ns|6.4ns|0.101| 0|0|634&nbsp;B|
|#5402|`StartFinishSpan`|net6.0|454ns|0.83ns|3.21ns|0.00767| 0|0|552&nbsp;B|
|#5402|`StartFinishSpan`|netcoreapp3.1|786ns|1.11ns|4.14ns|0.00748| 0|0|552&nbsp;B|
|#5402|`StartFinishSpan`|net472|769ns|1.45ns|5.62ns|0.0877| 0|0|554&nbsp;B|
|#5402|`StartFinishScope`|net6.0|675ns|0.866ns|3.24ns|0.00926| 0|0|672&nbsp;B|
|#5402|`StartFinishScope`|netcoreapp3.1|842ns|1.23ns|4.74ns|0.00928| 0|0|672&nbsp;B|
|#5402|`StartFinishScope`|net472|969ns|1.8ns|6.95ns|0.101| 0|0|634&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`RunOnMethodBegin`|net6.0|639ns|0.636ns|2.46ns|0.00953| 0|0|672&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`RunOnMethodBegin`|netcoreapp3.1|928ns|1.5ns|5.19ns|0.00892| 0|0|672&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/b099cc0a9d328f1b0ed686789f99fef9bb62078b)|`RunOnMethodBegin`|net472|1.12μs|1.72ns|6.65ns|0.101| 0|0|634&nbsp;B|
|#5402|`RunOnMethodBegin`|net6.0|709ns|1.06ns|4.12ns|0.00957| 0|0|672&nbsp;B|
|#5402|`RunOnMethodBegin`|netcoreapp3.1|971ns|1.52ns|5.69ns|0.00902| 0|0|672&nbsp;B|
|#5402|`RunOnMethodBegin`|net472|1.1μs|2.13ns|8.25ns|0.1| 0|0|634&nbsp;B|
</details>

**Review by bouwkast — APPROVED** [review]
👍

**Pull request merged**
