### PR TITLE
Add Callsite aspects analyzer to check for "safe" patterns

### PR DESCRIPTION
**Pull request by andrewlock**
## Summary of changes

Adds two analyzers that check for "safe" usage of the callsite arguments

## Reason for change

In CallTarget we explicitly wrap all the custom code in try-catch statements for safety. It's not technically easy to do that with CallSite, so this provides the next best thing - an analyzer that enforces specific patterns.

## Implementation details

There are two analyzers included

- `BeforeAfterAspectAnalyzer` that works with `[AspectMethodInsertBefore]` and `[AspectMethodInsertAfter]`
- `ReplaceAspectAnalyzer` that works with `[AspectCtorReplace]` and `[AspectMethodReplace]`

> The CodeFixProvider for `ReplaceAspectAnalyzer` is "best effort", and only works for aspects that follow an expected pattern, as otherwise there's too much risk of introducing a bug.

The easiest way to show what they do is to look at the unit tests, or the following GIFs of the analyzers and code fixes in action

aspect analyzer

aspect analyzer2

## Test coverage

Unit tests for the behaviour. Also verified that they show up in the IDE

## Other details

Setting the severity of these analyzers to `Warning` or `Error` breaks the build, as most of our aspects are non-compliant. For now, I've set it to `Info` so that nothing breaks, but you only get a minimal info about the error in the IDE:

image

When we fix these issues, we should be sure to change the severity of the analyzers to `Error` first, as it will make them easier to fix, and we will know we caught them all.

### CODE REVIEW

**Comment by andrewlock** [comment]
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (5835)](https://github.com/DataDog/dd-trace-dotnet/tree/d83be8588d86adf361d9b9474f9d55d13feba198)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/96ccec4d6f240d42a140ab95a7990cf9afe377b6)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5835) - mean (72ms)  : 65, 80
     .   : milestone, 72,
    master - mean (73ms)  : 64, 83
     .   : milestone, 73,

    section CallTarget+Inlining+NGEN
    This PR (5835) - mean (1,045ms)  : 1020, 1069
     .   : milestone, 1045,
    master - mean (1,045ms)  : 1019, 1071
     .   : milestone, 1045,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5835) - mean (108ms)  : 105, 112
     .   : milestone, 108,
    master - mean (109ms)  : 105, 113
     .   : milestone, 109,

    section CallTarget+Inlining+NGEN
    This PR (5835) - mean (732ms)  : 709, 755
     .   : milestone, 732,
    master - mean (730ms)  : 709, 750
     .   : milestone, 730,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5835) - mean (92ms)  : 89, 96
     .   : milestone, 92,
    master - mean (91ms)  : 87, 95
     .   : milestone, 91,

    section CallTarget+Inlining+NGEN
    This PR (5835) - mean (687ms)  : 647, 728
     .   : milestone, 687,
    master - mean (680ms)  : 654, 705
     .   : milestone, 680,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5835) - mean (192ms)  : 188, 195
     .   : milestone, 192,
    master - mean (193ms)  : 190, 197
     .   : milestone, 193,

    section CallTarget+Inlining+NGEN
    This PR (5835) - mean (1,153ms)  : 1120, 1185
     .   : milestone, 1153,
    master - mean (1,150ms)  : 1120, 1181
     .   : milestone, 1150,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5835) - mean (275ms)  : 271, 280
     .   : milestone, 275,
    master - mean (276ms)  : 271, 281
     .   : milestone, 276,

    section CallTarget+Inlining+NGEN
    This PR (5835) - mean (904ms)  : 882, 927
     .   : milestone, 904,
    master - mean (903ms)  : 883, 923
     .   : milestone, 903,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5835) - mean (266ms)  : 262, 270
     .   : milestone, 266,
    master - mean (267ms)  : 262, 271
     .   : milestone, 267,

    section CallTarget+Inlining+NGEN
    This PR (5835) - mean (891ms)  : 862, 921
     .   : milestone, 891,
    master - mean (888ms)  : 862, 913
     .   : milestone, 888,

```

**Review by daniel-romano-DD — APPROVED** [review]
Impressive job. Thanks a lot

**Review by kevingosse — APPROVED** [review]
:blindfold:

**Comment by andrewlock** [comment]
## Benchmarks Report for tracer :snail:

Benchmarks for #5835 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b): 
* 1 benchmarks are **faster**, with geometric mean 1.181
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.ActivityBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`StartStopWithChild`|net6.0|7.7μs|42ns|249ns|0.0151| 0.00753|0|5.42&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`StartStopWithChild`|netcoreapp3.1|9.84μs|53.9ns|324ns|0.0193| 0.00963|0|5.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`StartStopWithChild`|net472|16.2μs|72.9ns|291ns|1.03| 0.316|0.103|6.06&nbsp;KB|
|#5835|`StartStopWithChild`|net6.0|7.76μs|43.7ns|290ns|0.0149| 0.00743|0|5.42&nbsp;KB|
|#5835|`StartStopWithChild`|netcoreapp3.1|10.1μs|54.5ns|303ns|0.0193| 0.00967|0|5.62&nbsp;KB|
|#5835|`StartStopWithChild`|net472|16μs|40.3ns|156ns|1.02| 0.305|0.0905|6.07&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`WriteAndFlushEnrichedTraces`|net6.0|461μs|293ns|1.06μs|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|636μs|511ns|1.98μs|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`WriteAndFlushEnrichedTraces`|net472|845μs|752ns|2.91μs|0.422| 0|0|3.3&nbsp;KB|
|#5835|`WriteAndFlushEnrichedTraces`|net6.0|467μs|209ns|811ns|0| 0|0|2.7&nbsp;KB|
|#5835|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|647μs|339ns|1.31μs|0| 0|0|2.7&nbsp;KB|
|#5835|`WriteAndFlushEnrichedTraces`|net472|853μs|930ns|3.6μs|0.428| 0|0|3.3&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`SendRequest`|net6.0|200μs|1.17μs|11.3μs|0.187| 0|0|18.45&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`SendRequest`|netcoreapp3.1|216μs|1.24μs|9.65μs|0.246| 0|0|20.61&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`SendRequest`|net472|0.000625ns|0.00045ns|0.00168ns|0| 0|0|0&nbsp;b|
|#5835|`SendRequest`|net6.0|198μs|1.15μs|10μs|0.194| 0|0|18.45&nbsp;KB|
|#5835|`SendRequest`|netcoreapp3.1|219μs|1.24μs|8.74μs|0.207| 0|0|20.6&nbsp;KB|
|#5835|`SendRequest`|net472|0.000909ns|0.000574ns|0.00215ns|0| 0|0|0&nbsp;b|
</details>


<details><summary><strong>Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`WriteAndFlushEnrichedTraces`|net6.0|584μs|2.61μs|9.78μs|0.579| 0|0|41.71&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|701μs|3.9μs|23.7μs|0.332| 0|0|41.78&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`WriteAndFlushEnrichedTraces`|net472|888μs|3.66μs|14.2μs|8.42| 2.66|0.443|53.29&nbsp;KB|
|#5835|`WriteAndFlushEnrichedTraces`|net6.0|572μs|2.88μs|13.2μs|0.568| 0|0|41.66&nbsp;KB|
|#5835|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|687μs|3.51μs|16.4μs|0.351| 0|0|41.64&nbsp;KB|
|#5835|`WriteAndFlushEnrichedTraces`|net472|862μs|3.32μs|12.9μs|8.36| 2.64|0.44|53.34&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`ExecuteNonQuery`|net6.0|1.3μs|1.85ns|7.18ns|0.0142| 0|0|1.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`ExecuteNonQuery`|netcoreapp3.1|1.71μs|3.07ns|11.1ns|0.0137| 0|0|1.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`ExecuteNonQuery`|net472|2.05μs|1.8ns|6.98ns|0.157| 0|0|987&nbsp;B|
|#5835|`ExecuteNonQuery`|net6.0|1.29μs|1.8ns|6.97ns|0.0143| 0|0|1.02&nbsp;KB|
|#5835|`ExecuteNonQuery`|netcoreapp3.1|1.69μs|1.56ns|5.62ns|0.0136| 0|0|1.02&nbsp;KB|
|#5835|`ExecuteNonQuery`|net472|1.97μs|3.02ns|11.7ns|0.157| 0|0|987&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`CallElasticsearch`|net6.0|1.17μs|0.344ns|1.24ns|0.0135| 0|0|976&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`CallElasticsearch`|netcoreapp3.1|1.48μs|0.774ns|2.9ns|0.0133| 0|0|976&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`CallElasticsearch`|net472|2.47μs|1.39ns|5.2ns|0.157| 0|0|995&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`CallElasticsearchAsync`|net6.0|1.3μs|1ns|3.88ns|0.0131| 0|0|952&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`CallElasticsearchAsync`|netcoreapp3.1|1.53μs|1.41ns|5.29ns|0.0137| 0|0|1.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`CallElasticsearchAsync`|net472|2.69μs|1.4ns|5.25ns|0.166| 0.00134|0|1.05&nbsp;KB|
|#5835|`CallElasticsearch`|net6.0|1.17μs|0.81ns|3.03ns|0.0135| 0|0|976&nbsp;B|
|#5835|`CallElasticsearch`|netcoreapp3.1|1.59μs|1.5ns|5.62ns|0.0127| 0|0|976&nbsp;B|
|#5835|`CallElasticsearch`|net472|2.51μs|1.03ns|3.86ns|0.157| 0.00126|0|995&nbsp;B|
|#5835|`CallElasticsearchAsync`|net6.0|1.27μs|0.682ns|2.64ns|0.0133| 0|0|952&nbsp;B|
|#5835|`CallElasticsearchAsync`|netcoreapp3.1|1.67μs|1.94ns|7.25ns|0.0133| 0|0|1.02&nbsp;KB|
|#5835|`CallElasticsearchAsync`|net472|2.72μs|1.23ns|4.75ns|0.167| 0|0|1.05&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`ExecuteAsync`|net6.0|1.27μs|0.504ns|1.89ns|0.0134| 0|0|952&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`ExecuteAsync`|netcoreapp3.1|1.63μs|0.504ns|1.82ns|0.0131| 0|0|952&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`ExecuteAsync`|net472|1.74μs|0.698ns|2.7ns|0.145| 0|0|915&nbsp;B|
|#5835|`ExecuteAsync`|net6.0|1.3μs|0.891ns|3.33ns|0.0131| 0|0|952&nbsp;B|
|#5835|`ExecuteAsync`|netcoreapp3.1|1.66μs|3.65ns|14.1ns|0.0126| 0|0|952&nbsp;B|
|#5835|`ExecuteAsync`|net472|1.71μs|1.57ns|6.09ns|0.145| 0|0|915&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`SendAsync`|net6.0|4.22μs|1.64ns|6.37ns|0.0318| 0|0|2.22&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`SendAsync`|netcoreapp3.1|5.02μs|3.87ns|15ns|0.0376| 0|0|2.76&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`SendAsync`|net472|7.74μs|3.37ns|13.1ns|0.498| 0|0|3.15&nbsp;KB|
|#5835|`SendAsync`|net6.0|4.26μs|3.84ns|14.9ns|0.0318| 0|0|2.22&nbsp;KB|
|#5835|`SendAsync`|netcoreapp3.1|5.23μs|3.55ns|13.3ns|0.0364| 0|0|2.76&nbsp;KB|
|#5835|`SendAsync`|net472|7.74μs|4.81ns|18.6ns|0.498| 0|0|3.15&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`EnrichedLog`|net6.0|1.45μs|0.501ns|1.94ns|0.0233| 0|0|1.64&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`EnrichedLog`|netcoreapp3.1|2.14μs|2.21ns|8.57ns|0.0223| 0|0|1.64&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`EnrichedLog`|net472|2.57μs|1.24ns|4.79ns|0.25| 0|0|1.57&nbsp;KB|
|#5835|`EnrichedLog`|net6.0|1.57μs|1.04ns|4.04ns|0.0228| 0|0|1.64&nbsp;KB|
|#5835|`EnrichedLog`|netcoreapp3.1|2.24μs|0.985ns|3.55ns|0.0227| 0|0|1.64&nbsp;KB|
|#5835|`EnrichedLog`|net472|2.57μs|1.79ns|6.95ns|0.25| 0|0|1.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`EnrichedLog`|net6.0|113μs|250ns|967ns|0.056| 0|0|4.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`EnrichedLog`|netcoreapp3.1|119μs|277ns|1.07μs|0.0599| 0|0|4.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`EnrichedLog`|net472|148μs|197ns|764ns|0.664| 0.221|0|4.46&nbsp;KB|
|#5835|`EnrichedLog`|net6.0|114μs|144ns|556ns|0| 0|0|4.28&nbsp;KB|
|#5835|`EnrichedLog`|netcoreapp3.1|117μs|70.1ns|272ns|0.0583| 0|0|4.28&nbsp;KB|
|#5835|`EnrichedLog`|net472|146μs|83.3ns|322ns|0.658| 0.219|0|4.46&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`EnrichedLog`|net6.0|3.26μs|1.03ns|3.99ns|0.0302| 0|0|2.2&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`EnrichedLog`|netcoreapp3.1|4.22μs|2.79ns|10.4ns|0.0294| 0|0|2.2&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`EnrichedLog`|net472|4.98μs|9.62ns|37.2ns|0.32| 0|0|2.02&nbsp;KB|
|#5835|`EnrichedLog`|net6.0|3.13μs|0.936ns|3.62ns|0.0302| 0|0|2.2&nbsp;KB|
|#5835|`EnrichedLog`|netcoreapp3.1|4.05μs|1.9ns|7.35ns|0.0302| 0|0|2.2&nbsp;KB|
|#5835|`EnrichedLog`|net472|4.7μs|1.52ns|5.69ns|0.32| 0|0|2.02&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`SendReceive`|net6.0|1.43μs|1.26ns|4.89ns|0.0158| 0|0|1.14&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`SendReceive`|netcoreapp3.1|1.67μs|1.04ns|3.76ns|0.0158| 0|0|1.14&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`SendReceive`|net472|2.05μs|1.09ns|4.08ns|0.183| 0.00102|0|1.16&nbsp;KB|
|#5835|`SendReceive`|net6.0|1.45μs|0.674ns|2.52ns|0.016| 0|0|1.14&nbsp;KB|
|#5835|`SendReceive`|netcoreapp3.1|1.74μs|0.744ns|2.79ns|0.0156| 0|0|1.14&nbsp;KB|
|#5835|`SendReceive`|net472|2.05μs|1.06ns|4.12ns|0.183| 0.00102|0|1.16&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`EnrichedLog`|net6.0|2.8μs|1.14ns|4.42ns|0.0224| 0|0|1.6&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`EnrichedLog`|netcoreapp3.1|4.02μs|2.32ns|8.67ns|0.022| 0|0|1.65&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`EnrichedLog`|net472|4.45μs|1.3ns|4.67ns|0.322| 0|0|2.04&nbsp;KB|
|#5835|`EnrichedLog`|net6.0|2.66μs|0.842ns|3.26ns|0.0225| 0|0|1.6&nbsp;KB|
|#5835|`EnrichedLog`|netcoreapp3.1|3.91μs|3.57ns|13.8ns|0.0213| 0|0|1.65&nbsp;KB|
|#5835|`EnrichedLog`|net472|4.38μs|2.51ns|9.4ns|0.324| 0|0|2.04&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`StartFinishSpan`|net6.0|431ns|0.714ns|2.67ns|0.00804| 0|0|576&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`StartFinishSpan`|netcoreapp3.1|577ns|0.864ns|3.35ns|0.00785| 0|0|576&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`StartFinishSpan`|net472|658ns|0.773ns|2.79ns|0.0915| 0|0|578&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`StartFinishScope`|net6.0|513ns|1.18ns|4.43ns|0.00983| 0|0|696&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`StartFinishScope`|netcoreapp3.1|710ns|0.792ns|2.96ns|0.00938| 0|0|696&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`StartFinishScope`|net472|943ns|1.03ns|3.98ns|0.104| 0|0|658&nbsp;B|
|#5835|`StartFinishSpan`|net6.0|404ns|0.0773ns|0.289ns|0.00814| 0|0|576&nbsp;B|
|#5835|`StartFinishSpan`|netcoreapp3.1|564ns|0.595ns|2.31ns|0.00789| 0|0|576&nbsp;B|
|#5835|`StartFinishSpan`|net472|652ns|0.427ns|1.65ns|0.0916| 0|0|578&nbsp;B|
|#5835|`StartFinishScope`|net6.0|510ns|0.124ns|0.462ns|0.00976| 0|0|696&nbsp;B|
|#5835|`StartFinishScope`|netcoreapp3.1|680ns|0.246ns|0.922ns|0.00946| 0|0|696&nbsp;B|
|#5835|`StartFinishScope`|net472|868ns|0.568ns|2.2ns|0.104| 0|0|658&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Faster :tada: Same allocations :heavy_check_mark:



#### Faster :tada: in #5835

|  Benchmark         | base/diff | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.TraceAnnotationsBenchmark.RunOnMethodBegin&#8209;net6.0 | 1.181 | 689.03 | 583.30 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`RunOnMethodBegin`|net6.0|689ns|0.775ns|3ns|0.00962| 0|0|696&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`RunOnMethodBegin`|netcoreapp3.1|885ns|1.11ns|4.28ns|0.00956| 0|0|696&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/24b4b6efe291d266e21a232bc5c4c90b3f7d554b)|`RunOnMethodBegin`|net472|1.13μs|0.368ns|1.43ns|0.104| 0|0|658&nbsp;B|
|#5835|`RunOnMethodBegin`|net6.0|583ns|0.15ns|0.582ns|0.0097| 0|0|696&nbsp;B|
|#5835|`RunOnMethodBegin`|netcoreapp3.1|848ns|0.295ns|1.14ns|0.00948| 0|0|696&nbsp;B|
|#5835|`RunOnMethodBegin`|net472|1.12μs|0.278ns|1.08ns|0.105| 0|0|658&nbsp;B|
</details>

**Pull request merged**
