### PR TITLE
Support text map format

### LINKED ISSUE #514: Distributed tracing is impossible to implement
In addition to #508, there is another big issue with this library.

The only way to get the tracer to work now is to use the `OpenTracingTracerFactory`. It returns a wrapper that implements `ITracer` but underneath calls the `Tracer`. So far so good, except I can't use the existing `Tracer`, so I submitted #513.

Now, I want to do distributed tracing and therefore I need to extract or inject the context from a message. I am not using http apis, I use a message broker or event streams. In `OpenTracing` library, it is quite trivial - create a text map and ask it to serialize or deserialize the dictionary. But what works fine with `OpenTracing`, suddenly starts to break with `Datadog.Trace.OpenTracing`, because it expects that I have `ICodec` implemented in my parser. That would also be ok, but this interface, like many other interfaces and classes in this library, is **internal**. So, here comes the full stop and I am unable to move anywhere.

Even if I take the code from `Datadog.Trace.OpenTracing`, which is not a lot, it again has references to the `Datadog.Trace` library own **internal** classes.

All in all, I concluded that there's no way I can ever implement distributed tracing with Datadog and being five days from the end of our trial period, where everything else is (almost) very good, this is a huge blocked for us to engage with Datadog.

### PR DESCRIPTION
**Pull request by alanisaac**
Fixes #514 

Changes proposed in this pull request:

Using the `HttpHeadersCodec` to support `BuiltinFormats.TextMap`.  

As explained in the [documentation for the `OpenTracing` library](https://github.com/opentracing/opentracing-csharp/blob/461c6edd7b4209fe353eea7b927dd7046986e2b8/src/OpenTracing/Propagation/BuiltinFormats.cs#L7-L28), the difference between the two formats is that data written in the HttpHeaders format has to, naturally, work in an HTTP header.  TextMap format, on the other hand, has no constraints on the data.  Therefore, the `HttpHeadersCodec` should satisfy both use cases just fine.

`BuiltinFormats.HttpHeaders`
> keys written to the ITextMap MUST be suitable for HTTP header keys (which are poorly defined but certainly restricted); and similarly for values (i.e., URL-escaped and "not too long").

`BuiltinFormat.TextMap`
> the builtin 'TextMap' format expresses no constraints on keys or values.

@DataDog/apm-dotnet

### CODE REVIEW

**Comment by lucaspimentel** [comment]
Thanks, @alanisaac!

**Comment by alanisaac** [comment]
@lucaspimentel looks like many of the unit test checks failed.  Based on my read of the errors, this is just a pipeline issue and not the code -- but let me know if there's anything I can do to help!

**Comment by lucaspimentel** [comment]
@alanisaac: it's a permission issue on our side. I'll look into it, thanks.

**Comment by alanisaac** [comment]
@lucaspimentel any update on this?

**Comment by lucaspimentel** [comment]
@alanisaac: We wanted to release 1.15.0 first, which happened last night. I am merging this PR soon and it will be included in our next release. Thanks again!!

**Pull request merged**
