### PR TITLE
Configure the benchmarks project for micro-benchmarks

### PR DESCRIPTION
**Pull request by kevingosse**
- Added the project to the minimal solution
- Added a `microbenchmarks` folder and a gitignore file to ignore the contents of that folder

### CODE REVIEW

**Comment by tonyredondo** [comment]
Is that the same Benchmark project from the complete solution that wasn't added to the Minimal solution?

**Comment by kevingosse** [comment]
> Is that the same Benchmark project from the complete solution that wasn't added to the Minimal solution?

Yup. I thought about it for a while but saw no obvious reason why this couldn't be used for micro-benchmarks as well.

**Comment by kevingosse** [comment]
I don't know if there are any rules about what should and shouldn't go in the Minimal solution. I don't mind creating a benchmark solution, if needed.

**Comment by tonyredondo** [comment]
> > Is that the same Benchmark project from the complete solution that wasn't added to the Minimal solution?
> 
> Yup. I thought about it for a while but saw no obvious reason why this couldn't be used for micro-benchmarks as well.

Cool, seems fine by me

**Pull request merged**
