### PR TITLE
Change native format to custom style

### PR DESCRIPTION
**Pull request by tonyredondo**
Older `clang-format` versions doesn't support the `Microsoft` style. 
This PR uses a custom format (with some changes) after an agreement with @gleocadie

@DataDog/apm-dotnet

### CODE REVIEW

**Review by gleocadie — APPROVED** [review]
LGTM
Note: On my computer using VS2019 or clang-format (v12) tool, this does not work.

**Comment by tonyredondo** [comment]
> LGTM
> Note: On my computer using VS2019 or clang-format (v12) tool, this does not work.

I did some changes for windows in b819ff5, can you try again?

**Comment by gleocadie** [comment]
I tried but it does not work from the file.
(Pointer still on the right and not on the left)

**Review by lucaspimentel — APPROVED** [review]

**Comment by lucaspimentel** [comment]
For future reference, this is a continuation of https://github.com/DataDog/dd-trace-dotnet/pull/1544

**Pull request merged**
