### PR TITLE
[CI Visibility] `dd-trace ci configure` improvements

### PR DESCRIPTION
**Pull request by tonyredondo**
## Summary of changes

This PR contains a couple of CI Visibility improvements: 

- Log stderr on git pack errors.
- Add a logs into the SetupCIEnvironmentVariables method to ensure the log folder is created.
- Add powershell.exe as an exclude process when using dd-trace ci configure azp due to incompatibilities.

### CODE REVIEW

**Comment by andrewlock** [comment]
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (4572)](https://github.com/DataDog/dd-trace-dotnet/tree/6e2214ed38a14d04f524cd4f0aae6f2b61e5e573)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/98db3b3d9784eccefb07f6b818f96cac07be8d45)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4572) - mean (74ms)  : 61, 87
     .   : milestone, 74,
    master - mean (73ms)  : 59, 87
     .   : milestone, 73,

    section CallTarget+Inlining+NGEN
    This PR (4572) - mean (1,037ms)  : 1010, 1063
     .   : milestone, 1037,
    master - mean (1,037ms)  : 1006, 1069
     .   : milestone, 1037,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4572) - mean (107ms)  : 97, 117
     .   : milestone, 107,
    master - mean (105ms)  : 102, 109
     .   : milestone, 105,

    section CallTarget+Inlining+NGEN
    This PR (4572) - mean (735ms)  : 709, 762
     .   : milestone, 735,
    master - mean (733ms)  : 708, 759
     .   : milestone, 733,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4572) - mean (89ms)  : 85, 93
     .   : milestone, 89,
    master - mean (90ms)  : 86, 93
     .   : milestone, 90,

    section CallTarget+Inlining+NGEN
    This PR (4572) - mean (696ms)  : 665, 727
     .   : milestone, 696,
    master - mean (697ms)  : 656, 738
     .   : milestone, 697,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4572) - mean (194ms)  : 189, 198
     .   : milestone, 194,
    master - mean (191ms)  : 188, 195
     .   : milestone, 191,

    section CallTarget+Inlining+NGEN
    This PR (4572) - mean (1,139ms)  : 1105, 1172
     .   : milestone, 1139,
    master - mean (1,136ms)  : 1105, 1168
     .   : milestone, 1136,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4572) - mean (275ms)  : 270, 280
     .   : milestone, 275,
    master - mean (272ms)  : 264, 280
     .   : milestone, 272,

    section CallTarget+Inlining+NGEN
    This PR (4572) - mean (1,098ms)  : 1064, 1131
     .   : milestone, 1098,
    master - mean (1,087ms)  : 1049, 1125
     .   : milestone, 1087,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4572) - mean (268ms)  : 256, 280
     .   : milestone, 268,
    master - mean (261ms)  : 253, 269
     .   : milestone, 261,

    section CallTarget+Inlining+NGEN
    This PR (4572) - mean (1,052ms)  : 1017, 1086
     .   : milestone, 1052,
    master - mean (1,044ms)  : 1004, 1084
     .   : milestone, 1044,

```

**Comment by andrewlock** [comment]
## Throughput/Crank Report:zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (4572)](https://github.com/DataDog/dd-trace-dotnet/tree/6e2214ed38a14d04f524cd4f0aae6f2b61e5e573)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/f801aa7a6ed461cff6e312f171b0bddf873c94e3)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/89ae3f4ee7d85b824badda5873166707c9e560b4)
- [benchmarks/2.36.0](https://github.com/DataDog/dd-trace-dotnet/tree/dc5f664719def158652515f7fac3c87589c46596)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4572) (10.815M)   : 0, 10815284
    master (10.757M)   : 0, 10757144
    benchmarks/2.36.0 (11.139M)   : 0, 11139004
    benchmarks/2.9.0 (11.325M)   : 0, 11324702

    section Automatic
    This PR (4572) (7.560M)   : 0, 7560165
    master (7.555M)   : 0, 7554993
    benchmarks/2.36.0 (7.796M)   : 0, 7795573
    benchmarks/2.9.0 (8.180M)   : 0, 8179828

    section Trace stats
    master (7.504M)   : 0, 7503878
    benchmarks/2.36.0 (7.932M)   : 0, 7931920

    section Manual
    This PR (4572) (9.555M)   : 0, 9554977
    master (9.606M)   : 0, 9605693
    benchmarks/2.36.0 (9.854M)   : 0, 9854091

    section Manual + Automatic
    This PR (4572) (7.205M)   : 0, 7205115
    master (7.204M)   : 0, 7203954
    benchmarks/2.36.0 (7.368M)   : 0, 7368211

    section Version Conflict
    master (6.573M)   : 0, 6572683
    benchmarks/2.36.0 (6.826M)   : 0, 6825561

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4572) (9.598M)   : 0, 9598078
    master (9.657M)   : 0, 9656967
    benchmarks/2.36.0 (9.434M)   : 0, 9433740
    benchmarks/2.9.0 (9.767M)   : 0, 9766880

    section Automatic
    This PR (4572) (6.835M)   : 0, 6835438
    master (6.757M)   : 0, 6756556
    benchmarks/2.36.0 (6.695M)   : 0, 6694737

    section Trace stats
    master (6.753M)   : 0, 6753093
    benchmarks/2.36.0 (6.914M)   : 0, 6914146

    section Manual
    This PR (4572) (8.546M)   : 0, 8546293
    master (8.636M)   : 0, 8636103
    benchmarks/2.36.0 (8.612M)   : 0, 8612005

    section Manual + Automatic
    This PR (4572) (6.607M)   : 0, 6607119
    master (6.275M)   : 0, 6274658
    benchmarks/2.36.0 (6.562M)   : 0, 6562387

    section Version Conflict
    master (5.588M)   : 0, 5588305
    benchmarks/2.36.0 (5.848M)   : 0, 5847902

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4572) (10.174M)   : 0, 10174283
    master (10.296M)   : 0, 10295928
    benchmarks/2.36.0 (10.442M)   : 0, 10442160
    benchmarks/2.9.0 (10.288M)   : 0, 10288053

    section Automatic
    This PR (4572) (7.326M)   : 0, 7325863
    master (7.436M)   : 0, 7435973
    benchmarks/2.36.0 (7.461M)   : 0, 7460996
    benchmarks/2.9.0 (7.532M)   : 0, 7532387

    section Trace stats
    master (7.450M)   : 0, 7449699
    benchmarks/2.36.0 (7.459M)   : 0, 7458598

    section Manual
    This PR (4572) (9.118M)   : 0, 9118208
    master (9.194M)   : 0, 9194324
    benchmarks/2.36.0 (9.183M)   : 0, 9183081

    section Manual + Automatic
    This PR (4572) (7.127M)   : 0, 7127142
    master (7.093M)   : 0, 7093453
    benchmarks/2.36.0 (7.212M)   : 0, 7211940

    section Version Conflict
    master (6.591M)   : 0, 6590628
    benchmarks/2.36.0 (6.514M)   : 0, 6514071

```
```mermaid
gantt
    title Throughput Linux x64 (ASM) (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4572) (7.435M)   : 0, 7434582
    master (7.544M)   : 0, 7543647
    benchmarks/2.36.0 (7.497M)   : 0, 7496686
    benchmarks/2.9.0 (7.829M)   : 0, 7829234

    section No attack
    This PR (4572) (2.139M)   : 0, 2139252
    master (2.132M)   : 0, 2132148
    benchmarks/2.36.0 (2.139M)   : 0, 2138929
    benchmarks/2.9.0 (3.223M)   : 0, 3222946

    section Attack
    This PR (4572) (1.673M)   : 0, 1672547
    master (1.640M)   : 0, 1639899
    benchmarks/2.36.0 (1.679M)   : 0, 1678844
    benchmarks/2.9.0 (2.579M)   : 0, 2579343

    section Blocking
    This PR (4572) (3.009M)   : 0, 3008621
    master (3.115M)   : 0, 3115097
    benchmarks/2.36.0 (3.142M)   : 0, 3141981

```

**Review by andrewlock — APPROVED** [review]
LGTM

**Review by bouwkast — APPROVED** [review]
Looks good to me!

**Pull request merged**
