### PR TITLE
Fix nesting of Samples.AWS.SimpleNotificationService project

### PR DESCRIPTION
**Pull request by anna-git**
## Summary of changes

Fix this
image

to being 
image

### CODE REVIEW

**Review by andrewlock — APPROVED** [review]

**Comment by andrewlock** [comment]
Thanks for fixing this!

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #4252 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928): 
* 1 benchmarks are **faster**, with geometric mean 1.170
* 1 benchmarks have **more** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|653μs|180ns|649ns|0| 0|0|2.63&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`WriteAndFlushEnrichedTraces`|net472|789μs|441ns|1.65μs|0.393| 0|0|3.31&nbsp;KB|
|#4252|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|646μs|1.02μs|3.96μs|0| 0|0|2.62&nbsp;KB|
|#4252|`WriteAndFlushEnrichedTraces`|net472|787μs|492ns|1.91μs|0.396| 0|0|3.31&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`AllCycleSimpleBody`|netcoreapp3.1|41.4μs|46.2ns|173ns|0.0205| 0|0|1.63&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`AllCycleSimpleBody`|net472|41.3μs|111ns|430ns|0.265| 0|0|1.69&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`AllCycleMoreComplexBody`|netcoreapp3.1|230μs|187ns|699ns|0.114| 0|0|9.12&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`AllCycleMoreComplexBody`|net472|240μs|72.4ns|271ns|1.44| 0|0|9.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`ObjectExtractorSimpleBody`|netcoreapp3.1|169ns|0.0692ns|0.259ns|0.00372| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`ObjectExtractorSimpleBody`|net472|147ns|0.233ns|0.904ns|0.0446| 0|0|281&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|4.08μs|2.51ns|9.41ns|0.0509| 0|0|3.78&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`ObjectExtractorMoreComplexBody`|net472|4.08μs|4.29ns|16.6ns|0.618| 0.00608|0|3.89&nbsp;KB|
|#4252|`AllCycleSimpleBody`|netcoreapp3.1|40.5μs|47.7ns|172ns|0.0202| 0|0|1.63&nbsp;KB|
|#4252|`AllCycleSimpleBody`|net472|40.3μs|14.1ns|54.5ns|0.266| 0|0|1.69&nbsp;KB|
|#4252|`AllCycleMoreComplexBody`|netcoreapp3.1|228μs|372ns|1.29μs|0.113| 0|0|9.12&nbsp;KB|
|#4252|`AllCycleMoreComplexBody`|net472|236μs|66.2ns|256ns|1.42| 0|0|9.28&nbsp;KB|
|#4252|`ObjectExtractorSimpleBody`|netcoreapp3.1|181ns|0.0904ns|0.35ns|0.00373| 0|0|272&nbsp;B|
|#4252|`ObjectExtractorSimpleBody`|net472|142ns|0.18ns|0.695ns|0.0446| 0|0|281&nbsp;B|
|#4252|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|4.38μs|1.43ns|5.34ns|0.0504| 0|0|3.78&nbsp;KB|
|#4252|`ObjectExtractorMoreComplexBody`|net472|4.1μs|5.32ns|20.6ns|0.617| 0.00615|0|3.89&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`SendRequest`|netcoreapp3.1|187μs|250ns|969ns|0.186| 0|0|20.1&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`SendRequest`|net472|2.92E&#8209;05ns|2.92E&#8209;05ns|0.000101ns|0| 0|0|0&nbsp;b|
|#4252|`SendRequest`|netcoreapp3.1|191μs|287ns|1.11μs|0.191| 0|0|20.1&nbsp;KB|
|#4252|`SendRequest`|net472|0.000503ns|0.000179ns|0.000669ns|0| 0|0|0&nbsp;b|
</details>


<details><summary><strong>Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark</strong> - Same speed :heavy_check_mark: More allocations :warning:



#### More allocations :warning: in #4252

|  Benchmark         | Base Allocated | Diff Allocated | Change   | Change % |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark.WriteAndFlushEnrichedTraces&#8209;netcoreapp3.1 | 41.56 KB | 41.88 KB | 325 B | 0.78%

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|612μs|571ns|2.14μs|0.616| 0|0|41.56&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`WriteAndFlushEnrichedTraces`|net472|796μs|3.14μs|12.2μs|8.31| 2.37|0.396|53.25&nbsp;KB|
|#4252|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|627μs|1.2μs|4.33μs|0.306| 0|0|41.88&nbsp;KB|
|#4252|`WriteAndFlushEnrichedTraces`|net472|768μs|2.72μs|10.5μs|8.44| 2.68|0.383|53.25&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`ExecuteNonQuery`|netcoreapp3.1|1.27μs|0.526ns|1.97ns|0.00997| 0|0|736&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`ExecuteNonQuery`|net472|1.5μs|0.748ns|2.9ns|0.111| 0|0|698&nbsp;B|
|#4252|`ExecuteNonQuery`|netcoreapp3.1|1.22μs|0.981ns|3.67ns|0.0103| 0|0|736&nbsp;B|
|#4252|`ExecuteNonQuery`|net472|1.55μs|0.416ns|1.56ns|0.111| 0|0|698&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`CallElasticsearch`|netcoreapp3.1|1.28μs|0.266ns|0.995ns|0.0104| 0|0|760&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`CallElasticsearch`|net472|1.96μs|0.695ns|2.69ns|0.122| 0.000983|0|770&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`CallElasticsearchAsync`|netcoreapp3.1|1.3μs|0.466ns|1.8ns|0.0111| 0|0|808&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`CallElasticsearchAsync`|net472|2.08μs|1.09ns|4.08ns|0.131| 0.00104|0|827&nbsp;B|
|#4252|`CallElasticsearch`|netcoreapp3.1|1.3μs|0.432ns|1.61ns|0.0104| 0|0|760&nbsp;B|
|#4252|`CallElasticsearch`|net472|2.12μs|0.465ns|1.74ns|0.122| 0.00105|0|770&nbsp;B|
|#4252|`CallElasticsearchAsync`|netcoreapp3.1|1.34μs|0.411ns|1.48ns|0.0107| 0|0|808&nbsp;B|
|#4252|`CallElasticsearchAsync`|net472|2.09μs|0.516ns|1.86ns|0.131| 0.00105|0|827&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`ExecuteAsync`|netcoreapp3.1|1.41μs|2.49ns|9.33ns|0.0124| 0|0|928&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`ExecuteAsync`|net472|1.68μs|0.633ns|2.45ns|0.141| 0.000837|0|891&nbsp;B|
|#4252|`ExecuteAsync`|netcoreapp3.1|1.38μs|0.593ns|2.05ns|0.0124| 0|0|928&nbsp;B|
|#4252|`ExecuteAsync`|net472|1.57μs|0.394ns|1.48ns|0.141| 0.000789|0|891&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`SendAsync`|netcoreapp3.1|4.19μs|2.29ns|8.25ns|0.0334| 0|0|2.44&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`SendAsync`|net472|6.8μs|1.74ns|6.27ns|0.476| 0|0|3.01&nbsp;KB|
|#4252|`SendAsync`|netcoreapp3.1|4.35μs|1.6ns|5.98ns|0.0326| 0|0|2.44&nbsp;KB|
|#4252|`SendAsync`|net472|6.92μs|1.63ns|6.31ns|0.476| 0|0|3.01&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`EnrichedLog`|netcoreapp3.1|1.97μs|0.842ns|3.15ns|0.0218| 0|0|1.64&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`EnrichedLog`|net472|2.47μs|2.76ns|10.7ns|0.247| 0|0|1.56&nbsp;KB|
|#4252|`EnrichedLog`|netcoreapp3.1|1.85μs|0.88ns|3.29ns|0.0223| 0|0|1.64&nbsp;KB|
|#4252|`EnrichedLog`|net472|2.31μs|1.08ns|4.04ns|0.247| 0|0|1.56&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`EnrichedLog`|netcoreapp3.1|121μs|195ns|730ns|0.06| 0|0|4.22&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`EnrichedLog`|net472|148μs|88.4ns|342ns|0.667| 0.222|0|4.4&nbsp;KB|
|#4252|`EnrichedLog`|netcoreapp3.1|118μs|270ns|936ns|0| 0|0|4.22&nbsp;KB|
|#4252|`EnrichedLog`|net472|149μs|49.2ns|184ns|0.671| 0.224|0|4.4&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`EnrichedLog`|netcoreapp3.1|3.82μs|2.55ns|9.55ns|0.0494| 0|0|3.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`EnrichedLog`|net472|4.88μs|0.969ns|3.62ns|0.527| 0.00244|0|3.33&nbsp;KB|
|#4252|`EnrichedLog`|netcoreapp3.1|3.99μs|0.926ns|3.34ns|0.0497| 0|0|3.7&nbsp;KB|
|#4252|`EnrichedLog`|net472|4.9μs|1.28ns|4.79ns|0.527| 0.00245|0|3.33&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`SendReceive`|netcoreapp3.1|1.58μs|0.862ns|3.23ns|0.0135| 0|0|1.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`SendReceive`|net472|1.82μs|1.66ns|6.42ns|0.162| 0.000904|0|1.02&nbsp;KB|
|#4252|`SendReceive`|netcoreapp3.1|1.43μs|0.715ns|2.68ns|0.0136| 0|0|1.02&nbsp;KB|
|#4252|`SendReceive`|net472|1.79μs|0.591ns|2.29ns|0.162| 0.000893|0|1.02&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`EnrichedLog`|netcoreapp3.1|3.66μs|0.78ns|3.02ns|0.0219| 0|0|1.59&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`EnrichedLog`|net472|4.11μs|1.76ns|6.8ns|0.314| 0|0|1.97&nbsp;KB|
|#4252|`EnrichedLog`|netcoreapp3.1|3.72μs|7.6ns|28.4ns|0.0203| 0|0|1.59&nbsp;KB|
|#4252|`EnrichedLog`|net472|4.05μs|2.08ns|8.06ns|0.312| 0|0|1.97&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Faster :tada: Same allocations :heavy_check_mark:



#### Faster :tada: in #4252

|  Benchmark         | base/diff | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.SpanBenchmark.StartFinishScope&#8209;netcoreapp3.1 | 1.170 | 828.51 | 708.30 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`StartFinishSpan`|netcoreapp3.1|594ns|0.199ns|0.745ns|0.00741| 0|0|552&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`StartFinishSpan`|net472|709ns|0.291ns|1.13ns|0.088| 0|0|554&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`StartFinishScope`|netcoreapp3.1|829ns|0.355ns|1.33ns|0.00893| 0|0|672&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`StartFinishScope`|net472|864ns|0.752ns|2.91ns|0.101| 0|0|634&nbsp;B|
|#4252|`StartFinishSpan`|netcoreapp3.1|582ns|0.268ns|1ns|0.00751| 0|0|552&nbsp;B|
|#4252|`StartFinishSpan`|net472|693ns|0.596ns|2.31ns|0.0878| 0|0|554&nbsp;B|
|#4252|`StartFinishScope`|netcoreapp3.1|707ns|0.767ns|2.97ns|0.00929| 0|0|672&nbsp;B|
|#4252|`StartFinishScope`|net472|859ns|0.248ns|0.927ns|0.101| 0|0|634&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`RunOnMethodBegin`|netcoreapp3.1|861ns|0.26ns|0.971ns|0.00915| 0|0|672&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)|`RunOnMethodBegin`|net472|1.04μs|0.7ns|2.71ns|0.101| 0|0|634&nbsp;B|
|#4252|`RunOnMethodBegin`|netcoreapp3.1|830ns|0.401ns|1.5ns|0.00914| 0|0|672&nbsp;B|
|#4252|`RunOnMethodBegin`|net472|1.06μs|0.355ns|1.33ns|0.101| 0|0|634&nbsp;B|
</details>

**Comment by andrewlock** [comment]
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (4252)](https://github.com/DataDog/dd-trace-dotnet/tree/c20961aedcc3b2ad3ea7753feabf454516e5e5dc)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/fb6cff19be444db70f09833055b923226eee6928)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4252) - mean (3,012ms)  : 2934, 3091
     .   : milestone, 3012,
    master - mean (3,015ms)  : 2882, 3149
     .   : milestone, 3015,

    section CallTarget+Inlining+NGEN
    This PR (4252) - mean (3,745ms)  : 3664, 3825
     .   : milestone, 3745,
    master - mean (3,765ms)  : 3670, 3860
     .   : milestone, 3765,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4252) - mean (3,116ms)  : 3020, 3212
     .   : milestone, 3116,
    master - mean (3,136ms)  : 3033, 3239
     .   : milestone, 3136,

    section CallTarget+Inlining+NGEN
    This PR (4252) - mean (3,599ms)  : 3536, 3663
     .   : milestone, 3599,
    master - mean (3,600ms)  : 3523, 3678
     .   : milestone, 3600,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4252) - mean (3,099ms)  : 2970, 3228
     .   : milestone, 3099,
    master - mean (3,136ms)  : 3000, 3272
     .   : milestone, 3136,

    section CallTarget+Inlining+NGEN
    This PR (4252) - mean (3,549ms)  : 3485, 3614
     .   : milestone, 3549,
    master - mean (3,586ms)  : 3501, 3672
     .   : milestone, 3586,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4252) - mean (191ms)  : 185, 196
     .   : milestone, 191,
    master - mean (189ms)  : 184, 193
     .   : milestone, 189,

    section CallTarget+Inlining+NGEN
    This PR (4252) - mean (1,048ms)  : 1001, 1096
     .   : milestone, 1048,
    master - mean (1,023ms)  : 954, 1091
     .   : milestone, 1023,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4252) - mean (369ms)  : 365, 374
     .   : milestone, 369,
    master - mean (367ms)  : 364, 370
     .   : milestone, 367,

    section CallTarget+Inlining+NGEN
    This PR (4252) - mean (1,127ms)  : 1085, 1170
     .   : milestone, 1127,
    master - mean (1,115ms)  : 1086, 1145
     .   : milestone, 1115,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4252) - mean (357ms)  : 352, 362
     .   : milestone, 357,
    master - mean (356ms)  : 350, 362
     .   : milestone, 356,

    section CallTarget+Inlining+NGEN
    This PR (4252) - mean (1,074ms)  : 1026, 1122
     .   : milestone, 1074,
    master - mean (1,076ms)  : 1051, 1101
     .   : milestone, 1076,

```

**Review by zacharycmontoya — APPROVED** [review]
Thanks!!

**Comment by andrewlock** [comment]
## Throughput/Crank Report:zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (4252)](https://github.com/DataDog/dd-trace-dotnet/tree/c20961aedcc3b2ad3ea7753feabf454516e5e5dc)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/2dffb27058b8786d23f00c949938d07204affc9e)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/89ae3f4ee7d85b824badda5873166707c9e560b4)
- [benchmarks/2.31.0](https://github.com/DataDog/dd-trace-dotnet/tree/5a0f7f5a6023b3b0761baa6b1bcd53b8f3af5655)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4252) (11.062M)   : 0, 11061612
    master (10.782M)   : 0, 10782395
    benchmarks/2.31.0 (11.306M)   : 0, 11305708
    benchmarks/2.9.0 (11.145M)   : 0, 11144900

    section Automatic
    This PR (4252) (7.833M)   : 0, 7832592
    master (7.603M)   : 0, 7603118
    benchmarks/2.31.0 (8.090M)   : 0, 8089546
    benchmarks/2.9.0 (7.963M)   : 0, 7963150

    section Trace stats
    master (7.540M)   : 0, 7540023
    benchmarks/2.31.0 (8.033M)   : 0, 8032849

    section Manual
    This PR (4252) (10.044M)   : 0, 10044387
    master (9.592M)   : 0, 9592468
    benchmarks/2.31.0 (10.165M)   : 0, 10164939

    section Manual + Automatic
    This PR (4252) (7.470M)   : 0, 7470402
    master (7.292M)   : 0, 7292335
    benchmarks/2.31.0 (7.778M)   : 0, 7778298

    section Version Conflict
    master (6.491M)   : 0, 6491231
    benchmarks/2.31.0 (6.986M)   : 0, 6986072

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4252) (9.743M)   : 0, 9742631
    master (9.666M)   : 0, 9666178
    benchmarks/2.31.0 (9.572M)   : 0, 9571695
    benchmarks/2.9.0 (9.726M)   : 0, 9725883

    section Automatic
    This PR (4252) (6.926M)   : 0, 6926063
    master (6.803M)   : 0, 6803294
    benchmarks/2.31.0 (6.701M)   : 0, 6701349

    section Trace stats
    master (6.832M)   : 0, 6832445
    benchmarks/2.31.0 (6.837M)   : 0, 6837121

    section Manual
    This PR (4252) (8.483M)   : 0, 8483478
    master (8.504M)   : 0, 8504152
    benchmarks/2.31.0 (8.471M)   : 0, 8470689

    section Manual + Automatic
    This PR (4252) (6.615M)   : 0, 6614844
    master (6.540M)   : 0, 6540276
    benchmarks/2.31.0 (6.601M)   : 0, 6601385

    section Version Conflict
    master (5.941M)   : 0, 5941305
    benchmarks/2.31.0 (5.973M)   : 0, 5972804

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4252) (9.928M)   : 0, 9927880
    master (9.047M)   : 0, 9047244
    benchmarks/2.31.0 (10.213M)   : 0, 10213493
    benchmarks/2.9.0 (10.391M)   : 0, 10391357

    section Automatic
    This PR (4252) (6.830M)   : 0, 6830175
    master (7.183M)   : 0, 7182743
    benchmarks/2.31.0 (7.453M)   : 0, 7453187
    benchmarks/2.9.0 (7.456M)   : 0, 7455775

    section Trace stats
    master (7.020M)   : 0, 7020373
    benchmarks/2.31.0 (7.585M)   : 0, 7584519

    section Manual
    This PR (4252) (8.785M)   : 0, 8785268
    master (8.651M)   : 0, 8650813
    benchmarks/2.31.0 (9.207M)   : 0, 9206680

    section Manual + Automatic
    This PR (4252) (6.768M)   : 0, 6767652
    master (6.864M)   : 0, 6863746
    benchmarks/2.31.0 (7.364M)   : 0, 7364096

    section Version Conflict
    master (6.217M)   : 0, 6216845
    benchmarks/2.31.0 (6.485M)   : 0, 6485150

```
```mermaid
gantt
    title Throughput Linux x64 (ASM) (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4252) (7.311M)   : 0, 7310693
    master (7.504M)   : 0, 7503553
    benchmarks/2.31.0 (7.425M)   : 0, 7425109
    benchmarks/2.9.0 (7.910M)   : 0, 7909841

    section No attack
    This PR (4252) (2.255M)   : 0, 2254875
    master (2.253M)   : 0, 2253197
    benchmarks/2.31.0 (2.414M)   : 0, 2413606
    benchmarks/2.9.0 (3.200M)   : 0, 3199566

    section Attack
    This PR (4252) (1.920M)   : 0, 1920171
    master (1.892M)   : 0, 1892290
    benchmarks/2.31.0 (2.053M)   : 0, 2053475
    benchmarks/2.9.0 (2.541M)   : 0, 2540856

    section Blocking
    This PR (4252) (3.596M)   : 0, 3596342
    master (3.618M)   : 0, 3617559
    benchmarks/2.31.0 (4.136M)   : 0, 4136222

```

**Pull request merged**
